### ISSUE TITLE
convox ps --stats should time out

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1003]
https://circleci.com/gh/convox/rack/1191

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sNhu79rZ&#x2F;471-timeout-for-convox-ps-stats"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> timeout for convox ps --stats</a>

**Comment by MiguelMoll** [comment]
Forgot there is a timeout guard in place: https://github.com/convox/rack/blob/master/api/models/process.go#L558-L564

I wonder:
- If we should put one at the client level
- Is the CI error misleading?
