### ISSUE TITLE
convox deploy fails to recognize when docker isn't running

### ISSUE THREAD

**Issue by contra** [convox/rack#1007]
**Result of running `convox deploy` without docker running locally:**

![image](https://cloud.githubusercontent.com/assets/425716/17490483/012f05dc-5d71-11e6-8463-ffa1e725fee7.png)

**What should happen:** `convox` should show an error when docker isn't running.

```
client: 20160805175609
```

( Paying customer, if that matters for support reasons )

**Comment by contra** [comment]
Seems like the new `docker build` wrapper in the CLI doesn't report any stdout/stderr from the underlying process until success + process exit happens - this blocks out any errors that might occur + when it does work makes it seem like the process is hanging while the build is in progress.

**Comment by ddollar** [comment]
Fixed in #1231
