### ISSUE TITLE
Initial promote of a release returns “running” status through Convox API despite ECS having still “pending” status

### ISSUE THREAD

**Issue by jjperezaguinaga** [convox/rack#101]
This is a very picky issue but thought it's worth it reporting anyway: on an initial promote (i.e. app hasn't had any release running), you can get a response from Convox API that the app is already running, even though the ECS status for that specific instance might be “pending”.

A better way to see if is that after we do “convox deploy” we get something like this:
```
{
    "balancer": "jjperezaguinaga-io-2818939401.us-east-1.elb.amazonaws.com",
    "name": "jjperezaguinaga-io",
    "release": "RRUWYAHSOOR",
    "status": "running"
  }
```
when if logging into AWS, you get the following response:
![screen shot 2015-10-14 at 13 57 13](https://cloud.githubusercontent.com/assets/1128312/10482845/db32946a-727b-11e5-8e94-492349b0d58b.png)

During a few minutes, the application is still unavailable, and then everything goes all right.

**Comment by csquared** [comment]
Agreed. We're also reporting a stauts of `running` for apps that have been created an not deployed at #104

**Comment by csquared** [comment]
this should be fixed now!

```
  {
    "name": "foobles",
    "release": "RJEXANVOUVC",
    "status": "updating"
  }

```
