### ISSUE TITLE
Convox sends entire docker build context even if using `image` in docker-compose.yml

### ISSUE THREAD

**Issue by skwp** [convox/rack#1013]
If you point your docker-compose to an `image`, convox still tars up the entire docker build context. Here is example output from a build:

```
Analyzing source... OK
Uploading changes... 120.20 MB / 120.20 MB  100.00 % 33s
```

This is a problem because it unnecessarily wastes time and bandwidth in the transmission of data that should not need to be used on the other side.

**Comment by orangewolf** [comment]
Would sending everything both up and down from a registry remove this problem and lead to all around faster deploys? You're moving the data twice that way, once to the registry and once to the server, but you'd be moving smaller slices.
