### ISSUE TITLE
postgres service creation bad password

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#102]
I recently created a couple of RDS Postgres databases with the `convox services create` command. In both cases, it seems the password in the `postgres://...` URL returned by `convox services info` was incorrect.

I was able to work around the issue by going into the AWS web console and changing the password, then setting the new password on the URL in my app's environment.

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PRobp7L3&#x2F;198-bad-password-with-postgres-service-creation"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> bad password with postgres service creation</a>

**Comment by csquared** [comment]
having trouble reproducing with a database i just created

**Comment by csquared** [comment]
going to make another one -> thrid time is a charm!

**Comment by csquared** [comment]
this turned out to be a red herring
