### ISSUE TITLE
It should be hard to delete an app

### ISSUE THREAD

**Issue by beedub** [convox/rack#1035]
There should be more friction in the process for deleting an app. Right now, there is no confirmation, so the risk of fat fingering something important is high.

The minimum amount of friction (more is welcome) is asking for confirmation by typing the name of an app. Maybe even have the option of deleting apps disabled on the rack level?

**Comment by ddollar** [comment]
Related to #684

**Comment by ddollar** [comment]
```
Are you sure you want to delete important-app?
```

Add Y/N prompt if stdin is a TTY

**Comment by ddollar** [comment]
`convox apps delete` currently requires you to type out the full app name. Will consider adding a confirmation but it could potentially break existing CI scripts.
