### ISSUE TITLE
initial create of app results in status `running`

### ISSUE THREAD

**Issue by csquared** [convox/rack#104]
should probably be something more like "created"
then "deployed"
then "pending"
then "running"

see also #101

**Comment by jjperezaguinaga** [comment]
I can also confirm a similar issue appears on `convox rack scale`

```
➜  jjperezaguinaga-io git:(master) convox rack
Name     convox
Status   running
Version  20150919002113
Count    5
Type     t2.small
```
Even though the instances are just being created:
<img width="636" alt="screen shot 2015-10-20 at 17 16 13" src="https://cloud.githubusercontent.com/assets/1128312/10611859/663fd50a-774e-11e5-96b8-139a02f1a3bd.png">

After running `convox rack scale` you will get a immediate `updating` status, but at that time you still have only the instances you started with. There's a timeframe where those instances are created, and then the `running` message will show up on `convox rack`. Very similar to the apps status.

**Comment by csquared** [comment]
we now have the `creating` state

```~/convox$ cx apps create foobles
Creating app foobles... CREATING
~/convox$ cx apps info --app foobles
Name       foobles
Status     creating
```
