### ISSUE TITLE
Convox should warn or unlink services when deleting a linked app

### ISSUE THREAD

**Issue by adamenger** [convox/rack#1049]
Right now if you delete an app with a service link, it will break the service:

```
⮀ convox services
NAME             TYPE      STATUS
convox-events    webhook   running
fluentd-staging  fluentd   running
postgres-8492    postgres  running
syslog-4305      syslog    running
⮀ convox services link fluentd-staging --app lessons
ERROR: no such service: fluentd-staging
```

The fix right now is to modify the Cloudformation template that is managing the service and remove all references to the deleted app.

**Comment by mwarkentin** [comment]
+1 to cleaning up the link automatically when deleting an app.

**Comment by adamenger** [comment]
Current patch for this will warn with 412 precondition failed.

**Comment by ddollar** [comment]
Related to #1367
