### ISSUE TITLE
convox start fails on folders with capitalization

### ISSUE THREAD

**Issue by csquared** [convox/rack#105]
report from joonathan via slack:

> If folder name contains capitalization eg. `Telebot` then docker-compose itself is successfuly able to deal with that, but convox will fail
> convox start would fail, convox apps create would ​_succeed_​ but failure would come when doing convox deploy as image is unable to build due to the name issue

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;cGnDdUxw&#x2F;217-folders-with-captialization"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> folders with captialization</a>

**Comment by mattmanning** [comment]
This seems to happen because the uppercase name of the directory is getting passed into the tag:

```
RUNNING: docker tag -f clukzmffmc Feedchirp/clock
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
errors: [exit status 1]
```
