### ISSUE TITLE
No longer able to update

### ISSUE THREAD

**Issue by jason-riddle** [convox/rack#1053]
Not sure when this started happening, but I'm no longer able to update Convox.

```
convox update
Updating convox/proxy: | ERROR: exit status 1
```

I also don't remember ever having to login to anything to start using the tool?

```
convox --version
client: 20160813034921
ERROR: must login first
```

**Comment by mwarkentin** [comment]
Hey @jason-riddle, not sure about the first - but the second will occur if you're not logged in to a rack - either directly or via console.convox.com.

**Comment by ddollar** [comment]
The first error is because the CLI is trying to `docker pull convox/proxy` which is needed for `convox start`. Do you have a working Docker installation locally?

**Comment by jason-riddle** [comment]
Thanks @mwarkentin and @ddollar. Forgot that docker had to be running.
