### ISSUE TITLE
AccessDenied when pushing docker tag during build

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#1071]
Rack version `20160719172302`, this is blocking my production deploys.

This error has happened multiple times today, but never before today.  Always while pushing the docker tag for this process, but different builds (and tags) each time.  Here are logs from one of the `{name: "/build-XXX", image: "convox/api"}` processes:

```
[... snip stuff including a successful looking docker push ...]
Pushing tag for rev [31a461701fc2] on {https://convox-xxxx.us-east-1.elb.amazonaws.com:5000/v1/repositories/garbanzo-api-run/tags/BRMPNTMBXUS}
AccessDenied: Access Denied
    status code: 403, request id: 777DC1CA59889253
2016/08/16 00:07:18 exit status 1
```

There are 100 images in the underlying ECR, which is a suspiciously round number but not close to the limit of 1000.

**Comment by bobzoller** [comment]
Retried deploy twice.  Both times it made it _past_ the first docker tag (the `run` process), but failed on the second docker tag (the `web` process).  But I went into the underlying ECR and neither tag exists.

**Comment by bobzoller** [comment]
deleted all but the last 2 successful deploys worth of tags (2 for `run`, 2 for `web`), and got the same results: the tag of `run` seemed to succeed but AccessDenied on the tag of `web`, and neither tag actually exists in the ECR.

**Comment by mwarkentin** [comment]
@bobzoller Is it possible this is related to some of the permission related work that @MiguelMoll is doing? Looks like you're on an older version of rack, but have you upgraded the CLI lately?

**Comment by bobzoller** [comment]
Have not upgraded the CLI lately.

**Comment by MiguelMoll** [comment]
The permission changes should only come into play when installing a Rack. Building/promoting an app use another set of permissions that have not changed. This is definitely odd and worth checking out.

**Comment by bobzoller** [comment]
happy to screenshare / pair -- ping me on Slack today.

**Comment by bobzoller** [comment]
I'm able to tag a random image and push it manually to that repo.  Don't feel like that rules out an AWS issue, though. (especially as I can see the tags are gone but images remain, eg I still see "Already exists" in the docker push logs)

I tried deleting all the images in that repo, same result.

I've now opened an AWS support ticket.

**Comment by bobzoller** [comment]
I created a fresh convox app and was able to deploy (eg push to its ECR) just fine.  As I hadn't upgraded my rack or CLI, nor changed my app's convox config in a number of days before this suddenly started, I'm more and more convinced I've hit some ECR bug.

I'll continue to update this but don't feel like I need any convox eyes on it for now.

**Comment by bobzoller** [comment]
I'm going to close this for now.  It was more difficult for AWS Support to help since Convox proxies ECR requests, and ultimately I just don't know where the issue lies.  I gave up and deleted and re-created the convox app.

Everything works again with a fresh ECR, but of course the procedure is a bummer because it means a new ELB and I lose my release history.

**Comment by MiguelMoll** [comment]
That is definitely an option of last resort. Hopefully this doesn't show up again.
