### ISSUE TITLE
`convox env` should show complete picture

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#1073]
Currently, `convox env` shows only environment variables set via `convox env` - however environment variables can also be set in the `docker-compose.yml` `environments` declaration.

This means that to get a full picture of the environment variables for a given app, you need to:

* Look at the docker compose file
* Look at the output of `convox env`
* Merge the two in your head (since `convox env set` will override values set in `docker-compose.yml`

Ideally, I think convox should do this for you - running `convox env` could take the values from both, merge, and output the final list of environment variables.

Short discussion in slack:

```

mwarkentin [5:17 PM]  
@ddollar @noah: the `environment` section of `docker-compose.yml` will be used in the app when deployed to a rack, correct? Any thoughts on if `convox env` should use this and “merge” it with the configs stored in s3, for a better picture of what your environment looks like?
I don’t think it works like this at the moment


noah [5:52 PM]  
@mwarkentin: my first thought is that you’re right, `convox env` should show the big picture


jessepollak [5:52 PM]  
@noah: +1 to that idea cc @mwarkentin
```

**Comment by ddollar** [comment]
I don't really want to show these in `convox env` as that is the "overrides" than the complete set. It would be confusing to be able to `convox env unset` them. 

Maybe there is another place to show the complete set but I would be inclined to say use `convox run web export` for now.

**Comment by mwarkentin** [comment]
@ddollar Thoughts on a flag to do the above?

```
$ convox env
FOO=BAR
BAZ=QUX
$ convox env --all
FOO=BAR
BAZ=QUX
DC1=123
...
```

**Comment by ddollar** [comment]
That could possibly work. How would you specify the process?

**Comment by mwarkentin** [comment]
Ah true, processes could look different in this model. A couple options:

* `convox env web`
  * Possibly the simplest, however there's nothing indicating why the response would include more than a normal `convox env` call.
* `convox env web --all`
  * What happens if you try it without the `--all`? Just an error that says you need to set `--all`? That seems annoying.
* `convox env --all=web` or `convox env --process=web`
  * This doesn't seem too bad
* `convox env --all --process=web`
  * Would require more error messages if you forget one or the other option

I think I prefer the first or third option.. any opinions?

**Comment by ddollar** [comment]
`convox run web export` seems more discoverable / natural from a unixy perspective imo
