### ISSUE TITLE
Error creating rack with `--vpc-cidr` BUT without `--subnet-cidrs`

### ISSUE THREAD

**Issue by ephetic** [convox/rack#1079]
```
$ convox install --stack-name=convox-production \
   --region=us-east-1 --instance-count=4 --instance-type=m4.large \
   --vpc-cidr 10.2.0.0/16 \
   credentials.csv
```

The above command failed because Convox tried to create the `10.0.x.0/24` default subnets.  Repeating the command with `--subnet-cidrs 10.2.1.0/24,10.2.2.0/24,10.2.3.0/24` succeeded.

My expectation was the subnets would map to the specified VPC automatically, but there should at least be validation that aborts the command immediately rather than letting CloudFormation fail and rollback.

**Comment by nzoschke** [comment]
Thanks for the report. This has been fixed in the web installer and advanced options, which is the preferred install path now. Feel free to re-open if you're still stuck on CLI installer validation.
