### ISSUE TITLE
Impossible to delete otherwise unreachable rack - solution

### ISSUE THREAD

**Issue by frsechet** [convox/rack#1090]
Rack was "unreachable", so `convox uninstall` wasn't possible.
Cloudformation stack could not delete:
```
10:18:13 UTC+0200    DELETE_FAILED    AWS::EC2::VPC    Vpc    The vpc 'vpc-b1a910d5' has dependencies and cannot be deleted.
10:01:48 UTC+0200    DELETE_COMPLETE    AWS::IAM::Role    CustomTopicRole    
10:01:46 UTC+0200    DELETE_IN_PROGRESS    AWS::IAM::Role    CustomTopicRole    
10:01:43 UTC+0200    DELETE_COMPLETE    AWS::Lambda::Function    CustomTopic    
10:01:42 UTC+0200    DELETE_IN_PROGRESS    AWS::EC2::VPC    Vpc    
10:01:42 UTC+0200    DELETE_IN_PROGRESS    AWS::Lambda::Function    CustomTopic    
10:01:40 UTC+0200    DELETE_COMPLETE    Custom::EC2AvailabilityZones    AvailabilityZones    
10:01:34 UTC+0200    DELETE_IN_PROGRESS    Custom::EC2AvailabilityZones    AvailabilityZones    
10:01:31 UTC+0200    DELETE_FAILED    AWS::EC2::Subnet    Subnet0    The subnet 'subnet-4de64215' has dependencies and cannot be deleted.
10:01:23 UTC+0200    DELETE_IN_PROGRESS    AWS::EC2::InternetGateway    Gateway    
10:01:21 UTC+0200    DELETE_FAILED    AWS::EC2::VPCGatewayAttachment    GatewayAttachment    Network vpc-b1a910d5 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
10:01:11 UTC+0200    DELETE_FAILED    AWS::EC2::Subnet    Subnet2    The subnet 'subnet-12b72d76' has dependencies and cannot be deleted.
```

This seemed to point to IGW.
Deleting IGW by hand failed because of some public adresses in use.
Deleting those adresses by hand failed because they were reallocated automatically by ECS service (which was still running, although the rack was unreachable).
Deleting the ECS service by hand made it possible then for the stack to delete completely.

A possible solution could be: when uninstalling, check for services on that rack, first delete those, then delete the rack?

**Comment by ddollar** [comment]
If CloudFormation fails I would prefer to leave the deletions for the user to take care of. Seems dangerous to start getting into forced deletions and this doesn't come up very often at all so wouldn't be a well-exercised code path.
