### ISSUE TITLE
Add S3 VPC Endpoint

### ISSUE THREAD

**Issue by felixbuenemann** [convox/rack#1092]
The rack's CloudFormation template should include an S3 VPC Endpoint to speed up access to S3 buckets in the same region and save traffic costs caused by routing through the NAT gateways.

Adding a S3 VPC Endpoint will add a prefix list to the VPC which routes traffic to S3 in the same region over the internal network, bypassing NAT and Internet gateways.

VPC Endpoints are free, so this doesn't add any costs. The main difference is that S3 access logs would show the internal IP addresses of hosts instead of their public or NATed address.

Here's an article that compares performance of S3 VPC Endpoint vs. different NAT instances.

My own tests mostly with T2 instances also show much better performance when using the VPC endpoint vs. internet gateway when accessing S3 in the same region. Interestingly without a VPC endpoint access to S3 in the same region was much slower than access to S3 in another region.

Here is an example CloudFormation entry to add an endpoint:

``` json
"S3Endpoint": {
  "Type": "AWS::EC2::VPCEndpoint",
  "Properties": {
    "PolicyDocument": {
      "Statement": [
        {
            "Action": "*",
            "Effect": "Allow",
            "Resource": "*",
            "Principal": "*"
        }
      ]
    },
    "ServiceName": {
      "Fn::Join": [
        "",
        [
          "com.amazonaws.",
          {
            "Ref": "AWS::Region"
          },
          ".s3"
        ]
      ]
    },
    "RouteTableIds": [
      {
        "Ref": "RouteTable"
      }
    ],
    "VpcId": {
      "Ref": "Vpc"
    }
  }
}
```

**Comment by felixbuenemann** [comment]
Why was this issue closed without comment?

**Comment by ddollar** [comment]
It was closed due to age. If you'd like to submit this feature as a PR I would happily review and merge.

**Comment by felixbuenemann** [comment]
Thanks for the explanation.
