### ISSUE TITLE
`convox start` fails to run on cli version `20160818150650`

### ISSUE THREAD

**Issue by eladidan** [convox/rack#1094]
Running `convox start` gives the following error:
```
docker: Error response from daemon: oci runtime error: exec: "python /path/to/py/file": stat python /path/to/py/file: no such file or directory.
```
Running with docker-compose works.
My `docker-compose.yml` looks roughly like this:
```my-process:
  build: .
  environment:
    - KEY1
    - KEY2
    ...
#  this is only uncommented for testing with docker-compose:
#  env_file: .env
  command: python /path/to/py/file
  extra_hosts:
    - "dockerhost:10.0.2.2"
  labels:
    - convox.cron.MyScheduledTask= 00 22 * * ? python /path/to/py/file
```

Running on OS X with docker `Docker version 1.12.0-rc4, build e4a0dbc, experimental` (using `docker-machine` to run containers. not native)

The base image for my `Dockerfile` is `python:2.7.12`. Default `entrypoint`

**Comment by jordansexton** [comment]
I ran into this as well. I was able to get this to work by using the [exec form of `command`](https://github.com/convox/rack/pull/449). In your case, this would be

```
command: [python, /path/to/py/file]
```

**Comment by eladidan** [comment]
@jordansexton thanks, that works

**Comment by awsmsrc** [comment]
@eladidan can you possibly provide the Dockerfile here?

**Comment by eladidan** [comment]
@awsmsrc sorry for late response.
Something like: 
```
FROM python:2.7.12

MAINTAINER eladidan "eladidan@somewhere.com"

WORKDIR /app

COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app
```
Pretty basic stuff
