### ISSUE TITLE
Fix for fluentd service lambda

### ISSUE THREAD

**Issue by skwp** [convox/rack#1103]
The current fluentd service lambda had an error where it would drop log lines that had spaces in the json. We have made a release to the lambda here: https://github.com/reverbdotcom/convox-fluentd/releases/tag/1.0 but it needs to be uploaded to convox's s3 bucket. We added tests for the parser.

**Comment by skwp** [comment]
For more context, this was the fix: https://github.com/reverbdotcom/convox-fluentd/commit/eaf7dc26748e487599c61dccb05caceb7814be74

**Comment by skwp** [comment]
PR here: https://github.com/convox/rack/pull/1112

**Comment by skwp** [comment]
Something else is broken. Did you guys delete an old release? 

**Your access has been denied by S3, please make sure your request credentials have permission to GetObject for convox-us-east-1/release/20160815122924/fluentd.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied**

**Comment by ddollar** [comment]
This should be fixed in the latest rack
