### ISSUE TITLE
app specific SSL cert changed on app deploy after upgrading rack to 20160820033210

### ISSUE THREAD

**Issue by soulware** [convox/rack#1115]
App SSL cert got swapped from ACM managed to a self-signed cert after -
1) upgrading rack to 20160820033210
2) subsequent app deploy

We swapped the cert back to the ACM managed cert in AWS UI and it stayed correctly configured on subsequent deploys so it only appears to happen on the 1st deploy to the new rack.

**Comment by ddollar** [comment]
We discussed this on Slack but it appears the certificate was being set directly on the ELB rather than via Convox/CloudFormation.
