### ISSUE TITLE
health check doesn't work

### ISSUE THREAD

**Issue by contra** [convox/rack#1117]
**Issue:** Unhealthy releases get promoted over healthy ones even when health checks are configured
**Reproduce:** Deploy something that crashes with an error and does not listen to the configured port

**docker-compose.yml**
<img width="404" alt="screen shot 2016-08-22 at 4 18 51 pm" src="https://cloud.githubusercontent.com/assets/425716/17871462/a31d13c0-6889-11e6-8107-a17c00961d2b.png">

**Versions:**
<img width="357" alt="screen shot 2016-08-22 at 4 59 05 pm" src="https://cloud.githubusercontent.com/assets/425716/17871486/c898adda-6889-11e6-860a-f924a3bb81ae.png">

**Comment by contra** [comment]
Still happening on latest rack + CLI

**Comment by contra** [comment]
Haven't seen this happen in a while, I'll self close this

**Comment by contra** [comment]
Just when I thought I was out of the woods on this one, it happened again. Reopening.

**Comment by ddollar** [comment]
Since this appears to be a problem with your specific Rack installation please open this as a ticket inside https://console.convox.com so we can help you investigate.
