### ISSUE TITLE
Updating cron schedule for a scheduled-task has no effect

### ISSUE THREAD

**Issue by eladidan** [convox/rack#1118]
When updating the cron schedule in `docker-compose.yml` file.
e.g.
old:
```
labels:
  - convox.cron.mytask= 00 22 * * ? python /path/to/scheduled/task
```
to new:
```
labels:
  - convox.cron.mytask= 10 22 * * ? python /path/to/scheduled/task
```
After successfully deploying the app, the old schedule is still the trigger for the task's lambda.
![cw-event](https://cloud.githubusercontent.com/assets/5042281/17874591/84f3b712-6881-11e6-99b7-b0c6f904cfce.png)

**Comment by ddollar** [comment]
https://github.com/convox/rack/blob/c163efe9e60e9861c2f67a3944fb3bc6aae8c936/api/models/app.go#L804-L805

If you assign a range variable by reference you will end up with every object holding the same reference

**Comment by skwp** [comment]
Probably related: https://github.com/convox/rack/issues/494 original bug

**Comment by ddollar** [comment]
Fixed
