### ISSUE TITLE
Support [convox scale] locally when using [convox start]

### ISSUE THREAD

**Issue by kabriel** [convox/rack#1119]
When using `convox start` for local development, you cannot scale process counts with `convox scale`

**Comment by ddollar** [comment]
Thinking about a local rack but for right now we are avoiding state management with convox start. Is there something in particular you are trying to test?

**Comment by kabriel** [comment]
Locally trying to spin up multiple processes for one of my services in my app. It would be ideal to have the same tool experience locally and remotely.
