### ISSUE TITLE
Handle environment section in map format

### ISSUE THREAD

**Issue by ddollar** [convox/rack#112]
If you have an environment section like:

```
environment: 
  FOO: bar
  BAZ: qux
```

it will cause failures with the following error:

```
invalid manifest: yaml: unmarshal errors: line 4: cannot unmarshal !!map into []string
```

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gF97lXbe&#x2F;203-handle-environment-section-in-map-format"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Handle environment section in map format</a>

**Comment by RongxinZhang** [comment]
@ddollar is this issue fixed? I still seem to be receiving this error. on `convox deploy`

```yml
Promoting RFNBFONCPQO... ERROR: invalid manifest: yaml: unmarshal errors:
  line 8: cannot unmarshal !!map into []string
```

**Comment by ddollar** [comment]
Someone else also reported this recently. Seems like it's not handling both formats.

**Comment by RongxinZhang** [comment]
@ddollar hmm interesting: This is my docker-compose.yml
```yml
web:
  environment:
    NODE_ENV: "test"
  build: .
  volumes:
    - ./test:/src
  ports:
    - "3000:3000"

**Comment by ddollar** [comment]
Try

```
environment:
  - NODE_ENV=test
```

**Comment by RongxinZhang** [comment]
hm. nope:
```yml
Promoting ROFHMBQOEKK... ERROR: invalid manifest: yaml: unmarshal errors:
  line 7: cannot unmarshal !!str `NODE_EN...` into []string
```

tried:
 ```yml
# without quotes
environment:
  - NODE_ENV=ci

# with quotes
environment:
  - NODE_ENV="ci"
```
and this would break the normal `docker-compose up` command.

**Comment by ddollar** [comment]
Neither of those should break `docker-compose`. You can see we use this format in our own files:

https://github.com/convox-examples/sinatra/blob/master/docker-compose.yml

**Comment by RongxinZhang** [comment]
@ddollar your right. It does work.
This is the only one that doesn't work then.
```yml
NODE_ENV: "test"
```

**Comment by nzoschke** [comment]
This was also reported and investigated here: https://github.com/convox/rack/issues/313

Here's a breadcrumb about what needs to be fixed:

> But it is a bug that docker compose and convox startsupport the other form, but convox deploy doesn't. convox start does better parsing here:
> 
> https://github.com/convox/rack/blob/master/api/manifest/manifest.go#L304
> 
> Where convox deploy does simple YAML unmarshaling here:
> 
> https://github.com/convox/rack/blob/master/api/models/manifest.go#L24

**Comment by RongxinZhang** [comment]
Also noticed that:
```sh
ENV: "test"
ENV: test
```
