### ISSUE TITLE
Implement retry for lambda creation in case IAM propagation takes longer than 5sec

### ISSUE THREAD

**Issue by frankleng** [convox/rack#1120]
when IAM API encounters increased latency, app creation and deploy would fail with `The role defined for the function cannot be assumed by Lambda.`

seems like a case where IAM role is not available after the `put-role-policy` call. can we retry  `lambda create-function` call with a backoff instead of failing immediately?

https://github.com/convox/rack/blob/92b83616fb0ff568dd46b2860beb94a5e20d4948/provider/aws/lambda/formation/bin/create#L5

**Comment by ddollar** [comment]
We added some DependsOn to address this
