### ISSUE TITLE
Cannot link, update or delete service

### ISSUE THREAD

**Issue by d2rk** [convox/rack#1127]
Getting `ValidationError` when running `services link` or `services update`:

```
$ convox --version
client: 20160820024838
server: 20160819234527 (console.convox.com)

$ convox services link syslog-9049 --app foo 
ERROR: ValidationError: Stack [master-syslog-9049] does not exist
                 status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx
```

When trying to delete running service (e.g. `convox services delete syslog-9049`), it says `DELETING` but nothing is happening.

Any suggestions what can cause these problems?

**Comment by bladealslayer** [comment]
I've hit something related, probably. Creating and linking worked for me, but unlinking fails:

```
$ convox services unlink syslog-4629 --app my-app
ERROR: my-app- not found
```

(note the extra dash in the error message).

I have:

```
$ convox --version
client: 20160827235031
server: 20160827184744
```

**Comment by bladealslayer** [comment]
I tracked the issue I was experiencing to this: https://github.com/convox/rack/blob/master/provider/aws/service.go#L198 the `-link` suffix is 5 characters, but the line was changed in 7edd16a, @ddollar.

**Comment by d2rk** [comment]
I've updated rack to the latest version and that fixed all problems:

```
$ convox --version
client: 20160827235031
server: 20160827184744 (console.convox.com)
```
