### ISSUE TITLE
convox using large amounts of CPU

### ISSUE THREAD

**Issue by tommoor** [convox/rack#1129]
When running `convox start` I'm seeing excessive cpu usage between convox and the docker hyperkit process using ~100%, this is with a totally idle, simple sinatra app - it actually makes the fans on my macbook spin sometimes:

![image](https://cloud.githubusercontent.com/assets/380914/17919727/681678d8-6984-11e6-85e1-87482556a808.png)

with the `--no-sync` flag both the convox and hyperkit process use close to zero cpu, and running the same compose.yml with `docker-compose` also yields the same results of low cpu:
![image](https://cloud.githubusercontent.com/assets/380914/17919856/55590502-6985-11e6-8de4-7bc1d8738155.png)

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;1XDRvWbW&#x2F;744-code-sync-using-large-amounts-of-cpu"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Code sync using large amounts of CPU</a>

**Comment by ddollar** [comment]
Fixed in #1243
