### ISSUE TITLE
AWS Throttling Exceptions

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#1133]
We're just short of being plagued by AWS Throttling issues and need some help.

It seems like they occur most frequently during deploys of apps that have many (> 3) processes.  These are coming from CloudFormation DescribeStacks calls being made by the convox builder process.

But perhaps more worrisome is I've also seen scheduled jobs fail to start because the ecs-agent itself gets a throttling exception while pulling the container from ECR.  For jobs that only run daily, this means another 24 hours until it retries.  My unconfirmed hunch is this happens most often during timeframes where multiple scheduled jobs are firing.

I've spent the last few days going around with AWS support in the hopes that I could just get a rate limit increase, but I've just been denied.  Here's the last thing they said on the subject:

> Hello and welcome back,
> 
> Thank you for providing your logs, I have had a look through them and I can see the DescribeStacks API calls being made from your go sdk and also a lambda function. Most of the calls seem to come from the go sdk, for example:
>     {
>       "eventVersion": "1.04",
>       "userIdentity": {
>         "type": "IAMUser",
>         "principalId": "AIDAIB22BVMEYUM5ZFWEE",
>         "arn": "arn:aws:iam::XXX:user/convox/convox-KernelUser-1XJXG1XKLXEHY",
>         "accountId": "XXX",
>         "accessKeyId": "YYY",
>         "userName": "convox-KernelUser-1XJXG1XKLXEHY"
>       },
>       "eventTime": "2016-08-21T02:50:16Z",
>       "eventSource": "cloudformation.amazonaws.com",
>       "eventName": "DescribeStacks",
>       "awsRegion": "us-east-1",
>       "sourceIPAddress": "52.90.31.20",
>       "userAgent": "aws-sdk-go/1.1.18 (go1.6.2; linux; amd64)",
>       "requestParameters": {
>         "stackName": "convox-status"
>       },
>       "responseElements": null,
>       "requestID": "fdca5d41-6749-11e6-a775-1bdec881938c",
>       "eventID": "cafea5f2-ae3a-4722-8372-209909178eef",
>       "eventType": "AwsApiCall",
>       "recipientAccountId": "XXX"
>     },
> 
> From looking at those particular logs for just the DescribeStacks API, it would appear that the calls would range between 2-3 API calls a second which would be in range in my opinion. However I cannot see all of the other API calls being made to CloudFormation so it is hard to say exactly what is causing the throttling.
> 
> I had a chat with once of our CloudFormation Ops team members and unfortunately with the small amount of stacks you have, the service team will most likely deny an API limit increase. They would consider it if you had 1000's of stacks, but at the moment I would recommend you try the work around's I gave you in my previous correspondence.
> 
> These work arounds include using the "DependsOn" attribute in your template which would spread out the API calls so that so many calls won't be made at once. The other option was to increase expontential backoff retries or space out the retries so which would significantly help your issue.

Help!  Our migration to Convox has ground to a halt until we can work around this.  Happy to provide more logs, info, or help on PRs.

/cc @nzoschke

**Comment by nzoschke** [comment]
Are you doing `convox deploy` and tailing the build logs? Can you offer some logs during the deploy that include some of the throttling errors?

In doing some profiling of deploys, I see that the BuildLogs controller is the top offender of API calls. Every second it's querying CloudFormation, DynamoDB and S3.

https://github.com/convox/rack/blob/master/api/controllers/builds.go#L321

I'm working on optimizing this now

**Comment by gwongz** [comment]
I've been running into this issue as well when trying to build with the following rack info:
```
client: 20160820024838
server: 20160820033210 (console.convox.com)
```

**Comment by bobzoller** [comment]
12 hrs on `20160827184744` (which includes #1147) and we haven't had a deploy throttled yet.  decent signal but if we make it another 24-48 hrs without that'll be a great signal.

**Comment by mattbriancon** [comment]
We've the issue on `20160827184744` for the last two days but only on our production rack. Anecdotally, it seems to occur late in the afternoon but that may just be coincidence. Usually resolves itself after a couple more attempts to deploy.

**Comment by bobzoller** [comment]
I haven't seen a throttled deploy since #1147 went live on our rack 2 weeks ago.  Closing.
