### ISSUE TITLE
fluentd lambda missing for old release 20160815122924

### ISSUE THREAD

**Issue by skwp** [convox/rack#1143]
When merging #1112 please could you make sure that it is put into the buckets for old releases? Otherwise any attempt to use a service link will fail in cloudformation:

Your access has been denied by S3, please make sure your request credentials have permission to GetObject for convox-us-east-1/release/20160815122924/fluentd.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied

**Comment by ddollar** [comment]
Fixed in #1144
