### ISSUE TITLE
scheduled jobs fail to start due to AWS ThrottlingException

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#1164]
(splitting the scheduled jobs issue out from #1133)

I've seen scheduled jobs fail to start because the ecs-agent itself gets a throttling exception while pulling the container from ECR. For jobs that only run daily, this means another 24 hours until it retries. My hunch was this happens most often during timeframes where multiple scheduled jobs are firing, but he ecs-agent logs show a completely idle agent before attempting to pull the container.

I tried asking ECS for help resolving this as it seemed like a bug on their end (either ecs-agent or ECR), but they've now pushed back and said the lambda that starts the task should have a retry built into it to cover this case, so we're back in Convox-land.

Here's their reply:

> 2016-08-25T12:00:04Z [INFO] Adding event module="eventhandler" change="ContainerChange: arn:aws:ecs:us-east-1:XXX:task/2b5f1779-0765-4d87-8f11-5ee8e29f657a run -> STOPPED, Reason CannotPullECRContainerError: ThrottlingException: Rate exceeded
        status code: 400, request id: 75567eb3-6abb-11e6-9d4c-cb4ccd1cee97, Known Sent: NONE"
> 
> Is related to the GetAuthorizationToken call in the ECS agent. The current TPS limit is 1 TPS with 30 TPS burst for fetching a new token. This isn't a limit that can be changed at the moment, but we're looking in making improvements so we can increase it, as well as cache tokens in the ECS agent.
> 
> We would recommend adding backoff and retry in your run task from the lambda call for the moment.

/cc @nzoschke

**Comment by ddollar** [comment]
Fixed by #1205

**Comment by bobzoller** [comment]
haven't seen a throttling issue in 7 days.  closing!
