### ISSUE TITLE
API calls, involving ServiceGet fail when service has linked apps

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#1167]
API calls that involve `ServiceGet` fail when service has linked apps. For example, unlinking fails:

```
$ convox services unlink syslog-4629 --app my-app
ERROR: my-app- not found
```

(note the extra dash in the error message).

I have:

```
$ convox --version
client: 20160827235031
server: 20160827184744
```

This seems to be due to change in https://github.com/convox/rack/blob/master/provider/aws/service.go#L198 from 7edd16a, which leaves an extra dash in the app name. Changing the offset to `-5` fixes the issue, at least in my dev environment (ping @ddollar).

**Comment by ddollar** [comment]
Addressed by #1182

**Comment by jessepollak** [comment]
We're running into this issue - looking forward to a fix!

**Comment by jessepollak** [comment]
We also seem to running into this issue while using `convox services link syslog`. Is that the same or different?

**Comment by bladealslayer** [comment]
Works after #1182 (release 20160910125708).
