### ISSUE TITLE
Error creating Rack in regions with less than 3 Availability Zones

### ISSUE THREAD

**Issue by johnboy14** [convox/rack#117]
I get the following error when trying to create a rack in the ap-northeast-1 region.  

Failed AWS::EC2::Subnet: CustomResource attribute error: Vendor response doesn't contain AvailabilityZone2 key in object arn:aws:cloudformation:ap-northeast-1:645639678282:stack/convox/c60e8830-7723-11e5-a1e4-50ba4cba06d2|AvailabilityZones|afe29def-215d-435e-813c-7fb98c39a5f9 in S3 bucket cloudformation-custom-resource-storage-apnortheast1

**Comment by nzoschke** [comment]
Thanks for reporting this issue. This is a bug, as the expectation in the installer is that Convox should run everywhere where ECS and Lambda are available:

us-east-1, us-west-2, eu-west-1, ap-northeast-1

https://github.com/convox/rack/blob/master/cmd/convox/install.go#L61

There is previous work around CloudFormation in regions with less than 3 AZs in this (unfortunately dead) PR:

https://github.com/convox/kernel/pull/149

**Comment by ddollar** [comment]
Is this still valid?

**Comment by ddollar** [comment]
http://aws.amazon.com/about-aws/global-infrastructure/ shows several regions that still have only 2 AZs

**Comment by nzoschke** [comment]
This was fixed in https://github.com/convox/rack/pull/1033!

**Comment by mzelinsky** [comment]
Was it really fixed? I can't install convos in VPC with only 2 subnets (per zone), https://github.com/convox/rack/blob/f239d2854294b3c49e897bf815bff88d339182ab/cmd/convox/install.go#L220 says it all
