### ISSUE TITLE
"update in progress" on cloudformation not reflected on web panel

### ISSUE THREAD

**Issue by contra** [convox/rack#1172]
When CF looks like this during a deploy:

<img width="360" alt="screen shot 2016-08-31 at 1 13 22 pm" src="https://cloud.githubusercontent.com/assets/425716/18138861/c5382e50-6f7c-11e6-892c-48b215c23891.png">

The dashboard looks like this:

<img width="648" alt="screen shot 2016-08-31 at 1 13 32 pm" src="https://cloud.githubusercontent.com/assets/425716/18138865/cb1da5f2-6f7c-11e6-9ec7-9d1a248835af.png">

Seems like a bug, because sometimes the panel will reflect "Updating" with a yellow badge, but usually it doesn't seem to notice an update is happening.

**Comment by ddollar** [comment]
This status pulls directly from the CloudFormation status for the stack (the one that is shown in the top listing of stacks)

**Comment by ddollar** [comment]
Closing for now. If you see this again please capture a screenshot of the stack in the top listing of all the stacks that shows the stack status.
