### ISSUE TITLE
ps should include processes started with run

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#118]
`convox ps` should include processes started with `convox run`

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RKD2ambE&#x2F;214-convox-kill"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> `convox kill`</a>

**Comment by nzoschke** [comment]
This has landed. https://github.com/convox/rack/pull/270

**Comment by bobzoller** [comment]
:fireworks:
