### ISSUE TITLE
routing policy during a deployment

### ISSUE THREAD

**Issue by contra** [convox/rack#1183]
Is there any way to configure how new requests are routed during a deployment?

**Current issue**:

- User browser gets index.html from V2, which has a link to example.js
- User browser requests example.js, request gets routed to V1 which doesn't have example.js so it 404s

This happens until all old servers are gone, which can take up to 20-30 mins sometimes.

**Proposed solution**:

- During a deploy, keep routing requests to existing servers (let's call it V1)
- The second a server with newer code comes online during a rollout, start routing all new requests to the new server (V2)
- As requests to V1 servers finish, spin them down (convox already does this)

The goal is to stop routing requests to old code ASAP. This could be hidden behind a label to preserve backwards compat.

**Comment by ddollar** [comment]
We use ELB cookie-based affinity to try to keep users pointed at the same backend for the life of their session. https://github.com/convox/rack/blob/master/api/models/templates/app.tmpl#L451
