### ISSUE TITLE
convox run should pick a random machine

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#119]
currently, `convox run` launches the container on the same machine as the kernel.  it'd be more scaleable if it picked a random machine in the rack, and even better if it picked a machine based on available resources.

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;oG6z2rjP&#x2F;216-balance-convox-run-across-cluster"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> balance `convox run` across cluster</a>

**Comment by nzoschke** [comment]
Detached runs are started as a ECS task and therefore are scheduled well.

Agreed attached runs should be scheduled better.

**Comment by ddollar** [comment]
Fixed in #1231
