### ISSUE TITLE
Add support for tuning health check interval and healthy/unhealthy thresholds

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#1191]
Customising check interval and HealthyThreshold and UnhealthyThreshold were part of the proposal in #755, but got dropped (for simplicity?). It would be nice to have support for those, as they can be useful to avoid state flapping.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setting ELB helath check interval](https://trello.com/c/Hmkc2wK5/1296-setting-elb-helath-check-interval)
