### ISSUE TITLE
Error creating webhooks in PrivateApi rack

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1193]
I have a rack with

```
Private=Yes
PrivateApi=Yes
```

When I try to create a webhook service I see this error in CloudFormation:

![unspecified-27](https://cloud.githubusercontent.com/assets/44615/18284048/50cf2a3c-7436-11e6-8408-f3d645db2aaa.png)

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZbTrgxfn&#x2F;661-error-creating-webhooks-in-privateapi-rack"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Error creating webhooks in PrivateApi rack</a>

**Comment by MiguelMoll** [comment]
At this time, SNS does not support VPC endpoints. http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html#SendMessageToHttp.subscribe
