### ISSUE TITLE
the services create cli command doesn't support the rackflag

### ISSUE THREAD

**Issue by awsmsrc** [convox/rack#1202]
this is because we intentionally skip flag parsing due to all the different flags the different service types handle

this is the cause of: https://github.com/convox/console/issues/513

**Comment by redroot** [comment]
+1 just experienced this as well

**Comment by soulshake** [comment]
Why do we skip flag parsing instead of using `--` like in bash builtins?

From `man bash`:

```
--        A -- signals the end of options and disables further option processing.  Any arguments
          after  the  -- are treated as filenames and arguments.
```

**Comment by ddollar** [comment]
Deupe of #1107
