### ISSUE TITLE
unable to rollback app after upgrading rack

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#1204]
After upgrading our rack to `20160827184744`, we needed to rollback our `pick-api` app to a release that pre-dated the rack upgrade.  That CloudFormation update failed while recreating the `CustomTopic` Lambda with the following error:

```
01:59:45 UTC-1000	UPDATE_FAILED	AWS::Lambda::Function	CustomTopic	Your access has been denied by S3, please make sure your request credentials have permission to GetObject for convox-us-east-1/release/20160827184744/formation.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied
Physical ID:convox-pick-api-CustomTopic-4DAD4IHEBPF2
```

**Comment by ddollar** [comment]
Pretty sure this happened because we locked down the credentials in Rack more. This should be a one-time thing that won't have to happen again. Sorry about that!
