### ISSUE TITLE
log tailing doesn't work after upgrade to 20160905130000

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#1206]
Log tailing doesn't seem to follow new log entries after upgrading a stack to the latest release. Perhaps related to #1188? After running a `convox logs` or `convox rack logs` command, I receive the current chunk of logs, but no more output is shown.

**Comment by frewsxcv** [comment]
Running into this issue as well on `20160905130000`.

**Comment by ddollar** [comment]
Should be fixed by #1209

**Comment by bladealslayer** [comment]
Looks like it's fixed with #1209 (release https://github.com/convox/rack/releases/tag/20160910125708).
