### ISSUE TITLE
support multiline env vars

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1208]
- [ ] change storage format to json
- [ ] add json support to POST /apps/:app/environment via content-type
- [ ] `cat config.yml | convox env set CONFIG`

/cc @joshk

**Comment by mwarkentin** [comment]
Curious on the use case for this?

**Comment by ddollar** [comment]
Certificates or config files in env vars.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;suG9J1DR&#x2F;709-multiline-env-vars"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> multiline env vars</a>

**Comment by mwarkentin** [comment]
We just ran into a use case for this (certs). :)

**Comment by soulware** [comment]
:+1: for handling certs in env vars like this

**Comment by mwarkentin** [comment]
We've figured out that we can use [`sneaker`](https://github.com/codahale/sneaker) in our app containers to deal with this for now.

**Comment by soulshake** [comment]
Another possible workaround in the meantime could be encoding the key into a string with something like base64 and decoding it app-side if possible. (source: @mattmanning )
