### ISSUE TITLE
convox uninstall failed

### ISSUE THREAD

**Issue by aaronfeng** [convox/rack#121]
```
$ convox uninstall
Uninstalling Convox...
Deleted Access Key: xxxx
Skipped S3 Bucket: xxxx
Deleted ECS Service: Kernel
Deleted IAM User: xxxx
Deleted ECS TaskDefinition: KernelTasks
Skipped S3 Bucket: xxxx
Deleted Access Key: xxxx
Deleted Access Key: xxxx
Deleted KMS Key: EncryptionKey
Deleted IAM User: xxxx
Deleted IAM User: xxxx
Deleted Routing Table: xxxx
Deleted DynamoDB Table: xxxx
Deleted DynamoDB Table: xxxx
Deleted Kinesis Stream: xxxx
Deleted AutoScalingGroup: xxxx
Deleted ECS Cluster: xxxx
Deleted Elastic Load Balancer: convox
Deleted Security Group: xxxx
Deleted VPC Subnet: xxxx
Deleted Security Group: xxxx
Deleted VPC Internet Gateway: xxxx
ERROR: stack deletion failed
```

Stack deletion failed because RDS/Redis was still running.  This caused other resources such as routing table, VPC not to be cleaned up properly.  I ended up deleting resource by hand in reverse order: routing table, subnets, interface, rds, redis, and a few more things.

**Comment by csquared** [comment]
Thanks, @aaronfeng !  I think the right thing to do here is block the uninstall until everything has been deprovisioned. We can add an `uninstall --force` later.

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;FmoQ3h7x&#x2F;215-convox-uninstall-with-other-services"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> `convox uninstall` with other services</a>

**Comment by nzoschke** [comment]
Thanks for the report. Uninstall now instructs you to delete active services first. It also automatically retries the stack delete to assure the VPC gets removed correctly.

https://github.com/convox/rack/pull/286
https://github.com/convox/rack/pull/283

**Comment by RongxinZhang** [comment]
@nzoschke Uninstall is now "installing".

![screen shot 2016-01-28 at 3 24 34 pm](https://cloud.githubusercontent.com/assets/3782456/12662173/474b2a54-c5d3-11e5-9a23-8e7d919a8289.png)

**Comment by RongxinZhang** [comment]
It seems to be a messaging issue. Just change `install` to `uninstall`
