### ISSUE TITLE
Generate SSL certificates with Let's Encrypt

### ISSUE THREAD

**Issue by ianwalter** [convox/rack#1214]
I know this was suggested in #212 but it looks like it never made it in and the referenced issues don't say anything about Let's Encrypt. It would be a killer feature if Convox set up a Lambda function to generate, store, and renew the certificates for you with Let's Encrypt. Maybe I'm missing something but ACM seems like a very poor default solution.

**Comment by ddollar** [comment]
ACM certs can be generated for any domain you control and will automatically renew forever. Why do you feel that ACM is a poor default solution?

**Comment by ianwalter** [comment]
Sorry you're right, I still don't like that it uses email to verify, but it is a good default solution so I'll close this, thanks.
