### ISSUE TITLE
Add --desc flag to builds import or maintain source build description

### ISSUE THREAD

**Issue by redroot** [convox/rack#1216]
We use the `--desc` flag during deploys to our staging environment set the current Git SHA, this is lost when you use `builds import` as the description becomes `imported`. It would useful to either a) not override the builds description if it exists or b) be able to set the description again during import

Related line from original PR is here https://github.com/convox/rack/pull/1145/files#diff-9b8f498288da1f0280f0a0b5e46878d3R382

**Comment by ddollar** [comment]
Fixed in #1274 (imported builds maintain description)
