### ISSUE TITLE
`convox build --id` behaves differently than `convox deploy --id`

### ISSUE THREAD

**Issue by frewsxcv** [convox/rack#1219]
`--help` docs for both `convox build` and `convox deploy` mention:

```
--id                build logs on stderr, build id on stdout (useful for scripting)
```
### `convox build --id 2> error.txt 1> build.txt`
- build.txt: Contains the ID of the build
- error.txt: Contains the logs of the build (stdout)
### `convox deploy --id 2> error.txt 1> build.txt`
- build.txt: Contains stdout
- error.txt: Empty (presumably contains stderr)

So, from what I understand, `--id` on `convox deploy` has no effect.

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6EYHyBWQ&#x2F;700-convox-build-id-behaves-differently-than-convox-deploy-id"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> &#x60;convox build --id&#x60; behaves differently than &#x60;convox deploy --id&#x60;</a>
