### ISSUE TITLE
--no-cache doesn't pull updated "latest" image referenced in Dockerfile

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1222]
When a Dockerfile has

`FROM namespace/image:latest`

building with `--no-cache` will not actually refresh latest.

The correct image is used when building with a version-specific tag rather than `latest`, though.

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ss613DSy&#x2F;683-clef-basic-convox-build-doesn-t-pull-latest-image-tag"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> clef (basic): convox build doesn&#39;t pull latest image tag</a>

**Comment by jessepollak** [comment]
Thanks Matt!

**Comment by ddollar** [comment]
Fixed in #1231

**Comment by jessepollak** [comment]
Thanks y'all!
