### ISSUE TITLE
Add more options to SQS service

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1236]
A customer has requested the ability to set `ReceiveMessageWaitTimeSeconds`, `VisibilityTimeout`, and `MessageRetentionPeriod` via SQS service.

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mD6BZ8d9&#x2F;723-setting-properties-for-sqs-service"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Setting properties for SQS service</a>

**Comment by ddollar** [comment]
Fixed in #1261
