### ISSUE TITLE
Default ELB Port Configuration is TCP, but TCP + ProxyProtocol or HTTPS is a better default for many cases

### ISSUE THREAD

**Issue by andykent** [convox/rack#124]
When adding ports to an app they default to TCP. This is a problem for many HTTP based projects as it means you don't get the `HTTP_X_FORWARDED_*` headers added by the ELB like you would if they were setup as HTTP.

It's especially problematic when using SSL termination as it means you don't get the `HTTP_X_FORWARDED_PROTO` header.

For now I have manually edited my ELB port settings but this felt pretty ugly.

It would be nice if this was configurable somehow.

I would also argue that HTTP should be the default as I think that is likely to be by far the most common use case.

**Comment by matthewford** [comment]
:+1:

**Comment by csquared** [comment]
We've had a similar issue but solved it another way. We're terminating SSL at the container level by running an haproxy instance.

We then create the ssl listener with `convox ssl create --secure`, which takes care of setting up the ELB right by mapping the external port 443 to whatever you've told us in your `docker-compose.yml`
 
The only annoying part here is creating a script that generates a self-signed cert on bootup (for haproxy), but that's only a few lines of bash.

**Comment by matthewford** [comment]
Just got bitten by this again, should be documented and ideally configurable

**Comment by mtrofimm** [comment]
+1

**Comment by ddollar** [comment]
a good first step would be turning that into a parameter on the app cloudformation stacks
https://github.com/convox/rack/blob/master/api/models/templates/app.tmpl#L217
https://github.com/convox/rack/blob/master/api/models/templates/app.tmpl#L274

once it's a param you can at least change it manually and be sure convox won't overwrite the change
then we can look at how to bring that knob out into the cli

**Comment by mwarkentin** [comment]
@ddollar Your links are not pointing to the right spot anymore, can you re-point the places that would need to be parameterized?

If you press `y` while on a github page, it will change the url to include the git commit hash, which guarantees that things don't move around on you. :smile:

**Comment by ddollar** [comment]
The main argument against doing this automatically is that websockets do not work on ELB HTTP listeners.

**Comment by dlanger** [comment]
@ddollar That makes sense - although not doing it means that any app that collects IPs for user analysis and tracking (or even something like detecting an attack) is broken out-of-the-box, and those are pretty common things to do.

I've started a PR to add a parameter to the stack in https://github.com/dlanger/rack/pull/1, but I'm not sure where to take it from there.

**Comment by matthewford** [comment]
Implementing https://github.com/convox/rack/issues/320 would also close this issue.

**Comment by nzoschke** [comment]
You can now turn on Proxy Protocol thanks to https://github.com/convox/rack/issues/320

**Comment by soulware** [comment]
My preference would be TCP/SSL + Proxy Protocol as the default.

**Comment by idyll** [comment]
TCP/SSL with Proxy Protocol is what I will use. So if it’s not the default please make it easy for me.

**Comment by dlanger** [comment]
My two cents would be HTTPS by default, with an easy switch to TCP/SSL + Proxy. I feel like the most common thing to run on Convox is a web service, and most docs out there assume your LB sets `X-Forwarded-For` properly. 

If we stick with TCP/SSL as the default, I think we should at the least have a section in the docs covering what to do if you're running a web server and want to get the origin IP (with a link to the nginx etc. docs on Proxy Protocol).

**Comment by peterlauri** [comment]
I think default for 80/443 could be default. And when uploading ssl, it would swap to HTTPS for the respective port listener. All other ports than 80/443 could default to TCP.

**Comment by nzoschke** [comment]
This is effectively solved with the Load Balancer labels. Docs: https://convox.com/docs/load-balancers/

Thanks for all the feedback everyone :)
