### ISSUE TITLE
"docker login" Password exposed to command line.

### ISSUE THREAD

**Issue by Incognito** [convox/rack#1246]
While using Convox I noticed that the password for docker login is exposed in base64 to the command line. I know this is ultimately an upstream issue where docker hasn't made a decision on what to do about this, but I think Convox can make this situation less prone to attack.

Presently if I run some threat analysis or logging software against my convox hosts I'll receive log entries such as `docker login -e foo@bar.com -u  FOO -p Y2xlYXJ0ZXh0IHBhc3N3b3Jk`.

I believe this can be passed as an env-var or perhaps just a temporary bash variable exposed to only to `rack`, so the log might look something like: `docker login -e foo@bar.com -u  FOO -p $FOO_PASSWORD_7`.

There's some "prior art" that appears to solve this problem in in similar situations. For example, some command line programs refuse to accept (or have deprecated) password parameters due to security concerns about leaking sensitive credentials. This sort of setup is also common among production web servers that store database passwords outside of the codebase and want to prevent logging the actual password (or storing it in source control).

Relevant code: https://github.com/convox/rack/blob/f9af7a356a95807bd4c40a33b41c8008c78ad8fd/api/models/docker.go#L124

I'm happy to answer any questions about this. :)

**Comment by ddollar** [comment]
This is fixed in #1231 thanks!
