### ISSUE TITLE
Rack/apps become unreachable after all instances get agent set to false

### ISSUE THREAD

**Issue by frsechet** [convox/rack#1247]
On a rack with version `20160916121812` and Autoscale=Yes, all instances suddenly set agent to false and the rack and apps became unreachable.
The ECS services still mostly showed "X desired, X running", but a few services had "X desired, 0 running".

A manual termination had new instances immediately restart and the service came back to normal.

Convox/ECS should have terminated those instances automatically and replaced them.
Also, no reason why the agent on 3 instances would become false at once (no change was performed to the rack at that moment).

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XnQCTfmC&#x2F;753-rack-apps-become-unreachable-after-all-instances-get-agent-set-to-false"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Rack&#x2F;apps become unreachable after all instances get agent set to false</a>

**Comment by ddollar** [comment]
Not sure what happened here but don't have much to go on. If you see behavior like this again please open a ticket in Console and we can work with you to diagnose in place.
