### ISSUE TITLE
List and kill one-off process

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#125]
We start many processes via detached run, and need the ability to kill those processes later.  I think this means the run API should return the pid, and there should be a new API and `convox kill` command that accepts one or more pids to terminate.

related to #118

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RKD2ambE&#x2F;214-convox-kill"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> `convox kill`</a>

**Comment by nzoschke** [comment]
This will land soon and expose a PID in the Process List API.

https://github.com/convox/rack/pull/270

The Process Kill API does not yet handle terminating these.

**Comment by nzoschke** [comment]
I think https://github.com/convox/rack/pull/270 was backed out. Changing the title of this as a reminder fix it too.

**Comment by nzoschke** [comment]
This was addressed in https://github.com/convox/rack/pull/394. Update to 20160302193502 and give it atry.
