### ISSUE TITLE
`convox services url` does not work with S3 service

### ISSUE THREAD

**Issue by jmcvetta** [convox/rack#1251]
When running an S3 service in Convox, the `convox services info` command correctly displays the S3 bucket's URL.  However the `convox services url` command does not work.  For example:

```
$ convox --version
client: 20160921211114
server: 20160916121812 (console.convox.com)
(dev) ---{18:02:02}-{jmcvetta@carbon}-{~/work/revrocket/rrapp}---

$ convox services info revrocket-static
Name    revrocket-static
Status  running
Exports
  URL: s3://SECRET:SECRET@oregon-revrocket-static
(dev) ---{18:02:19}-{jmcvetta@carbon}-{~/work/revrocket/rrapp}---

$ convox services url revrocket-static
ERROR: URL does not exist for revrocket-static
```

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [`convox services url` should return a URL](https://trello.com/c/PjoVxUzD/1184-convox-services-url-should-return-a-url)
