### ISSUE TITLE
autoscaling goes insane during any change

### ISSUE THREAD

**Issue by contra** [convox/rack#1257]
Reproduce by: Rolling an API key, doing a deploy, changing an SSL cert - literally anything that does a cloudformation update.

It does this crazy thing where it one by one recycles every instance, and spends about 15 minutes doing each one. That means changing an SSL cert takes over an hour to finish in cloudformation, during this period you can't touch your rack at all since it is updating. This is really really wild.

### Info

<img width="296" alt="screen shot 2016-09-23 at 6 12 52 pm" src="https://cloud.githubusercontent.com/assets/425716/18802836/62a750dc-81b9-11e6-97f1-17f6f0677633.png">

- Rack version is `20160922164843`
- I'm running 5 instances of a node process.
- I have autoscaling on.
- I have these labels:

```yaml
labels:
    - convox.port.443.protocol=https
    - convox.port.80.protocol=http
    - convox.health.port=3000
    - convox.health.path=/v1/tables
    - convox.health.timeout=30
    - convox.deployment.minimum=100
    - convox.deployment.maximum=200
    - convox.start.shift=8000
    - convox.idle.timeout=120
```

### CloudFormation Logs

(Read from bottom to top)

<img width="1307" alt="screen shot 2016-09-23 at 6 09 36 pm" src="https://cloud.githubusercontent.com/assets/425716/18802769/ef08b1ac-81b8-11e6-9d06-d4d94684be88.png">

<img width="1346" alt="screen shot 2016-09-23 at 6 04 21 pm" src="https://cloud.githubusercontent.com/assets/425716/18802671/43976f7a-81b8-11e6-9772-d91271cebcab.png">

**Comment by ddollar** [comment]
Need to document Autoscale

**Comment by contra** [comment]
@ddollar What other info do you need?

**Comment by ddollar** [comment]
I think this issue is conflating Amazon's AutoScalingGroup with Convox's autoscale feature.

AWS AutoScalingGroups will roll instances any time configuration changes. Changing the Rack API key changes instance userdata which requires rolling the instances.

Changing an SSL certificate should not affect anything related to AutoScaling.

If you open a ticket on Console we can help dig in to your specific instance of Rack to figure out what might be going on.

**Comment by ddollar** [comment]
I'm going to close this issue as it is related to a specific installation of Rack. 

We are also going to add more documentation about Convox autoscaling and how it works.

**Comment by contra** [comment]
@ddollar Were you not able to reproduce it? I can spin up a new rack and make this happen pretty reliably, so it isn't like I did anything weird to my rack that makes this not a real problem.
