### ISSUE TITLE
status "rollback_failed" shows as "running"

### ISSUE THREAD

**Issue by frsechet** [convox/rack#1266]
When in a state when an app deploy fails and a rollback also fails, CloudFormation is in status `rollback_failed`. However, convox shows that as `running`, and doesn't prevent new deploys.

Of course, they can't deploy, but `convox apps info` should reflect that status so you know something is wrong and you have to go into cloudformation and force the rollback.

Ideally, this rollback forcing should be automatic or at least doable from convox CLI...

**Comment by nzoschke** [comment]
This is fixed in https://github.com/convox/rack/pull/1945.
