### ISSUE TITLE
`convox install` should respect AWS_DEFAULT_REGION envvar 

### ISSUE THREAD

**Issue by soulshake** [convox/rack#1267]
# What I do

`$ export AWS_DEFAULT_REGION=eu-central-1`
`$ convox install --stack-name dev`

# What happens

The rack gets installed in the `us-east-1` region.

# What I expect to happen

The rack gets installed in the `eu-central-1` region.

# Reasons this is a problem

Because a user gets logged in directly to the rack at the end of the installation process, commands like `convox ps`, `convox apps` etc are no longer being applied to the expected region, so apps and processes don't show up, which is confusing.

`convox switch <racks in other region(s)>` fails silently.

# Workaround

* Delete the wayward rack with `convox uninstall <rack> <region>`, then run `convox install` again, specifying `--region`, or
* Run `convox login console.convox.com` again, and you'll need to manually add the rack you installed to console (its hostname and password can be found in `~/.convox/auth`).

**Comment by ddollar** [comment]
Fixed in #1270
