### ISSUE TITLE
"not enough memory available to start process" during deploy

### ISSUE THREAD

**Issue by contra** [convox/rack#1272]
<img width="1276" alt="screen shot 2016-09-28 at 5 02 30 pm" src="https://cloud.githubusercontent.com/assets/425716/18932210/657b125c-859d-11e6-809f-b156d0dd2bac.png">

<img width="460" alt="screen shot 2016-09-28 at 5 03 03 pm" src="https://cloud.githubusercontent.com/assets/425716/18932232/749f47f8-859d-11e6-9e4d-2f0f65ca5241.png">

**Comment by ddollar** [comment]
That means you don't have enough available space on your cluster to run a build (which may also explain some of the other issues you have been seeing)

What is the type/count your Rack is scaled to?

**Comment by contra** [comment]
@ddollar Last screenshot has that info

**Comment by ddollar** [comment]
Sorry about that. You can try `convox rack params set BuildMemory=NNN` where NNN is a number in MB. The default is 1024.

**Comment by contra** [comment]
@ddollar Updated from a t2.micro to a t2.small, which has 2GB of RAM (should be more than enough for the 1GB default build memory) - now getting a hang for 10+ minutes, then CI kills it.

Shouldn't the build memory be based on the size of the instance, with a max of 1GB? Otherwise t2.nano and t2.small will always fail to deploy.

**Comment by ddollar** [comment]
Probably, but trying to keep this already-complicated release as small as possible. The default size works well with the default rack instance type. Planning to update Console to help pick most of these values automatically.

**Comment by ddollar** [comment]
Closing this for now as you should be able to work around this error with the command pasted above.

**Comment by contra** [comment]
@ddollar If the problem is valid and something you want to fix at some point shouldn't the issue stay open? Otherwise I feel like this is going to get lost in the void for good.

**Comment by contra** [comment]
Still happening even on a t2.small (2GB RAM, way more than what should be needed). Any ideas?

<img width="1273" alt="screen shot 2016-09-28 at 10 21 41 pm" src="https://cloud.githubusercontent.com/assets/425716/18938879/fb8e836a-85c9-11e6-9197-4b06ba2dbe6b.png">

**Comment by contra** [comment]
Can I get this reopened since this is still a bug/regression?

**Comment by contra** [comment]
Ping - I haven't been able to deploy for two weeks because of this bug. Can this please be reopened?

**Comment by nadurthi** [comment]
I am also experiencing the same problem.

**Comment by contra** [comment]
@nadurthi Any workaround? I feel like I've tried everything - increasing the memory of the instances or the build memory seems to do nothing. Decreasing the build size helps maybe 1/100 deploys but is unpredictable.

**Comment by ddollar** [comment]
@contra Are you still on t2.small? Could you please paste the output of `convox rack params | grep Build`

**Comment by contra** [comment]
@ddollar I've tested t2.micro, t2.small, and t2.medium with build memory ranging from 512mb -> 2048mb

```
$ convox rack params | grep Build

BuildCpu                 0
BuildImage
BuildMemory              2048
```

**Comment by ddollar** [comment]
The error you are seeing is that there is not enough room on the ECS cluster to schedule the build process.

Try changing `BuildMemory` to be smaller. `BuildMemory` is the memory reserved for the build task on the ECS cluster. Try `t2.small` and `BuildMemory=256` or `BuildMemory=512`

**Comment by contra** [comment]
@ddollar 512 same error, 256 it hangs forever pretty reliably.

**Comment by cadebward** [comment]
`convox rack params set BuildMemory=512` fixed this for us. On t2.micro

**Comment by electroma** [comment]
I run with BuildMemory=1024 and latest version (20161206211458) - still get "not enough memory available to start process" randomly. Any suggestions?

**Comment by ddollar** [comment]
Anyone still seeing these issues?

**Comment by contra** [comment]
@ddollar I decreased the project size to work around it, but the issue is still there on a large project.

**Comment by bleib1dj** [comment]
@ddollar We just started seeing this today as well (Release 20170210204814). Running `convox rack params set BuildMemory=512` fixed it for us for the time being.

**Comment by mikeover** [comment]
Seeing this also with micro instances and the starter convox/rails app. Tried setting BuildMemory to 512 but problem persists.

**Comment by peterhel** [comment]
512 seems to fix it for me.

**Comment by contra** [comment]
Tagged as `needsinfo`, what info do you need?

**Comment by nzoschke** [comment]
I'm also seeing this on a build instance. In this case the instance has 15 GB of memory, which concurrent builds can consume.

My first inclination is to turn off all memory placement constraints and limits entirely, which is how `BuildCpu=0` works. However it doesn't look like `BuildMemory=0` is a valid input without conditionally not specifying memory at all.

I'm also not entirely sure how build performance would be impacted by removing all memory limits, but I predict it will be a fine experience, and better than all builds getting blocked for an indefinitely time window.

```
$ convox rack params | grep Build
BuildCpu                 0
BuildImage
BuildInstance            c4.2xlarge
BuildMemory              2048
```

**Comment by contra** [comment]
@nzoschke Might be a diff issue - mine is from `convox run` not build.

**Comment by nzoschke** [comment]
@contra most of the comments here indicate build errors.

However I think every "not enough memory available to start process" error is related. `convox build`, and `convox run` both try to schedule new tasks in the cluster. This can easily get blocked based on the task memory reservation vs the total cluster size / other running tasks.

I think a good general approach for one-offs is to use a small soft memoryReservation value.

https://github.com/convox/rack/pull/2212 opens up this path for builds, however you may still need to tune BuildMemory.

I'll do some experimentation to see if we can/should default builds/runs to something like `MemoryReservation=64` to eliminate this class of error entirely.

-Noah

**Comment by RedaBenh** [comment]
I get often this issue.
Running `convox rack params set BuildMemory=512`  fixed this for us. 
```

BuildCpu                    0
BuildMemory              512
InstanceCount            3
InstanceType             t2.small
```
