### ISSUE TITLE
Autoscaling does not trigger when new build task needs to run

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#1279]
Autoscaling doesn't seem to trigger when a new build task has to be executed on rack version `20160928105531`. As a result, if the rack doesn't have 1GB of free memory (the current default for build task) on an ECS instance, the build fails.

This makes it impossible to deploy on a rack with autoscaling under some conditions. Ideally, the rack would scale up and run the build automatically.

**Comment by ddollar** [comment]
What are the current scale parameters of your rack? (count, instance size)

**Comment by ddollar** [comment]
We try to always leave at least one extra instance worth of capacity when autoscaling.

**Comment by bladealslayer** [comment]
This is a testing rack with t2.small instances. Based on currently deployed apps, autoscaler computes 4 instances, but all of them had < 1024MB free memory. Memory reservation was ~ 74%.

**Comment by ddollar** [comment]
Gotcha. We should count the builder in the autoscale calculation.
