### ISSUE TITLE
Trouble configuring an app deployed in a nginx Docker image

### ISSUE THREAD

**Issue by KahunaKarstoon** [convox/rack#1282]
In short, we create a Docker image based on an nginx image (Dockerfile below) that houses a website.  We have run a variety of tests on the Docker Image and so that is our deployable unit.  We then use Convox to deploy that image in a Convox rack (docker-compose.yml below).  However, when it is deployed, we need to configure a couple of things.   We have found a way around some, but biggest issue we have is that end-point one of the services the website talks to is different depending upon the environment it is deployed to.

Thus we can't configure that end point when we are building the Docker image.  Unfortunately, nginx ignores the environment section of the docker-compose.yml (there seem to be several hacks about rewritting the nginx configuration file out there).  Trying to use the "convox env" isn't working either (shell command below).

Thus we thought about using the /etc/hosts file to point the app to the right service.  But we can't figure out how to include --add-host in the docker-compose.

Dockerfile:
`FROM tutum/nginx
RUN rm /etc/nginx/sites-enabled/default
ADD ./nginx /etc/nginx
COPY dist /usr/src/app`

docker-compose.yml (variables are macro replaced):
`nginx:
  restart: always
  image: ${registry_base}/synapse:${tag}
  ports:
    - 80
  environment:
    - NODE_ENV=production
    - MIDAS_API_URL=http://midas-api.${domain_name}/`

Convox commands:
`
sh "convox login ${env.CONVOX_RACKNAME} --password ${env.CONVOX_PASSWORD}"
sh "convox env set NODE_ENV=staging EOLAS_DOMAIN=${domainName} --app ${appName}-staging"
sh "convox deploy --app ${appName}-staging --description '${tag}' --file ${tmpFile}"
`

**Comment by ddollar** [comment]
Needs add-host/ExtraHosts for links

**Comment by KahunaKarstoon** [comment]
Okay - so - this requires an enhancement then?  And I'm not just missing something obvious.

**Comment by ckesselh** [comment]
Any idea why this is still an issue even after the corresponding change has apparently been implemented 14 days ago?

https://github.com/convox/rack/blob/master/manifest/service.go#L294

**Comment by ddollar** [comment]
This is only set up locally. We need to thread these hosts through to ExtraHosts in the ECS TaskDefinition.
