### ISSUE TITLE
HTTP API when dealing with processes should also return process ID

### ISSUE THREAD

**Issue by asyazwan** [convox/rack#1295]
My use case is running a container (detached), and all I get in case of success is `true`. It would be better for logging purposes to get the process ID.

**Comment by asyazwan** [comment]
Also, success should not mean HTTP request was done successfully -- we have HTTP code 200 for that. I noticed that even when there isn't enough memory to run new containers, I still get `success: true` and no new containers were created.

**Comment by contra** [comment]
Partial PR: https://github.com/convox/rack/pull/2130

Have a major reliance on this API, will do anything to help fix this ASAP. Any guidance on submitting a PR?

**Comment by stevelacy** [comment]
#2192 should close this, should another issue be opened for the memory limit and success message?

**Comment by MiguelMoll** [comment]
@asyazwan Thanks for filing this issue and it should be resolved in the [20170515223736](https://github.com/convox/rack/releases/tag/20170515223736) release.

Let's open another issue with any specifics about memory limits, etc.
