### ISSUE TITLE
convox login password unexpected behaviour (env overrides everything)

### ISSUE THREAD

**Issue by frsechet** [convox/rack#1311]
Expected behaviour for `convox login` would be to be able to override ~/.convox/auth and env var with a `--password` flag (files < env < cmdline)

Current behaviour is: files < cmdline < env

tested on convox client 20161007164641

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [convox login password unexpected behaviour (env overrides everything)](https://trello.com/c/RJL332pC/839-convox-login-password-unexpected-behaviour-env-overrides-everything)

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs: Clarify the notion of "logging in" / switch racks](https://trello.com/c/FeHjGyjc/1267-docs-clarify-the-notion-of-logging-in-switch-racks)
