### ISSUE TITLE
Detect use of mysql2 gem and change LINK_SCHEME

### ISSUE THREAD

**Issue by jhspaybar** [convox/rack#1313]
I was following your getting started guide and rails examples in part, but decided to use the mysql2 gem instead(largely because I might want to use Aurora which is mysql compatible, but not pg compatible).  I couldn't run generators or the rails console and it turns out it's because the DATABASE_URL began mysql:// rather than mysql2:// .  In my Gemfile I only had the mysql2 gem, but it wasn't detected.  I had to add LINK_SCHEME=mysql2 to the database container in my docker-compose.yml to get things to work.  This seems like something that could be detected, or documented better potentially.  I'm happy to contribute something along either path if you point me towards the area of code I should be looking.

**Comment by ddollar** [comment]
Hmm. Seems like this distinction should happen on the client side as the Docker image should not need to know which client is using it. Seems pretty crazy that the mysql2 gem wouldn't take mysql:// URLs.

**Comment by ddollar** [comment]
Closing for now, we'll need to figure out a way to have clients handle this.
