### ISSUE TITLE
`convox exec` with bad container ID hangs the terminal

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1328]
```
$ convox exec foo bash
ERROR: could not find process

```

At this point the `convox` process seems to stop responding to any signals.

**Comment by soulshake** [comment]
Related: #1441 and #1495

**Comment by sc-chad** [comment]
This now creates a hidden prompt instead of hardlocking after the latest release. @mattmanning

**Comment by ddollar** [comment]
Should be fixed by #1544
