### ISSUE TITLE
`convox env` throws 301 if app is in `rollback` status

### ISSUE THREAD

**Issue by bisrael** [convox/rack#1347]
`convox env` throws 301 when app is in `rollback` status

Got `ERROR: BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region
    status code: 301, request id` for a while until the app rollback completed.

**Comment by nzoschke** [comment]
Similarly we see errors during a `convox build` for an app in rollback status

```
Creating tarball... OK
Uploading: 43.14 MB / 43.14 MB [=========================] 100.00 % 0s
Starting build... ERROR: invalid ECR hostname: .dkr.ecr.us-west-2.amazonaws.com
```
