### ISSUE TITLE
Service Events / Webhooks not setting status properly

### ISSUE THREAD

**Issue by bisrael** [convox/rack#1348]
For instance:

scale some stuff `convox scale web --count=2`
then try to set some env vars `convox env set VAR=1`
then release it `convox releases promote RABCDEFGHIJK`

and you'll get slack notifications for all of those, even though the last one fails because the app is updating from the scaling still

**Comment by bisrael** [comment]
this also happens for similar commands like `convox services delete` while they're updating

**Comment by nzoschke** [comment]
Thanks. We will review rack events and make sure they reflect any error status that happens in the controller.

**Comment by nzoschke** [comment]
This behavior is improved for builds and releases with the latest rack release.

**Comment by nzoschke** [comment]
But releases and services need some more follow up work.

**Comment by nzoschke** [comment]
Rack, apps and releases are sending proper hooks now.

Services has not been addressed. Updating the issue title to reflect that.
