### ISSUE TITLE
env variables set before a deploy but not promoted are not picked up by the deploy

### ISSUE THREAD

**Issue by bisrael** [convox/rack#1349]
Scenario:

set an env variable needed in your next deploy:
`convox env set MYVAR=1`

deploy your app:
`convox deploy --description="Uses MYVAR"`

then you'll notice in the task definition in EC2 that `MYVAR` is not in the task's environment

**Comment by mwarkentin** [comment]
I think we ran across this recently as well - I believe it used to work the other way around? I assume it was during the builds refactor that this behaviour changed?

**Comment by bisrael** [comment]
it's certainly not the behavior i would expect

**Comment by bladealslayer** [comment]
This certainly causes some trouble when new app is created, if the app needs some env variables to be present in order to start properly. Without the variables, the app is stuck in updating state, because containers keep exiting.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploying doesn't apply new env vars](https://trello.com/c/crP1xvK0/1114-deploying-doesn-t-apply-new-env-vars)

**Comment by ddollar** [comment]
This is no longer the case
