### ISSUE TITLE
Support excluding certain files from a release (.dockerignore)

### ISSUE THREAD

**Issue by andykent** [convox/rack#135]
I have files that are not required for the build and can grow quite large over time. It really slows down deploys. It would be helpful if there were a way to ignore these files and exclude them from the upload. 

Maybe supporting `.dockerignore` files is the most sensible approach, given that anything in there would be ignored at build time anyway it should be safe not to include them in the release. 

http://docs.docker.com/reference/builder/#dockerignore-file

**Comment by csquared** [comment]
makes sense. its tempting to just do the build locally but doing the build inside of AWS make pulling images a *lot* faster. getting a card in the public trello

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Z0sxoXf6&#x2F;213-dont-upload-ignored-files-during-build"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> dont upload ignored files during build</a>

**Comment by asyazwan** [comment]
Archive on S3 does not honor `.dockerignore`. I have:
```
client: 20151121030849
server: 20151114015052 (grid.convox.com)
```
