### ISSUE TITLE
allow configuration of ELB ConnectionDraining Timeout

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#1350]
One way to speed up deploys is to lower the `ConnectionDraining.Timeout` attribute of the ELB from its [default of 5 minutes](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-conn-drain.html#enable-conn-drain).  Let's expose another docker label that allows me to customize this value.

(I plan to work up a PR)

**Comment by bobzoller** [comment]
FWIW, [Convox has this pegged to 60 seconds](https://github.com/goodeggs/rack/blob/master/api/models/templates/app.tmpl#L416), so already much lower than the 5 minute default.

Still probably worth being able to customize though.  In our environment we could drop it to 30 seconds.

**Comment by MiguelMoll** [comment]
This is now available: https://convox.com/docs/docker-compose-labels#convoxdrainingtimeout
