### ISSUE TITLE
add http(s) support for syslog services

### ISSUE THREAD

**Issue by bisrael** [convox/rack#1358]
Some services like Logentries don't support multiple white-listed IPs on TCP connections (even TCP+TLS), but allow them for HTTPS connections.

currently, syslog services only support TCP, TCP+TLS and UDP.

would be great to allow HTTP(S) support

**Comment by idris** [comment]
An option to modify the format would also help, since Logentries uses token-based logging to identify logs.  This way Convox's syslog service could inject the token for us.

References:
https://docs.logentries.com/docs/syslog-ng
https://docs.logentries.com/docs/rsyslog

**Comment by edkellena** [comment]
+1 to this.  Token based logging would be a massive boon.  Relying on an IP <-> port mapping sounds ok in practice, but with the ephemeral nature of containers, instances and IP's that's not really scalable.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [token-based https syslog](https://trello.com/c/wsngayxR/439-token-based-https-syslog)

**Comment by bisrael** [comment]
@ddollar was this implemented? can't find it in the docs? thanks.
