### ISSUE TITLE
Cannot info/unlink/delete syslog services

### ISSUE THREAD

**Issue by kolanos** [convox/rack#1359]
I have three syslog services:

```
$ convox services
NAME                TYPE      STATUS
account-papertrail  syslog    running
api-papertrail      syslog    running
papertrail          syslog    running
```

But I can't get info, unlink or delete them:

```
$ convox services info papertrail
ERROR: frontend not found

$ convox services info api-papertrail
ERROR: api not found

$ convox services info account-papertrail
ERROR: account not found

$ convox services unlink papertrail --app=development-frontend
ERROR: frontend not found

$ convox services unlink api-papertrail --app=development-api
ERROR: api not found

$ convox services unlink account-papertrail --app=development-account
ERROR: account not found

$ convox services delete papertrail
Deleting papertrail... ERROR: frontend not found

$ convox services delete api-papertrail
Deleting api-papertrail... ERROR: api not found

$ convox services delete account-papertrail
Deleting account-papertrail... ERROR: account not found
```

```
$ convox --version
client: 20161026221149
server: 20161026154439 (console.convox.com)
```

I am now seeing this with syslog services that don't have "papertrail" in the name.

**Comment by kolanos** [comment]
I just upgraded to the following versions and am still getting this error.

client: 20161028232500
server: 20161026221456 (console.convox.com)

**Comment by mwarkentin** [comment]
There used to be a specific service type called papertrail- wonder if this is a remnant of some special casing for that.

**Comment by kolanos** [comment]
Updated this issue, I am now seeing this with syslog services without "papertrail" in the name.

**Comment by mattmanning** [comment]
The cause of this seems to be that the services were linked to apps that got deleted. That's what I found in my own testing. I'm assuming in this case that `frontend`, `api`, and `account` were app names.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can't unlink/delete services linked to deleted apps](https://trello.com/c/SaccsbR0/1160-can-t-unlink-delete-services-linked-to-deleted-apps)

**Comment by kolanos** [comment]
@mattmanning No, actually the app names are `development-frontend`, `development-api` and `development-account`. And they were not deleted, they're still there to this day.

However, since reporting this I have noticed something odd about this problem. It appears to be something that only happens after a certain amount of time after the service is created. It's almost as though convox "forgets" the service after a certain amount of time. I've also seen it "forget" a service after linking it to an app. By "forget" I mean I cannot `info` or `delete` the service anymore, it gives me the unknown error above.

**Comment by mattmanning** [comment]
@kolanos Does this Rack happened to be named `development`? You can check by running `convox rack` and looking at the Name returned.

Thanks.

**Comment by kolanos** [comment]
@mattmanning Yes, the rack name is `development`.

**Comment by mattmanning** [comment]
The root of this problem seem to be apps that were previously linked getting deleted. We've released a change to prevent the deletion of apps with linked services. https://github.com/convox/rack/pull/1450
