### ISSUE TITLE
Convox start shouldn't silently fail when docker daemon isn't running

### ISSUE THREAD

**Issue by sgtpepper43** [convox/rack#1362]
My docker daemon wasn't running when I ran `convox start`, and it just exited without printing anything. It was confusing until I ran `docker build .` and got something about the docker daemon not running. It's probably not a common case, but it would be good to forward that message on to the user so they know what's up.

**Comment by bisrael** [comment]
this should be titled "convox start shouldn't fail silently"

it also fails when you forget to set an env var, and have to sit through a few minutes of `convox doctor` to find out why instead of the (almost literally) zero seconds convox start fails in.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix missing `convox start` errors](https://trello.com/c/5opE8u0I/973-fix-missing-convox-start-errors)

**Comment by MiguelMoll** [comment]
Fixed via #1422. 👍
