### ISSUE TITLE
convox rack showing an updating rack as running

### ISSUE THREAD

**Issue by shidenkai0** [convox/rack#1363]
Hi,

As mentioned in the #convox channel on slack, I started the update of my staging rack running convox 20161001030309 a few hours ago, the rack is still not up to date, and when I try to start over the update, I have
```bash
Updating convox/proxy: FAILED
Updating convox: OK, 20161028232500
Updating to 20161026221456... ERROR: system is already updating 
```
, while convox rack gives me the status of the rack as running. It turns out the CloudFormation stack has the UPDATE_ROLLBACK_FAILED status. The "running" status is therefore misleading in this case.

**Comment by MiguelMoll** [comment]
Fixed via https://github.com/convox/rack/pull/1423
