### ISSUE TITLE
Is there an API I can use in place of the Convox CLI

### ISSUE THREAD

**Issue by jkurz** [convox/rack#1377]
I would like to have the comfort of a underlying API, which we could use and build tools around if needed. Is the only way to interact with a rack, via the cli? 

How would one make their own tools to interact with a rack?

**Comment by mwarkentin** [comment]
@jkurz You have full access to the API, it's not documented too well unfortunately.

Here are the docs (styling seems broken currently): https://convox.com/api

You can also interact with the API via the CLI w/ `convox api get <path>`

**Comment by jkurz** [comment]
ok if you could let me know how to authenticate that would be great. I don't see anything in the api docs about it. Also when I try and get the api endpoints from the cli I get

```
C02J41R5DKQ4:hello-convox jkurz$ convox api get apps
ERROR: Get https://convox-9453.us-east-1.elb.amazonaws.comapps: dial tcp: lookup convox-9453.us-east-1.elb.amazonaws.comapps on 10.x.x.x:53: no such host
```

the convox rack is on the public internet, so it should be able to get these values correct?

**Comment by mwarkentin** [comment]
Try: convox api get /apps/

If the convox CLI works, the CLI API commands should work as well.

**Comment by simonwoodcock** [comment]
So I managed to get this working with the API recently on one of our project.

When I tried /apps/ it would only bring back the rack associated to the user.

I added `Rack: org/rack` in the header of the api call to interact with a different rack which works well.
Convox API uses basic auth so adding an `Authorization` header with the value being `Basic` followed by a base 64 encoded string which needs to be `:api-key-goes-here` will allow you to authenticate.

Example below from an https call I pulled out of one of our nodejs scripts:
```
      var options = {
        host: 'console.convox.com',
        path: '/apps',
        method: 'GET',
        headers: {
            Authorization: 'Basic [BASE_64_ENCODED_STRING]',
            Rack: 'org/rack-name'
        }
    };
    
    var req = https.request(options, function(res) {
      //res will contain the reply
    });
```

or for this with not much nodejs experience:
```
curl -H"Authorization: Basic [BASE_64_ENCODED_STRING]" -H"Rack: org/rack-name" https://console.convox.com/apps
```

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/convox/rack/issues/1377 (rack -> site)](https://trello.com/c/QAGcZ0uo/1139-https-github-com-convox-rack-issues-1377-rack-site)

**Comment by soulshake** [comment]
We've fixed the API documentation, see it here: https://convox.com/api
We'll be adding sample code and more documentation in the near future.
