### ISSUE TITLE
More than one app per vm

### ISSUE THREAD

**Issue by jkurz** [convox/rack#1379]
I have a 3 node cluster. I would like to scale my app to 20 replicas. Is this not possible with convox?
I tried and it started running into prot mapping issues in ECS and stopped at 3.

* also a bug it seems, the app is stuck in a updating state now and I cannot scale it back down to -1 or any number for that matter. So now it seems I have to edit directly in ECS or delete the app and recreate it.

**Comment by mwarkentin** [comment]
@jkurz This is currently a limitation of using ECS + ELB (classic load balancers) as they don't support dynamic port mapping - only one process can be running on a specific port per instance.

See https://github.com/convox/rack/issues/1373 for discussion on ALB support, which would enable scaling processes > number of instances.

**Comment by jkurz** [comment]
ok thank you. Going to close this then.
