### ISSUE TITLE
docker tag conflict on docker 1.9.0

### ISSUE THREAD

**Issue by redbugz** [convox/rack#1390]
I started running through the getting started guide. Unfortunately I am stuck on docker 1.9.0 until some things get updated on our side, and I get this error a lot:

```
build  │ running: docker tag convox/web convox/worker
build  │ Error response from daemon: Conflict: Tag convox/worker:latest is already set to image 51576a43dadc, if you want to replace it, please use -f option
```

It appears from #781 this fixes a problem with docker 1.12

For now, I have to run:
`docker rmi convox/web convox/worker` whenever I get the error, which is very frequent.

Is there any way to get this to work with both 1.9.0 and 1.12+?

**Comment by nzoschke** [comment]
I'd be happy to accept a patch with a test for this, but backwards compatibility with a 2015 release of Docker is not a priority. 

Closing now, but feel free to re-open if you're still stuck.

**Comment by nzoschke** [comment]
Re-opening.

We say that Docker 1.9 is the min required version, so its a bug that we dont support the right tag syntax on 1.9.

**Comment by ddollar** [comment]
Let's update the Docker minimum required wherever we say that
