### ISSUE TITLE
Wish to be able to name our databases

### ISSUE THREAD

**Issue by denmat** [convox/rack#1393]
We have a requirement where an app has two different databases (event sourcing app - events in one db, projectors in another). 

Currently we can create two databases using the `convox services..` command, but it creates the DB Name as 'app'. 

The template is parameterised but uses the default:
https://github.com/convox/rack/blob/master/provider/aws/templates/service/postgres.tmpl#L14

It would be great if this could be named either after the service name or pass in a parameter.

Thanks

**Comment by MiguelMoll** [comment]
You definitely can name the database via:
`convox services create postgres --database=mydb`

I doubled checked the [docs](https://convox.com/docs/postgresql/) and we'll update them with the `--database` parameter. Thanks for the feedback. If you run into anything else, please let us know.
