### ISSUE TITLE
convox start -f fails with status code 1

### ISSUE THREAD

**Issue by d2rk** [convox/rack#1403]
Getting status code 1 without any message when running `convox start -f docker-compose/development.yml`. However, there is no problem with `convox start -f development.yml`.

**Comment by soulshake** [comment]
I'm able to reproduce this.

```
$ ln -s $PWD/docker-compose.yml subdir/docker-compose.yml

$ convox start -f subdir/docker-compose.yml

$ echo $?
1
```
