### ISSUE TITLE
Custom SSL - Docker Compose Labels

### ISSUE THREAD

**Issue by matt-smith** [convox/rack#1421]
It would be great to allow the setting of a custom SSL within the docker-compose.yml once a custom SSL has been uploaded using the `convox certs create` command.

for example.
```
- convox.port.443.protocol=https
- convox.port.443.certificate=acm-88c6f6c06907
```

Therefore removing the need for having to create the `*.*.elb.amazonaws.com` certificates if you are bringing your own.

**Comment by mwarkentin** [comment]
Part of the problem here might be how this works across multiple racks if you have different domains / certs.

**Comment by ddollar** [comment]
Can we somehow make a label that specifies the secure domain(s) and then either pick a matching ACM cert from the account or generate one?
