### ISSUE TITLE
add --id support to convox env commands

### ISSUE THREAD

**Issue by bisrael** [convox/rack#1424]
similar to how `convox deploy` accepts `--id` and only outputs the ID of the created release, it would be very useful for scripting to support this across env commands

example usage is for scripts to roll api keys or urls automatically

thanks!

**Comment by mwarkentin** [comment]
@nzoschke I believe this was actually released already in https://github.com/convox/rack/pull/1594

**Comment by soulshake** [comment]
Resolved by #1594
