### ISSUE TITLE
support compatibility flags for aurora

### ISSUE THREAD

**Issue by contra** [convox/rack#1428]
#622 added the ability to spin up aurora services, but is missing the flag to set different compatibility modes.

AFAIK there is:

- Postgres
- MySQL

![image](https://cloud.githubusercontent.com/assets/425716/20801219/223c67ac-b7b6-11e6-8d1d-9220a2ad6749.png)

More info: https://aws.amazon.com/blogs/aws/amazon-aurora-update-postgresql-compatibility/

**Comment by mwarkentin** [comment]
Yeah, postgres support for aurora was [announced yesterday](https://aws.amazon.com/about-aws/whats-new/2016/11/announcing-postgresql-compatibility-for-amazon-aurora/).

**Comment by contra** [comment]
I think they're adding more based on this screenshot

![image](https://cloud.githubusercontent.com/assets/425716/20801199/09cbaaa2-b7b6-11e6-88ab-41e6f1cf66b5.png)

**Comment by seivan** [comment]
Any updates on this? We have access to Aurora postgresql now.

**Comment by contra** [comment]
Yeah, also have access if you need anything for this. Seems like a quick win.

**Comment by contra** [comment]
Should be identical to mysql aurora, but the value is `aurora-postgresql` instead of `aurora` for the instance type (looked at the source).

**Comment by ddollar** [comment]
Convox is currently only taking feature requests for Generation 1 through support tickets on paid accounts. That being said, I'd happily merge a pull request adding this resource.
