### ISSUE TITLE
CLI should verify instance types for Automatic Failover Redis

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1431]
If you create an Elasticache Redis using the `convox services create` command the CloudFormation create will fail if you are using T2 cache node types. The CLI should verify `--instance-type` before starting CloudFormation.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CLI should verify instance types for Automatic Failover Redis](https://trello.com/c/olc4sCMb/1302-cli-should-verify-instance-types-for-automatic-failover-redis)

**Comment by ddollar** [comment]
Maybe this could be AllowedValues or something for the parameter? I'm hesitant to add a bunch of one-off validation in the CLI for these. Is there some way to encode it in CloudFormation to fail sooner?

**Comment by MiguelMoll** [comment]
For clarity, I was able to create a redis resource with all 3 t2 types (cache.t2.micro|small|medium). I take it this enhancement should check for typos for the `--instance-type` value?

**Comment by ddollar** [comment]
Unless this irreversibly breaks something let's let CloudFormation provide the validation here
