### ISSUE TITLE
Support `stdin_open` option in docker-compose.yml

### ISSUE THREAD

**Issue by idris** [convox/rack#1442]
The `stdin_open` option can be useful for running locally with `convox start`.

My use case:
I'm using [babel-watch](https://github.com/kmagiera/babel-watch) in development, which allows you to restart the server by simply typing `rs<Enter>`.

When using `docker-compose` to run (instead of `convox start`), I can just attach to the process and type `rs`.  However, when running via `convox start`, I have no way of doing that so I have to stop the whole cluster and re-run `convox start`, which is much more time consuming.

**Comment by idris** [comment]
Interesting: It seems like `convox start` does use `-i`, which _should_ make it accept STDIN when I attach.  However, STDIN still doesn't seem to work.

Thoughts?

**Comment by mwarkentin** [comment]
@idris May be related to the tty stuff in https://github.com/convox/rack/issues/827 and related issues/PRs..

**Comment by idris** [comment]
@mwarkentin thanks, that does look related.  You mentioned:
> I'm hoping to take a crack at this soon.

Any progress on this?

**Comment by mwarkentin** [comment]
Unfortunately, no.

**Comment by ddollar** [comment]
Closing this in favor of #827. We'll add support for `tty: true`
