### ISSUE TITLE
Can't update rack to latest release `20161207212928`

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#1449]
Rack was launched in existing VPC. Looks like the recent template changes break the update.

```
$ convox rack update --rack staging
Updating to 20161207212928... ERROR: ValidationError: Unresolved resource dependencies [Gateway] in the Outputs block of the template
	status code: 400, request id: 241078d9-bd19-11e6-98b3-b9a3b370edfd
```

```
$ convox --version
client: 20161208021221
server: 20161123204337 (console.convox.com)
```

**Comment by MiguelMoll** [comment]
Apologies for that. Could you try the latest from this morning addresses this issue? It would be release `20161208145749`

**Comment by bladealslayer** [comment]
The latest release fails too, but differently. The CloudFromation stack update kicks in, but couple of the resources fail to create:

```
09:33:59 UTC+0200	CREATE_FAILED	AWS::EC2::VPCGatewayAttachment	ExistingGatewayAttachment	The request must contain the parameter internetGatewayId
...
09:34:01 UTC+0200	CREATE_FAILED	AWS::EC2::Route	RouteDefault	Exactly one of [GatewayId, InstanceId, NetworkInterfaceId, NatGatewayId, VpcPeeringConnectionId, EgressOnlyInternetGatewayId] must be specified and not empty
```

**Comment by MiguelMoll** [comment]
Apologies for the late response. We're definitely working on a resolution for this. The fix should be ready for the next release.

**Comment by mattmanning** [comment]
This is fixed in https://github.com/convox/rack/releases/tag/20161213012529
