### ISSUE TITLE
Stopping Instances Feature Unavailable

### ISSUE THREAD

**Issue by dev6** [convox/rack#1458]
How can I go about stopping the instances when I am not using the app or for other reasons? Tried stopping them from AWS console but they get initiated again automatically. Tried searching the API but couldn't find any feature which does that.

**Comment by mwarkentin** [comment]
@dev6 There's nothing built in to Convox for this, but you can modify the autoscaling group configuration via AWS Console or API to reduce it to 0 instances.

We do this via scheduled actions on our dev clusters to automatically turn them off in the evening and on weekends.

**Comment by dev6** [comment]
@mwarkentin I did try this as well but I get an Error everytime I try to reduce the instance count to 0

`
Whoops... ValidationError: Parameter 'InstanceCount' must be a number not less than 3 status code: 400, request id: d25a8390-be35-11e6-9cb9-cb9d1ba1883e 
`

**Comment by mwarkentin** [comment]
@dev6 Yeah, you can't do it via the Convox CLI, but you can do it directly via AWS.

If it were to be supported in convox, it could either be something like:

* `convox rack [suspend/resume]`
* `convox rack scale --count=0` - where `1`, `2` are invalid

Having an explicit action for suspending the rack could be helpful - there could then be options for terminating ELBs, etc. (with the explanation that app URLs, etc. would change when the rack is resumed).

**Comment by ddollar** [comment]
I like `convox rack suspend` and `convox rack resume`. We could require that Autoscale be on for these to work.
