### ISSUE TITLE
Add default link strategy for resources

### ISSUE THREAD

**Issue by spencerhakim** [convox/rack#1461]
It'd be great if `resources link` had a default link strategy for resource types that don't provide their own linking strategy. For example, linking isn't possible for S3 or MySQL resources, but `resources info` reports that both types export a `URL` variable. If the default strategy could pass those variables onto my container (presumably with a prefix based on the resource name, e.g. `MY_S3_RESOURCE_URL`) similarly to how linking works in `docker-compose.yml`, that would be a huge improvement.

**Comment by ddollar** [comment]
Closing in favor of #466
