### ISSUE TITLE
CLI should display rack and app at beginning of command output

### ISSUE THREAD

**Issue by idris** [convox/rack#1464]
It would be nice if every CLI command first outputted the rack and app that it's acting on.  This way you know if you made a mistake and, say, left out a `-a <app-name>`

**Comment by soulshake** [comment]
I think this would be handy too, maybe if it could be toggled with `CONVOX_DEBUG`.
If you haven't seen it already, you might try the [PS1 helper](https://convox.com/docs/cli#active-rack-command-prompt-helper) for your prompt.

**Comment by bisrael** [comment]
this could break scripts that rely on parsing cli command output, maybe make it optional as @soulshake suggests or a --debug flag
