### ISSUE TITLE
EFS - how to delete service volume and orphaned volumes

### ISSUE THREAD

**Issue by SonOfBytes** [convox/rack#1492]
In trying to move a convox/postgres server from non-persistent to persistent PGDATA volumes (omitted volumes in Dockerfile at first) the PGDATA directory got corrupted some how and the DB server refused to stay up.

There appeared to be no easy way to clear out the EFS volume for the "database" service.  This meant that the only obvious way to get the necessary behaviour without creating a temporary service box and delete everything by hand was to rename the service from "database" to "db" and change all the necessary env vars.  Also now that "database" service no longer exists there is still "database" files left behind.

It would be useful to have some level of `efs` command line interface to manage orphans or reset volumes.

**Comment by ddollar** [comment]
You can do this with `convox instances ssh <instance-id> rm /volumes/foo/bar`

Going to add this to docs todo

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [how to clean up persistent volumes](https://trello.com/c/cMQ77zia/1470-how-to-clean-up-persistent-volumes)
