### ISSUE TITLE
non-rolling upgrades for some services (e.g. when locking on shared EFS volumes)

### ISSUE THREAD

**Issue by SonOfBytes** [convox/rack#1493]
In using the `convox/postgres` image I noticed that a deploy to a simple web+database application with the necessary `links` and `depends-on` had an undesired behaviour for the app.

The `web` service `depends-on` the `database` service.  It also has a start up script that waits for the DB to be ready before starting the django app (which performs db migrations first before starting).

What happens is that the `database` service is rolled forward.  Then the`web` service rolls forward.  However the `database` service fails to start because the old version of the database has a lock on the volume.  It then exits.

In the mean time `web` service starts and sees the DB is up and working on the old version and starts to migrate.  Fails the migration when the old version is torn down.  In the mean time there is no new version because it has exited and will restart once the process dead is caught.

If health services are used on the database service then it will never roll forward as the lock file is blocker until the old version is stopped.

It would make a lot more sense for services that can't have shared resources (like the db) to have a non-rolling upgrade option.  i.e. it is stopped, rolled forward, started and then the depending services rolled forward.  This mitigates the costly option of using RDS for HA - if transient service interruptions in the DB can handled at the web application layer.

**Comment by mwarkentin** [comment]
@SonOfBytes you can specify the rollout strategy using [`convox.deployment` labels](https://convox.com/docs/docker-compose-labels/#convoxdeployment).

Something like this should work I think:

```
database:
  image: convox/postgres
  labels:
    - convox.deployment.minimum=0
    - convox.deployment.maximum=100
```

**Comment by SonOfBytes** [comment]
Thanks @mwarkentin - that was not clear from the docs that was a possible outcome :)

That seemed to work with respect to database.  What was interesting is the order.  The DB was rolled forward after the web app when the web app depends on the database.  I wonder if this the intent?

**Comment by mwarkentin** [comment]
Yeah, I don't think the ECS scheduler has a concept of dependency ordering that I'm aware of.

**Comment by SonOfBytes** [comment]
Happy to close this unless it is deemed documentation update would help.

**Comment by ddollar** [comment]
I added this to our docs todo
