### ISSUE TITLE
EFS is incredibly slow - workaround needed

### ISSUE THREAD

**Issue by frsechet** [convox/rack#1496]
Here is a write up provided by @nzoschke on how slow EFS is (in certain use cases - mostly many writes of small files): https://docs.google.com/document/d/1Mtu3C6UDDCHhDEGUFPeDAyJFUdsEqHj1oTUwIPm48Ls

Some numbers to illustrate:
- write 130 4KB files: 3.5s
- untar 11k files to EFS volume, 98MB: ~10min

So yeah, EFS is slow. For understandable reasons (redundancy, scalability, availability etc.), but it is slow to the point where it is unusable in some common use cases (shared application cache between containers for example).

After a chat with a EFS PM, the only solution is (currently) to create a custom NFS share on a EC2 instance to replace EFS for such use cases.

To do:
- define proper replacement solution (https://www.softnas.com/wp/products/nas-storage/, https://objectivefs.com/...)
- attach/mount it to a rack (via InstanceBootCommand?)
- map `/path/to/my/nfs-share:/container/path/to/my/data` in docker-compose.yml

Some additional costs and ops overhead may incur. But it's either that or something completely unusable (or redeveloping some stuff in each app to make it suck less).

**Comment by nzoschke** [comment]
Thanks. +1 for bringing your own volume somehow, reliability be darned.

Currently we whitelist a few host paths like `/var/run/docker.sock` but the rest turn into a directory on EFS. See here for a recent patch:

https://github.com/convox/rack/commit/42a2f564f0d0fa4bce85559d6f19e374ae9da7c4

So I think we need a convention for another path to pass through where you can mount your own volume during boot. 

`/mnt` seems like a good host path, but this could use a design and security review.

**Comment by ddollar** [comment]
Can also take responsibility for mounting something at `/volumes`

**Comment by nzoschke** [comment]
@ddollar great call. 

You can set an InstanceBootCommand to a script that does a:

`umount /volumes && mount -t nfs -o nfsvers=4.1 $NFS_URL /volumes`

**Comment by frsechet** [comment]
That would kill EFS completely, right? So what about `/volumes/mycustomnfsshare/my/path` to ensure compatibility of both systems?

**Comment by nzoschke** [comment]
Yes unmounting /volumes will disable the Convox EFS stuff entirely.

Yes, mounting a custom NFS on `/volumes/mycustomnfsshare/` could also work.

**Comment by frsechet** [comment]
So, in order to keep EFS and add another volume in a rack, I need another mounting point, not `/volumes`.

**Comment by nzoschke** [comment]
If you can bind mount (or equivalent) a custom NFS over the EFS `/volumes` then perhaps not. 

I haven't tested that possibility.

But that was my original thought, that we'd want to let you pass something like `/mnt/mycustomnfsshare` through.
