### ISSUE TITLE
certs generate to apex

### ISSUE THREAD

**Issue by ryanhiebert** [convox/rack#1498]
ACM by default sends the confirmation email to the contact in the whois record of the apex domain, as well as a bunch of typical emails for the domain in question. You can, when creating the request, ask that those emails be sent instead to email addresses at the apex domain instead of whatever subdomain you're looking to get a certificate for.

We should add a `--apex` flag to the `convox certs generate` command.

**Comment by ryanhiebert** [comment]
https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-validate.html

**Comment by ddollar** [comment]
Related to #879
