### ISSUE TITLE
Cron doesn't working 

### ISSUE THREAD

**Issue by icewind** [convox/rack#1501]
I use convox to schedule daily backup of my mongodb. So I wrote 
```
labels:
    - convox.cron.mongobackup=0 0 * * ? /mongobackup.sh
```
in my docker compose. App was successfully deployed and running. Lambda record `mongodb-backup` and CloudWatch entry were created as well. Script is invoking, but not doing anything. 
If I'm invoking it directly using `convox exec <app_id> /mongobackup.sh` everything is fine.

The script itself https://gist.github.com/icewind/e884bf59870f2808d0f08461a6b1efd7

All env variables are defined in `docker-compose.yml` and accessible within the container. Also I defined them(just to make sure) in aws lambda console

Logs in cloudwatch: https://yadi.sk/i/zcL7fYcZ34SBxc

**Comment by ddollar** [comment]
Since this appears to be a problem with your specific Rack installation please open this as a ticket inside https://console.convox.com so we can help you investigate.

**Comment by matt-smith** [comment]
@ddollar I think I can reproduce this scenario. Should I also open a case?
