### ISSUE TITLE
SQS resources available on the public internet

### ISSUE THREAD

**Issue by jayjanssen** [convox/rack#1507]
The manual states that convox created resources in AWS are not available to the private internet.  However, I was able to create an SQS queue in my AWS rack and connect to it with a client outside that rack (local laptop) using the convox resources info credentials.  Is that expected?

**Comment by mwarkentin** [comment]
Some of the resources like mysql/postgres/redis have a `--private` option, not sure if there's something similar for SQS (or if that's even an option at the AWS level).

**Comment by ddollar** [comment]
Solved by convox/site#426
