### ISSUE TITLE
convox rack ps --stats support?

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#1508]
Follow up on https://github.com/convox/rack/issues/272

Just discovered this handy command - especially with `convox rack ps --all`.

I immediately tried running the same with the `--stats` option, unfortunately I think the non-app processes broke:

```
$ convox rack ps --stats
ERROR: convox-kraken not found
$ convox rack ps -all --stats
ERROR: convox-kraken not found
```

I think either getting stats for those rack containers (ideal), or just handling the error and leaving those columns blank would be fine.

**Comment by skwp** [comment]
Confirmed, I see the same issue.
