### ISSUE TITLE
App level linking

### ISSUE THREAD

**Issue by SonOfBytes** [convox/rack#1511]
I have a client with an app that has a traditional Public (DMZ)/Private architecture.  There are sensitive elements in the private service that should not be directly accessible from the internet.  Although this could be somewhat done in the same app there is a need for a distinct segregation as well as having different convox app env settings that cannot be shared.

Is there a way to model 2 apps so they can be linked to effectively model the following pattern?

![dmz-app](https://cloud.githubusercontent.com/assets/1942530/21674925/c82d509a-d327-11e6-9a38-24554375fd64.png)

**Comment by mwarkentin** [comment]
https://convox.com/docs/port-mapping/

I think what you want is the internal port mapping - e.g.  Instead of specifying ports 5000:443 which creates a public load balancer, just specify 5000. This will create an internal ELB which is only accessible within the VPC or via VPN/peering.

**Comment by SonOfBytes** [comment]
Ah yes I missed the point that an internal app is available to others apps in the rack.  I presumed, wrongly, that this was limited to in the same app.

Is there a way to link the apps generated ELB end points between apps through some kind of  configuration linking?  Or is the only way is to query the app and set DNS or an env setting per app so they can connect?

**Comment by mwarkentin** [comment]
@SonOfBytes Yes, currently you just get the endpoint from `convox apps info --app <app>` - it will show internal endpoints just like it does external. Then you can set an environment variable on the other app with this value so it knows where to send its traffic.
