### ISSUE TITLE
Container Discovery/Networking (i.e. for Elixir clustering)

### ISSUE THREAD

**Issue by mrrooijen** [convox/rack#1514]
I'm working on an Elixir app that needs to operate in a cluster (i.e. 10 app containers connected together).

I have a DNS-based solution set up which works on docker-compose, but I haven't been able to get it to work with convox.

My `docker-compose.yml` contains the following:

```yml
version: "2"
services:
  app:
    build: .
    environment:
      - SNAME
      - COOKIE
```

My `Dockerfile` contains the following:

```Dockerfile
FROM elixir

RUN mkdir /app

WORKDIR /app

ADD config /app/config
ADD lib /app/lib
ADD mix.exs /app/mix.exs

RUN mix deps.get && mix compile

# Basically grab the container ip at container boot-time and use it
# in `--name` along with `$SNAME` (=app) to make it connectable from other containers.
CMD elixir \
    --name $SNAME@`ip -4 addr show eth0 | grep -Po 'inet \K[\d.]+'` \
    --cookie $COOKIE \
    -S mix run --no-halt
```

When I `docker-compose up` and `docker-compose scale app=3`, the Elixir processes will perform DNS lookups (on `$SNAME`) to figure out where all of the containers are located.

For example, `docker-compose exec app bash` into one of the running containers and performing a `nslookup app` will yield the 3 ip addresses of the running app containers.

```
root@848da6efec66:/app# nslookup app
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	app
Address: 172.19.0.3
Name:	app
Address: 172.19.0.4
Name:	app
Address: 172.19.0.2
```

I then use these to dynamically connect the Elixir nodes together. Basically this ends up happening at some point on the `app_1` container in Elixir:

```elixir
Node.connect(:"app@172.19.0.3")
Node.connect(:"app@172.19.0.4")
```

And now the nodes are connected.

Is this (or something like this) currently possible with Convox?

**Comment by nzoschke** [comment]
DNS doesn't work like that on Convox / ECS at the moment. 

Here is a nice reference architecture for a ECS / Route 53 solutnion: https://aws.amazon.com/blogs/compute/service-discovery-an-amazon-ecs-reference-architecture/

Another idea... Could you use the AWS ECS API directly to find tasks, instances and IPs?

**Comment by seivan** [comment]
Any updates on this? Rather not rely on AWS API for discovery.

**Comment by mrluc** [comment]
An option that has worked in the past is to use the Weave AMI with Convox. It adds DNS-based service discovery to ECS.

However, I don't know if that is still a valid approach.
