### ISSUE TITLE
Failed to set application parameter Internal=No

### ISSUE THREAD

**Issue by electroma** [convox/rack#1524]
Convox rack version 20161206211458.
Application is deployed and runs as Internal.
When I try to execute `convox apps params set Internal=No` it fails with
`Updating parameters... ERROR: ValidationError: No updates are to be performed.
	status code: 400, request id: 43b5f1ae-d453-11e6-80f4-2592f73b8353`.
CloudFormation log shows ROLLBACK_COMPLETE after failure on step
`CREATE_FAILED |	AWS::Lambda::Function | CustomTopic | The runtime parameter of nodejs is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs4.3) while creating or updating functions.`

**Comment by mwarkentin** [comment]
@electroma I think you just hit the issue described here: https://github.com/convox/site/pull/431/files?short_path=844ffa2#diff-844ffa29ba7dbac5f51695cc2b0e1fd0

**Comment by electroma** [comment]
👍 that was quick!
I'll update the rack and try one more time.
