### ISSUE TITLE
convox install: garbage remaining from failed install attempt

### ISSUE THREAD

**Issue by bentheax** [convox/rack#1526]
I tried to install Convox on 2017-01-06 and encountered an error that has now been resolved. After updating the client and again trying to install today, I get greeted with the message:

> Stack "convox" already exists. Run `convox uninstall` then try again

Following the instructions and running `convox uninstall convox ap-southeast-2` does not work. [Looking in the code](https://github.com/convox/rack/blob/bb2da3f616a5f0582bd83ce2196ad27dda8492a2/cmd/convox/install.go#L373) indicates this is due to a failure to create a CF stack. When I check on the CloudFormation templates via the AWS web UI I can see that, yes, there is a convox stack in ROLLBACK_COMPLETE status. So there's two things occurring here:

- `install` failing to clean up fully when encountering an error
- `uninstall` cannot detect and remove partial installs

Manually removing the stack allows `install` to proceed without issues.

EDIT: It looks like the uninstall is definitely designed to clean up a stack in a rollback complete state. It exited before attempting the delete at https://github.com/convox/rack/blob/0448b04268b9e7808a83037374ebc52cb77fd5b9/cmd/convox/uninstall.go#L94 . Unfortunately, since I've already removed the stack, I have little information about why it failed to be described. If you're not seeing wider reports of issues with uninstalls failing, it might just be some (low priority) edge-case that I've bumped into here.

**Comment by nzoschke** [comment]
Thanks for the feedback. It's probably related to this: https://github.com/convox/rack/issues/1416

If you have any more info, please add it to that ticket. Thanks!
