### ISSUE TITLE
Export outputs for cross stack referencing

### ISSUE THREAD

**Issue by bentheax** [convox/rack#1528]
I have an idea for some extra functionality. It's low hanging fruit, but it's also low value.

Use case:

Creating a template for DNS and would like to be able to reference the load balancer address of an app without hard-coding the load balancer's current address. See: 

Proposed solution:

The generated app template exports the load balancer name as "#{app_name}-BalancerWebHost". See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html

Pro:

- Easier integration with stacks outside of Convox
- Prevented from terminating the app accidentally while external references exist

Con:

- Prevented from terminating the app deliberately while external references exist
- CNAME of a load balancer is likely fairly stable, anyway, barring drastic changes to the template.

**Comment by nzoschke** [comment]
Really nice idea.

**Comment by mwarkentin** [comment]
Yeah, this is similar to what we have at the rack level, which is really nice.
