### ISSUE TITLE
convox ssl does not recognise --app flag

### ISSUE THREAD

**Issue by bentheax** [convox/rack#1529]
I have a project that uses underscores in its name. Though this doesn't violate any AWS constraints that I'm aware of, there's a regex in convox CLI that forces me to avoid them. Consequently I have to specify `--app project-name-with-dashes` when running project commands.

Unfortunately, it seems like `convox ssl` doesn't respect this flag no matter when I put it.

`convox ssl update --app <app> <endpoint> <cert>` and `convox ssl update <endpoint> <cert> --app <app>` both fail with "Incorrect Usage." whereas `convox ssl --app <app> update <endpoint> <cert>` appears to just be inferring the project name.

The workaround is to temporarily change the project folder so it can be inferred to the actual project name.

**Comment by mwarkentin** [comment]
I think this is fixed by https://github.com/convox/rack/pull/1522.

**Comment by nzoschke** [comment]
Yes this is fixed in #1522. Thanks for the repot.
