### ISSUE TITLE
App deployment fails with `20170106053301` when scheduled tasks are defined

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#1539]
App that has scheduled tasks defined prior to `20170106053301`, fails to deploy on rack running `20170106053301` release. Reason is that CloudFormation can't replace custom-named resources (the scheduled task lambda function).

Workaround is to deploy the app without the scheduled tasks and re-add them afterwards.

**Comment by ddollar** [comment]
Will be fixed by #1530 on release
