### ISSUE TITLE
Update convox to pass privilege mode settings as part of docker-compose.yml through to ECS 

### ISSUE THREAD

**Issue by johnboy14** [convox/rack#155]
I need to run a container in privileged mode but when I pass the privileged setting as part of my docker-compose.yml file, convox seems to ignore it.  I discussed this issue with Noah and he recommended creating an issue for this.

**Comment by csquared** [comment]
Good call -> just created a card out of this.

**Comment by nzoschke** [comment]
Thanks Chris. We talked through this a little more. Recently ECS added support in the Task Definition for a lot more Docker options available in `docker run`. Including privileged mode. It should be very useful to wire up more docker-compose.yml to Task Definition options for convox apps.

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

**Comment by nzoschke** [comment]
We should also double check the ECS AMI and resulting docker version when adding support for more docker config.

**Comment by johnboy14** [comment]
Is it possible to update the ECS AMI or the version of docker running on them?.

**Comment by nzoschke** [comment]
Right now it is possible only by specifying a different Ami for the convox stack.

https://github.com/convox/rack/blob/master/api/dist/kernel.json#L104

**Comment by nzoschke** [comment]
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container_agent_versions.html is the list of ECS AMI Docker versions

**Comment by johnboy14** [comment]
Are you guys going to make the privileged mode change or wait for AWS to update the AMI?.

**Comment by johnboy14** [comment]
Is it possible to determine when this issue might get fixed?.

**Comment by nzoschke** [comment]
Thank you for your patience. @mattmanning just submitted privileged for `convox start` here:

https://github.com/convox/rack/pull/332/files

**Comment by nzoschke** [comment]
We've also upgraded the AMIs and now have Docker 1.9 available everywhere. So one thing remains:

- [ ] Pass privileged true/false to the CloudFormation Custom Resource Lambda function, and ECS task definition

**Comment by johnboy14** [comment]
Thanks for this guys.  I assume it can be read from the manifest also and passed to ECS?.

**Comment by nzoschke** [comment]
@johnboy14 yes, this now gets passed through to ECS too. 

`convox rack update` and you should get version 20160210165552 or later which handles privileged: true in the docker-compose.yml. Example:

https://github.com/convox/rack/blob/fe229e20bd9543c76cf31ba1e8314df1ee06c471/api/models/fixtures/worker.yml

Thanks again for the feature request.
