### ISSUE TITLE
Q: How secured env values are injected into an app

### ISSUE THREAD

**Issue by SonOfBytes** [convox/rack#1552]
My understanding of `convox env` commands is that they are stored in S3 encrypted by KMS.  Ie this is not just using server side S3 encryption but the actual data is encrypted.

At which point a process needs to decrypt the data using KMS and inject it to the docker env.  What is that process and how are the environment variables injected?

I'm trying to understand the controls that are in place around sensitive env variables.

Thanks for your help in clarifying this!

**Comment by ddollar** [comment]
I created a card on our roadmap to document this better.

https://trello.com/c/X4EwUvER/363-add-doc-explaining-how-env-is-stored-and-how-it-is-injected-into-the-environment

We store environment encrypted at rest on S3 using a KMS key that is created as part of the Rack. These are then set as environment variables on the TaskDefinition that will be given to ECS.

**Comment by mwarkentin** [comment]
They're also stored in the release table in DynamoDB.

**Comment by SonOfBytes** [comment]
Yes I have just realised they are unencrypted in DynamoDB :(
