### ISSUE TITLE
`--id` support for convox env set

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#1560]
`convox build` and `convox deploy` both support a `--id` option to improve scripting support:

> --id				build logs on stderr, build id on stdout (useful for scripting)

It'd be nice if `convox env set` had this as well (which also creates a new release like the other two).

**Comment by soulshake** [comment]
Ooh, I hadn't even noticed the existence of the `--id` flag. Will try to address this in a separate PR.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [--id support for 'convox env set'](https://trello.com/c/xACBkP84/1576-id-support-for-convox-env-set)

**Comment by nzoschke** [comment]
Closing this in favor of an earlier issue #1424
