### ISSUE TITLE
service/resource postgres - multiple database support in one instance

### ISSUE THREAD

**Issue by SonOfBytes** [convox/rack#1570]
I'm evaluating convox for a client which has a multi-az RDS instance from which multiple databases are configured for.

Is it possible to set up multiple databases in a `convox resources` postgres instance?  i.e. add another database_url to an existing instance?

**Comment by mwarkentin** [comment]
I don't think RDS supports this (but not 100% on that). I think you need to use the master user and then create the extra DBs yourself.

**Comment by SonOfBytes** [comment]
Thanks. I believe using the master user is how it was done originally - it would be nice to have an interface that could support this so there was a single way to get the url end points.

**Comment by mwarkentin** [comment]
Yeah, we've been working on some separate DB management tooling using ansible ourselves..
