### ISSUE TITLE
convox build returns error when using ecr url in FROM

### ISSUE THREAD

**Issue by sc-chad** [convox/rack#1578]
In Dockerfile:

```
# This is built from the amazon-linux-image docker directory
FROM #######.dkr.ecr.us-west-2.amazonaws.com/amazon-linux-image/main
```

Doing: ```eval $(aws ecr get-login)```

We get: 

```
convox build
Creating tarball... OK
Uploading: 141.95 KB / 141.78 KB [=======================] 100.12 % 0s
Starting build... OK
Authenticating ########.dkr.ecr.us-west-2.amazonaws.com: Login Succeeded

running: docker build -f /tmp/045347694/Dockerfile -t dojo/dojo-consume /tmp/045347694
Sending build context to Docker daemon 1.248 MB
Step 1 : FROM ########.dkr.ecr.us-west-2.amazonaws.com/amazon-linux-image/main
denied: User: arn:aws:iam::########:user/convox/demo-somerackuser-KernelUser-3K3D5TRH7QYW is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:us-west-2:########:repository/amazon-linux-image/main
ERROR: build error: exit status 1
ERROR: app build failed
```

**Comment by mwarkentin** [comment]
@sc-chad did you follow the instructions in https://convox.com/docs/private-registries/?

**Comment by sc-chad** [comment]
@mwarkentin Thanks michael.  Just curious why isn't this done by default?  Since convox created the registry why do I have to give convox access to use it remotely?

**Comment by mwarkentin** [comment]
I might've misunderstood what you were trying to do - convox creates an ECR to store it's own build containers, but if you want to build and push containers and then reference those in your convox builds, you'll need to create your own ECR and then provide access (that's how I understand it anyways).

**Comment by denmat** [comment]
I followed the instructions in the above link too (add the ecr user, get the creds, etc), it worked for the next deploy but has since stopped working with a similar message (there would have been about 12hrs between deploys).

**Comment by MiguelMoll** [comment]
Checking in to see if this is still an issue? Around the time this issue was created, we noticed there was bug were adding the same registry that rack uses to store images would cause a `ERROR: build error: exit status 1`.

There is now validation so that users can't add the registry and [specific](https://github.com/convox/rack/blob/9328b0c586275e39a60786670cbe6db754d44e6b/provider/aws/dist/rack.json#L893-L902) read-only permissions for repositories in the registry.
