### ISSUE TITLE
Option to override deployment options for emergencies

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#1585]
Just thinking through an idea we had while dealing with a bad deploy - we rolled back the release using `convox releases promote`, but then had the enjoyment of waiting a few minutes for 2 new containers to come up, waiting for some old ones to be removed, then another new container come up, then the last old one get removed.

I was wondering if it would be possible to have a CLI option to override our default deployment options (`min=100`, `max=200`) with something like `min=0`, `max=500`. Not sure what it would be called - maybe something like `--force`, `--fast`, or `--downtime`. **A short period of downtime would be expected in exchange for a faster release promotion cycle.**

This CLI option would be available on anything that promotes a new release:

* `convox deploy`
* `convox releases promote`
* `convox env set`
* `convox env unset`

Any thoughts on if this is technically feasible / desirable?

**Comment by matthewford** [comment]
When I've had to do this, I've resulted to manually modifying the existing task to min=0, and convox will update it to the default after the deploy

**Comment by ddollar** [comment]
The current default options should allow for fast deploys in all cases.
