### ISSUE TITLE
Services on one Rack should not be visible in other Racks

### ISSUE THREAD

**Issue by gisnalbert** [convox/rack#159]
Hi all,

My scenario is that I have two Convox racks on the same AWS region (Rack1 and Rack2).
If I create a service in Rack1 this service is visible to the CLI when targeting Rack2 -- even thought it is not possible to access the service out of the box, as each Rack is on its own VPC.

**Comment by johnboy14** [comment]
Just out of interest.  How do you create different racks in the same Region?

**Comment by gisnalbert** [comment]
@johnboy14  give it rack a different rack name (i.e. convox install --stack-name rackName)

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bnOSdK6g&#x2F;225-multiple-racks-in-one-aws-account"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> multiple racks in one AWS account</a>

**Comment by csquared** [comment]
thanks, y'all! you're totally right -> i think we're missing some tagging here. i've created a card for the top-level issue: making multiple racks in a single aws account.

**Comment by csquared** [comment]
i'm +1 for doing this via choosing a stack-name. we let you configure stack-name at the CLI. if the grid were to name the stack after its name in the grid (which is guaranteed unique) we're also fine.  this stack-name then can be the tag (or at least the semantic part) be used for later CF calls

**Comment by csquared** [comment]
i also wonder if there's a way to do this via an IAM restriction. that'd probably be more effort up front but could make querying simple (no tag to pass around and filter)

**Comment by nzoschke** [comment]
This is because of CloudFormation stack name conflicts. I am closing this in favor of the work happening here:

https://github.com/convox/rack/issues/200
https://github.com/convox/rack/pull/328
