### ISSUE TITLE
Only one security group can be associated to an app

### ISSUE THREAD

**Issue by kemper** [convox/rack#1591]
When configuring the ingress for a privately deployed application, I'm only able to set a single security group:

convox apps params set SecurityGroup=sg-xxx

The rule limit of a security group in amazon is 50 and I currently have 60+ rules spread across 3 security groups.

It looks like I can attach more security groups outside of convox as a workaround. If I do, will that be generally safe when using other convox commands? That is, assuming I don't do a "convox apps params set SecurityGroup"

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support multiple Security Groups per app](https://trello.com/c/ZPxFywMK/438-support-multiple-security-groups-per-app)

**Comment by soulshake** [comment]
@kemper Thanks for your request. I've added this to our Roadmap; feel free to vote on [the card here](https://trello.com/c/ZPxFywMK/438-support-multiple-security-groups-per-app).

We haven't tested your workaround yet, but it's interesting. Have you noticed any unexpected results?

**Comment by ddollar** [comment]
It's currently impossible to do iteration in CloudFormation so we'll have to stay with one security group until they make something easier on that front.
