### ISSUE TITLE
Not able to reuse existing subnets and NAT Gateways

### ISSUE THREAD

**Issue by kemper** [convox/rack#1592]
There doesn't appear to be anyway to reuse existing subnets. The documentation notes that there is a "--subnet-cidrs" option and issue #902 implies that that option would suffice for reusing subnets.

However, when I actually do a convox install I get this error:

Failed AWS::EC2::EIP: The maximum number of addresses has been reached.

The error message is misleading; I only have 3 NAT gateways for my 3 existing public subnets.

Seems like it's trying to create a new set of NAT gateways, which I would not expect it to do if it was going to reuse the existing subnets.

**Comment by kemper** [comment]
Worth mentioning that for my test, I launched one rack with the  --private option and then tried to reuse the vpn, internet gateway, and CIDR's of the first rack I created (2nd rack also with the --private) option.

**Comment by ddollar** [comment]
I'm pretty sure this error means your account has reached the maximum quota of EIPs for the region (it's default to 5) and a Rack install uses 3.
