### ISSUE TITLE
instance-level commands

### ISSUE THREAD

**Issue by ddollar** [convox/rack#16]
- [x] API for listing instances
- [x] CLI command for listing instances
- [x] CLI command for SSHing into an instance
- [x] API for updating SSH key
- [x] CLI command for updating SSH key

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;FcoXrwLC&#x2F;140-instance-level-commands"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> instance-level commands</a>

**Comment by nzoschke** [comment]
- [ ] CLI command for terminating an instance

**Comment by csquared** [comment]
i'm gonna call the instances servers

**Comment by csquared** [comment]
here's a proposal:

```
# Convox Instance Level Commands

What is an "instance"? Too amazon-y.
Let's use "machines" (docker does this too).

## `convox machines`
list all machines in cluster

## `convox machines ssh <machine> <command | sh>`
generate a key locally in a temp dir
update the key for that single machine
ssh into that machine with the local key
that key is deleted off the remote machine in <n> hours

## `convox machines kill <machine>`
issue a shutdown

```

**Comment by csquared** [comment]
rather than keeping keys around, just have the `ssh` command generate it and POST it to the convox APi.

**Comment by csquared** [comment]
would like to ensure keys are always deleted after a point in time, which basically means if you have the API key, you have SSH access. considering the API key gives you compute access i think this is acceptable for now. worth it to ensure ssh actions are well logged

**Comment by nzoschke** [comment]
I'd like to keep "instances". There's no good reason to abstract this part of AWS away. We also use InstanceCount and InstanceSize in the CF template.

**Comment by nzoschke** [comment]
Likewise I think it should be `convox instances terminate` to match AWS.

**Comment by nzoschke** [comment]
There is tons of room for improvement around SSH access, but I'd like to see a CLI path to set up the existing rack SSH implementation first.

For this, a user needs to add a public key to EC2 and give it a name, then set update the Key parameters on the Convox stack with that name. This will restart the entire fleet.

https://github.com/convox/rack/blob/master/api/dist/kernel.json#L505

**Comment by nzoschke** [comment]
The dynamic SSH key stuff is a great idea. Some more food for thought:

* GitHub has SSH pub keys for users. I really like the CircleCI and GitHub integration where you can SSH into a build machine temporarily with no additional key junk.

* Anyone with the API key can do pretty much anything interactively via our `convox run` and `convox exec` APIs. 

* One of our friends is working on AWS access as a service. It already has very advanced SSH key management. https://www.foxpass.com/

**Comment by ddollar** [comment]
If we're going to do dynamic SSH handling, I think it should look like this:

* Rack generates an SSH key during kernel installation (maybe as part of the kernel.json)
* Rack brokers instance-level shells using its own authentication piped to ssh sessions that it manages using the key it knows

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GlqMwDZ7&#x2F;243-ssh-to-instances"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> SSH to instances</a>
