### ISSUE TITLE
code sync: preserve ownership or allow configuration to specify ownership of sync'd files

### ISSUE THREAD

**Issue by twelve17** [convox/rack#1600]
The [docker best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/) document recommends using a non-root user for deployments if the service does not require such privileges.  Thus, my dockerfile contains something like this:

```
RUN useradd --user-group --create-home --shell /bin/false app

WORKDIR /app
COPY . . 
RUN chown -R app:app . 

USER app

ENTRYPOINT [...]
CMD [...]
```

When the service is built via `convox start`, the files have the correct permission.  However, if I edit a file on the host, when the code syncs to the container, the file now ends up with owner `root`.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [code sync: preserve ownership or allow configuration to specify ownership of sync'd files](https://trello.com/c/I4xtDlXz/1658-code-sync-preserve-ownership-or-allow-configuration-to-specify-ownership-of-sync-d-files)
