### ISSUE TITLE
Replace custom connection draining w/ native support

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#1608]
* [Docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-draining.html)

Convox has currently implemented container connection draining using lambda and EC2 instance lifecycles. AWS just released their own implentation which should simplify the convox code.

> There are times when you might need to remove an instance from a cluster; for example, to perform system updates, update the Docker daemon, or scale down the cluster size. Container instance draining enables you to remove a container instance from a cluster without impacting tasks in your cluster. It works by preventing new tasks from being scheduled for placement on the container instance while it is in the DRAINING state and replacing service tasks on other container instances in the cluster, if the resources are available.
>
> When you set a container instance to DRAINING, any service tasks in the PENDING state are stopped immediately. Service tasks on the container instance that are in the RUNNING state are stopped and replaced according to the service deployment configuration parameters. 
>
> You can use the [UpdateContainerInstancesState](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateContainerInstancesState.html) API action or the [update-container-instances-state](http://docs.aws.amazon.com/cli/latest/reference/ecs/update-container-instances-state.html) command to change the status of a container instance to DRAINING.

**Comment by MiguelMoll** [comment]
Indeed the DRAINING state has been a lot of help. Rack is using it [here](https://github.com/convox/rack/blob/9328b0c586275e39a60786670cbe6db754d44e6b/provider/aws/lambda/lifecycle/main.go#L93-L98).
