### ISSUE TITLE
Create a Convox rack with a defined password

### ISSUE THREAD

**Issue by gisnalbert** [convox/rack#161]
Would it be possible to create a Convox rack with a pre-defined password, instead of a generated password on each installation? I have looked at the documentation and the trello board and have not found any mention on this.

This would make it a lot simpler to automate the creation of multiple racks (i.e. one per environment).

Regards,

**Comment by nzoschke** [comment]
"Password" is a Rack CloudFormation Parameter, so setting it's initial value as well as updating it later is very straightforward.

Right now the installer always generates a random password that is passes onto the CloudFormation CreateStack call:

https://github.com/convox/rack/blob/master/cmd/convox/install.go#L271
https://github.com/convox/rack/blob/master/cmd/convox/install.go#L284

Add one more flag to the install command to read `--password` or `ENV[PASSWORD]` and use that if set:

https://github.com/convox/rack/blob/master/cmd/convox/install.go#L91-L96

I'm applying the `help wanted` label as I think this would be great feature for someone else to contribute.

**Comment by nzoschke** [comment]
Implemented in https://github.com/convox/rack/pull/455.

Thanks you @gisnalbert for the feedback and @mwarkentin for the implementation!
