### ISSUE TITLE
`convox builds` not able to run from CI with the deploy key

### ISSUE THREAD

**Issue by edkellena** [convox/rack#1610]
Trying to run a `convox builds` command from CI using the deploy key hits a wall as it only allows certain commands:

```
ERROR: Command not supported for deploy key (try build, promote, deploy)
```

This makes moving builds between racks impossible.

Background:
I'm trying to do a deploy to our staging/dev environment and also get the build onto production (but not promoted) so it's ready to go whenever we want.  I was doing a simple `convox deploy` for dev and then separately `convox build` for production, but that obviously builds the whole app twice, so thought it would be neater/quicker/better to move the already built app to the production rack.

**Comment by MiguelMoll** [comment]
This is a reasonable request. As deploy keys are Console specific, I'll move this over to it's internal project. Please keep the conversation going here if needed.

**Comment by edkellena** [comment]
Hey @MiguelMoll just checking in to see if this has had any traction?
I have a handy script that I would love to run on CI rather than manually to do this...

```
cat pipeBuilds.sh                                                                                                                              
#!/bin/bash

APP_NAME=$1
RACK1=${2:-development}
RACK2=${3:-production}

BUILD_ID=$(eval "convox builds -a $APP_NAME --rack $RACK1 | awk 'NR==2 {print \$1}'")

convox builds export $BUILD_ID -a $APP_NAME --rack $RACK1 | convox builds import -a $APP_NAME --rack $RACK2
```

**Comment by MiguelMoll** [comment]
@edkellena This is something we're trying to sort out. Apologies for the delay. As this pertains to Console, would you be able to create a support ticket through that interface stating this request? Linking to this issue would help too. Thanks!

**Comment by edkellena** [comment]
Hey, sure, I mentioned it in support ticket 423.  I can raise a specific ticket though if that's better?

**Comment by MiguelMoll** [comment]
Ah I just found 423. But it's been closed as that was a slighting different issue. If you could open a new one, that would be appreciated. 👍

**Comment by edkellena** [comment]
595 raised 😉

**Comment by MiguelMoll** [comment]
This is now available in latest Console. 🎉
