### ISSUE TITLE
Convox gets stuck on bad promote / deploy.  Auto Cancel?

### ISSUE THREAD

**Issue by sc-chad** [convox/rack#1613]
This has been brought up a few times in slack so I was asked if I would open a ticket here.

If a deploy or a promotion of an app is bad for whatever reason.  

Currently it will end up in this loop of:
```
create
start
stop
kill
```
While it is doing this the app stays in an "Updating" state and can't be rolled back. 

The two options currently far as I know are:
Manually rolling back via cloudformation
Doing `convox app cancel app_name` or something close

Instead of the current methods, it would be nice if convox could detect when a bad promotion has happened and auto cancel the app promotion and roll back to the previous.  While also communicating to user that the deploy/promote failed.

**Comment by spencerhakim** [comment]
The [docs](https://convox.com/docs/rolling-updates/#automatic-rollback) say it should happen after 10 minutes, but the one time I waited for it to happen, it didn't.

10 minutes is kind of a long time to wait anyway, at small scales you'll know things are broken way soon. It should probably be a computed value like `((convox.health.timeout + 2) * 2) * [scale count] * 3`, with `((convox.health.timeout + 2) * 2)` based on the documentation around the health check interval and how many times it's allowed to fail, and the 3x multiplier just for some wiggle room. With the default value of `convox.health.timeout=3` and a single process, that comes out to 30 seconds, which seems pretty reasonable.

**Comment by paulkernfeld** [comment]
What if `convox deploy` contained a `--timeout` arg that could be manually set, which would automatically cancel the update if it didn't resolve in a particular amount of time? Obviously intelligently setting a default timeout would be great as well, but this could be a good way to let users opt in to the functionality while bugs are ironed out.
