### ISSUE TITLE
Command: convox instances ssh <id> with error: ssh: no key found locks terminal

### ISSUE THREAD

**Issue by sc-chad** [convox/rack#1614]
```
client: 20170123152656
server: 20170123010613 (console.convox.com)
```

If you try to do:
```convox instance ssh <some_id>``` 
and you get an error.  It hard locks like the exec command used to do.

**Comment by MiguelMoll** [comment]
This has been solved on recent racks.
```
> convox instances ssh i-0c4f5e47ea87b7f7d
ERROR: ssh: no key found
>
```

Please reopen if that is not the case.
