### ISSUE TITLE
Use environment declaration in docker-compose.yml to whitelist container environment when deployed to ECS

### ISSUE THREAD

**Issue by amsb** [convox/rack#1624]
Currently, the statement "because the environment holds sensitive secrets, the environment declaration is a whitelist." in the [Convox Guide](https://convox.com/guide/environment) only applies to the local development environment but would be even more powerful if extended to the deployed environment on ECS where environment whitelisting would give a simple yet effective mechanism for controlling the distribution of secrets amongst containers.

**Comment by jayjanssen** [comment]
+1, I agree it would be useful to limit the environment exposed to each service in some way.  However, it's not as simple as only including variables listed in the docker-compose -- linked services get variables too that are not explicitly called out in the compose file and that needed variable list often changes in an actual rack.
