### ISSUE TITLE
Use COMPOSE_FILE environment variable as default file when set

### ISSUE THREAD

**Issue by amsb** [convox/rack#1626]
Docker Compose uses the COMPOSE_FILE environment variable as the default when set:

https://docs.docker.com/compose/reference/envvars/#composefile

Doing the same with Convox would make it a bit easier to manage test/build/deploy scripts.

**Comment by ddollar** [comment]
Doing a bit of feature request culling here. Please use the `-f` flag to `convox start` or `convox build`
