### ISSUE TITLE
How are secrets exposed to containers?

### ISSUE THREAD

**Issue by lvh** [convox/rack#1634]
From spelunking the code, I discovered that `convox env` writes a file to S3 using a KMS key. How does a deployed application access that environment? 

My goal is to limit access to environment variables, and get audit logs on access. Can I expect a new container being launched to map to a CloudTrail access for that KMS key?

**Comment by dlanger** [comment]
They're set as environment variables in the ECS task definition - not sure how that looks in CloudTrail.

**Comment by lvh** [comment]
Thanks! This explains a lot; I have since found the documentation page with those keywords. AFAICT the answer is that you'll see CT logs on deploy (technically: on release), because that's when it gets decrypted and stuffed into ECS task definitions. That means you don't have access logs for anything past that point (not a criticism, just an observation). Thanks again :)
