### ISSUE TITLE
Support for IAM Task Roles

### ISSUE THREAD

**Issue by lvh** [convox/rack#1635]
By default, containers running on ECS have access to the IAM Role of the host unless this is explicitly disabled (is that the case for Rack?). ECS additionally supports [IAM Roles for Tasks][irt]. It appears this isn't currently supported by Rack. It would be convenient if there was a way to specify this for Rack, so that application privilege management could be tied closely to IAM.

[irt]: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

**Comment by dlanger** [comment]
I haven't used it, but I think this was implemented in https://github.com/convox/rack/pull/1659

**Comment by mattmanning** [comment]
This feature was released in Rack version 20170207013217.
