### ISSUE TITLE
`convox resources proxy` undocumented

### ISSUE THREAD

**Issue by contra** [convox/rack#1645]
When you run `convox resources proxy` it returns the usage for `convox resources info`.

Also appears this command is undocumented on the website and absent from all CLI docs.

**Comment by soulshake** [comment]
@contra Thanks for the heads up, will fix this ASAP.

By the way, `convox resources proxy` is documented [here](https://convox.com/docs/convox-proxy/#access-external-resources-with-convox-resources-proxy). If you let me know how you were searching for it, I can try to fill in some keywords that would make it easier to find.
