### ISSUE TITLE
Inconsistent display and reporting of errors 

### ISSUE THREAD

**Issue by soulshake** [convox/rack#1664]
Some ideas for improving logging and error reporting consistency in the CLI:

- we should write logs to a file on disk (`/var/log/convox.log`...) to provide debugging info without being too verbose on stdout
- we should actually report extra information when `CONVOX_DEBUG` is present (currently only used in one sync-related context, I believe)
- we should log consistently to Rollbar, distinguishing properly between validation errors and our-fault errors, for every error displayed to the user
- every error that is user-facing or sent to Rollbar should have corresponding test coverage
- we should ensure accurate exit codes

Since Rollbar reporting is logically separated from user-facing error display, it's both messy and difficult to be sure that all errors are being both displayed and reported.

Perhaps we could implement a helper/wrapper for error handling to ensure things are reported 1. to the user, 2. to logs on disk, and 3. to Rollbar.

Extra credit if:
- We can improve the `if err != nil{}`-to-code ratio
- We can set `CONVOX_DEBUG` not only to true or false, but to `1`, `2`, etc

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make Github issue for logging/debug mode/CLI stats](https://trello.com/c/xvdYQcwu/1525-make-github-issue-for-logging-debug-mode-cli-stats)

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CLI logging and error reporting](https://trello.com/c/flog8LsF/1791-cli-logging-and-error-reporting)
