### ISSUE TITLE
SSL certificate chain support?

### ISSUE THREAD

**Issue by sherbondy** [convox/rack#173]
Hey all,

@rjocoleman suggested this in a proposal for the then-unreleased ssl certificate functionality in convox:
https://github.com/convox/kernel/issues/100

Would be great to revisit adding cert chain support. I'll probably have to continue to rely on uploading and assigning certificates manually via the aws cli or web dashboard in the meanwhile, as would most people who want to deploy a public-facing website via convox (chrome on android in particular is finicky about this).

Just want to chime in that after perusing the web for a bit, I found another project that might be of interest for automating the certificate chain generation process:
https://github.com/zakjan/cert-chain-resolver/

(In case there's some issue about adding a dependency on cfssl)

They've ported it to go as well:
https://github.com/zakjan/cert-chain-resolver/tree/golang

I think to play nice with Amazon's requirements, would want to use the "--intermediate-only" option.

A bare minimum solution would be to avoid the auto-generated chain altogether and just amend the convox cli / api to support the optional third parameter for a user-specified chain file.

AWS docs detailing the certificate chain here: http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs_manage.html#UploadSignedCert

Could have a go at a PR for an initial implementation of this if you point me in the right direction!

Thanks.

**Comment by nzoschke** [comment]
chain support was reviewed and improved in https://github.com/convox/rack/pull/263
