### ISSUE TITLE
Port tunnel into Rack

### ISSUE THREAD

**Issue by ddollar** [convox/rack#18]
Add the ability to create a tunneled port from a user's local machine into the Rack for temporary access to management consoles, etc.

- [ ] API for local port tunnel into rack
- [ ] CLI for local port tunnel into rack

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XnbBcCeZ&#x2F;142-port-tunnel-into-rack"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> port tunnel into rack</a>

**Comment by nzoschke** [comment]
Can the same effect be achieved with `convox ssh` somehow?

**Comment by aisipos** [comment]
In principle, `convox instances ssh` could be used to do port tunneling, but for now it seems ssh arguments aren't being passed down to ssh in the command line. 

Possibly another option in the future to see internal services would be to add OpenVPN as a supported convox service. This would be convenient for users, but probably a pain to implement. I have seen some efforts to automate much of the install, for instance here: https://github.com/Nyr/openvpn-install/blob/master/openvpn-install.sh

**Comment by ddollar** [comment]
Closed by #475
