### ISSUE TITLE
Volume not mounted on deploy when defined in `docker-compose.yml`

### ISSUE THREAD

**Issue by asyazwan** [convox/rack#183]
I experienced this today. I removed `COPY . /app` from my `Dockerfile`. I thought it's fine since in `docker-compose.yml` I have `volumes: .:/app`.

`convox start` works as expected but `convox deploy` will not mount the volume. Is `volume` from compose file actually being used by non-local convox operations?

What I expect is the mount will translate into copying from S3 into `/app` (while still honoring `.dockerignore`).
What happened: empty `/app`, nothing copied from S3.

**Comment by benjamin0** [comment]
I'm having the same issue, nothing in ```volumes:``` is being mounted. I've tried with relative and absolute paths, but the issue is the same

**Comment by benjamin0** [comment]
I should add that it works fine with ```convox start```, but ```convox deploy``` doesn't mount the volumes.

**Comment by csquared** [comment]
That's right -> I hunted down the line of code that is stripping all the volumes except the docker socket.  https://github.com/convox/rack/blob/b3da20b4215d0677676605f0973b65bd35d147df/api/models/helpers.go#L427-L431  

I'm not 100% sure why but my guess is that its not straightforward how you would get a file onto the instance to mount in-> you'd probably need to provide your own AMI or customize the startup scripts to ensure the files are on the machines on boot up, which *somewhat* defeats the ephemeral nature of instances. What do you guys think?

**Comment by csquared** [comment]
I think this should be documented better. It seems like it shouldn't work locally if we're explicitly disabling it in production and warn you that its not going to mount the volumes (would save most of the WTFs on what is happening)

**Comment by benjamin0** [comment]
Thanks for the quick response, @csquared. My use case is mounting config files as stated in the [documentation](https://convox.com/docs/developing-locally/).
>The volumes key is passed to docker run to mount a volume for read and write access into the running container. This is useful for mapping in config files that exist in your source repository or for mapping the source code directories into the docker container so you can do code reloading on change detection.
>

I think for mounting config files in production, it could work similarly to `COPY`. Mapping source code directories for code reloading is probably more of a development requirement, not production. If it's not possible to mount config files this way, ```convox start``` should mimic how ```convox deploy``` works to avoid confusion.

**Comment by mfine** [comment]
Not sure how the ECS volumes mounting is going to work - the [To provide nonpersistent empty data volumes for containers](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html) section makes it sound like we need a "named" volume without a path (that docker will manage for us?), and somehow we map that volume to a map point? Don't know how that would integrate with: [ecs.go#L388-L407](https://github.com/convox/rack/blob/master/api/cmd/formation/handler/ecs.go#L388-L407)

Ideas?

**Comment by ddollar** [comment]
We don't currently support volumes in production. This may change with something based on top of EFS when it becomes available.

**Comment by nzoschke** [comment]
This did change and volumes via EFS are available on https://github.com/convox/rack/releases/tag/20160714004416
