### ISSUE TITLE
Add encryption-at-rest option to database resources

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1834]
https://trello.com/c/2HnO4koL/89-add-encryption-at-rest-option-to-database-resources

**Comment by SonOfBytes** [comment]
Is this WIP?

**Comment by MiguelMoll** [comment]
Not at the moment. Contributions are welcomed! 😃

**Comment by SonOfBytes** [comment]
PR submitted - guidance required on tests and use of KMS key :)

**Comment by MiguelMoll** [comment]
Dupe #1335
