### ISSUE TITLE
CLI description, argument, help consistency and cleanup

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1860]
data: {u'text': u'https://github.com/convox/rack/issues/1779', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 26, u'shortLink': u'efteFk3N', u'id': u'5874589bb341d597857671a0', u'name': u'CLI description, argument, help consistency and cleanup'}}
date: 2017-02-08T13:15:21.057Z
id: 589b19e9a027db69e2ceb965
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/efteFk3N/26-cli-description-argument-help-consistency-and-cleanup

**Comment by MiguelMoll** [comment]
Fixed via #1996
