### ISSUE TITLE
Guide and Doctor

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1870]
## [Guide Outline on GitHub](https://github.com/convox/site/issues/295)

data: {u'text': u'https://github.com/convox/rack/issues/1811', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 442, u'shortLink': u'PMNaQTAN', u'id': u'588fa6c7b682276825fb0e77', u'name': u'Guide and Doctor'}}
date: 2017-02-08T13:15:52.975Z
id: 589b1a08c9278253b279bac3
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/PMNaQTAN/442-guide-and-doctor

**Comment by nzoschke** [comment]
Closing in favor of https://github.com/convox/site/issues/295
