### ISSUE TITLE
Elasticsearch resource

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1872]
data: {u'text': u'https://github.com/convox/rack/issues/1813', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 47, u'shortLink': u'xUHGXHWZ', u'id': u'5874595dabb9c1c2dfafcf84', u'name': u'Elasticsearch resource'}}
date: 2017-02-08T13:15:54.959Z
id: 589b1a0a565fc9a7727d8a33
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/xUHGXHWZ/47-elasticsearch-resource

**Comment by MiguelMoll** [comment]
Dupe #1324
