### ISSUE TITLE
ECS autoscaling

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1882]
data: {u'text': u'https://github.com/convox/rack/issues/1797', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 52, u'shortLink': u'ZYLqsaH5', u'id': u'58745985705fe4c547ec34c5', u'name': u'ECS autoscaling'}}
date: 2017-02-08T13:15:39.359Z
id: 589b19fb76fb6bae1de23bb1
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/ZYLqsaH5/52-ecs-autoscaling

**Comment by MiguelMoll** [comment]
Vague trello card. Let's open another one if needed.
