### ISSUE TITLE
Alarms

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1883]
Customer request:

"We would like to define alarms in our compose file. This is an example alarm (not our example, just Amazon example)

Basically just a cpu alarm above 70% for the instance (but via convox this should be the process/container)

aws cloudwatch put-metric-alarm --alarm-name cpu-mon --alarm-description "Alarm when CPU exceeds 70 percent" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 70 --comparison-operator GreaterThanThreshold --dimensions "Name=InstanceId,Value=i-12345678" --evaluation-periods 2 --alarm-actions arn:aws:sns:us-east-1:111122223333:MyTopic --unit Percent"

data: {u'text': u'https://github.com/convox/rack/issues/1807', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 79, u'shortLink': u'TAnKJV3w', u'id': u'5876d8ac9d5117c37b28cd4e', u'name': u'Alarms'}}
date: 2017-02-08T13:15:49.641Z
id: 589b1a058b551dbeb68a6626
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/TAnKJV3w/79-alarms

**Comment by nzoschke** [comment]
Closing in favor of https://github.com/convox/rack/issues/1883
