### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1884]
data: {u'text': u'https://github.com/convox/rack/issues/1803', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 55, u'shortLink': u'Gvva4Vus', u'id': u'587459950e3082dcc369d65b', u'name': u'Routing'}}
date: 2017-02-08T13:15:46.911Z
id: 589b1a02e42e5a6f818430fa
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/Gvva4Vus/55-routing

**Comment by nzoschke** [comment]
Closing in favor of https://github.com/convox/rack/projects/23
