### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1887]
data: {u'text': u'https://github.com/convox/rack/issues/1806', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 53, u'shortLink': u'OK3eKpf0', u'id': u'5874598ab429c34d9d2a7310', u'name': u'Linking'}}
date: 2017-02-08T13:15:49.032Z
id: 589b1a05ca3231287a1a6c57
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/OK3eKpf0/53-linking

**Comment by nzoschke** [comment]
Closed in favor of https://github.com/convox/rack/projects/33
