### ISSUE TITLE
Stable channel

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1889]
data: {u'text': u'https://github.com/convox/rack/issues/1809', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 43, u'shortLink': u'XT6cqB4O', u'id': u'5874592613d536a2681f3573', u'name': u'Stable channel'}}
date: 2017-02-08T13:16:03.599Z
id: 589b1a13016e6987b07db0b8
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/XT6cqB4O/43-stable-channel

**Comment by MiguelMoll** [comment]
This feature is currently being designed. Believe a better issue can be opened later. Closing for now.
