### ISSUE TITLE
Ability to restart a running container without redeploying

### ISSUE THREAD

**Issue by asyazwan** [convox/rack#189]
Today I encountered a situation where I would like to restart a single service inside an app. It would be nice if there is `convox restart -a prod <service_id>`.

**Comment by jdubie** [comment]
:+1:

**Comment by asyazwan** [comment]
Just to be clear, currently there is `convox stop <proc_id>` to achieve a restart. And to stop is currently doing `convox sclae --count 0`. Even though I disagree with such naming, it achieves desired results.

**Comment by contra** [comment]
I think this would be good to add - convox stop no longer exists, btw.

**Comment by mwarkentin** [comment]
@contra I think the actual command is `convox ps stop`:

```
$ convox ps --help
convox ps: list an app's processes

Usage:
  convox ps <command> [args...]

Subcommands: (convox ps help <subcommand>)
  info		show info for a process
  stop		stop a process
```

**Comment by skwp** [comment]
Yeah stop is pretty confusing causing a restart...this should at least be documented or better yet aliased as `restart`
