### ISSUE TITLE
Lambda Custom Topic Off Node 0.10

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1891]
data: {u'text': u'https://github.com/convox/rack/issues/1792', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 383, u'shortLink': u'KJsy1hqI', u'id': u'586fa7b88f453663d6688afa', u'name': u'Lambda Custom Topic Off Node 0.10'}}
date: 2017-02-08T13:15:34.077Z
id: 589b19f62f55dc581d900b0c
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

data: {u'text': u'Another idea: Can we update lambda functions and runtimes in place outside of cloudformation?', u'list': {u'name': u'Big Projects', u'id': u'5874264096c4913948a0ac7d'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 383, u'shortLink': u'KJsy1hqI', u'id': u'586fa7b88f453663d6688afa', u'name': u'Lambda Custom Topic Off Node 0.10'}}
date: 2017-01-16T23:32:58.898Z
id: 587d582a4fc05ad9fa547bc2
idMemberCreator: 4f26df78114e3e040d62d52d
memberCreator: {u'username': u'nzoschke', u'fullName': u'Noah Zoschke', u'avatarHash': u'53c860bb51950517f3cf01e346cea68d', u'id': u'4f26df78114e3e040d62d52d', u'initials': u'NZ'}
type: commentCard

https://trello.com/c/KJsy1hqI/383-lambda-custom-topic-off-node-0-10

**Comment by MiguelMoll** [comment]
Apps have been moved off of Node 0.10. Racks are being updated as AWS rolls out regions that support in-place runtime change.
