### ISSUE TITLE
Local Rack

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1895]
data: {u'text': u'https://github.com/convox/rack/issues/1796', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 54, u'shortLink': u'jZCR9WPL', u'id': u'5874598cb132d2f109322ea8', u'name': u'Local Rack'}}
date: 2017-02-08T13:15:38.152Z
id: 589b19fa735acf47b72e969b
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

data: {u'text': u'Possibly add an environment variable to tell convox start to do a: eval $(aws ecr get-login) before building.  Another possible option would be have convox check the Dockerfile / docker-compose to see if the image file has an ecr url in it.  If so login before hand instead of pulling local.', u'list': {u'name': u'Big Projects', u'id': u'5874264096c4913948a0ac7d'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 54, u'shortLink': u'jZCR9WPL', u'id': u'5874598cb132d2f109322ea8', u'name': u'Local Rack'}}
date: 2017-01-18T21:57:00.246Z
id: 587fe4ac70f5436b151e6cfc
idMemberCreator: 587fe45651ab9927d9410b5f
memberCreator: {u'username': u'chadupton', u'fullName': u'Chad Upton', u'avatarHash': None, u'id': u'587fe45651ab9927d9410b5f', u'initials': u'CU'}
type: commentCard

https://trello.com/c/jZCR9WPL/54-local-rack

**Comment by nzoschke** [comment]
Closing in favor of https://github.com/convox/rack/projects/27
