### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1896]
data: {u'text': u'https://github.com/convox/rack/issues/1799', u'list': {u'name': u'Rack', u'id': u'5899e3224255b666d6e7d9e9'}, u'board': {u'shortLink': u'XxvWeICx', u'id': u'587425638297353d93b2d4af', u'name': u'Roadmap'}, u'card': {u'idShort': 66, u'shortLink': u'PuUYJ3D0', u'id': u'5876d7110dc466fb3a8ce584', u'name': u'Webhooks'}}
date: 2017-02-08T13:15:40.922Z
id: 589b19fcd62bcb6d7a8c389b
idMemberCreator: 4f3c59c1d9d3e56b446861d8
memberCreator: {u'username': u'ddollar', u'fullName': u'David Dollar', u'avatarHash': u'4b941446da3c56990164d470ea22bb2f', u'id': u'4f3c59c1d9d3e56b446861d8', u'initials': u'DD'}
type: commentCard

https://trello.com/c/PuUYJ3D0/66-webhooks

**Comment by MiguelMoll** [comment]
Vague Trello issue. Let's open another one with more details if needed.

**Comment by MiguelMoll** [comment]
Vague Trello issue. Let's open another one with more details if needed.
