### ISSUE TITLE
Moving secrets out of the environment

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1899]
Document a way to manage secrets without `convox env`.

https://trello.com/c/spSVnC08/61-moving-secrets-out-of-the-environment

**Comment by dlanger** [comment]
I'm not sure if it's what you mean on this, but I'd be very excited to get secrets out of ECS environment parameters and into something else (managing them though the `convox env` command, though, is nice).

Some ideas @mwarkentin and I have considered:
* Populate a directory with one file per secret, and then we can read from there in our code
* Add entries to `/etc/environment` 
* Come up with a version of [`envdir`](https://pypi.python.org/pypi/envdir) that reads from `convox env`, and either inject that at build-time or just provide it and make it our responsibility to add it to the container

We've also used [`sneaker`](https://github.com/codahale/sneaker) for secrets which don't work well with `convox env` (like shared private keys), and while I've never tried it, [`credstash`](https://github.com/fugue/credstash) promises to be the same thing implemented differently.

**Comment by SonOfBytes** [comment]
I've just hit the limitation on env

`$ convox deploy
Deploying app
Creating tarball... OK
Uploading: 22.07 KB / 21.90 KB [=========================] 100.79 % 0s
Starting build... ERROR: InvalidParameterException: Container Overrides length must be at most 8192`

Hit this limit by having keys and certs for an app injected.

A nice pattern is credstash (unicreds in golang) as a service pattern modified to support release filtering would be great.  Standing up the infra for credstash is trivial - kms, dynamodb

Not sure comfort in envdir as having stuff written to docker fs layers on disk unencrypted feels like an opportunity to leak sensitive materials.

**Comment by mwarkentin** [comment]
I think I've seen people mounting a volume with their secrets in a container - might be better than directly writing the files to the container FS?

**Comment by dlanger** [comment]
Putting the secrets into a docker layer would definitely be a step back.
