### ISSUE TITLE
Have `convox init` run all buildpack detects via a `convox/init` image

### ISSUE THREAD

**Issue by MiguelMoll** [convox/rack#1911]
A docker image with buildpacks pre-installed is an effective way to detect many types of apps.

## Detect

- [x] Ruby
- [x] NodeJS
- [x] Clojure
- [x] Python
- [x] Java
- [x] Gradle
- [x] Scala
- [x] PHP
- [x] Go

## Image

- [ ] Publish image source to GitHub
- [ ] Publish image to Dockerhub
- [ ] Add to rack release management

**Comment by nzoschke** [comment]
## QA Checklist

### Init Image
- [ ] docker rmi convox/init
- [ ] convox update

### Example app gives friendly errors
- [ ] git clone ruby-getting-started
- [ ] convox start
- [ ] convox deploy

### Example app is dockerized
- [ ] convox init
- [ ] convox start
- [ ] convox deploy

**Comment by nzoschke** [comment]
Some QA notes...

- [ ] `convox init` when you dont have the image should display some friendly output

**Comment by nzoschke** [comment]
Maybe something like `Building ruby app to generate metadata. This could take a while...`

**Comment by MiguelMoll** [comment]
Went out via #1932
