### ISSUE TITLE
Internal Load Balancers

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#192]
If a docker-compose.yml has only one port instead of a pair (e.g):

```
ports:
  - 5000
```

Then an “internal” load balancer will be created. This will only be accessible inside the VPC.

**Comment by nzoschke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;hJ0HGNvv&#x2F;244-internal-load-balancers"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> internal load balancers</a>

**Comment by cleblanc87** [comment]
thoughts on making the internal elb creation optional somehow?

i was looking at using the convox api & nginx/haproxy to do service discovery similar to https://github.com/jwilder/nginx-proxy which we use for local dev, most like going to attempt this setup for deployment using https://github.com/mashape/kong, which will also have load balancing built in soon https://github.com/Mashape/kong/issues/157. this would eliminate the need for elbs in our use case

**Comment by gisnalbert** [comment]
Sorry for hi-jacking the internal ELB issue, but I believe this feature can be extended to include internal ELB for app creation as well:

Scenario: deploy multiple micro services, each one as its own app on convox. But all these services only exposes REST APIs, so it would be accessible only internally on the rack -- by other services and by the UI front end.
Only the front end would be exposed publicly.

On the described scenario, I would only need to secure the APIs with public ELBs (at least initially!).

Potential CLI can be along the lines of:

```
convox build --expose-elb=false (default true)
```

**Comment by nzoschke** [comment]
This was fixed in https://github.com/convox/rack/pull/213

Optional ELBs is commonly requested, however I don't see a clear path to it. Particularly tricky is how the ECS and ELB integration is a key part of deploying new containers.
