### ISSUE TITLE
KernelUser needs `elasticloadbalancing:ApplySecurityGroupsToLoadBalancer` permission 

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#1927]
Reported by Lisa in Slack

The `convox apps params set SecurityGroup=...` command errors out with:

`API: elasticloadbalancing:ApplySecurityGroupsToLoadBalancer User: arn:aws:iam::100371365652:user/convox/convox-uat-KernelUser-1DUQTUTJYDBHP is not authorized to perform: elasticloadbalancing:ApplySecurityGroupsToLoadBalancer on resource: arn:aws:elasticloadbalancing:us-east-1:100371365652:loadbalancer/vault-client-vault-clien-KV6CTG3`

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [KernelUser needs `elasticloadbalancing:ApplySecurityGroupsToLoadBalancer` permission](https://trello.com/c/tq6ZTtKK/1907-kerneluser-needs-elasticloadbalancing-applysecuritygroupstoloadbalancer-permission)

**Comment by MiguelMoll** [comment]
Fixed via #1932
