### ISSUE TITLE
Add HTTPS support for Proxy tunnels

### ISSUE THREAD

**Issue by SonOfBytes** [convox/rack#1928]
According to the documentation the proxy tunnel is unencrypted.

https://convox.com/docs/convox-proxy/

"Under the hood, this creates an HTTP websocket tunnel through your Rack process"

This means that sensitive data that we may upload to services like RDS are going unencrypted over the  wire.

**Comment by MiguelMoll** [comment]
Believe the documentation should be clarified. Data over the wire to any remote resource is encrypted over HTTPS and secure websocket (WSS).

**Comment by MiguelMoll** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update proxy doc that data is encrypted](https://trello.com/c/PoUx7jw6/2277-update-proxy-doc-that-data-is-encrypted)
