### ISSUE TITLE
Add docker tags to builds and  releases etc

### ISSUE THREAD

**Issue by grandmore** [convox/rack#193]
Can tags be added to the cli so they appear in deploy, build,and info etc. It's very difficult to know which build is which, especially when we start rolling back.

## Display example
**Current display**

ID | CREATED | STATUS
------------ | ------------- | -------------
RPQXMFAQLVL | 1 day ago | active
RYPZKUHXVHT | 2 day ago |
RBFTTSYHHGY | 3 day ago |

**Preferred Display**

ID | CREATED | STATUS | TAGS
------------ | ------------- | ------------- | -------------
RPQXMFAQLVL | 1 day ago | active | V3, Production, latest
RYPZKUHXVHT | 2 day ago |        | V2, Production  
RBFTTSYHHGY | 3 day ago |        | V1, Production  

#### Normal Workflow
1. Push code to github (push v2)
2. Github Webhook tells Convox to deploys new release (deploy v2)
3. Rinse and repeat

#### Rollback process
1. Push code to github (push v2)
2. github webhook tells Convox to deploy new release (deploy v2)
3. Release has problems, so I manually roll it back. (roll back deploy to v1)
4. push fixed code to github (push v3)
5. github webhook tells Convox to deploys new release (deploy v3)

This way I can manually pull back a release, but still automatically deployed a new version when it gets push to the repository again.

Currently I have no way of knowing what version is running. copying docker tags would make this trivial.

## Complex Workflow example
Our workflow is actually a little more complicated as we use 2 branches, Master and Production, with feature builds, fixes and releases within them.

Master, is for live public releases.
Production, is for internal releases.

We use the git branching model. so we have a lot of control. But it makes it doubly hard to know which release is which
![Gitflow](http://nvie.com/img/git-model@2x.png)
[A successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mBfDHtWm&#x2F;251-add-docker-tags-to-builds-and-releases"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add docker tags to builds and releases</a>

**Comment by nzoschke** [comment]
@asyazwan also requested tagging releases in https://github.com/convox/rack/issues/190. Will docker tags satisfy your request, or do you want another way to set tags?

**Comment by nzoschke** [comment]
Actually I'm a little unclear about docker tags myself. @grandmore do you mean git tags?

**Comment by nzoschke** [comment]
## Design Playbook

- [ ] Sketch CLI commands
- [ ] Sketch CLI outputs
- [ ] Sketch API

**Comment by asyazwan** [comment]
I'd personally be happy with any form of tagging.

**Comment by nzoschke** [comment]
The build API now has a description field.

```bash
$ convox build --description "version 10"
Creating tarball... 
...
web.BFLSEVFNWWG: digest: sha256:16890ab287cc3fbc49dd99c6346324d6eb228c71891e407091c5b2ed788e2cd7 size: 9200

$ convox builds
ID           STATUS    RELEASE      STARTED         ELAPSED  DESC      
BFLSEVFNWWG  complete  RDIVQDJPQDH  14 seconds ago  5s       version 10
```

This is also used with console.convox.com's auto build system:

```

$ convox builds info
ID           STATUS    RELEASE      STARTED       ELAPSED  DESC
BPLZADWVUXF  complete  RBKBQQLPUUT  17 hours ago  269m50s  push nzoschke/httpd refs/heads/master 7a16037e8aafed70ed97fff2417a16c9ac8f8deb
BHXQABKIRPN  complete  RKKHVGHVDBC  1 day ago     5m26s    push nzoschke/httpd refs/heads/master 21505a985b9ae0b24081300cbdc405855a3878ee
BYOLUWWNOFR  complete  RFCHLALYKPK  1 day ago     4m37s    push nzoschke/httpd refs/heads/master ae82d936f44b93a30e4e4d369627d72493b117bf
BIEONUUDCTB  complete  RVBYWNZUSSE  1 day ago     6m36s    push nzoschke/httpd refs/heads/master 878c48db40be191da5ef83711256a80527afad88
BAXZPQGLQTX  complete  RNLGHCPMSQR  1 day ago     133m51s  push nzoschke/httpd refs/heads/master 57e767201b5801f5a83efd25735d750d6af8bf23
BRUYIQUPJVH  complete  RCBZQSQDYFQ  1 day ago     246m23s  push nzoschke/httpd refs/heads/master a29006718c5ed5040e40b3bf420da6f020d15d12
BAYTAQJJPGI  complete  RUYDHTDASGX  2 days ago    4m32s    push nzoschke/httpd refs/heads/master 939219f215f8f6928bdc54d6ec6fbb475c4073a3
BHLDCEBWYEY  complete  RBYCCUKXNBN  2 days ago    11m23s   push nzoschke/httpd refs/heads/master ee03aa2d43225b531921c3b59569d85cb5369d11
BVTFLGEBQCR  complete  RHYEEAXQKJD  2 days ago    4m35s    push nzoschke/httpd refs/heads/master a9f588ab38f0591f3d1f93629207790a7d66abf7
BXZNQSZJIDI  complete  RYMXARXWAKP  2 days ago    5m18s    push nzoschke/httpd refs/heads/master 099b59f613d262c143b4fb3f7b588d2187528536
BAALUAHPTXJ  complete  RDBIDUUSXEG  2 days ago    4m53s    push nzoschke/httpd refs/heads/master acd00bcfa3377dc6b5fd3da3183fbd3c2c172402
BJLHWWHVUJP  complete  RDLDJBYKDYO  2 days ago    5m7s     push nzoschke/httpd refs/heads/master 85f7617751050af1b1f68f399fb7349c08de44be
BAOYQXXGSRD  complete  RYRKHENSGXI  3 days ago    4m42s    push nzoschke/httpd refs/heads/master 388e0902abdc4b2253a95446f43b3bf4d3965183
BMJPYLHYKYI  complete  RUATFNJHXGX  3 days ago    11m33s   push nzoschke/httpd refs/heads/master 39477587effdeffdb0e4a53c5db71b5589cfcbe5
```

**Comment by nzoschke** [comment]
I propose that build descriptions should be sufficient for tagging things for now.  Every release has a build id so you can look up the original build description.

Perhaps a release object in the releases APIs should include the build description too, but that can be another issue.

I'm closing this issue because it's pretty old, but feel free to re-open it with more questions or open a new issue for additional feature requests.
