### ISSUE TITLE
Dedicated flag does not set the vpc tenancy to dedicated

### ISSUE THREAD

**Issue by cleblanc87** [convox/rack#1933]
When passing the --dedicated flag on install, the instance tenancy it not set as "dedicated". The templates has "default" hardcoded, but it should use the existing tenancy parameter.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dedicated tenancy not working](https://trello.com/c/W8mgvQJd/1933-dedicated-tenancy-not-working)

**Comment by cleblanc87** [comment]
Hey guys, any update here?

**Comment by soulshake** [comment]
@cleblanc87 We're testing a fix; if there are no problems the fix should be out within the next few days.

**Comment by mattmanning** [comment]
Closing. This was fixed in #2026 and released in version 20170309001137.
