### ISSUE TITLE
Convox start should handle SIGTERM nicely

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#1946]
Handling `SIGTERM` nicely would make it easier for Convox users to write automated scripts that use `convox start`. I am using this in order to run some simple tests on an nginx server.

When I use ctrl+C to exit out of `convox start`, it is kind enough to stop the docker containers that it has created. The same thing happens when I run `kill -INT XXXX` on a `convox start` process that I had started.

Conversely, when I try `kill XXXX` or `kill -15 XXXX`, `convox start` prints out `Terminated (core dumped)`, exits with return code -15, and does not kill the Docker processes that it has started.

One can easily work around this by sending `SIGINT` instead of `SIGTERM`, but I think this change would make `convox start` a bit easier to pick up.

**Comment by SonOfBytes** [comment]
I have also seen effects that I have not investigated, where running `convox start` in an iTerm that has multiple partitioned windows, that a resize of the window causes the `convox start` to terminate.  I presume it's receiving a signal - thus the comment this issue.

**Comment by ddollar** [comment]
This should happen now.
