### ISSUE TITLE
Build instance visibility

### ISSUE THREAD

**Issue by soulshake** [convox/rack#1948]
After setting the `BuildInstance` Rack param, there's no further visibility into the build instance in the console.convox.com UI. Currently, users have to check the EC2 dashboard to even see that it exists.

The build instance doesn't show in `convox instances` by design; the logic being that it would be confusing since it would not be used to run app containers.

But as a result, from the Convox console, the user has no way of knowing the server even exists. Having some way to validate the build server is engaged would be a good thing.

Users should also be able to:
- See build log with time to build, eventually any network / CPU / memory limits imposed by the server 
- Upgrade / downgrade the instance type (and even auto-scale it?) 
- See idle times and possibly scheduling 
- See cached images, gems, etc for understanding build requirements and efficiency...

Thanks @usiegj00 for the feedback.

**Comment by mwarkentin** [comment]
Maybe worth keeping in mind as well - if / when task placement support lands, a big part of that is being able to specify specific instance types, etc. which tasks should be placed on. This would indicate a cluster that is made up of multiple instance types, etc (which reminds me a bit of this build instance ASG).

**Comment by MiguelMoll** [comment]
Michael's great point aside (something definitely to keep in mind) and given visibility is a good thing, I'm looking for some clarity on the bullet points.

> See build log with time to build, eventually any network / CPU / memory limits imposed by the server
User could see the build log as usual with `convox builds logs`. CPU and Memory limits work the same way with `BuildCpu` and `BuildMemory` and their given defaults. (Networking saving it for a later discussion.)

> Upgrade / downgrade the instance type (and even auto-scale it?)
The `BuildInstance` params can be changed at anytime upgrading/downgrading the instance. (Autoscaling saving it for a later discussion.)

> See idle times and possibly scheduling
We could start with the info from `convox instances` but for the build instance. Would need more info as to what "possibly scheduling" would look like.

> See cached images, gems, etc for understanding build requirements and efficiency...
Probably a long term goal, this would require more input and design. Just an observation, not really asking for anything here.

**Comment by mwarkentin** [comment]
Could be nice to have an easy command to ssh in to the build instance as well - this would help for investigating what's cached, etc. `convox builds ssh` or `convox instances ssh build`? 

Other option is the build server showing up in `convox instances` and using `convox instances ssh` as usual.

**Comment by leemachin** [comment]
@mwarkentin That would be super helpful. We have our build instance in a private rack, and without going into AWS to set up a VPC and all of that for SSH access, we occasionally get deployment failures when docker has consumed all of the disk space.

**Comment by ndbroadbent** [comment]
Sorry to comment on an old issue, but was this ever resolved? Is there a way to SSH into the build instance?
