### ISSUE TITLE
Need to be able to set default or choose AWS account from the web console

### ISSUE THREAD

**Issue by denmat** [convox/rack#1950]
We currently build into two AWS accounts - one for dev/staging and one for production.

Via that cli we can build our stacks into the account we like by using our AWS credentials. Via the web console we can only see one integration (we have enabled both) and cannot choose which one to build into.

We would like to be able to view each of our AWS account integrations and choose between them from the console when installing a new rack.

**Comment by MiguelMoll** [comment]
This is a shortcoming we are aware of and looking to address. Thanks for the feedback. 👍 

Going to close this issue as we're tracking it internally and it's Console specific. We could post future updates here if needed.
