### ISSUE TITLE
JS error in audit log session playback screen

### ISSUE THREAD

**Issue by twelvelabs** [convox/rack#1952]
I ran `convox exec $PROCESS_ID bash` on an app, then went to the audit log to test out the session playback functionality described here: https://convox.com/blog/session-playback/, but all I saw was an empty space where the player should be. JS console shows:

```
[Error] TypeError: document.registerElement is not a function. (In 'document.registerElement("tty-player", {prototype: TTYPlayerPrototype})', 'document.registerElement' is undefined)
	(anonymous function) (tty-player.js:1715)
	Global Code (tty-player.js:1716)
```

I'm running latest Safari (10.0.3) on OS X Sierra (10.12.3).

**Comment by MiguelMoll** [comment]
Thanks for the report. 👍 

As this is a Console specific bug, I went ahead and created a ticket to track this for that project. Going to close this issue now but please don't hesitate to continue the conversation here. We'll make notes of any future updates here too.
