### ISSUE TITLE
convox doctor, but only validation

### ISSUE THREAD

**Issue by contra** [convox/rack#1967]
`convox validate` might be a good one

This should validate and fail on anything that would cause `convox deploy` to fail. This is extremely useful for CI, PRs, etc.

**Comment by MiguelMoll** [comment]
Validation certainly is. In fact, we've been adding more and more validation into convox start, release and promote commands. As neat as a `validate` command would be, we believe that validation should happen seamlessly without the user having to run yet another command.

Any specific issues you recently ran into that should've been caught during a validation phase?

**Comment by contra** [comment]
@MiguelMoll Here's what my CI looks like:

- run tests
- build some shit
- run convox deploy

By the time convox deploy is called, the CI has been doing stuff for ~20 minutes. 20 minutes of time just to find out some cron flag was invalid.

100% agree that validation should be run always whenever doing things like deploy, release, etc. but a way to validate your file without having to deploy or build an image would be extremely helpful.

If you're opposed to a new command, what about a flag for `convox doctor` that runs validation and fails (w/ exit code 1) when the config is invalid in any way?

**Comment by MiguelMoll** [comment]
I see what you mean now. I agree something beforehand would be really useful instead of waiting till the end to find out it wont work. Ideally build the app would validate too. Thanks for the feedback, greatly appreciated. 👍

**Comment by contra** [comment]
@MiguelMoll Plus, with a command you could run validation on `pre-commit` just like a linter

**Comment by contra** [comment]
Tagged as `needsinfo`, what info do you need?

**Comment by MiguelMoll** [comment]
That's my fault, didn't switch it after you provided more information.
