### ISSUE TITLE
Release Rollback Takes long time

### ISSUE THREAD

**Issue by chuckxwu** [convox/rack#1973]
Hello,

There is configuration error in current release. When I try to roll back (via cancel command) to previous release (which has configuration error as well), it took really long time for recover.
I can not delete the apps as well.
Is there a way to speed it up?

$ convox apps
APP   STATUS
ipdb  rollback

**Comment by ddollar** [comment]
Apologies that you didn't get an answer sooner. If you're looking for help with a Rack, the best way to get help quickly is by opening an ticket on Console (https://console.convox.com)

If you're still having issues please open a ticket there and we can dive in with you.
