### ISSUE TITLE
`convox apps` and `convox resources` share namespace but this isn't clear

### ISSUE THREAD

**Issue by stevepereira** [convox/rack#1979]
I shouldn't be able to delete an app by attempting to deleting a resource. It's also misleading to have no resource for `foo` but then having an error appear when running `convox resources create postgres --name=foo` because `foo` exists as an app

Also: Because of completely unrelated events, I'd like to add a vote for `convox apps restore` :)

**Comment by MiguelMoll** [comment]
Thanks for the great feedback. I can see where apps and resources sharing a namespace can be confusing. We'll definitely give that another look.

I'd like to hear more about `restore` though. Why do you think thats needed and what would it accomplish?

**Comment by ddollar** [comment]
Fixed now
