### ISSUE TITLE
Can not share volume from two services

### ISSUE THREAD

**Issue by chuckxwu** [convox/rack#1981]
Below is our docker-compose file.
services:
  ipdb-cron:
...
    lables:
      - convox.volumes.shared.global=true
    volumes:
      - /shared:/ipdb-data
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  ipdb-api:
    depends_on:
      - ipdb-cron
    lables:
      - convox.volumes.shared.global=true
    volumes:
      - /shared:/ipdb-data

I can see the following mount point on ipdb-api and ipdb-cron.
us-east-1b.fs-d2a70b9b.efs.us-east-1.amazonaws.com://convox-demo-appname>/ipdb-cron/shared on /ipdb-data
and
us-east-1b.fs-d2a70b9b.efs.us-east-1.amazonaws.com://convox-demo-appname>/ipdb-api/shared on /ipdb-data

How can I share volumes between two services?
Thanks,

**Comment by soulshake** [comment]
Hi @chuckxwu thanks for reaching out.
It's not currently possible to share volumes between containers of different services in the same app.

Please feel free to add details about your use case/upvote/subscribe to https://github.com/convox/rack/issues/1140 in the meantime.
