### ISSUE TITLE
Add CF failure events into an app's logs

### ISSUE THREAD

**Issue by MiguelMoll** [convox/rack#1984]
Getting all Cloudformation events that indicate a failure during a stack update (e.g. a deploy) will give a user's better visibility into whats going on. These events will be available via `convox logs`.

**Comment by mwarkentin** [comment]
Thoughts on the same for rack logs during rack upgrades, etc?

**Comment by MiguelMoll** [comment]
That's definitely the plan. Starting off with app deployments.

**Comment by MiguelMoll** [comment]
Went out via https://github.com/convox/rack/pull/2006 with both app and rack logs.

**Comment by mwarkentin** [comment]
Nice!
