### ISSUE TITLE
`convox init` for Rails remaining issues

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1985]
### Address binding in development

When I run my app in development mode (RAILS_ENV=development RACK_ENV=development), the ruby server (puma in this case) binds to localhost rather than 0.0.0.0.

I see 3 potential solutions for this:

1. Edit the generated `command` in docker-compose.yml to add `-b 0.0.0.0`.
2. Inject the environment variable SERVER_NAME=0.0.0.0
3. Inject the environment variable HTTP_HOST=0.0.0.0

1 seems like the best option that would work everywhere. 2 and 3 are puma-specific. It still bugs me that I can't tell why this behavior is RAILS_ENV specific, but these solutions work in development and production.

### Build arg for Bundler

Users need to be able to specify which gem groups to exclude when bundling gems this can be done by adding:

`ARG BUNDLE_WITHOUT="development:test"`

to the Dockerfile. `development:test` matches the Heroku ruby buildpack's default value. Making it a build arg means users can override it locally in their `.env` and in production using `convox env set` if desired.

### .env in .gitignore

Can we inject .env into the .gitignore if .gitignore exists and doesn't already have .env?

### Installing new gems

This is more of an open question for me right now. How do we want users to install new gems when developing. We previously suggested

1. Edit the Gemfile
2. Run `convox start` which will install the gems and generate changes to `Gemfile.lock`
3. Code-sync will sync the updated `Gemfile.lock` back to the host

With the Heroku buildpack this results in:

```
 The command '/bin/sh -c /tmp/heroku-buildpack-ruby/bin/compile /app /tmp/cache' returned a non-zero code: 1
ERROR: build error: exit status 1
```

I'm pretty sure the buildpack wants Gemfile and Gemfile.lock to already match. Do we tell users they have to run `bundle install` on the host to generate the correct Gemfile.lock, or is there some way to make it happen in the dev container?

**Comment by nzoschke** [comment]
Any idea what the ` The command '/bin/sh -c /tmp/heroku-buildpack-ruby/bin/compile /app /tmp/cache' returned a non-zero code: 1` error is? I'm guessing the buildpack is complaining about Gemfile and Gemfile.lock not matching.

**Comment by MiguelMoll** [comment]
Ref: https://github.com/mattmanning/convox-rails-example/commit/ad73e43a4958e38e9de961f6ca7e90a00e180803

**Comment by MiguelMoll** [comment]
Went out via https://github.com/convox/rack/pull/2006
