### ISSUE TITLE
How long are my Convox logs retained?

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#1994]
Can I be sure that Convox logs will be retained forever? If not, what actions should I be taking to back my logs up?

**Comment by paulkernfeld** [comment]
Also, if this is already documented, I would love to see a link to the docs.

**Comment by markfermor** [comment]
@paulkernfeld i believe we looked into this before and they are stored in AWS cloudwatch logs. I'm pretty sure they are stored indefinitely when looking at the configuration. IE AWS console -> Cloudwatch -> (click on) Logs. You'll see a ton of LogGroups and you should see one for your app and see that's it's configured to "Never Expire". Hope that helps - i'm not sure if it is documented.

**Comment by paulkernfeld** [comment]
Thanks, @markfermor!

Is it useful to leave this issue open as a request for documentation?

**Comment by MiguelMoll** [comment]
This is correct.Not specifying a retention policy for Cloudwatch logs, by default they are set to "Never Expire". We should definitely document this. 👍 

I'll inform the team to document it as soon as they can. Thanks!

**Comment by paulkernfeld** [comment]
Thanks @MiguelMoll !
