### ISSUE TITLE
App and Stack name collisions on different racks in the same region

### ISSUE THREAD

**Issue by gisnalbert** [convox/rack#200]
It is not possible to create a app on Rack1, if an app with the same name already exists on Rack2.
Rack1 and Rack2 deployed on the same AWS region.

I believe this may be related to #159

**Comment by csquared** [comment]
this one is a little tougher because amazon enforces the uniques of stack names in an AWS account.  considering this is under the hood, it might make sense to prefix the Cloudformation Stack name of all apps and services created by a rack with that rack's name. Might be a pain to strip out, but I can't think of a cleaner way.

**Comment by xtfxme** [comment]
I'm going to start looking into this today, so any additional input is appreciated.

Would it be beneficial to use a randomly generated (shared rack and apps) prefix or postfix? This would be easy to strip without knowing the racks name (in the app case). This would however allow racks with the same name, which seems like possibly a problem.

Anything else I should consider?

**Comment by ddollar** [comment]
Prefixing app names with the stack name of the Rack should be ok. App stacks should have an `app` tag that contains the actual app name so anywhere that needs to display it can use that.

**Comment by gisnalbert** [comment]
@xtfxme 
Just have to be careful with prefix/postfix because of maximum length names on some AWS resources (e.g. internal ELBs has a limit of 32 characters on the names, and right now Convox uses the app name on the ELB name).

**Comment by pyjsorg** [comment]
Ah good to know. Since the ELB has its own randomness appended we can probably keep using only the app name there, vs the longer rack + app name.

**Comment by xtfxme** [comment]
Ah good to know. Since the ELB has its own randomness appended we can probably keep using only the app name there, vs the longer rack + app name.

**Comment by xtfxme** [comment]
PR: https://github.com/convox/rack/pull/327

**Comment by nzoschke** [comment]
The PR moved to: https://github.com/convox/rack/pull/341

**Comment by nzoschke** [comment]
This is released. `convox update` to >= 20160223211445 to get it.

This behavior only applies to new apps/services. You will need to delete and re-create old apps/services to stop the old behavior.

Thanks a ton to @xtfxme for contributing to this patch.
