### ISSUE TITLE
Include network I/O, disk I/O in `convox ps --stats` output

### ISSUE THREAD

**Issue by JoshuaGross** [convox/rack#2000]
It would be nice to have some additional stats listed in `convox ps --stats` output. Besides memory and CPU usage, it's nice to also see:

* network I/O
* disk I/O
* disk space usage
* number of processes/threads on the system
* ...?

It may be too much to ask for all of the above, but it seems like Docker does make it easy-ish to get these metrics and more:

https://docs.docker.com/engine/reference/commandline/stats/#examples

https://www.datadoghq.com/blog/how-to-collect-docker-metrics/#stats-memory

**Comment by MiguelMoll** [comment]
Intent with `convox ps` is for metrics on the app's processes. I could be wrong but are you looking for instance stats instead (# of threads through me off a bit)? But as you mentioned docker provides a lot of insight into what's going on. `--stats` could use a level up if it's really useful.
