### ISSUE TITLE
Feature: control convox autoscaling

### ISSUE THREAD

**Issue by iosdev-republicofapps** [convox/rack#2007]
Hi,

Suppose that I am using a classic ELB within Convox to balance incoming RTMP streams to nginx instances.  Let's say I want a max of two incoming rtmp instances per EC2 instance behind the ELB in convox.

I know that ELB uses round robin for tcp, which is fine, but how would I use Convox autoscaling in this case?  In other words, if I have N EC2 instances, then I know my fleet can handle 2 N total incoming RTMP streams.  I want Convox to autoscale based on the number of tcp connections to my ELB and allocate one EC2 instance for every 2 connections to the ELB (these connections are long-lasting persistent connections to receive the incoming video).  Can this be done with Convox by having it interact with ELB?

If not, is there an API for Convox autoscaling so that if my own business logic server tracks the number of current connections to ELB, it can tell convox to scale up?

Thanks!  :-)

**Comment by MiguelMoll** [comment]
This is an interesting problem. There isn't a way currently to autoscale based on TCP connections. Current implementation takes memory and cpu usage into account.

By disabling autoscale in the rack and using your own business logic, you could scale the rack instances by calling `convox rack params set InstanceCount=N` where _N_ is the number of instance desired.

**Comment by ddollar** [comment]
Yes, scaling has an API. https://github.com/convox/rack/blob/master/client/system.go#L129
