### ISSUE TITLE
Code sync for `convox start <process>` style one off commands

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#2009]
Useful for commands things like code generators to have the generated files synced back to the host.

**Comment by twelvelabs** [comment]
Is there a workaround for this? I'm working on a Rails app and need to run `rake assets:precompile`. If I add that to the `Dockerfile` then it ends up causing the image to be rebuilt constantly during local development (even though compiled assets are only used in production). I'd prefer to have a build script that does something like:

```bash
convox start app bundle exec rake assets:precompile
# other tasks that are only relevant to prod deploys
convox deploy
```

**Comment by mwarkentin** [comment]
@twelvelabs If you `convox start`, and then `docker exec <container id> bundle exec rake assets:precompile` those files should get sync'd out. Not sure if you can do it in one shot though.

Another option might be to leverage [build args](https://convox.com/docs/dockerfile/#arg), but I'm not super familiar with how those work.

**Comment by ddollar** [comment]
This works now
