### ISSUE TITLE
Validate manifest in `convox deploy`

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#2017]
After loading the manifest in `convox start`, we run `Validate()` on it [here](https://github.com/convox/rack/blob/master/cmd/convox/start.go#L91). We load the manifest in a similar way in `convox deploy`, but we don't `Validate()` it [here](https://github.com/convox/rack/blob/master/cmd/convox/deploy.go#L60
).

Discussed here: https://github.com/convox/rack/pull/1920#issuecomment-279531409

**Comment by soulshake** [comment]
Resolved by https://github.com/convox/rack/pull/1936
