### ISSUE TITLE
RACK vs CONVOX_RACK

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#2023]
`egrep -r RACK ./*` in the Rack repo shows that we are using the `RACK` environment variable in a number of places, but there's at least one critical place where `CONVOX_RACK` has been used for a very long time (`cmd/convox/main.go`).

We should pick one or the other. (I vote for `CONVOX_RACK`; `RACK` seems a bit too generic.)

Also need to update the [CLI envvar doc](http://localhost/docs/cli-environment-variables/#convoxrack) as this references both `RACK` and `CONVOX_RACK`.

```
$ echo "RACK: $RACK / CONVOX_RACK: $CONVOX_RACK"
RACK:  / CONVOX_RACK: 

$ cat ~/.convox/rack 
squirrels/legit

$ cat .convox/rack
cat: .convox/rack: No such file or directory

$ convox rack
Name     legit
Status   running
Version  20170216230221
Region   us-east-1
Count    3
Type     t2.small

$ RACK=squirrels/dev convox rack
Name     legit
Status   running
Version  20170216230221
Region   us-east-1
Count    3
Type     t2.small

$ CONVOX_RACK=squirrels/dev convox rack
Name     dev
Status   running
Version  20170216230221
Region   us-east-1
Count    3
Type     t2.small
```

**Comment by MiguelMoll** [comment]
I believe the `RACK` throughout the repo is server side. Which is something users won't be able interact with via the CLI. `CONVOX_RACK` is the one that should be used with the CLI.

**Comment by MiguelMoll** [comment]
Closing for now as there is a context distinction with the two variables.
