### ISSUE TITLE
convox import does not respect build id in build.json

### ISSUE THREAD

**Issue by SonOfBytes** [convox/rack#2025]
When doing an import (as part of a build export/import promotion pipeline), the newly imported build does not have the build id from build.json.

This makes tracking the build through the pipeline really hard without some external metadata tracking which is making the pipe smarter than we want to.

Here is the Build id tag (BVDQPGHTMLU) from the tar.gz

{
  "id": "BVDQPGHTMLU",
  "app": "app-dev",
  "description": "",
  "logs": "object:///build/BVDQPGHTMLU/logs",
  "manifest": --- CUT FOR BREVITY ---,
  "release": "RCTQWNBCEDJ",
  "reason": "",
  "status": "complete",
  "started": "2017-03-02T17:08:45.509242863Z",
  "ended": "2017-03-02T17:08:50.405035012Z"
}

**Comment by MiguelMoll** [comment]
This behavior was done intentionally. The `description` is maintained though from build to build. Would that help in keeping track of it? 

We can also give this another pass if needed.

**Comment by SonOfBytes** [comment]
Ideally we would not want to use `description` as a pipeline metadata tracker.

I would be interested in hearing how you see the role of build id.

For us it represents the artefact identity, and being able to reliably track that through various environments (like dev, staging, perf, prod) would make pipeline tooling easier and reduce human confusion when trying to deal with issues.

Not having a build id to trigger downstream jobs as we import into the downstream environment makes things significantly harder and we are having to put user intervention into the process.

**Comment by MiguelMoll** [comment]
Very good points. I believe this is something we can address. Thanks for the input

**Comment by ddollar** [comment]
Build ID is created on import to allow the same build to be imported without error and to avoid the user needing to determine/generate build IDs.
