### ISSUE TITLE
convox init feedback

### ISSUE THREAD

**Issue by soulshake** [convox/rack#2028]
## `convox init` fails with `exit status 125`

```
>ls 
Procfile _includes/ composer.json composer.lock fabu_manager/ index.php vendor/

>convox init 
Updating convox/init... OK 
ERROR: unable to detect app type: convox/init - exit status 125
```

Running the command directly reveals the issue:

```
$ docker run -ti -v //C/Users/isaac/Documents/Projects/YMCA/ymca_fabu:/app convox/init detect /app 
docker: Error response from daemon: C: drive is not shared. Please share it in Docker for Windows Settings. 
See 'docker run --help'.
```

Sharing the C drive in Docker for Windows settings allows the `docker run` line to run correctly.

If possible, we should display more information about the error coming from Docker.

**Comment by ddollar** [comment]
`convox init` now converts apps from gen1 to gen2
