### ISSUE TITLE
faster crons?

### ISSUE THREAD

**Issue by contra** [convox/rack#2029]
Is it possible to do anything faster than one minute using the convox cron system?

Trying to run something every 5 seconds.

AWS has a limit of 1 minute, you could get around this by scheduling multiple jobs (I think)

**Comment by MiguelMoll** [comment]
As you mentioned, current format is limited. We have some future ideas that may address this. Could you elaborate on using multiple jobs?

**Comment by contra** [comment]
@MiguelMoll My idea is unreliable, scheduling multiple crons at the same time and assuming skew will stagger them.

You tagged this as needs info, is there anything you need from me to consider this valid?

**Comment by MiguelMoll** [comment]
That label was to pick at the multiple jobs idea. Mostly me not understanding but you cleared that up. I see this as valid request. Some design would be needed, if possible, as this would go against AWS limitations.

**Comment by mwarkentin** [comment]
@contra Not sure what stack you're using, but you can do sub-minute scheduled tasks with [celery](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html) - I assume other worker libs would have something similar.
