### ISSUE TITLE
Show (or link to) release notes in rack update UI

### ISSUE THREAD

**Issue by twelvelabs** [convox/rack#2035]
Not sure if this is a dupe of #1873 but whenever I see that there's a update available for my rack, the first thing I want to do is review the release notes before I press the update button. Would be nice if there was some means of doing that from the console (and as per #1873 being able to do it from CLI would be sweet, too).

**Comment by MiguelMoll** [comment]
Thanks for the feedback. As Console is separate project from Rack, I've made a note of this enhancement request in it's internal tracker. We can update this issue with any future progress but in the mean time I'll close it. Please feel free to leave any comments.

**Comment by awsmsrc** [comment]
This feature has been added to consloe
