### ISSUE TITLE
Convox deploy gets stuck cycling. No visible error as to why cycling.

### ISSUE THREAD

**Issue by blackdynamo** [convox/rack#2044]
Hey guys,

I am creating an issue to collect all the information related to the cycling issue I have been experiencing for 3 days. I originally posted in this issue: [2036](https://github.com/convox/rack/issues/2036#issuecomment-285505969)

TL;DR; I am deploying a node service and the first deploy seems to work fine. Any deploys that follow seem to get stuck in updating. Then when I cancel the update, it gets stuck rolling back and then eventually fails rolling back.

![image](https://cloud.githubusercontent.com/assets/245688/23773719/c563d9a0-04dd-11e7-95ed-0224ca3f936c.png)
![image](https://cloud.githubusercontent.com/assets/245688/23773741/e09280fa-04dd-11e7-968d-4012c0ac4a47.png)
![image](https://cloud.githubusercontent.com/assets/245688/23773701/ae8615ae-04dd-11e7-8bac-4f6facdd56e8.png)
![image](https://cloud.githubusercontent.com/assets/245688/23773801/12e53bec-04de-11e7-8178-025b391864d4.png)
![image](https://cloud.githubusercontent.com/assets/245688/23802826/c379a202-0571-11e7-930e-2f854d89ed07.png)

**Comment by blackdynamo** [comment]
I tried rebuilding the rack again this morning but it failed to build or seems partially built.

![image](https://cloud.githubusercontent.com/assets/245688/23802859/e35c4c96-0571-11e7-8b9d-f4b5131150d6.png)
![image](https://cloud.githubusercontent.com/assets/245688/23802885/f8546944-0571-11e7-8387-75acd5a9784e.png)

CF Logs for the rack
[cf-logs.txt](https://github.com/convox/rack/files/834465/cf-logs.txt)

**Comment by blackdynamo** [comment]
Adding to the cycling issue, I have started the rack from scratch, first deploy works, but subsequent deploys cause the cycle. No errors are output in `convox logs`

**Comment by ddollar** [comment]
My guess would be that your app is failing health checks for some reason and not stabilizing in ECS. If you submit a ticket in Console we can do some live debugging of your Rack with you.

**Comment by blackdynamo** [comment]
@ddollar Thanks! @soulshake helped me through this. Health checks were exactly what was causing the issue. What's still a little confusing is when you do the first deploy, it's almost like it ignores the health checks and the system comes alive. Then all subsequent deploys will do the health check.

It would be nice if the logs could show something like:

```
Health check fail
Health check fail
SIGKILL
Container killed due to health check failure
```
