### ISSUE TITLE
Build Instances don't use InstanceRunCommand

### ISSUE THREAD

**Issue by dlanger** [convox/rack#2046]
We use `InstanceRunCommand` to download credentials (since we don't have rack-level credentials), add additional SSH keys, and kick off a bootstrap script that configures monitoring and security tooling.

Experimentation shows that builder instances don't run this command, meaning we're running blind (save CloudWatch) on the state of those instances. 

From Slack:

> ddollar [11:47 AM] 
> @dlanger it appears not, though i cant think of a reason why they shouldnt
> 
> ddollar [11:47]  
> https://github.com/convox/rack/blob/master/provider/aws/dist/rack.json#L1560   https://github.com/convox/rack/blob/master/provider/aws/dist/rack.json#L1418

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make build instances respect InstanceRunCommand](https://trello.com/c/FnL87RGY/2102-make-build-instances-respect-instanceruncommand)

**Comment by MiguelMoll** [comment]
Fixed via [20170321123755](https://github.com/convox/rack/releases/tag/20170321123755)
