### ISSUE TITLE
Failure to create default convox-events service

### ISSUE THREAD

**Issue by blackdynamo** [convox/rack#2047]
Hey guys,

Just noticed something weird in the web console. Not sure if it's also happening in the CLI but it says that `Failure to create default convox-events service.... continuing...`. Seems like it might be a false message but not sure. Once I create a new rack everything seems fine and the CloudFront logs look fine.

![image](https://cloud.githubusercontent.com/assets/245688/23802859/e35c4c96-0571-11e7-8b9d-f4b5131150d6.png)
![image](https://cloud.githubusercontent.com/assets/245688/23802885/f8546944-0571-11e7-8387-75acd5a9784e.png)

**Comment by MiguelMoll** [comment]
Thanks for feedback. Is there any more information you can provided as to the install options that were used? 

As this is an issue with Console (and not Rack), I'm going to track this bug in a separate internal ticket but please continue the conversation here if you like.

**Comment by blackdynamo** [comment]
@MiguelMoll Sounds good. The only special install options that were set is checking off the private mode.
