### ISSUE TITLE
Route53 integration

### ISSUE THREAD

**Issue by anthonyrisinger** [convox/rack#205]
What are the thoughts/plans on automatic DNS management via Route53? This is closely related to #201, in that new apps should be accessible from a canonical url.

It's likely we'll implement a solution and upstream it, so I'm looking for guidance here before moving too far ahead. Currently we are using a an external webhook to perform Route53 operations in response to `app:create` and `app:delete` events.

**Comment by ddollar** [comment]
If base domain name were a Rack setting e.g. `example.org`, then we could use Route53 to automatically set CNAMEs to the various load balancers. If we had an app named `foo` with processes named `web` and `api` then we could create these names:

* `web.foo.example.org`
* `api.foo.example.org`

**Comment by grandmore** [comment]
I have been thinking about this as well. It could also differentiate between internally and externally accessible domains.  Service discovery between apps if were doing a sudo-microservices architecture. Sometimes we want the end-points to be private

Internal:
web.foo.example
api.foo.example

external
web.foo.example.org
api.foo.example.org

**Comment by sveneh** [comment]
+1

**Comment by pilgrim2go** [comment]
+1

**Comment by harlow** [comment]
This would be great. We're currently doing the following with Route53:

1. create a hosted zone called `staging.local` on Staging Rack
2. create a hosted zone called `production.local` on Production Rack

After creating a new service "foo" on each Rack we go into Route53 and add:

`foo.staging.local` CNAME to staging app
`foo.production.local` CNAME to production app

It would be great if we could `convox params set HostedZone=staging.local` and then when creating an app it would automatically create a CNAME for `appname.staging.local`

**Comment by bejmuller** [comment]
+1

**Comment by frsechet** [comment]
+1000

**Comment by joelpresence** [comment]
+1
