### ISSUE TITLE
Binary download failing

### ISSUE THREAD

**Issue by coccyx** [convox/rack#2051]
Downloads at https://convox.com/install/linux.zip are failing with an error:

>   ERROR
>   
>   The request could not be satisfied.
>   
>   CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin 
>  closed the connection. 
>   Generated by cloudfront (CloudFront)
>   Request ID: h5cikD_wVrEn8UdioEdT3rfC3735r4uiYqB9tcaRutiwcqnOPJ6biA==

**Comment by soulshake** [comment]
Hi @coccyx, thanks for the report. This was resolved by https://github.com/convox/site/pull/639.
