### ISSUE TITLE
Launch Racks in Certain Availability Zones

### ISSUE THREAD

**Issue by chuckwu-aa** [convox/rack#2053]
It is useful for RI instance cases. 
For example, I want to launch 2 in us-east-1a and 2 in us-east-1b. And it is key for cost saving for production usage case.
Another key scenario is for some availability zone cost matters scenario. For example, we want to launch racks into one zone for one rack for mapreduce tasks to reduce cross zone network traffic. Based on current design, it is hard to launch such computing rack. 
It is good to support launch racks in single availability zone or customized az plan (e.g. us-east-1a:3,us-east-1b:4).

Reference ticket "Restrict ECS cluster to certain AZs" (https://github.com/convox/rack/issues/513)

**Comment by matthewford** [comment]
@chuckwu-aa yeah, I in the end had to plan for 3 RIs one in each AZ
