### ISSUE TITLE
Multi-region ELB instances?

### ISSUE THREAD

**Issue by xtfxme** [convox/rack#206]
While extremely rare(?), a region going down would take down an entire rack... what are the thoughts on replication across racks and/or regions? And ELB distribution across that? We can build our own layer above convox but I trying to get a feel for any long-term goals regarding multi-region awareness.

**Comment by bladealslayer** [comment]
ELBs live within a region. You can't use an ELB across multiple regions. For routing to multiple regions, you'd need a higher level service - DNS (Route53).

However, replicating data and convos services (databases, etc) across regions is a different story, especially if you'd want to do this in a generic way that can be useful to different applications.

**Comment by xtfxme** [comment]
Ahh ok, This is my first experience with AWS... I was thinking an ELB could also be a global resource. DNS works well enough at that level.

I like the idea of replication, but we are probably going to punt on this until some arbitrary point in the future. Current focus is managing many little racks.
