### ISSUE TITLE
Creation of Rack stuck in `installing`.

### ISSUE THREAD

**Issue by advance512** [convox/rack#2072]
I've just created a rack, as expected, via Convox.com:

```
***** TASK 1/1 [rack_install] for job ********-****-****-****-************


     ___    ___     ___   __  __    ___   __  _
    / ___\ / __ \ /  _  \/\ \/\ \  / __ \/\ \/ \
   /\ \__//\ \_\ \/\ \/\ \ \ \_/ |/\ \_\ \/>  </
   \ \____\ \____/\ \_\ \_\ \___/ \ \____//\_/\_\
    \/____/\/___/  \/_/\/_/\/__/   \/___/ \//\/_/


Installing Convox (20170315195000)...
Using AWS Access Key ID: ********************
Created ECS Cluster: staging-Cluster-************
Created IAM Managed Policy: KernelUserGeneralPolicy
Created IAM Managed Policy: KernelUserPolicy
Created IAM Managed Policy: KernelUserIAMPolicy
Created CloudWatch Log Group: staging-LogGroup-************
Created Lambda Function: staging-LogSubscriptionFilterFunction-************
Created Lambda Function: staging-InstancesLifecycleHandler-*************
Created Lambda Function: staging-CloudformationEventsHandler-************
Created Lambda Function: staging-CustomTopic-************
Created VPC Internet Gateway: igw-********
Created VPC: vpc-********
Created S3 Bucket: staging-settings-*************
Created Routing Table: rtb-********
Created KMS Key: EncryptionKey
Created EFS Filesystem: fs-********
Created DynamoDB Table: staging-builds
Created DynamoDB Table: staging-releases
Created Security Group: sg-********
Created Security Group: sg-********
Created Security Group: sg-********
Created IAM User: staging-KernelUser-************
Created VPC Subnet: subnet-********
Created Access Key: ********************
Created VPC Subnet: subnet-********
Created VPC Subnet: subnet-********
Created Elastic Load Balancer: staging
Created ECS TaskDefinition: WebTasks
Created ECS TaskDefinition: RackBuildTasks
Created ECS TaskDefinition: MonitorTasks
Created Unknown: AWS::KMS::Alias: alias/convox-staging
Created AutoScalingGroup: staging-Instances-************
Created ECS Service: WebService
Created ECS Service: MonitorService
Created CloudFormation Stack: staging
Waiting for load balancer....
Logging in...
Success, try `convox apps`
***** FINISHED TASK 1/1 [rack_install] for job ********-****-****-****-************
``` 

However, the rack is stuck as `installing`:

```
$ convox racks
RACK            STATUS
company/staging installing
```

The state of the Rack has been `installing` for 50+ minutes. Looking in CloudFormation, both the staging and staging-convox-events stacks are in state `CREATE_COMPLETE` and have finished over 40 minutes ago.

Any idea what to do next?

**Comment by advance512** [comment]
I deleted the rack manually the `convox` CLI tool.
It still appears in the convox.com console.. and I can't delete it, nor delete the organization (as it has racks).
Not a great start to using Convox..

I'm creating a "production" rack instead, to see if I can get it working at all..

**Comment by MiguelMoll** [comment]
Apologies for the inconvenience. That is definitely odd and unexpected behavior. If you don't mind, could you open a support ticket via the Support tab in console.convox.com? That allows us to provide better support and communication for your particular case instead of this issue.

Our [Slack](https://invite.convox.com/) channel is also another option we can provide help.

I'm going to close this issue as it doesn't pertain to Rack itself but Console. Please feel free to update this issue however you see fit. Thanks for the feedback!

**Comment by blackdynamo** [comment]
Sorry to bump this, but I recently experienced this issue. I submitted an email to support@convox.com, as well as looked for assistance in slack. What I ended up doing was cleaning up everything in CloudFormation and it was still hanging as "installing". I ended up calling the delete rack api call used on the console and it fixed my problem.

**Comment by advance512** [comment]
I just experienced this issue again today.
