### ISSUE TITLE
No instance health-check done when rolling instances (during keyroll, AMI update, etc.)

### ISSUE THREAD

**Issue by dlanger** [convox/rack#2083]
We accidentally set a custom AMI which wasn't suitable for Convox - it lacked the ECS agent and a few other essential bits. When we updated convox to use this AMI, it deployed out fine...and the Rack API and all our app promptly went down, and we had to manually update the `Ami` parameter of the CloudFormation stack to recover.

My expectation was that the waits and instance lifecycle actions that Convox does on rolling an instance did some tests to make sure that the instance was in a good state before sending the `SUCCESS` signal. Investigation of the CloudFormation JSON shows this [isn't the case](https://github.com/convox/rack/blob/master/provider/aws/dist/rack.json#L1629-L1630) - all we're doing is waiting for the setup tasks to finish.

Possible checks we could send before registering `SUCCESS`:
* Has the ECS agent started and stayed up?
* Has Docker started and stayed up?
* Does ECS see the instance as healthy (I'm not sure about this one, as it may not even try until you send `SUCCESS`)?

This didn't happen in production because we do staging first, but if it had, it would have taken down the whole cluster.

**Comment by ddollar** [comment]
This is done now
