### ISSUE TITLE
Support scaling linked services

### ISSUE THREAD

**Issue by JoshuaGross** [convox/rack#2086]
My understanding, reading through the docs, is that you can link a single process of a service to another application. The application gets the env vars:

```
SERVICE_PORT
SERVICE_HOST
...
```

Docker-compose, from my understanding, similarly allows linking but allows you to scale the linked services. So if my `service` is scaled to 3 processes, my linked application gets:

```
SERVICE_1_PORT
SERVICE_1_HOST
SERVICE_2_PORT
SERVICE_2_HOST
SERVICE_3_PORT
SERVICE_3_HOST
```

I think this would help tremendously in some simple distributed application setups.

**Comment by mwarkentin** [comment]
@JoshuaGross Are you thinking about this for local development (`convox start`), or after your application is deployed?

When deployed, services get an ELB which handles passing requests to all registered containers, in addition to providing a static URL for other services to reference.

**Comment by JoshuaGross** [comment]
Since ELB doesn't support sticky sessions for TCP, I'm essentially trying to load-balance manually. I have an application where I need N services but I need to know which instance I'm sending packets to. Is there another easier way of doing this in the convox/AWS ecosystem?

**Comment by mwarkentin** [comment]
@JoshuaGross Ah, gotcha. In that case I think you'll need to roll your own service discovery - a few options that I'm aware of but haven't used myself:

* consul
* weave
* [envoy](https://lyft.github.io/envoy/)

**Comment by JoshuaGross** [comment]
Right on, was hoping to avoid running additional services as my current needs aren't complex. Thanks for the links!

**Comment by advance512** [comment]
This seems like a good idea. It also doesn't sound problematic to implement - might give it a go.

Using ELBs for microservices is prohibitively expensive in many cases.
