### ISSUE TITLE
docker-compose v3 support

### ISSUE THREAD

**Issue by contra** [convox/rack#2104]
v3 seems to be a thing now, opening this ticket for it - docs will need updating as well

https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading

**Comment by MiguelMoll** [comment]
This is something worth tracking.

**Comment by anicholson** [comment]
@ddollar what caused this to close? v3 isn't supported from what I can see (still getting errors about v3)

**Comment by mwarkentin** [comment]
Gen2 is moving away from using `docker-compose.yml` to `convox.yml`.

**Comment by ddollar** [comment]
See #2555

**Comment by anicholson** [comment]
@mwarkentin / @ddollar thanks, fair enough. I note, though, that I hit this because I was attempting to `convox init` an existing app that had a v3 `docker-compose.yml`, so I don't believe it can be completely ignored?
