### ISSUE TITLE
`unable to build app` immediately

### ISSUE THREAD

**Issue by contra** [convox/rack#2109]
```
$ time convox build
ERROR: unable to build app: staeco

real    0m0.471s
user    0m0.064s
sys     0m0.021s
```

This started happening out of nowhere today. The error is immediate, which makes me think the rack is uninvolved.

- `convox doctor` looks fine
- `convox start` runs fine
- Rack is latest version (20170325002636)
- Rack status is `running`
- CLI is latest version (20170321220441)

No idea where to go from here, convox isn't giving me any info to go on.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["unable to build app" error](https://trello.com/c/blcmuZsa/2268-unable-to-build-app-error)

**Comment by MiguelMoll** [comment]
There was a recent change that got rid of that error as it wasn't helpful. Originally that error would present itself if the app was in a status other than `creating`, `running`, or `updating`. The app could've been in a rollback state.

Do you get the same message with version `20170330142818`? Would you happen to know what was the status of the app at that moment?

**Comment by contra** [comment]
After updating to the latest rack and CLI this issue went away. The rack at the time was marked as running, so not sure it was the problem. Closing since it went away, but no idea what fixed it.
