### ISSUE TITLE
Convox idempotent approach in build pipelines

### ISSUE THREAD

**Issue by SonOfBytes** [convox/rack#2113]
For one of my clients that uses Terraform (not the issue here :P) like an idempotent deployment pipeline.  Ie express "I want my environment to look like X" and tool "makes necessary changes to make it look like X".

Is there a pattern where convos rack, apps, resources, env can all be managed in this manner (not necessarily via Terraform) from first install, through changes, to decommissioning?

Scripting goes so far but will ultimately become troublesome because fresh install is a rare event in a active service.

**Comment by mwarkentin** [comment]
@SonOfBytes There's the beginnings of a terraform convox provider here (not mine): https://github.com/mattaitchison/terraform-provider-convox

Would likely require a lot more work, but could be an option for you.

**Comment by SonOfBytes** [comment]
Thanks @mwarkentin I'll take a look at that.

I'm not sure the right answer is terraform - tho maybe it could be?  My concern would be a splitting of function between the convox command and the terraform provider framework.

The use of the API would be a useful abstraction in this.  I'm wondering if the convos command can present a local interface?  Maybe move more stuff out of main and into consumable packages?

**Comment by mwarkentin** [comment]
@SonOfBytes Yeah, I'm not sure that's been answered. There are certain things that seem like they would be very nice about it, but could introduce challenges around configuration drift if you modify things via CLI, etc.

Actually quite similar to the sometimes confusing way that some labels in the docker-compose.yml work (eg. they only apply when the app is first created, or similar).

**Comment by SonOfBytes** [comment]
The more I think about this I think there is some value in looking more at this.  I think having terraform to manage the AWS resources managed by convox is not ideal because it goes against the ethos of the service.

However, I think there is value in terraform having a convox provider to manage state via the API.  This means that Users can have a seamless service contract with all the resources on AWS, and allows for idempotent expression in a way that Users already understand.

Following this train of thoughts I think the following opens up

- docker-compose.yml becomes a base level service contract that is sufficient for local development and forms a foundation for that contract in AWS.
- The command line can evolve to handle local dev (docker commands) and AWS state (via terraform talking to the convox API)
- where the docker-compose.yml is becoming overloaded to define rich services maybe using terraform as the contract expression natively can form the bridge.  It is a well known format and can effectively allow the convox provider to expand into new deeper services than can be expressed by docker-compose.yml alone.  It would also be a provider that can be blessed by the convox team.

I know this is a bit radical - just sharing the idea as it may have value ;P

**Comment by SonOfBytes** [comment]
@MiguelMoll @ddollar - I was looking a little more at this in my spare time.  As I started to play with some terraform plugin code I wanted to integrate it to the convox cli configs by using the client cli code.

Looks like all the config code is in the main package of the convox cli and not readily reusable.  Do you feel this should be in a non-main package so it can be treated as a abstracted implementation from the files?  If so would you think it should be in the client package?

If you do I might look at moving the relevant code out of the main and writing necessary tests etc and submitting a PR.  Let m know what you think as I would like to play with a terraform interface while leveraging as much of the cli code as possible.

**Comment by mwarkentin** [comment]
@SonOfBytes do you think leveraging the CLI over interacting w/ the convox API directly makes sense?

Here are the [api docs](https://convox.com/api) if you weren't aware.

**Comment by SonOfBytes** [comment]
@mwarkentin I think a blend of both probably makes sense depending where the authoritative logic lives.

I'll play some more and see what I hit.  I'm trying to think about this from even creating a Rack from scratch.

**Comment by mwarkentin** [comment]
I think generally the important logic all lives on the API, as the CLI is a client, and can't be fully trusted. @ddollar @nzoschke could probably confirm though.

CLI might have some extra client side validation, etc.
