### ISSUE TITLE
When running 'bundle package' in a Rails app, removals are not synced properly 

### ISSUE THREAD

**Issue by lovitt** [convox/rack#2119]
To repro:

1. In a Rails app, run `convox start`.
2. From within the container, run `bundle package --all`.
3. Remove a gem from the Gemfile.
4. Run `bundle package --all` again.

Observe that the gem has been removed from the `vendor/cache` directory in the container, but remains in the `vendor/cache` directory on the host.

Additions and modifications seem to sync to the host properly, but removals do not.

**Comment by MiguelMoll** [comment]
I believe this is intentional behavior. We didn't want code sync to delete files off the the host machine as that could cause issues and data loss if it wasn't the intent.

Is there a strong use case/demand for this feature?
