### ISSUE TITLE
duplicate syslog linking fails with a positive output message

### ISSUE THREAD

**Issue by jayjanssen** [convox/rack#2121]
I have an app that is linked to one syslog resource.  If I try to link it to another, the CLI says it is 'linked'.  However, I can watch the resource 'rollback' via 'convox resource' and the app is not listed in the triggers for the syslog's lambda function.

Worse, if I try to unlink the app from the original resource, it says "resource is not linked to app"

```
> convox resource create syslog --name=syslog1 --url=...
app1> convox resource link syslog1
> convox resource create syslog --name=syslog2 --url=...
app1> convox resource link syslog2
Linked syslog2 to app1              <- but it is not
app1> convox resource unlink syslog1
ERROR: resource syslog1 is not linked to app app1    <- but it is
```

**Comment by ddollar** [comment]
This should be fixed now
