### ISSUE TITLE
Deploy fails due to "no such build" error

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2122]
I'm a bit reluctant to post my entire build log file on GitHub, but when I ran `convox deploy`, it failed at this point. I have successfully deployed many times with Convox, and this is the first time I've seen this error. I actually do see the missing build in my ECR Docker repo, so maybe this is a race condition or something? Please let me know what additional information I can provide.

```
...lots of Docker pushes
abcdef123456: Pushed
booker.BXXXXXXXXXX: digest: sha256:aaaabbbbccccddddeeeeffff1111222333444 size: 999
ERROR: no such build: BXXXXXXXXXX
```

```
client: 20161123220503
server: 20170111205227
```

**Comment by MiguelMoll** [comment]
This is an odd one, thanks for reporting it. Do you see the build when running `convox builds`? Do you see a release ID there too? How about the status of the app (`convox apps info`) and rack (`convox rack`)?

Would you be able to run `convox release promote $RELEASE_ID` and report back?

**Comment by paulkernfeld** [comment]
I do see an associated release ID when I run `convox builds`. When I promoted this release by running the command you suggested, it did initiate an update (although my app did not launch because of an application error).

**Comment by MiguelMoll** [comment]
@paulkernfeld Any more information that can help reproduce this error? Are you seeing it consistently still?

**Comment by paulkernfeld** [comment]
Sorry, I can't really offer any additional information on this; I have only ever seen it happen once.

**Comment by MiguelMoll** [comment]
All good. We'll close this issue for now and reopen it if needed.
