### ISSUE TITLE
Logging breaks for a specific service in an app when service restarts

### ISSUE THREAD

**Issue by jayjanssen** [convox/rack#2124]
I can't quantify this very well, but this seems to be limited to a very specific service in one app.  I'm very unsure what is different about this service that causes this issue.  I'm filing this here as I don't have Convox support and didn't get any replies in #convox.

- App has two services
- A fresh deploy will cause both services to log normally
- If service 2 restarts in any way, its logging stops
- This stops syslog and `convox logs`
- Service 1 doesn't have this issue
- Changing the syslog resource link doesn't fix the issue
- service 1 logs fine while service 2 does not
- service 1 has a count of 2, service 2 has a count of
- Service 1 as an elb, service 2 does not.
- service 2 is actually running and working fine, the logs just don't come through.

This rack is not on your console, but I can check anything you want and provide more info.

**Comment by bladealslayer** [comment]
I haven't been able to pinpoint the cause, but I've experienced issues with logging multiple times. The convox agent seemed to just not pick new log entries at all on the affected instances/services.

**Comment by ddollar** [comment]
Logging now uses ECS-native configuration
