### ISSUE TITLE
Convox agent in a loop trying to tail log files of containers with NativeLogging enabled

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#2133]
Update: After some more debugging, clarifying the issue: looks like convox agent mistakenly tries to tail the log file of app containers for apps with `NativeLogging` enabled. Those containers don't have log file at all on the EC2 instances. (Issue title updated as well.)

Using rack version `20170404185653`, when I enable NativeLogging for an app, the instances on which the corresponding service containers are scheduled start to have increased CPU usage (I've seen up to 70% usage on t2.medium instances). The culprits seem to be `dockerd` and some `agent` process started by `docker-containerd-shim`.

This seems to cause some instance instability (instances considered unhealthy, getting teriminated, new containers starting slower, etc).

**Comment by nzoschke** [comment]
Thanks for the report, this is news to me.

The expectation is that the standard ECS / Docker / awslogs driver should be performant and reliable.

Can you share some more system information on this issue? What AMI, ECS Agent version, Docker version, and some outputs of `ps` and `docker ps`.

**Comment by bladealslayer** [comment]
Sure!

Convox rack version: 20170405220740
AMI: ami-275ffe31
ECS Agent: 1.14.1
Docker version 1.12.6, build 7392c3b/1.12.6

Some outputs:

```
$ convox instances ssh i-****
Last login: Wed Apr  5 15:51:25 2017 from ****

   __|  __|  __|
   _|  (   \__ \   Amazon ECS-Optimized Amazon Linux AMI 2016.09.g
 ____|\___|____/



[ec2-user@ip-**** ~]$ top -d1
top - 16:40:10 up 4 days,  2:32,  1 user,  load average: 2.43, 0.72, 0.28
Tasks: 158 total,   1 running, 157 sleeping,   0 stopped,   0 zombie
Cpu(s): 43.9%us, 12.3%sy,  0.0%ni, 42.8%id,  0.0%wa,  0.0%hi,  0.0%si,  1.1%st
Mem:   4049656k total,  3671124k used,   378532k free,   406748k buffers
Swap:  5242876k total,      168k used,  5242708k free,  1118240k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 3709 root      20   0 53180  48m 8396 S 56.8  1.2  41:00.47 agent
 2926 root      20   0 1382m  71m  29m S 50.9  1.8  41:49.30 dockerd
 2940 root      20   0  210m  14m  11m S  7.0  0.4   2:21.82 docker
 3694 root      20   0  206m 3288 2632 S  4.0  0.1   1:18.73 docker-containe
```

As soon as ECS schedules a container from an app with NativeLogging enabled to a host, some `agent` process and the `dockerd` immediately start taking up lots of CPU. This high usage disappears almost immediately when that container is stopped (scheduled on different host), or when native logging is disabled for the app. Terminating / provisioning new instances doesn't seem to have any effect.

**Comment by nzoschke** [comment]
Thanks. Can you also poke at the convox/agent container a bit? Perhaps there's a side effect of that running next to the awslogs stuff.

**Comment by bladealslayer** [comment]
@nzoschke I scaled up the rack to have enough totally free instances. Now I have an instance that runs just one app container - from the app with native logging on. The behaviour is the same. Convox agent seems to be running on all instances, regardless of whether they are running any app containers. Tried stopping it, but it gets automatically restarted.

I actually only now noticed that the `agent` process consuming CPU is actually the convox agent process. Wasn't sure before, as they were multiple ones named `agent`.

Now that I saw it's convox's agent, I checked its logs... it looks like it is in a loop constantly trying to tail the app containers log file, even though that app container doesn't have one at all (NativeLogging is enabled):

```
{"log":"agent:0.70/i-**** container subscribeLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f count#DockerLogsRetry=1\n","stream":"stdout","time":"2017-04-09T17:37:21.036966047Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=start\n","stream":"stdout","time":"2017-04-09T17:37:21.036980654Z"}
{"log":"agent:0.70/i-**** container subscribeLogs readLines id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=start\n","stream":"stdout","time":"2017-04-09T17:37:21.036985268Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f count#DockerLogsError=1\n","stream":"stdout","time":"2017-04-09T17:37:21.037651245Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=end\n","stream":"stdout","time":"2017-04-09T17:37:21.037667641Z"}
{"log":"agent:0.70/i-**** container subscribeLogs readLines id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=end exit=true\n","stream":"stdout","time":"2017-04-09T17:37:21.03767197Z"}
{"log":"agent:0.70/i-**** container subscribeLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f count#DockerLogsRetry=1\n","stream":"stdout","time":"2017-04-09T17:37:21.03815631Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=start\n","stream":"stdout","time":"2017-04-09T17:37:21.038180355Z"}
{"log":"agent:0.70/i-**** container subscribeLogs readLines id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=start\n","stream":"stdout","time":"2017-04-09T17:37:21.038185788Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f count#DockerLogsError=1\n","stream":"stdout","time":"2017-04-09T17:37:21.038813923Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=end\n","stream":"stdout","time":"2017-04-09T17:37:21.038829371Z"}
{"log":"agent:0.70/i-**** container subscribeLogs readLines id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=end exit=true\n","stream":"stdout","time":"2017-04-09T17:37:21.038833801Z"}
{"log":"agent:0.70/i-**** container subscribeLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f count#DockerLogsRetry=1\n","stream":"stdout","time":"2017-04-09T17:37:21.039355188Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=start\n","stream":"stdout","time":"2017-04-09T17:37:21.039366657Z"}
{"log":"agent:0.70/i-**** container subscribeLogs readLines id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=start\n","stream":"stdout","time":"2017-04-09T17:37:21.039370487Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f count#DockerLogsError=1\n","stream":"stdout","time":"2017-04-09T17:37:21.039949661Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=end\n","stream":"stdout","time":"2017-04-09T17:37:21.03996459Z"}
{"log":"agent:0.70/i-**** container subscribeLogs readLines id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=end exit=true\n","stream":"stdout","time":"2017-04-09T17:37:21.039968908Z"}
{"log":"agent:0.70/i-**** container subscribeLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f count#DockerLogsRetry=1\n","stream":"stdout","time":"2017-04-09T17:37:21.04051658Z"}
{"log":"agent:0.70/i-**** container subscribeLogs readLines id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=start\n","stream":"stdout","time":"2017-04-09T17:37:21.040533213Z"}
{"log":"agent:0.70/i-**** container subscribeLogs followDockerLogs id=dc798b51eba9e631e29cc8b7327862191f23533d146a572bae1e3ff29bc1421f at=start\n","stream":"stdout","time":"2017-04-09T17:37:21.04053789Z"}
```

where `dc798b51eba9` is the app's container.

**Comment by nzoschke** [comment]
Very useful, thanks. I would expect the convox/agent to not try to follow the container logs since there is no LOG_GROUP environment variable for the task. Perhaps that assumption is incorrect and it's spinning on logging errors for some reason.

**Comment by nzoschke** [comment]
@bladealslayer I have an agent and rack release in testing now. See https://github.com/convox/rack/pull/2140 for details.

Can you try a `convox rack update 20170410163137-native-logging` and report how it looks?

**Comment by bladealslayer** [comment]
@nzoschke I will try and report. Thanks!

**Comment by bladealslayer** [comment]
@nzoschke by the way, convox inserts some own environment variable in containers. E.g. `LOG_GROUP`. It would be great if those have non-generic names (maybe prefix with `CONVOX_`?), so that they don't collide with variables that might be used by the app.

**Comment by bladealslayer** [comment]
@nzoschke rack version `20170410163137-native-logging` seems to work nicely.

**Comment by mwarkentin** [comment]
There was some discussion on namespacing quite a ways back on https://github.com/convox/rack/issues/417.

**Comment by MiguelMoll** [comment]
As per @nzoschke, this is fixed. 👍
