### ISSUE TITLE
"not enough memory available to start process" for one off processes?

### ISSUE THREAD

**Issue by contra** [convox/rack#2135]
Having an issue where we've got a lot of one-off commands, but it seems like they do not trigger autoscale when an instance hits its limit.

For the purposes of this issue, let's say:

- I have ~1000 one-off processes running, new ones starting and old ones stopping constantly
- autoscale is enabled
- instance type is t2.small

Currently given this environment you can only execute a few commands before you start getting `not enough memory available to start process` errors from `convox run`. 

Expected behavior is that it triggers autoscale and processes go on new instances, and when finished those instances scale back down accordingly. The instance count should be fluid to one-off commands just as it is with running `convox scale --count` manually.

**Comment by contra** [comment]
Any way we can help out with this? We use convox processes at critical points in our application and will have to switch to something else if we can't resolve this in the next few days. Any leads or pointers so we can do our own PR would be helpful, we haven't received anything on issues or in our support tickets :(

**Comment by contra** [comment]
After looking through https://github.com/convox/rack/blob/master/api/workers/autoscale.go I think the only adjustment that would need to be made is for https://github.com/convox/rack/blob/39d7e9bc649d39e9eb32f3595724ba735022a1fb/provider/aws/capacity.go#L48-L96 to take running one-offs into account, right?

**Comment by ddollar** [comment]
You can use `AutoscaleExtra` to configure extra instances in the autoscaler to give you some room. Fargate will hopefully solve this once released in more regions.
