### ISSUE TITLE
"ERROR: could not find process" on convox run

### ISSUE THREAD

**Issue by contra** [convox/rack#2136]
No idea what this is, but just happened on our CI server:

```
$ convox run web "echo 123"
ERROR: could not find process
```

What would cause something like this?

**Comment by ddollar** [comment]
Because this issue would involve debugging your individual Rack would you please open a support ticket in Console (https://console.convox.com)?

Opening a support ticket requires at least a Basic plan. We offer a 7 day free trial if you're new to Convox and would like to try us out.

**Comment by contra** [comment]
@ddollar I will reopen all of my tickets from github as console tickets, thanks.
