### ISSUE TITLE
`convox.balancer=false` causes envvar based linking to not work

### ISSUE THREAD

**Issue by advance512** [convox/rack#2139]
I have an app with several microservices that works fine using internal ELBs and envvar based linking.

A cost of $16-20 per ELB per microservice type can be extremely prohibitive for young startups - a modern app can very quickly get to tens of different microservices. To remedy this, I set `convox.balancer=false` and redeployed the app, expecting it to work as all microservices are currently run with a scale of 1.

However, it seems that envvar based linking does not work at all when using `convox.balancer=false`, even when there is only one container. I can understand how it could fail (logically) in case of scale>1, since there is indeed no load balancing. But why would it not work with scale=1?

Also, wouldn't it make sense to use one of the many existing open source load balancers, e.g. nginx, haproxy, or even the wonderful traefix load balancer which has in-built ECS support?
https://docs.traefik.io/toml/#ecs-backend

**Comment by advance512** [comment]
Yes. This seems to be caused because:

`
func (s Service) HasBalancer() bool {
	if s.Labels["convox.balancer"] == "false" {
		return false
	}
`
https://github.com/convox/rack/blob/master/manifest/service.go#L111

which in turn:
`
func (m Manifest) Balancers() []ManifestBalancer {
	balancers := []ManifestBalancer{}

	for _, entry := range m.Services {
		if entry.HasBalancer() {
			balancers = append(balancers, ManifestBalancer{
				Entry:  entry,
				Public: len(entry.InternalPorts()) == 0,
			})
		}
	}

	return balancers
}

func (m Manifest) GetBalancer(name string) *ManifestBalancer {
	for _, mb := range m.Balancers() {
		if mb.Entry.Name == name {
			return &mb
		}
	}

	return nil
}
`
https://github.com/convox/rack/blob/master/manifest/balancer.go#L19

and finally:
`
			mb := m.GetBalancer(link)
			if mb == nil {
				// commented out to be less strict, just don't create the link
				//return m, fmt.Errorf("Cannot discover balancer for link %q", link)
				continue
			}
`
https://github.com/convox/rack/blob/master/api/models/release.go#L539

This causes services with no balancer to be _silently_ dropped out, with no warning or error, and hence no linked envvars are created.

Is this by design?

**Comment by ddollar** [comment]
Yes, this is by design. Convox does not have any built-in service discovery and instead relies on balancers placed in front of each service to give a static hostname (env var) for finding it.

**Comment by advance512** [comment]
Question: how does `convox start` work without ELB? Can't we force this emulated load balancer to run in AWS, as well?
