### ISSUE TITLE
Rack update generated a lot of scary EOF errors

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2141]
1. My rack update command failed with an `EOF` error
2. All rack API commands failed with `EOF` errors
3. I ran `convox login myHost`
4. Things were apparently fixed

```
paul ~/projects/thePlatform revert-python2-shebangs $ convox rack update --wait
WARNING: Required update found.
Please run `convox rack update` again once this update completes.
Updating to 20170202012654... UPDATING
Waiting for completion... ERROR: Get https://uat-convox-561984580.us-west-2.elb.amazonaws.com/system: EOF
paul ~/projects/thePlatform revert-python2-shebangs [1]$ convox --version
client: 20170406014059
ERROR: Get https://uat-convox-561984580.us-west-2.elb.amazonaws.com/system: EOF
paul ~/projects/thePlatform revert-python2-shebangs $ convox apps info
ERROR: Get https://uat-convox-561984580.us-west-2.elb.amazonaws.com/apps/theplatform: EOF
paul ~/projects/thePlatform revert-python2-shebangs [1]$ convox rack logs
ERROR: websocket.Dial wss://uat-convox-561984580.us-west-2.elb.amazonaws.com/system/logs: EOF
```

**Comment by ddollar** [comment]
If you were moving up from a really old rack it's possible for the instance roll and convox API roll to have a period of unavailability in the Convox API. This happened as we switched from custom resource handlers to native ECS service handlers in CloudFormation.

This was likely a one-time event and you shouldn't have seen any downtime in your apps as long as they were scaled to 2 or greater (as usual).
