### ISSUE TITLE
Limit KernelUser with aws:SourceIp restriction

### ISSUE THREAD

**Issue by lairdnote** [convox/rack#2148]
Currently, KernelUser permission is still big and no aws:SourceIp restriction. The kernel user secret key may be used outside rack to have big security concern.
From AWS, they suggest using switch role to handle it.

https://aws.amazon.com/premiumsupport/knowledge-center/source-ip-switch-role/

Can you help consider it or use other ways to fix it?

Thanks.

**Comment by MiguelMoll** [comment]
We're making a few changes so that the rack can use a default role with the option for the user to provide their own role. Definitely want to move away from using keys.

**Comment by ffjia** [comment]
@MiguelMoll could you elaborate more on how to use role instead of keys?

**Comment by MiguelMoll** [comment]
It's still a work in progress and will be part of [Praxis](https://github.com/convox/praxis). You'd be able to specify the role's ARN for Rack to use.

**Comment by ddollar** [comment]
Kernel User no longer has a secret key but uses an IAM role instead
