### ISSUE TITLE
convox app create - incorrect status code on failure

### ISSUE THREAD

**Issue by markfermor** [convox/rack#2158]
From Convox slack channel is below chat transcript. OR (https://convox-public.slack.com/archives/C08HXR97Z/p1492534195913605)

> mfermor [5:49 PM] 
> Hey Guys, i think there is a bug when first trying to create an app, if that fails the exit code returns as 0 rather than a valid exit status.
> ```$ convox apps XXX-pr-193 --rack XXX --wait
> Creating app XXX-pr-193... CREATING
> Waiting for XXX-pr-193... FAILED
> Rolling back... DONE
> ERROR: Update rolled back
> OK
> $ echo $?
> 0
> ```
> (edited)
> 
> ddollar [5:50 PM] 
> @mfermor what error did it fail with?
> 
> [5:51] 
>  ```$ convox apps create 1
> Creating app 1... ERROR: app name can contain only alphanumeric characters, dashes and must be between 4 and 30 characters
> $ echo $?
> 1```
> 
> mfermor [5:52 PM] 
> looking at the cloudformation it errors on the customLambda function trying to “Custom::ECRRepository” with “Invalid PhysicalResourceId”. I think you might not find the same problem because it’s perhaps reporting that the roll back was successful. However if it’s the first time you’ve tried to biuld the app, Cloudformation is left in a state in which the template can only ever be updated
> 1 reply Today at 7:07 PM View thread
> 
> ddollar [5:52 PM] 
> ah gotcha
> 
> mfermor [5:53 PM] 
> then next time we try and do something such as convox env stuff, it fails saying S3 bucket not found in region
> 
> [5:54] 
> which is because the stack has rolled back to nothing. I only spot it our side because we rely on the error codes in our automation
> 
> ddollar [5:54 PM] 
> @mfermor yep looks like a bug
> 
> [5:54] 
> https://github.com/convox/rack/blob/master/cmd/convox/apps.go#L161
> 
> [5:54] 
> that OK should probably be in an else
> 
> mfermor [5:54 PM] 
> ahh :thumbsup:
> 
> ddollar [5:55 PM] 
> actually looking at the rest of the code that `stdcli.Error` should be `return`ed
> 
> [5:55] 
> https://github.com/convox/rack/blob/master/cmd/convox/apps.go#L158

PR coming for this shortly - created an issue so this and the PR can be linked

**Comment by markfermor** [comment]
So this was happening for me on app create for reasons that were not obvious to see. When I did "convox app create X" as I said above the cloudformation stack build would fail but would also automatically rollback, with that rollback we loose any errors that would have been present in the custom Lambda function CF was calling out to (which is where the failure was coming from). As CF stack deletes everything on rollback including the lambda logs for that function, to combat this problem, I took the template contents, params etc of the failed template build and created a new stack manually outside of convox completely and then changed the automatic rollback setting CF has to false. So the stack build still failed but now i could see why when looking at the Lambda logs.

error: InvalidParameterException: Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*''
status code: 400, request id: XXX-XXX-XXX-XXX-XXX

**Comment by markfermor** [comment]
Adding a couple more bits of info - just in case anyone else comes across it in the future..

After the above was solved there was then a new error which appears to be the same issue as reported here #1843 - seems like app name is too long, should be simple enough to change app name. Couldn't see any errors for this in Lambda or the CF stack (don’t think it even got far enough through the process for it to start running a stack update), so these must be calls happening direct to AWS/Convox APIs? The error wasn’t very clear. “Error: InvalidParameterException: startedBy longer than 36” but as it matches the error in the issue mentioned, shorting our app name a little solved this one.

After changing appname again to get over the previous error, then another new error which is now related to ELB name length as seen in the Cloud formation stack on convox deploy. "LoadBalancer name cannot be longer than 32 characters" - found it very hard to find/impossible to find what ELB name was trying to be set on the stack update (even when looking at the cloudformation templates uploaded to the application specific S3 bucket, it seemed to upload the rolled back to version rather than the version that was trying to be deployed - so either i missed out or it's impossible to get hold of. Might be worth uploading the attempted cloud formation template and any params etc OR perhaps having it configurable to set cloud formation to not automatically roll back). Anyway the error in the cloud formation events was obvious enough (as mentioned in this paragraph above), and just tweaked the app name length again. Can't help but think some validation on the convox side could help reduce the long process i've gone through and provide for a faster feedback experience to developers (rather than getting most of the way through a deployment and then failing) but also allow Convox to control the error messages that might have been seen in this case, but i guess that depends on the experience trying to be a achieved (a mostly hands off of AWS or a bit of good experience of both AWS and Convox).

**Comment by MiguelMoll** [comment]
Thanks for this amazingly detailed report. 👍 Going to take the PR forward and get it released.

**Comment by MiguelMoll** [comment]
@markfermor Thanks for filing this issue and the PR for the fix. It should be resolved in the 20170515223736 release.
