### ISSUE TITLE
Can't create redis resource with dedicated tenancy

### ISSUE THREAD

**Issue by brandonblock** [convox/rack#2163]
Redis and Elasticache require a VPC that allows dedicated and non-dedicated instances but if Convox creates a VPC for dedicated instances, it disallows non-dedicated instances.

A workaround is to create a VPC with default tenancy, and install a rack into it with the dedicated flag set. That way you get dedicated EC2 instances but you can create services that require non-dedicated.

**Comment by ddollar** [comment]
Seems like a reasonable workaround until AWS allows dedicated types for those resources.
