### ISSUE TITLE
Support for custom IAM roles, users, and security groups

### ISSUE THREAD

**Issue by jason-riddle** [convox/rack#2168]
In my current position, the ability to create IAM roles as a developer has been removed. Instead, there is a self-service model where I need to request roles ahead of time and have them approved. With this restriction in place, convox seems like a non-starter since it is generating these resources on the fly. I would like to be able to specify a custom IAM role, as well as a IAM user and set of security groups.

**Comment by MiguelMoll** [comment]
At least with custom IAM roles, we're currently in the process of rewriting the Cloudformation template which would allow user's to specify a role for Rack to use or fall back to a default role.

Could you elaborate a bit more on what you'd like to see with custom security groups?

**Comment by jason-riddle** [comment]
I haven't thought about what the custom security groups would look like. I would need to give it some more thought.

**Comment by MiguelMoll** [comment]
Sounds good, no rush of course. Going to close the issue for now but feel free to update the ticket as you see fit.
