### ISSUE TITLE
TEMPLATE_FILE too large

### ISSUE THREAD

**Issue by chuckwu-aa** [convox/rack#2169]
When I follow the guide in development session, I can not test customized rack json file due to template file size issue.
https://github.com/convox/rack/blob/1fa5450b6f7674c1f85d4fff70ffd82fc9b3b161/Development.md

$ TEMPLATE_FILE=./provider/aws/dist/rack.json convox install --stack-name=convox-dev

[12:06] 
at ‘templateBody’ failed to satisfy constraint: Member must have length less than or equal to 51200

Even we have already compressed the json file via compacting, it still doesn't work.

**Comment by MiguelMoll** [comment]
This is a known limitation of Cloudformation. We should update the docs to reflect this. We're currently in the process of rewriting the template and breaking it up into various pieces for better organization and by nature help us avoid this limit.

Thanks for the report. I'll close it for now but please continue the conversation if needed. 👍 

Ref: https://github.com/convox/rack/issues/714
