### ISSUE TITLE
`convox apps info` should show endpoints for containers with `convox.balancer=false`

### ISSUE THREAD

**Issue by erikcw** [convox/rack#2178]
This would be useful in order to quickly setup a local tunnel with `convox proxy` to containers created without an ELB using `convox.balancer=false`.  

Currently, `convox proxy 8899:ec2-*********.compute-1.amazonaws.com:59090` works -- but discovering the hostname of the instance running the service is rather roundabout (login to ECS console, filter by service name, drill down to service task, get the instance the task is running on, then lookup the DNS in EC2 console).

Alternatively -- a quick way to get the instance id and hostname from `convox ps` would get the job done.

**Comment by ddollar** [comment]
#2341 should cover this
