### ISSUE TITLE
Error setting `PrivateApi=yes`

### ISSUE THREAD

**Issue by apeace** [convox/rack#2184]
I have a fresh rack where I ran `convox rack params set PrivateApi=Yes`. CloudFormation starts processing this and eventually hangs for a long time. Eventually it fails with:

```
Service arn:aws:ecs:us-east-1:<account>:service/<rack>-WebService-<id> did not stabilize
```

Looking at the WebService in ECS, I am seeing `Desired count: 2, Running count: 1` and the error:

```
service <rack>-WebService-<id> was unable to place a task because no container instance met all of its requirements. The closest matching container-instance <id> is already using a port required by your task.
```

I have not launched any apps into the rack at this point. This occurred using the latest rack `20170502211928`, and I also tried downgrading the rack to `20170330004259` and still saw the same result.

**Comment by apeace** [comment]
I was able to work around this by bumping the rack up to 7 instances, then running `convox rack params set PrivateApi=Yes`, then bumping it back down to 3 instances.

I also removed by `BuildInstance` first, and kept this in place during the above procedure. I don't think this had any effect, since after removing `BuildInstance` but before bumping to 7 instances, I still got the same failure.

Hope this helps someone!

**Comment by MiguelMoll** [comment]
Since you manually increased the instance count to 7, was autoscaling disabled for the rack? Autoscaling should've have bumped up the number of instances needed to achieve this.

By removing `BuildInstance`, do you mean setting its value to an empty string? That's not a problem as the general rack instances would be used to build images in that case.

I'll close this issue now as it seems you're problem is solved, but please reopen it if you need to. Thanks!

**Comment by apeace** [comment]
`Autoscale` was always set to `Yes`.

And yes, by removing `BuildInstance` I meant `convox rack params set BuildInstance=`.

Also, the rack had three instances, and no apps. So even without autoscaling, it seems like this shouldn't have happened.

No need to re-open, we are good now!

**Comment by MiguelMoll** [comment]
Thanks for the clarification. One thing to keep in mind is that Rack itself runs as a "special" app in the cluster. So when ECS tries to replace it given it has different deployment configuration, if there aren't any ports available, you end up with the "no ports available" error from ECS.

I can see this happening with autoscale disabled but not enabled. Thanks for the info!
