### ISSUE TITLE
Can't import a build into another app running on the same rack

### ISSUE THREAD

**Issue by davesilva** [convox/rack#2189]
I have two apps, `api-staging` and `api-feature-branch` running on the same rack. I'd like to be able to move a build from `feature-branch` to `staging` as described in the docs, but when I do that I get an error that the build already exists:

    $ convox builds export BEUWPRARFMB -a api-feature-branch | convox builds import -a api-staging
    Exporting BEUWPRARFMB... OK
    ERROR: build id BEUWPRARFMB already exists

But when I look at the destination app, the build isn't in there - it's only present in the app I'm exporting from:

    $ convox builds -a api-staging
    ID  STATUS  RELEASE  STARTED  ELAPSED  DESC

    $ convox builds -a api-feature-branch
    ID           STATUS    RELEASE      STARTED     ELAPSED  DESC
    BEUWPRARFMB  complete  RCURTKCTITO  3 days ago  3m13s

Just to be sure, I also tried splitting the export/import into two commands and got the same result:

    $ convox builds export BEUWPRARFMB -a api-feature-branch > build.tgz                               
    Exporting BEUWPRARFMB... OK

    $ convox builds import -a api-staging < build.tgz
    Uploading: 530.27 MB / 530.27 MB [====================] 100.00 % 4m11s
    Importing build... ERROR: build id BEUWPRARFMB already exists

I've been evaluating Convox for possible use at work and it seems great, but I'd really like to be able to script moving a build between environments without having to spin up separate racks for each of them. Is there any workaround I can use to make this work?

**Comment by MiguelMoll** [comment]
This is a tricky one as keeping the same build ID is expected behavior that was put in place recently. That way, the same image could be tracked through the flow between various racks.

Current workaround would be (as you stated) is to have the apps running in different racks. We'll definitely take your situation into account as we develop a proper solution.
