### ISSUE TITLE
"convox apps params set Internal=Yes" fails

### ISSUE THREAD

**Issue by beedub** [convox/rack#2190]
Our app has a load balancer name with 32 chars. Trying to set `Internal=Yes` for the app fails because of a cloudformation update failure: `LoadBalancer name cannot be longer than 32 characters`.

**Comment by aochsner** [comment]
FWIW, starting to get the same error.  Rack is on version `20170531220422`

**Comment by jayjanssen** [comment]
Same.  I don't see this on my other apps, just the internal one and just on one service that doesn't seem to have an overly long name.

**Comment by pauldub** [comment]
I'm also affected by this issue, is there a workaround?
