### ISSUE TITLE
Adding from and to to convox logs

### ISSUE THREAD

**Issue by shidenkai0** [convox/rack#2191]
Hi everyone, 

As of today, convox logs only supports a "from" cli parameter to specify a time span for which to get the logs. This makes it very inconvenient to query logs in a specific time span that doesn't end now, and forces the user to use the aws cli to query CloudWatch directly as follows:

``` aws logs get-log-events --log-group-name prod-foo-app-LogGroup-TC9RVI8RA8CD --log-stream-name e64da06a9c44acf91465224496ee29282599c92a6ced647ddfc2b0b07b05afcd --start-time 1494410354000 --end-time 1494411248000 ```  

As you can see, this is neither convenient nor user-friendly, as it implies diving into CloudWatch in order to find the log group and log stream that contain the relevant app logs, using unix timestamps moreover.

Would it be welcome to submit a PR adding a ```--to``` flag to ``` convox logs ```, and extending the accepted input of ``` --from ```  to absolute times?

The flags could take the following formats for instance : 

```--from='08/05/2017 12:34' ```
```--from='1h ago' --to='2m ago' ```

I would like to open a discussion to gather what others and the Convox team think about it.

**Comment by mwarkentin** [comment]
That sounds pretty nice to me. :)

**Comment by MiguelMoll** [comment]
Indeed sounds useful. Going to see if we can get some ideas going here.
