### ISSUE TITLE
`convox killall` or `convox stopall`

### ISSUE THREAD

**Issue by contra** [convox/rack#2206]
Feature request. Similar semantics to `killall` command.

Would be nice to be able to type `convox killall <name>` instead of having to look up each individual process ID.

**Comment by mwarkentin** [comment]
:+1:

**Comment by contra** [comment]
```sh
convox_killall() {
  convox api get /apps/$2/processes | jq -r '.[] | select(.name == "$1") | .id' | xargs -n 1 convox ps stop
}
```

`convox_killall appname processname

**Comment by mwarkentin** [comment]
We have some automated jobs which kill certain worker types regularly.. ideally we'd fix this, but in the meantime, it causes a huge amount of spam in our audit logs:

![](https://mwarkentin-snaps.s3.amazonaws.com/Convox_2017-08-02_15-32-14.png)

Replacing that with a single audit log entry would be really nice..

**Comment by ddollar** [comment]
What's the use case for killing all processes of a certain type?

**Comment by mwarkentin** [comment]
In this case we had certain worker processes that would end up hanging for unknown reasons and stop processing from the queue - this was our hack to keep things running. Upgrading the worker library eventually fixed the hanging workers, but this hack was in place for a long time until we got there.

**Comment by ddollar** [comment]
The use for something like this seems to be pretty small for a dedicated API.
