### ISSUE TITLE
Convox should not attempt impossible rack updates

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2209]
In #2142, my rack got into a "rollback failed" state when I ran `convox update` because it tried to update directly from `20170202012654` to `20170405220740`. It turned out that the correct solution was to first update to `20170306140228`, then to update again from that. In order to avoid this problem, the user would need to have some very specific knowledge.

**Comment by mwarkentin** [comment]
@paulkernfeld There is the concept of "required" releases in convox, which is basically what you described - if you try upgrading beyond it, it will upgrade to that version instead, and then you'll need to launch another upgrade.

It's possible that it was missed that this was required in this case.

**Comment by paulkernfeld** [comment]
Oops, I didn't know that this was already a thing! Must have been a one-time omission in this case.
