### ISSUE TITLE
Build `failed to register layer: devmapper`

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#2210]
I have seen a few reports of device mapper errors during a build. We need to:

- [ ] Root cause device mapper errors
- [ ] Fix root cause
- [ ] Or automate instance replacement

For example:

```
...
628128ca0bac: Pull complete
failed to register layer: devmapper: Thin Pool has 10010 free data blocks which is less than minimum required 10126 free data blocks. Create more free space in thin pool or use dm.min_free_space option to change behavior
ERROR: build error: exit status 1
ERROR: myapp build failed
```

**Comment by mwarkentin** [comment]
@nzoschke That sounds similar to the issue we saw when our custom AMI was configured with the base 20GB volume instead of the 50GB volume provided by convox. Might be worth checking if those reports are also using custom AMIs or not.
