### ISSUE TITLE
How do I get Convox to detect when an update has failed?

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2215]
The [update docs on automatic rollback](https://convox.com/docs/rolling-updates/#automatic-rollback) say:

> If there are errors starting new processes, new processes are not verified as healthy, or the rollout doesn’t complete in 10 minutes, an automatic rollback is performed. This will result in a rollback or failed state for the app:

Is there something that I can do in order to make Convox detect that my app is not running? Right now, the app gets stuck in a kill/restart loop as described in #1613.

**Comment by ddollar** [comment]
We would need configurability for the ECS CloudFormation resources. Currently this can take quite a long time to roll back.
