### ISSUE TITLE
Feature Request: Service-level (Task definition) role configuration 

### ISSUE THREAD

**Issue by bvalerius** [convox/rack#2222]
As opposed to #1659 adding functionality for apps to have task roles, it would be useful to also allow service-level role configuration.

For example, if I have N services running in my app, I may only want one of them to have a role to execute a Lambda outside of the rack.

**Comment by ddollar** [comment]
Gen2 apps have an `IamPolicy` param that you can set to the ARN of a custom IAM policy.
