### ISSUE TITLE
Repeated "no such release" error setting env vars

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2234]
When I try to set env vars with `--promote`, it says `no such release`.

```
booker [EG-356_Update_version_of_scala-common_and_grpc_in_booker] % convox env set FREEBIRD_WORLDSPAN_PCC=IDK FREEBIRD_WORLDSPAN_PCC=IDK --promote
Updating environment... OK
Promoting RRYUARTCFHI... ERROR: no such release: RRYUARTCFHI
booker [EG-356_Update_version_of_scala-common_and_grpc_in_booker] % convox env set FREEBIRD_WORLDSPAN_PCC=IDK FREEBIRD_WORLDSPAN_PCC=IDK --promote
Updating environment... OK
Promoting RPZPHBHJWTW... ERROR: no such release: RPZPHBHJWTW
booker [EG-356_Update_version_of_scala-common_and_grpc_in_booker] % convox env set FREEBIRD_WORLDSPAN_PCC=IDK FREEBIRD_WORLDSPAN_PCC=IDK --promote
Updating environment... OK
Promoting RXNVJDQQQUD... ERROR: no such release: RXNVJDQQQUD
```

I think it might be because I switched Convox racks while the command was running; is it possible that Convox could try to promote the release in the new rack rather than the rack in which I set the env var?

**Comment by mwarkentin** [comment]
@paulkernfeld Might be worth testing - what happens if you specify the rack w/ `--rack <rack name>` in the command?

**Comment by paulkernfeld** [comment]
I think that one needs to be using Convox Console, which I'm not, in order to specify `--rack`. Does that sound right?

**Comment by mwarkentin** [comment]
Yes, I think `--rack` requires console. I think you're probably right about it being caused by switching racks while the operation is running.

**Comment by ddollar** [comment]
Closing for now. "Current Rack" is currently set for the entire CLI so yes switching in the middle of a command can do bad things.
