### ISSUE TITLE
Deployment fails if udp port listed before tcp port

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#2238]
In the docker-compose.yml this works:

```
ports:
  - 80:80/tcp
  - 5000:5000/udp
```

But this:

```
ports:
  - 5000:5000/udp
  - 80:80/tcp
```

Results in a CloudFormation error.

<img width="1208" alt="screenshot 2017-06-22 15 16 57" src="https://user-images.githubusercontent.com/44615/27451669-e801d2d2-575d-11e7-9f32-815c7d276351.png">

**Comment by ddollar** [comment]
Noted. Absent in Gen 2 so closing for now.
