### ISSUE TITLE
Lost symlink in app after `convox build`

### ISSUE THREAD

**Issue by bangn** [convox/rack#2246]
Hi there,

I'm trying to build deploy our Ruby app using convox. However, after building the app, all symlinks in our app are lost.

Our app basically have the structure like below:
```
app
-- file1.rb
-- file2.rb
-- file3.rb
-- group
---- file1.rb --> ../file1.rb  # Symlink to upper file.
---- file2.rb --> ../file2.rb
---- file3.rb --> ../file3.rb
```

After running `convox deploy` and shell into the container, all the symlinks are lost.

**Comment by ddollar** [comment]
This should not be the case. What OS are you deploying from?

**Comment by qnm** [comment]
@ddollar This was from OSX, would you like me to verify it's still the case?

**Comment by ddollar** [comment]
Yes please
