### ISSUE TITLE
Access ECR with Instance Role?

### ISSUE THREAD

**Issue by ffjia** [convox/rack#2248]
Hello,

Is it possible to add the ECR read-only policy to instance IAM Role when adding ECR repo from different account? Since it might have security risk that someone have the access key and secret key of that IAM user, then he can get all the images. Also it's hard to limit the access source. Idea?

**Comment by ddollar** [comment]
The keys have been removed in favor of IAM roles all around.

**Comment by ffjia** [comment]
Great, so it means we won't this step [here](https://convox.com/docs/private-registries/#adding-an-amazon-ec2-container-registry-ecr-from-a-different-account)? And how should we allow cross account ECR access now?
