### ISSUE TITLE
Couple of cli tweaks

### ISSUE THREAD

**Issue by whatyoubendoing** [convox/rack#2249]
Not sure where the right place to put this is - there are a couple of CLI tweaks which would be nice to have - I may even have a crack at implementing them myself if you guys see value in them. 

- Have a confirmation &  --force options for when running `convox resources delete`  resources/services. Currently its quite easy to remove resources by mistake. 
- Remove options which can not be updated from `convox resources update -h`

**Comment by jontonsoup** [comment]
#1 is here: https://github.com/convox/rack/pull/2313

**Comment by ddollar** [comment]
Closing for now as #2313 covers it. You can configure stack termination protection in the AWS web UI for now.
