### ISSUE TITLE
Template error for syslog linked to lots of apps

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#2251]
A user writes:

We're trying to add a syslog resource (`convox resources link syslog-4435 --app <appname>`) but are getting the following error:

```
'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
```

We have 25+ "outputs" on that syslog, so that's why the template is so large. But according to my googling if this uses a file on s3 rather than raw JSON in a REST request it will work?

**Comment by ddollar** [comment]
This should no longer be an issue due to the new stack update mechanism in Rack using S3 as a middleman.
