### ISSUE TITLE
Cannot authenticate with private git repo with manual build

### ISSUE THREAD

**Issue by kolanos** [convox/rack#2254]
According to the "Building From a Git Repository" section in https://convox.com/docs/builds/ it should be possible to run:

    $ convox build https://github.com/myuser/myproject.git

But when running this against a private GitHub repo I get the following error:

    fatal: could not read Username for 'https://github.com': No such device or address
    ERROR: exit status 128

Tried adding `convox@` to the URL and get:

    fatal: could not read Password for 'https://convox@github.com': No such device or address

I have a workflow that is integrated with GitHub and can clone this private repo without issue. How do I do the same manually?

**Comment by ddollar** [comment]
Workflows work using your Github Oauth token to clone the project locally and then build from the local directory. To manually do this you should do the same thing. Clone using your own auth then `convox build .`
