### ISSUE TITLE
rack wont go private

### ISSUE THREAD

**Issue by contra** [convox/rack#2255]
```
$ convox rack params set Private=Yes
Updating parameters... OK
```

Takes forever, but finally ends up failing and rolling back here:

![screen shot 2017-07-17 at 10 34 09 am](https://user-images.githubusercontent.com/425716/28273149-8618b36a-6adb-11e7-8de3-81a0fd536f17.png)

Rack version is 20170606013346

Worked fine on one rack, does not work on this rack - tried 10 or so times. Both racks have an identical configuration and version.

**Comment by ddollar** [comment]
Please try again on the latest version of Rack and comment to reopen if this is still an issue for you.
