### ISSUE TITLE
update from 20170606013346 -> 20170712160322 fails

### ISSUE THREAD

**Issue by contra** [convox/rack#2256]
I've tried this 10 to 15 times across multiple racks, I've yet to get this to work. The update process starts, some stuff happens, then it reports the same version so I'm assuming the update failed.

Running this now, will report back with detailed logs in one minute.

**Comment by contra** [comment]
![screen shot 2017-07-17 at 11 27 00 am](https://user-images.githubusercontent.com/425716/28275769-e31a93f6-6ae2-11e7-811d-51aadf82789c.png)

Then hangs forever - so far been hanging for 30 minutes. Eventually it times out because the rack state goes back to running and you can attempt it again. Will post those logs when it happens.

**Comment by contra** [comment]
![screen shot 2017-07-17 at 1 54 25 pm](https://user-images.githubusercontent.com/425716/28282163-7c500de4-6af7-11e7-9040-b1bdd687711b.png)

Culprit looks like: `Group did not stabilize. {current/minSize/maxSize} group size = {4/6/1000}. Failed Scaling Activity: the encrypted flag cannot be specified since device /dev/xvda has a snapshot specified. Launching EC2 instance failed.`

**Comment by ddollar** [comment]
This should be fixed in the latest version of Rack.
