### ISSUE TITLE
Rack stuck in 'installing' state - cannot remove

### ISSUE THREAD

**Issue by kylemclaren** [convox/rack#2267]
Rack provisioned correctly and was running, then mysteriously reverted to `installing` state despite the CF stack showing as completed in the AWS console. Deleted CF stack manually but now cannot remove the rack from the Convox dashboard because the Settings tab doesn't give me an option to remove the rack.

**Comment by kylemclaren** [comment]
```
➜  ~ convox uninstall test us-east-1 --force


     ___    ___     ___   __  __    ___   __  _
    / ___\ / __ \ /  _  \/\ \/\ \  / __ \/\ \/ \
   /\ \__//\ \_\ \/\ \/\ \ \ \_/ |/\ \_\ \/>  </
   \ \____\ \____/\ \_\ \_\ \___/ \ \____//\_/\_\
    \/____/\/___/  \/_/\/_/\/__/   \/___/ \//\/_/


Using AWS CLI for authentication...
ERROR: can not find rack named test
Are you authenticating with the correct AWS account?
See AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and ~/.aws/credentials
```

**Comment by kylemclaren** [comment]
@ddollar any thoughts on this one. I am kinda stuck, not having access to the backend for the dashboard.

**Comment by mateusz-fiolka** [comment]
+1

**Comment by ddollar** [comment]
Please send me an email at david@convox.com with the name of your organization, rack name, any other details you have.
