### ISSUE TITLE
CLI: alpine linux support

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#2272]
We use alpine for most of our docker images - it would be nice to be able to use the convox CLI without needing to install `glibc` as well. Any thoughts on if this is something you could support? Maybe for praxis if it was an issue with equinox builds?

**Comment by jmcvetta** [comment]
FWIW, this seems effective for making latest `convox` binary run on Alpine 3.7 (latest):

```dockerfile
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
```

Credit for this solution belongs to https://github.com/edkellena/docker-convox/blob/master/Dockerfile

**Comment by ddollar** [comment]
This is likely fixed now as CLI builds are no longer using equinox

**Comment by mwarkentin** [comment]
Thanks, I’ll test it out. 😀

**Comment by nikmash** [comment]
Was this confirmed as fixed? Can't seem to get the convox binary working in alpine

**Comment by jmcvetta** [comment]
@nikmash No, it's not fixed.  You can add the following workaround to your `Dockerfile`:

```
# Workaround Alpine-compatibility bug
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
```
