### ISSUE TITLE
Secure environment and TaskRole features conflict

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#2306]
It looks like that setting app's TaskRole and using `convox.environment.secure=true` features conflict with each other. The reason being that the secure environment is implemented internally by setting a special task role and only one task role can be defined for an ECS task.

I'm not sure what a workaround could be, but probably this should at least be documented.

**Comment by mwarkentin** [comment]
Is this still the case now that secure env is enabled by default on gen 2?

**Comment by bladealslayer** [comment]
I haven't had a chance to test that.

**Comment by denmat** [comment]
Doesn't work for me with gen2 (without setting `convox.environment.secure=true`).

```
convox apps params set TaskRole=arn:aws:iam::blahblah:role/service-role/a-role 
Updating parameters... ERROR: No updates are to be performed
```

```
convox apps params
NAME              VALUE
BackendFormation  1,128,256
LogBucket
NginxFormation    1,128,256
PollerFormation   1,128,256
Rack              blahblah
WorkerFormation   1,128,256
```

This is the task role associated with the ECS task:
```
arn:aws:iam::blahblah:role/convox/blahblah-ServiceRole-CNBVH0MCHGWG
```
This is the task role that allows decrypting environment keys.

**Comment by ddollar** [comment]
This has been solved in Gen2 by adding an `IamPolicy` parameter for apps that simply adds a custom policy to the existing Task Role. This will remain unsolved for Gen 1.
