### ISSUE TITLE
Restrict permission of Lambda Execution Role 

### ISSUE THREAD

**Issue by ffjia** [convox/rack#2331]
Hi there,

I'd like to know if we could have more restricted IAM Policy for Lambda execution role? Now the policy looks like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "*",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```
The Lambda function normally should not need admin permission to all aws resource, right?

**Comment by ddollar** [comment]
To which role are you referring? The CustomTopicRole is on its way out so spending time limiting it seems wasteful.

**Comment by ffjia** [comment]
That's good, how do you plan to replace `CustomTopicRole`?

**Comment by ddollar** [comment]
Migrating away from custom cloudformation resources.
