### ISSUE TITLE
Add install option for customized cloudformation URL

### ISSUE THREAD

**Issue by ffjia** [convox/rack#2332]
Hello,

This is a feature request, it's good if you guys could allow customized cloudformation template URL when running `convox install`.

Furthermore, is it possible to use this option to retrieve all related files (CFN tmpl, lambda functions, versions.json) from our own S3 bucket, instead convox.s3.amazonaws.com?

**Comment by ddollar** [comment]
You can do this with the Amazon web ui, CLI, or API for now. More detailed information added in #2343
