### ISSUE TITLE
Error creating Rack in regions with less than 3 Availability Zones (REOPEN)

### ISSUE THREAD

**Issue by mzelinsky** [convox/rack#2335]
Hi.
It seems that this issue https://github.com/convox/rack/issues/117 was not closed as this code still exists https://github.com/convox/rack/blob/b9894760d2da5762ec266c5c0762f0de2fa63f05/cmd/convox/install.go#L226

The code above doesn't allow creating Rack in existing VPC with less than 3 Availability Zones.

**Comment by ddollar** [comment]
Would you be interested in putting together a PR?
