### ISSUE TITLE
[GEN2] Proposal: support loading convox.yml from .convox/config.yml

### ISSUE THREAD

**Issue by mwisner** [convox/rack#2336]
Reading the docs, I believe gen2 requires the convox.yml file to be located in the root of the project. 

However with gen 1 applications at least we are able to place the app name in a file at `.convox/app` (which prevents us from having to always pass it in as an argument (https://convox.com/docs/cli/#overriding-app-defaults)

I'm wondering if it would make sense to keep all the convox related files in a folder `.convox`?

**Comment by mwisner** [comment]
Another thought: Allow app name to be set in convox.yml... Just trying to keep all the convox stuff in one spot.

**Comment by ddollar** [comment]
Going to leave this as-is for now. The `.convox` directory is for CLI-level config. The `convox.yml` is the manifest for the entire application.
