### ISSUE TITLE
Need a rack/app parameters to enable S3 access logging

### ISSUE THREAD

**Issue by robatwave** [convox/rack#2337]
Racks and applications get provisioned with S3 buckets for convox-internal use, and we'd like to be able to turn on access logging for them across the board. To that end we'd need 2 rack/app parameters:

1. bucket - setting this should cause access logging to be enabled on all S3 buckets
1. key prefix

**Comment by ddollar** [comment]
This now happens by default to a bucket. You can configure the bucket used with the `LogBucket` rack param.
