### ISSUE TITLE
How can I forward rack logs to Papertrail?

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2364]
Recently, a rack update caused my rack to enter a bad state. I'd like to be able to monitor my rack logs to detect this kind of situation in the future. Is there an easy way to forward my rack logs to Papertrail? I have already set up a syslog resource and I'm forwarding app logs to it, I just don't know how to do this for the rack logs.

**Comment by advance512** [comment]
FYI, this seems dead for Gen2.
https://github.com/convox/rack/issues/2388

**Comment by paulkernfeld** [comment]
Hmm, that's a bit concerning. Thanks for the heads-up!

**Comment by ddollar** [comment]
Not currently possible but if you'd like to submit a design proposal / PR I'd be happy to take a look.
