### ISSUE TITLE
Upload byte reporting inconsistency 

### ISSUE THREAD

**Issue by NilsJPWerner** [convox/rack#2385]
On creating and uploading a tarball on a deploy I got the flowing information. Is this a bug or was there actually more data uploaded than anticipated?

`Uploading: 240.37 KB / 240.19 KB [=======================] 100.07 % 0s`

**Comment by ddollar** [comment]
Not sure but I've never seen this behavior. Does it happen every time for you?

**Comment by NilsJPWerner** [comment]
Yeah this happens almost every time

**Comment by ddollar** [comment]
I haven't been able to reproduce this. If you can figure out what's going on I'd be happy to accept a PR but this seems both rare and minor so I'm going to close this issue.
