### ISSUE TITLE
[GEN2] Errors creating ACM certificates: too many requests. Cannot deploy to production

### ISSUE THREAD

**Issue by advance512** [convox/rack#2387]
When deploying, with the exact same `convox.yml` and code, I am getting:
`Cannot request more certificates in this account. Contact Customer Service for details`
In gen2 - can't deploy new code. 
Supposedly we reached the ACM certificate count limits.
https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_acm

I am *not* trying to request any new certificates or domains. I am simply deploying the same code, with the same amount of domains set in `convox.yml`. It seems to be re-requesting the creation of certificates, even though I already have them. Also, the limit is supposedly 100, but I only have 10 certificates.
https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_acm

I delete one certificate and tried to re-deploy. 
Then I see, that gen2 attempts to create certificates twice. I see the same domain twice, in the AWS Certificate Manager. 
Could it be that it makes requests which I don't see in the AWS certificate manager, hence getting to 100 and causing this issue?

My temporary solution: removed all `domain` directives from the `convox.yml` file, and manually allocated my wildcard certs to the ALB. 
It was not a long term solution, since the ALB stopped forwarding traffic soon after.

I think that the bug is that Convox creates many many requests - I get 4-8 certificate approval request emails for each new domain I added to my `convox.yml`. And potentially, it attempts to create new certificates for a domain, even though a certificate with this domain already exists. I think that, *perhaps*, the ACM control panel doesn't show all requests made automatically - but that I did indeed reach the limit of 100.

I submitted a request for Amazon, to increase the ACM limits following the issue I encountered.
Their reply:

```I checked your use case with a Certificate Manager engineer. They stated that the error messages that you added to the correspondence came from a CloudFormation stack with configuration errors. Increasing the Number of ACM Certificates limit may help resolve the issue so I've proceeded with the limit increase request.
```

**Comment by ddollar** [comment]
Convox only creates one certificate per service that has a custom domain.

If you hit your limits you'll need to ping support for a limit increase.
