### ISSUE TITLE
Certificates are overridden on deploy (ELB listeners)

### ISSUE THREAD

**Issue by pilt** [convox/rack#2389]
This happens after an upgrade from 20171129034158 to 20171204232334. We use the traditional docker-compose.yml format.

We have used `convox ssl update` to set ACM certificates on many services. After the upgrade, the certificates are reset to some default IAM cert every time we deploy/promote releases.

**Comment by ddollar** [comment]
Thanks for the heads up. I've unpublished that release and will get a fix out shortly.

**Comment by pilt** [comment]
Thanks! And thanks for a great product!
