### ISSUE TITLE
[GEN2] Allow configuration of acceptable status codes for health checks

### ISSUE THREAD

**Issue by mwisner** [convox/rack#2402]
https://convox.com/docs/gen2/convox-yml/#health

I think it would be useful to allow users to configure the advanced health check settings (Healthy threshold, Unhealthy threshold, Timeout, Interval, Success codes) via convox.yml. 

I'm attempting to deploy standard community docker images / applications that require basic auth to access and do not have any urls that expose a 200 status to anon users. 

Currently without some sort of way to configure the acceptable http statuses i'm unable to deploy the application. (I haven't experimented with manually editing yet)

**Comment by ddollar** [comment]
You can do this, it's just not advertised yet. Instead of

```
health: /
```

configure it like

```
health:
  path: /
  interval: 5
  timeout: 3
```

**Comment by ddollar** [comment]
No configurable success codes yet, but will look at adding that in a future release. Please also feel free to submit a PR doing the same.

**Comment by mwisner** [comment]
Yeah I was just digging around in the code seeing if I could track something down... 

Being able to set the status codes is really specifically what I'm looking for. 

Looks like it's called "Matcher"? http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html

**Comment by ddollar** [comment]
This is now 200-399 by default

**Comment by mwisner** [comment]
@ddollar  While this is great, there are still a bunch of use cases in which configuration would be helpful. 

For example, applications that are completely hidden behind 401 and 403 errors.

There are a lot of developer tools that hide behind basic auth and cannot be ran on convox because of this without forking or adding in health check endpoints 

For example in order to get this running: https://github.com/PGBI/kong-dashboard

I have to maintain a fork of the repo because 100% of the endpoints require auth.
