### ISSUE TITLE
`AWS/CloudFormation UPDATE_FAILED CronFunction ZipFile length cannot exceed 4096 characters. For larger source use S3Bucket/S3Key properties instead.`

### ISSUE THREAD

**Issue by brendanjerwin** [convox/rack#2403]
Getting: `AWS/CloudFormation UPDATE_FAILED CronFunction ZipFile length cannot exceed 4096 characters. For larger source use S3Bucket/S3Key properties instead.` when attempting to promote a release with many processes with long, descriptive, names.

Our quick analysis of the lambda function shows about 2k characters of boilerplate code, and a big `taskDefinitions` object that grows with the number of processes in the service. We seem to have reached a limit.

I imagine this should use the S3 style for getting code to the lambda rather than embedding in the function definition.

**Comment by brendanjerwin** [comment]
@ddollar I'm going to look into fixing this myself. Its really starting to affect our day-to-day operations. Any hints or direction on where to look, what to do?

**Comment by ddollar** [comment]
AFAIK new versions of Rack don't use a big `taskDefinitions` object. What version are you on?

**Comment by ranjit009** [comment]
How did you resolve this ? Just by importing the lambda function from the S3 instead of embedding into the function ?
