### ISSUE TITLE
Development.md is missing

### ISSUE THREAD

**Issue by yebyen** [convox/rack#2406]
Looks like https://github.com/convox/rack/commit/287a389f40a0d3470b5d3746f35c8a62ebce7cf9 wiped out Development.md without comment but the reference to that file was left in README.md

Is there wrong information in this file, or was it deleted on purpose?  Any chance there's an updated version of it to be published?

Thanks!

**Comment by ndbroadbent** [comment]
+1, I was trying to figure out how to compile the `convox` cli from source but couldn't find any instructions. Thanks @yebyen for pointing me to the commit

**Comment by ddollar** [comment]
DEVELOPMENT.md has returned
