### ISSUE TITLE
[GEN2] Support gen 1 / docker advanced build setttings

### ISSUE THREAD

**Issue by mwisner** [convox/rack#2411]
https://convox.com/docs/docker-compose-file/#build

In gen 1 we are able to specify both an alternative Dockerfile and context.

These options are pretty useful for a number of situations but generally speaking is preventing us from using a project structure that isolates our docker stuff to a sub-folder of the project. 

example:
https://github.com/pydanny/cookiecutter-django/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D

**Comment by idris** [comment]
Related/duplicate: #2380

**Comment by ddollar** [comment]
https://github.com/convox/rack/pull/2415
