### ISSUE TITLE
[GEN2] Multiple domains for a service?

### ISSUE THREAD

**Issue by idris** [convox/rack#2422]
In gen1 I have multiple domains pointing to my ELB, and I have a wildcard certificate attached to the service in Convox so that all of the domains work properly with HTTPS.

In gen2's `convox.yml`, the `domain` field only supports a single domain, and it auto-generates a new certificate for that domain and attaches it to the service.  So if I CNAME other domains to the endpoint, they [a] fail SSL check and [b] don't work because the ALB doesn't know where to route the request on that domain.

To solve this, `domain` could accept an array or a comma-separated string (to support something like `${HOST}`).

**Comment by ddollar** [comment]
The domain field does accept a comma-separated string
