### ISSUE TITLE
[GEN2] Suggestions related to domains

### ISSUE THREAD

**Issue by ffjia** [convox/rack#2430]
Hello,

I found two small issues related to custom domains w/ gen2 application.

1. Need to approve SSL certificate request every time new application deployed. For example, if the custom domain is `myapp.mydomain.tld`, I have to approve this request. Next time if I use `mynewapp.mydomain.tld`, I need to do it again whether I really need the certificate or not.

Is it possible to let user use a wildcard SSL cert like `*.mydomain.tld`? Or add an option to skip the certificate creation proccess?

2. For ALB rules, it looks like Convox will add a rule which uses xxxxxxxxxxxxxx.convox.site domain, even if I specify custom domain in `convox.yml`. The ALB rules limit is 100, which means one ALB can only support less 50 applications. Could you guys help skip the (xxxxxxxxxxxxxx.convox.site route) rules if custom domain(s) is used?

**Comment by ddollar** [comment]
Issue 1 has been covered by a new issue #2470 

Issue 2 has a PR #2451 with some comments
