### ISSUE TITLE
No lifecycle hooks created for Spot Auto Scaling Group?

### ISSUE THREAD

**Issue by ffjia** [convox/rack#2432]
Hello there,

Found one error in Spot instance system log:

`An error occurred (ValidationError) when calling the CompleteLifecycleAction operation: No active Lifecycle Action found with instance ID i-09c7205a117f0d09a
ValidationError: Stack arn:aws:cloudformation:us-east-1:087528170461:stack/fjia-dev/0f4ae510-c386-11e7-b43f-503f23fb5536 is in UPDATE_COMPLETE state and cannot be signaled`

I'd like to know why there are no lifecycle hooks for Spot? Will it has impact on instance startup and ASG update?

**Comment by ffjia** [comment]
It looks like the Spot ASG launch configuration update does not work well w/o lifecycle hooks.

**Comment by ddollar** [comment]
Merged, thanks!
