### ISSUE TITLE
'convox resources create postgres' fails when given '--database' option

### ISSUE THREAD

**Issue by NilsJPWerner** [convox/rack#2446]
When creating a postgres resource, passing in a database name with the `--database=` option causes the creation process to fail and then rollback without creating anything in rds.

**Comment by ddollar** [comment]
Can you please paste any relevant logs from the CloudFormation events here? The CloudFormation template is [here](https://github.com/convox/rack/blob/master/provider/aws/templates/resource/postgres.tmpl) if you'd like to put together a patch.
