### ISSUE TITLE
add `--encrypted` option for mysql resources

### ISSUE THREAD

**Issue by brandonblock** [convox/rack#2449]
Looks like this is supported for Redis and Prostgres by not mysql. Just for kicks I passed `--encrypted` and got an `encrypted=true` in the confirmation message but when I check the AWS console, the instance does not have encryption enabled.

**Comment by ddollar** [comment]
I'd be happy to merge this PR if you'd like to work on it. You should be able to largely copy the implementation from `postgres`

**Comment by ddollar** [comment]
Closed by #2474
