### ISSUE TITLE
OnDemandMinCount should be set to a minimum of 1

### ISSUE THREAD

**Issue by spencerhakim** [convox/rack#2454]
Due to the [placement constraint for ApiMonitorService](https://github.com/convox/rack/blob/156995d1347eca7c81b1d786ff1e7139766b43fb/provider/aws/formation/rack.json#L2116), rack updates will fail when it is configured to only use spot instances. Either Convox should force a minimum of 1 on-demand instance, or this constraint should be removed.

Personally, I'd like the option to only use spot instances, I can always just set the price limit relatively high to avoid downtime. I'm also a bit confused as to why this constraint was added in the first place, but only for the ApiMonitorService and not the ApiWebService. `git blame` just pointed to a massive commit, so I didn't gain any insight from there.

**Comment by ddollar** [comment]
OnDemandMinCount should be set to a minimum of 1. The monitor must run on demand because it's the code that decides how to readjust the AutoScalingGroups to start more on demand instances if all of the spots go away.

**Comment by erikcw** [comment]
If the monitor must not run on a spot instance, than I would love if it could either be run as a lambda function, or if a dedicated instance could be configured for it.

For example, if my rack is full of `m5.4xlarge` spot instances and I really only want spot instances -- then the option to run monitor on a `t2.nano` or similar.

This would satisfy the desire of keeping costs to a minimum while at the same time providing the stability needed for the monitor instance and other convox core essential containers.

**Comment by ddollar** [comment]
Would definitely consider a PR turning the monitor into a lambda function

**Comment by mwarkentin** [comment]
Fargate might be a nice easy step too - guess that only solves for us east 1 for now though.
