### ISSUE TITLE
Multi-argument convox run commands do not work on newer racks.

### ISSUE THREAD

**Issue by mwisner** [convox/rack#2455]
I have a few racks... and some of them are still on gen 1...

On a gen 1 rack (20171023163225) the command:
`convox run django python manage.py createsuperuser`

Works as expected... but on one of my gen 2 (20180112161435) racks, that same command just brings me into the python shell.

On both racks, `convox run django bash` brings me into the bash shell, and both racks actually have the same docker containers running on them. 

This leads me to believe that the command arguments (or anything after the first space) is being striped somewhere.

```
convox --version
client: 20180116142102
server: 20180112161435 (console.convox.com)
```
A non-python example:

new rack:
```
convox run django "echo 'test'"
```
(no output)

old rack:
```
convox run django "echo 'test'"
test
```

**Comment by mwisner** [comment]
I did some additional review of this problem...

We've got auditing enabled in our account and in the audit log it correctly identifies the command ran the full command in the audit log... and using the playback video you can actually see it going straight into whatever the first word of the command is.

**Comment by mwisner** [comment]
So, after some digging I started reviewing our various docker files and entrypoint scripts and tracked this issue down.

The entrypoint script that we had been using that caused the issues above was:

```bash
#!/bin/bash
set -e
cmd="$@"

exec $cmd
```

Updating the script to: 

```bash
#!/usr/bin/env bash

set -o errexit
set -o pipefail

exec "$@"
```

Seems to have resolved this issue.

Specifically, after some digging, it looks like:

```bash
cmd="$@"
exec $cmd
```
Does not work, but:
```bash
exec "$@"
```
Works fine.

**Comment by mwisner** [comment]
Closing this, as I don't think as I don't think this is anything to do with Convox, most likely a human error on my part (knowledge of bash) or something to do with docker itself?

**Comment by mwarkentin** [comment]
Might've just needed to wrap the cmd var in quotes? `exec "$cmd"` or `exec "${cmd}"`
