### ISSUE TITLE
ERROR: error starting container on Covnox run

### ISSUE THREAD

**Issue by jontonsoup** [convox/rack#2456]
Convox run is not working on rack version 
client: 20180116142102
server: 20180112161435 (console.convox.com)

convox run web /bin/sh                                                                                                                                                             

ERROR: error starting container

**Comment by ddollar** [comment]
Please post any relevant logs from `convox rack logs` here

**Comment by jontonsoup** [comment]
Where do we find those logs?

The output on the console is just that unfortunately. I did notice doing a key roll solved the problem.

**Comment by ddollar** [comment]
If you run `convox rack logs` you can get rack logs during the error. If you recreate this please post the logs here and I'll reopen.
