### ISSUE TITLE
Unable to scale service to count=-1

### ISSUE THREAD

**Issue by mwisner** [convox/rack#2457]
Rack Version: 20180112161435
client: 20180116142102
server: 20180112161435 (console.convox.com)
Application: gen 2.

When running:
```bash
convox scale <service> --count=-1
```

It appears to be successful, and even outputs the list of services along with the desired count set at -1.

However after a few seconds it comes back with the original count.

Cloudformation is reporting:

```
12:33:50 UTC-0500 | UPDATE_FAILED | AWS::ECS::Service | ServiceDashboardService | Task count can not be lesser than 0
-- | -- | -- | -- | --
```

Is this way of disabling an application no longer supported?

**Comment by ddollar** [comment]
Gen2 has no `count=-1` because the ALB is at the Rack level so there is nothing to disable.

**Comment by mwisner** [comment]
Okay thanks for the response @ddollar.  I'll try and open up a PR tomorrow on the docs site at least to make a note that this isn't relevant for gen 2:

https://convox.com/docs/scaling/#scaling-down-unused-services

Also, if it's of any worth... Our use case is pretty similar to the one described in the docs... Except we've got a few one-off developer specific services we keep around to help debug issues in various environments, that we only spin up if a developer specifically needs them, and then scales them back down when not in use.

**Comment by mwarkentin** [comment]
Yeah, you can scale those down to 0. -1 was specifically to save money on ELBs which are $18/m - w/ alb it isn’t really applicable anymore (thankfully).
