### ISSUE TITLE
Differents security groups

### ISSUE THREAD

**Issue by betodalas** [convox/rack#2483]
Hello today we have a problem.

All apps on generation 2 are controlled by router balance. but, if do I need configure some apps in different security groups I can't use another security group. We'd like some tool to control the security groups to apps.

thanks

**Comment by ddollar** [comment]
ACM is most likely the solution here. Could you please add some details about why you need a security group for certain apps? I'd be happy to help you come up with a design for configuration so that you can work towards a pull request.
