### ISSUE TITLE
Convox rack ps command: issues with --all and --stats

### ISSUE THREAD

**Issue by mwisner** [convox/rack#2485]
There seems to be a couple of issues with the `convox rack ps` command.

```bash
convox rack ps --help
convox rack ps: list rack processes

Usage:
  convox rack ps [options]

Options:
   --rack value  rack name
   --stats       display process cpu/memory stats
   -a, --all     display all processes including apps
```
```bash
convox rack ps --all
ID            APP           NAME     RELEASE         STARTED       COMMAND
2dee28700220  <RACK>  monitor  20180126132639  13 hours ago  bin/monitor
82513938d247  <RACK>  web      20180126132639  13 hours ago  bin/web
93acc62c290b  <RACK>  web      20180126132639  13 hours ago  bin/web
```
I for sure have a handful of applications and services running on this rack, which are not listed even after adding the --all flag.

```bash
 convox rack ps --stats
ERROR: <RACK> not found
```
And the --stats command doesn't seem to work.

Notes:
convox --version
client: 20180207133713
server: 20180126132639 (console.convox.com)

**Comment by jontonsoup** [comment]
I'm not sure if this is related to this issue or not, but my stats are showing up as zero. Will open a new issue if needs to be tracked separately. 


client: 20180207133713
server: 20180202205308 (console.convox.com

```
ID            NAME  RELEASE      CPU %  MEM           MEM %  STARTED     COMMAND
60756f616ee3  web   RYPTZBVZUUK  0.00%  0.0MB/1500MB  0.00%  2 days ago
a449e2937cdf  web   RYPTZBVZUUK  0.00%  0.0MB/1500MB  0.00%  2 days ago
```

**Comment by mwarkentin** [comment]
Main issue for that (I believe there's some performance issues with it so it was disabled): https://github.com/convox/rack/issues/2263

**Comment by jontonsoup** [comment]
Ah okay— kinda confusing It wasn’t removed

**Comment by ddollar** [comment]
Removing the CLI arg for now
