### ISSUE TITLE
yaml: unmarshal errors with entrypoint / command

### ISSUE THREAD

**Issue by neohunter** [convox/rack#2487]
I'm getting a filed to build error:

```
***** TASK 1/2 [build] for job ....
Authenticating ...
Login Succeeded
Cloning into '/tmp/269816496'...
ERROR: error loading manifest: yaml: unmarshal errors:
  line 5: cannot unmarshal !!seq into string

ERROR: build failed
```

this is my docker-compose.yml

```
version: '2'
services:
  web:
    build: .
    entrypoint: ["bin/docker-entrypoint.sh"]
    command: ["bundle exec rails s -p 3000 -b '0.0.0.0'"]
    volumes:
      - .:/app
    ports:
      - "80:3000"
    restart: always
  ```

docker-compose up works like a charm

**Comment by ddollar** [comment]
`entrypoint:` currently only accepts a string for parsing

https://github.com/convox/rack/blob/master/manifest1/service.go#L27

Take a look at how `command:` is defined with a custom type and unmarshaller if you'd like to submit a PR.

https://github.com/convox/rack/blob/d150dfb03a1af916844bc75e066f4f368c0a3f39/manifest1/yaml.go#L138-L163
