### ISSUE TITLE
convox install gets stuck after 'Created SSL Certificate: RouterApiCertificate'

### ISSUE THREAD

**Issue by swisslala** [convox/rack#2490]
When trying to install a new rack in a new aws account the installation stalls and no other indicators/logs are available.

`     ___    ___     ___   __  __    ___   __  _
    / ___\ / __ \ /  _  \/\ \/\ \  / __ \/\ \/ \
   /\ \__//\ \_\ \/\ \/\ \ \ \_/ |/\ \_\ \/>  </
   \ \____\ \____/\ \_\ \_\ \___/ \ \____//\_/\_\
    \/____/\/___/  \/_/\/_/\/__/   \/___/ \//\/_/

Installing Convox (20180202205308)...
(Private Network Edition)
Reading credentials from file /****.csv
Using AWS Access Key ID: ******
Created SQS Queue: https://sqs.us-east-1.amazonaws.com/****/convox-ci-gitmoney-CloudformationEvents-197J93NPD0C3K
Created CloudWatch Log Group: convox-ci-gitmoney-LogGroup-1X9XDBBL0DOEG
Created SQS Queue: https://sqs.us-east-1.amazonaws.com/****/convox-ci-gitmoney-AccountEvents-1PGR9704TTP7R
Created ECS Cluster: convox-ci-gitmoney-Cluster-1Q179ZSV451HR
Created Routing Table: rtb-f039df8c
Created Security Group: sg-8a146efd
Created Security Group: sg-a80a70df
Created Lambda Function: convox-ci-gitmoney-InstancesLifecycleHandler-DJANKH5MAAJE
Created Lambda Function: convox-ci-gitmoney-CustomTopic-1252CP9ICVZXR
Created NAT Elastic IP: 52.203.50.187
Created NAT Elastic IP: 35.170.93.215
Created Security Group: sg-62136915
Created Security Group: sg-bc0379cb
Created S3 Bucket: convox-ci-gitmoney-logs-c28o59yjztdj
Created S3 Bucket Policy: convox-ci-gitmoney-LogsPolicy-17VZJOYZKRQ1F
Created KMS Key: EncryptionKey
Created DynamoDB Table: convox-ci-gitmoney-releases
Created EFS Filesystem: fs-c7eb048f
Created VPC Subnet: subnet-45ce826a
Created VPC Subnet: subnet-ffcc80d0
Created VPC Subnet: subnet-3834075c
Created VPC Subnet: subnet-12221176
Created VPC Subnet: subnet-9effbfc3
Created VPC Subnet: subnet-7bfbbb26
Created S3 Bucket: convox-ci-gitmoney-settings-3ewfpmxqypry
Created Elastic Load Balancer: convox-ci-gitmoney
Created Hosted Zone: Z3BPOX4M6X81ZZ
Created DynamoDB Table: convox-ci-gitmoney-builds
Created KMS Alias: alias/convox-convox-ci-gitmoney
Created ECS TaskDefinition: ApiBuildTasks
Created ECS TaskDefinition: ApiWebTasks
Created ECS TaskDefinition: ApiMonitorTasks
Created NAT Elastic IP: 52.87.8.40
Created NAT Gateway: nat-03f6cd8dc7efd66e6
Created Routing Table: rtb-dc37d1a0
Created NAT Gateway: nat-07fe57625d376cf37
Created Routing Table: rtb-4b02e437
Created AutoScalingGroup: convox-ci-gitmoney-Instances-HSCRYWJII446
Created Application Load Balancer: Router
Created NAT Gateway: nat-074cdf72db503e7f0
Created Routing Table: rtb-7b33d507
Created SSL Certificate: RouterApiCertificate`

Your only option is to kill it (see below CF log)

15:43:01 UTC-0500 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | convox-ci-gitmoney | The following resource(s) failed to create: [ApiMonitorService, ApiWebService]. . Rollback requested by user.
-- | -- | -- | -- | --
  | 15:42:57 UTC-0500 | CREATE_FAILED | AWS::ECS::Service | ApiWebService | Resource creation cancelled
  | 15:42:54 UTC-0500 | CREATE_FAILED | AWS::ECS::Service | ApiMonitorService | Service arn:aws:ecs:us-east-1:415640329495:service/convox-ci-gitmoney-ApiMonitorService-D4T6WMUVSE06 did not stabilize.
  | 12:48:22 UTC-0500 | CREATE_COMPLETE | AWS::ElasticLoadBalancingV2::Listener | RouterListener443 |  
  | 12:48:22 UTC-0500 | CREATE_IN_PROGRESS | AWS::ElasticLoadBalancingV2::Listener | RouterListener443 | Resource creation Initiated

**Comment by swisslala** [comment]
Ok tried again and poked around. It looks like ECS is not registering the EC2's that are in the ASG. I have 3 running but the cluster shows 0 backing ec2 hosts. This is holding up CF and thus the install.

<img width="1216" alt="screen shot 2018-02-13 at 10 11 59 pm" src="https://user-images.githubusercontent.com/12313656/36186123-f3977eaa-110a-11e8-8ad4-6fc971cb2489.png">
<img width="1386" alt="screen shot 2018-02-13 at 10 09 18 pm" src="https://user-images.githubusercontent.com/12313656/36186124-f59fbba4-110a-11e8-86f3-a9554e22ea8b.png">
<img width="1199" alt="screen shot 2018-02-13 at 10 06 30 pm" src="https://user-images.githubusercontent.com/12313656/36186126-f824d774-110a-11e8-8446-18f4a54e4263.png">
<img width="1186" alt="screen shot 2018-02-13 at 10 06 23 pm" src="https://user-images.githubusercontent.com/12313656/36186127-fa2c4f98-110a-11e8-839c-6f8046f04e8a.png">
<img width="1212" alt="screen shot 2018-02-13 at 10 06 16 pm" src="https://user-images.githubusercontent.com/12313656/36186132-fec72fb4-110a-11e8-9a25-fdc8a2f0ba07.png">

This was on a Terraformed VPC.

**Comment by ddollar** [comment]
This ended up being a problem with the VPC configuration (DNS was not enabled)
