### ISSUE TITLE
Convox detached run doesn't generate logs.

### ISSUE THREAD

**Issue by sjl2** [convox/rack#2493]
## Issue
Run the following in a command line pane:

```sh
$ convox logs 
```

While leaving that running, run the following command in another pane:

```sh
$ convox run <service> 'echo hello' --detach
```

Previously, we were able to see the `hello` printed in the logs. When we switched over to a gen-2 app, no logs are posted. Ideally, we would be able to have the detached process' logs written to where `convox logs` read them.

## Proposed Fix
We investigated why this might be, and narrowed it down to the `generateTaskDefinition2` function in [`rack/provider/aws/processes.go`](https://github.com/convox/rack/blob/d150dfb03a1af916844bc75e066f4f368c0a3f39/provider/aws/processes.go#L922). 

In this function, when the `ContainerDefinition` is [initialized](https://github.com/convox/rack/blob/d150dfb03a1af916844bc75e066f4f368c0a3f39/provider/aws/processes.go#L1004-L1013), it doesn't set the log driver like it's done in the [ECS handler](https://github.com/convox/rack/blob/4ded9633d2b3c6078172456aa17d134f9f73d3b2/provider/aws/lambda/formation/handler/ecs.go#L332-L352) as per the AWS `ContainerDefinition` [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-logconfiguration).

If it's possible for this log driver to be set, it should push logs to the same CloudWatch log group that `convox logs` reads from.

Hope this helps!

**Comment by sjl2** [comment]
@robinjoseph08

**Comment by jontonsoup** [comment]
Also seeing this on Gen1. 

This is a pretty high priority for us. I'd like to make a PR. @ddollar do you have suggestions for how to implement (likewise is there a doc that explains the codebase structure)?

**Comment by mwarkentin** [comment]
We are seeing this on our test racks as well for both gen1 and gen2 apps.

**Comment by ddollar** [comment]
#2519
