### ISSUE TITLE
convox scheduled-task should indicate failure if process  has non 0 exit code

### ISSUE THREAD

**Issue by eladidan** [convox/rack#2494]
Consider this service: 
```
test:
  image: alpine
  labels:
    - convox.cron.myjob=* * * * ? exit 1
```

which produces this log line when executing:
```
2018-02-16T02:33:38Z test:RTHKIVAVORP/cron skew=8655ms command=exit 1 result=success task=arn:aws:ecs:us-west-2:300632719215:task/4a76ab98-dc8b-4dd4-8170-6739faad36a0
```

I would expect the result to be failure when the process fails.

Our motivation is to create a log alert on every scheduled task that fails to complete successfully, but can't find an AWS metric or convox log that would help me do that. I also tried to see whether the lambda that is triggered by the Cloudwatch event fails to execute, but it seems that the lambda only launches the ECS task but does not wait for it, so that's no help.

**Comment by ddollar** [comment]
This success marks if the task was successfully launched. You have a couple of options:

* monitor the ECS task status and check for exit code
* wrap your process in a shell script that captures exit code and prints a log line
