### ISSUE TITLE
url unsafe characters allowed in env var names when setting through pipe and cannot be unset

### ISSUE THREAD

**Issue by bisrael** [convox/rack#2495]
suppose you have the following file:

File `.env`:
```bash
T47sS7d5s5LyHsOidLnf1erxpNdnWAnt0BjYNjEw/3e6sD1dyx389AY=
```

and you pass this to `convox env set` like `cat .env | convox env set`

convox will set this blank environment variable "correctly"

however, when attempting to unset this variable via `convox env unset` a 404 is generated.

`convox env unset "T47sS7d5s5LyHsOidLnf1erxpNdnWAnt0BjYNjEw/3e6sD1dyx389AY"`
`Updating environment... ERROR: response status: 404 404 page not found`

Presumably this is because the route to unset a variable uses the DELETE command at `/apps/{app}/environment/{key}` and the forward slash in the key name creates a route like `/apps/myapp/environment/T47sS7d5s5LyHsOidLnf1erxpNdnWAnt0BjYNjEw/3e6sD1dyx389AY` which the mux router barfs on.

This could be fixed by either url-encoding the key at the client and decoding at the rack, or passing the key in the request body of http call (if mux allows bodies for DELETEs, HTTP does not forbid it).

Additionally, it should be considered to disallow unsafe characters from being set at all.

As it stands right now, there's no way to clear this accidental malformed variable from your app environment.

Thanks,
-Blake

**Comment by bisrael** [comment]
i realized my unset command has quotes on it which aren't needed, but it fails all the same without the quotes.

**Comment by ddollar** [comment]
Would accept a pull request limiting env var names to an acceptable regex. A-Za-z0-9-_ seems like it would do the trick

**Comment by ddollar** [comment]
You can use `convox env edit` to edit the whole env at once.
