### ISSUE TITLE
Load Balance public and private

### ISSUE THREAD

**Issue by betodalas** [convox/rack#2500]
Hello,

After changes from Convox, I saw one problem that will occours with my applications.
I have 10 apps and only two apps needs public access, the rest will be private access, only to network.

I have one idea, if would been created two load balances pointed to all instances, but one load balancer will be private and another load balancer will be public. Each one with your respective SG.

With this change, the communication would be faster, because, inside server, the access will be with private load balance, and outside server will be from public load balancer.

**Comment by mwarkentin** [comment]
That’s how gen 2 works, there’s one public and one private ALB I believe.

**Comment by betodalas** [comment]
on bellow address says:

Generation 2 apps are all served from a single ALB per Rack using hostname-based routing.

And the convox created one load balancer.

**Comment by mwarkentin** [comment]
I think the docs might need to be fixed - just confirmed we have two (internal and external) in our test environment:

![image](https://user-images.githubusercontent.com/67560/36606992-4993d896-1893-11e8-8ba4-929d038a1458.png)

You might need a certain condition to trigger the creation of the second (eg. set an internal param on an app or have a process which is internal only).

**Comment by betodalas** [comment]
Hello,

Ok I understood.

So, this isn't solve my problem. I would need, two differents security groups. 2 apps, would be public access and 8 apps would be access only some ips.

Maybe, if I choice how many balancers I would be have, this would be solve my problem.

Or another way for use 2 SG

**Comment by ddollar** [comment]
This is solved using the `Internal` rack parameter and the `internal:` service attribute in Gen2.

**Comment by betodalas** [comment]
Hello,

I need two public SG, to allow some apps to world ans some apps to some ips. 

thanks

**Comment by ddollar** [comment]
Management of WAF is not currently on the Convox roadmap. If you’d like to submit it as a feature request please do so through a paid Console account.

**Comment by betodalas** [comment]
Can I have two balancers for the same app? For example, the private and public balancer to the same app. When I access this app with dns in server, this will access with private ip, when I access this app  outside the server will access with public ip

**Comment by exalted** [comment]
> Can I have two balancers for the same app? For example, the private and public balancer to the same app. When I access this app with dns in server, this will access with private ip, when I access this app outside the server will access with public ip

I too would be curious to hear more about this… 👍

**Comment by mwarkentin** [comment]
Do you want the same process to be available publicly and privately? Or one service public, another private within the app?

We do the latter pattern and it works fine.

**Comment by exalted** [comment]
I guess, at least in my mind, for any given service (i.e. process), if a request comes from public network (e.g., internet) it should go through the public load balancer, HTTPS, etc.; whilst a request coming from the private/internal network, whether it is from another service of the same app, or a service from another app in the same [convox] rack, should go through the private load balancer, and perhaps no HTTPS, etc.

What do you think?

**Comment by exalted** [comment]
^ Meaning: same service that with different way to reach to it depending on who's calling, at the same time — not one OR the other…
