### ISSUE TITLE
Is there a way to have a docker-compose.yml file for local development, and one for production?

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2518]
I have `convox/postgres` and `convox/redis` in my `docker-compose.yml`, so that I can develop locally with `convox start`. I also set up postgres and redis resources on my production rack. But when I deployed with `convox deploy`, I saw that it also set up containers for postgres and redis, instead of using the RDS and ElasticCache resources.

What is the correct way to do this?

**Comment by mwarkentin** [comment]
@nbroadbent check out the -f option.

**Comment by mwarkentin** [comment]
The other way is to deploy those containers but then scale them to 0 or -1 (which will destroy any related LBs as well).

**Comment by ndbroadbent** [comment]
@mwarkentin Thanks! I'll set up `docker-compose.prod.yml` and set up a script or alias to run `convox deploy -f docker-compose.prod.yml`
