### ISSUE TITLE
Update fails after encrypting EBS volume

### ISSUE THREAD

**Issue by mumumumu** [convox/rack#2521]
I'm trying to update my rack from `20180202205308` to `20180303135343` and getting this failure: 
```
Group did not stabilize. {current/minSize/maxSize} group size = {1/2/2}. 
Failed Scaling Activity: the encrypted flag cannot be specified since device /dev/xvda has a snapshot specified. 
Launching EC2 instance failed.
```
<img width="1605" alt="screen shot 2018-03-06 at 11 09 54 am" src="https://user-images.githubusercontent.com/1393482/37043587-ff44e934-212e-11e8-90fd-9e3d4c85d6cd.png">

Prior to this update I turned on encryption for the EBS volume with this command:
`convox rack params set EncryptEbs=Yes`

It appears to be the same issue as https://github.com/convox/rack/issues/2256 that was fixed in an update.

**Comment by ddollar** [comment]
Should be fixed by #2522
