### ISSUE TITLE
Default CPU and memory are too low - My Rails app fails to boot before timeout

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2525]
I've been trying to get my Rails app to boot for the last couple of hours. The app would always timeout, receive the SIGTERM signal, then restart. I'm using `m4.large` instances. I set `convox.health.interval=120` and `convox.health.timeout=60`, but that was still not enough time.

I just ran `convox scale`, and saw:

```
NAME  DESIRED  RUNNING  CPU  MEMORY
web   1        1        128  256
```

I was finally able to get my app to boot by running `convox scale web --cpu 1024 --memory 2048`. 
I think it was just the memory that was too low. On Heroku, my app is using ~400MB, so I'll probably use `--memory 1024`.

I think 512MB might be a better default, and it would be nice if there was more information about this in the docs. I read the [Scaling](https://convox.com/docs/scaling/) page, but I think it would be nice to add this to the [Getting Started](https://convox.com/docs/getting-started/) page, or one of the earlier pages.

**Comment by ndbroadbent** [comment]
Closing, just wanted to let you know about my experience so far

**Comment by mwarkentin** [comment]
@nbroadbent Just a note that you can encode scaling values in convox.yml so it can be created with the correct values up front.

**Comment by ndbroadbent** [comment]
Thanks @mwarkentin! It's strange, my `docker-compose.yml` used to have:

```
cpu_shares: 512
mem_limit: 1024MB
```

But that still wasn't enough to boot my app before a timeout. Unfortunately I didn't check `convox scale` until after I removed those lines.

**Comment by ndbroadbent** [comment]
OH, also I think I'm still on the gen 1 (`docker-compose.yml`), instead of gen 2 (`convox.yml`).

I read through the "Changes", "convox.yml", and "Creating an Application" docs, but the documentation seemed to be quite sparse, so I wasn't sure if Gen 2 was stable yet.

Is it safe to create a Generation 2 application?
