### ISSUE TITLE
Create redis cluster name

### ISSUE THREAD

**Issue by NilsJPWerner** [convox/rack#2528]
It would be great if `convox resources create redis --name=redis-app` could use the provided name parameter in the cluster name in elasticache. Currently it generates a random string like 'pur159wvqo5juidn' for the name and it's hard to track down the correct cluster.

**Comment by ddollar** [comment]
If you'd like to make a PR you'll need to implement a `Name` parameter here and make sure that the current behavior does not change when the parameter is blank.

https://github.com/convox/rack/blob/master/provider/aws/templates/resource/redis.tmpl

**Comment by NilsJPWerner** [comment]
Thanks @ddollar I'll see what I can do!

**Comment by ddollar** [comment]
Going forward Convox is only going to accept feature requests for Generation 1 from support tickets on paid accounts. Please feel free to send in a PR implementing this and I'd happily merge it.
