### ISSUE TITLE
SSL not yet implemented on generation 2

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2529]
I just created a gen 2 app, and I'm getting this error when trying to use an SSL certificate:

```
$ convox ssl update web:443 acm-************
Updating certificate... ERROR: not yet implemented on generation 2
```

My app needs SSL, so should I just use gen 1 for now?

I could really use the instance packing from gen 2, so that I don't have to run so many servers. I think I'll go back to a single service, and I'll just run web + workers in the same container.

**Comment by ndbroadbent** [comment]
I figured out how to manually set the SSL certificate in the AWS console. I set it on the `produ-Route-***********` application load balancer. Awesome that you can set multiple SSL certs, and it will use SNI to select the correct one based on the host

**Comment by ddollar** [comment]
Set a `domain: foo.example.org` attribute on your service and SSL will automatically be enabled using that domain and an ACM certificate.

You can also use env var expansion for this: `domain: ${HOST}`

**Comment by ndbroadbent** [comment]
Ohhhhh, that's very cool. I didn't realize that SSL was set up automatically when you configure a domain. It makes sense after reading the "domain" section in the [convox.yml docs](https://convox.com/docs/gen2/convox-yml/), but I think that could be a little bit clearer, and maybe added to the [SSL docs](https://convox.com/docs/ssl/) as well.

Thanks for the help!
