### ISSUE TITLE
Deploy seems stuck with service continuously being killed

### ISSUE THREAD

**Issue by ameros** [convox/rack#2530]
When my app boots it needs more memory so after `convox deploy` it stucks with service continuously being killed cause of (which I found in ECS Events):

> OutOfMemoryError: Container killed due to memory usage

I could not find working solution to set memory / scale through `convox.yml` ([this](https://github.com/convox/rack/blob/master/manifest/testdata/full.yml#L30-L31) doesn't seem to work). Not quite sure then if it needs some implementation / fix or just correct setting. I could scale afterwards but this is not what I'm looking for.

**Comment by ddollar** [comment]
Needs implementation of memory and CPU scale to be read from `convox.yml`

**Comment by ddollar** [comment]
This is done now
