### ISSUE TITLE
Add a queue for commands, instead of returning an UPDATE_IN_PROGRESS error

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2532]
Sometimes I want to run multiple `convox scale` commands in a row, but I have to wait for the previous update to finish before I can run another one. It would be nice if convox had a "command queue", so that I could queue up different scaling or release commands, and they would be applied in order.

**Comment by ddollar** [comment]
`convox promote <id> --wait && convox scale ...` etc.

You can also scale in multiple dimensions at once by manipulating the app's parameters. See `convox apps params` and `convox apps params set`
