### ISSUE TITLE
convox env shows env variables not in use

### ISSUE THREAD

**Issue by david-harkness** [convox/rack#2536]
```convox env```
Shows what variables are currently set.
It would be nice, if there was a flag to flag to show what is different compared to active env variables.

When there are hundreds of environmental variables, stare and compare can be annoying.

e.g.
```
$ convox env --diff [ReleaseID |  Default to active]
VAR1=1
<<FOO=2
>>FOO=3
```

Locally, I might right a script that merges output of following two commands with some fancy regex. 
``convox releases info RWJNXUMCITW``
``convox env``

**Comment by ddollar** [comment]
I would accept a pull request that implemented `convox env --release ID`
