### ISSUE TITLE
Detecting app killed due to OOM?

### ISSUE THREAD

**Issue by paulkernfeld** [convox/rack#2538]
I recently noticed that one of my apps restarted unexpectedly. Looking at the metrics in CloudWatch, it appeared to be caused by an OOM error. Is there an easy way to set up an alarm for this situation? As an analogy, with a Heroku app I would set up a Papertrail alert that was triggered by R14 or R15 errors.

A couple ideas that I have had:
- Set up a CloudWatch alarm for when the memory usage of any app goes above 80%. This seems to be the most straightforward option. One disadvantage of this is that I would need to remember to add a new CloudWatch alert for each new app.
- Use Datadog as suggested in [this blog post](https://www.datadoghq.com/blog/monitor-aws-ecs-convox-integration/). Although there is a per-host fee, it should be pretty easy to set up a memory reservation alert across all apps.
- Listen to a CloudWatch event stream for any relevant events. I haven't worked with CloudWatch Events before, so I'm not even sure whether such an event exists.

**Comment by jontonsoup** [comment]
@paulkernfeld I noticed that I stopped seeing OOM in the logs recently. Did you see this in your logs?

**Comment by ddollar** [comment]
This should be coming back to the app logs in #2541
