### ISSUE TITLE
Upgrade AMI for ECS to the latest

### ISSUE THREAD

**Issue by alex** [convox/rack#254]
https://aws.amazon.com/about-aws/whats-new/2016/01/amazon-ec2-container-service-supports-docker-1-9/

**Comment by nzoschke** [comment]
Thanks for the request. This was updated in https://github.com/convox/rack/commit/ec656701123e710c488f01ad132901e630484c2f#diff-8790f93fd844ac06dd6f33c547fa238d

Issue a `convox rack update` to roll it out to your cluster.
