### ISSUE TITLE
Switch to the overlay2 storage driver for Docker, or add a rack param

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2543]
I would like to use the `overlay2` storage driver so that my builds are faster.  (I was talking about this in another issue: https://github.com/convox/rack/issues/2531#issuecomment-371921184)

[Also see the discussion about this for Kubernetes](https://github.com/kubernetes/minikube/issues/1380#issuecomment-338231991). Docker (and Kubernetes) have `overlay2` as the default driver.

It would be great if the launch configuration user data set up the overlay2 driver, like this: https://github.com/aws/amazon-ecs-agent/issues/746#issuecomment-312773776

Or maybe you could add a rack param like `DockerStorageDriver`.

**Comment by ddollar** [comment]
I'd accept a PR adding that rack parameter.

**Comment by ndbroadbent** [comment]
I just set up `overlay2` via the `InstanceBuildCommand`, and my builds are so much faster now. The `ARG` steps are almost instant, and my builds only take `4m 4.177s`, down from `16m 11.575s`.

Here's what I ran to set up `overlay2` on my instances:

```
convox rack params set InstanceBootCommand="dmsetup remove_all; vgremove --force docker; mkfs -t ext4 -L docker -i 4096 -F /dev/xvdcz; rm -rf /var/lib/docker/*; mkdir /var/lib/docker/overlay2; mount /dev/xvdcz /var/lib/docker/overlay2; echo 'DOCKER_STORAGE_OPTIONS=\"--storage-driver=overlay2\"' > /etc/sysconfig/docker-storage; grep -v "dm\.basesize" /etc/sysconfig/docker > /etc/sysconfig/docker-tmp; mv -f /etc/sysconfig/docker-tmp /etc/sysconfig/docker; rm -rf /var/lib/ecs/data/* /var/cache/ecs/*"
```

Here's my initial attempt at adding an "Overlay2" rack param: https://github.com/FormAPI/rack/commit/f4ec3da489ccdf2a1f4f793aa7ee367853fb2fe3

It probably needs a lot of work, and I'm not sure how to run the tests. Haha I tried running `ci/tests/example-app rails`, and I got a bit freaked out when it started setting up a new app on my production rack.

**Comment by ffjia** [comment]
@ndbroadbent how long it'll take? The whole process of `overlay2` setup? Would it be easier to do that with customized AMI?

**Comment by ndbroadbent** [comment]
Hi @ffjia, I haven’t measured how much time this takes, but it should only add about 5-10 seconds to the boot time. I haven’t noticed any significant delays when starting a new instance.

A customized AMI would be great. I actually did create a custom AMI after running these commands, but I didn’t know how to configure convox to use it.

**Comment by ffjia** [comment]
Well, 5-10 seconds extra boot time should be fine. You could use Rack parameter `Ami` to set customized AMI.

**Comment by ndbroadbent** [comment]
Oh thanks! For some reason I didn’t see the `Ami` parameter. But I think I’ll continue using the official ECS AMI with my custom boot command, since it doesn’t add much time.

**Comment by advance512** [comment]
@ndbroadbent 
did you find a good solution for overlay2 support? I am a tad worried about the `InstanceBootCommand`.

**Comment by ndbroadbent** [comment]
@advance512  I'm still using the `InstanceBootCommand` and it's working great for my builds, but I've heard some reports of people running out of disk space when using `overlay2`. I'm afraid I haven't looked into that yet, so YMMV

**Comment by advance512** [comment]
Yes, I ran into the same issue and had to drop the InstanceBootCommand. Too
bad, it made our builds 10x faster.
ᐧ

**Comment by ndbroadbent** [comment]
@ddollar I was wondering if you might have a moment to help me figure out the problem with this `InstanceBootCommand`:

```
convox rack params set InstanceBootCommand="/etc/init.d/docker stop; \
dmsetup remove_all; \
vgremove --force docker; \
mkfs -t ext4 -L docker -i 4096 -F /dev/xvdcz; \
rm -rf /var/lib/docker/*; \
mkdir /var/lib/docker/overlay2; \
mount /dev/xvdcz /var/lib/docker/overlay2; \
echo 'DOCKER_STORAGE_OPTIONS=\"--storage-driver=overlay2\"' > /etc/sysconfig/docker-storage; \
grep -v dm\.basesize /etc/sysconfig/docker > /etc/sysconfig/docker-tmp; \
mv -f /etc/sysconfig/docker-tmp /etc/sysconfig/docker; \
/etc/init.d/docker start; \
rm -rf /var/lib/ecs/data/* /var/cache/ecs/*; \
start ecs
```

I've been hearing lots of reports of people running out of disk space. Here's some more info I received from someone:

> When I ssh to the build instance, I can see that the overlay2 folder has around 7G of data:

```
# sudo du -sh overlay2
7.1G    overlay2
```

> My device is having 1000G:

```
blockdev --getsize64 /dev/xvdcz
1073741824000
```

> When I cd in overlay2 and do something like:

```
$ sudo fallocate -l 100G gentoo_root.img
fallocate: gentoo_root.img: fallocate failed: No space left on device
```

> So for some reason overlay2 will blocking all writing after around 7.1G

```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.6G   56K  7.6G   1% /dev
tmpfs           7.6G     0  7.6G   0% /dev/shm
/dev/nvme0n1p1  7.8G  7.8G     0 100% /
overlay         7.8G  7.8G     0 100% /var/lib/docker/overlay2/20d22be3427b4c8f31269b517f36548263bd67d744786af4cfbee91368985212/merged
shm              64M     0   64M   0% /var/lib/docker/containers/09cab313662a4fc7b10de88bc9ac3ea8f8e2a970a9ac6892b39558d8a278c1b7/shm
```

> Look like ovelay is only using 7.8G instead of the whole device storage.

---------------------------------

Can you see if I'm missing any configuration settings to set the correct size? Thanks!

**Comment by ndbroadbent** [comment]
This looks like it could be the issue: https://trello.com/c/KBGQgEqL/1052-1-overlay2-filesystem-size-is-40-by-default-and-it-wont-grow

`overlay2` will only use 40% of the available space by default, so you have to set `CONTAINER_ROOT_LV_SIZE`. Was struggling to figure out where to set it, but [looking at this file](https://github.com/projectatomic/container-storage-setup/blob/df26a0d994b9aee6dbdcdd1755377db7d0d31aa5/container-storage-setup.conf), I think it goes in `/etc/sysconfig/docker-storage-setup`.

-----------------------

@advance512 I haven't been able to reproduce the "running out of disk space" error, so would be grateful if you could help me test the new `InstanceBootCommand` with `CONTAINER_ROOT_LV_SIZE`:

```
convox rack params set InstanceBootCommand="/etc/init.d/docker stop; \
dmsetup remove_all; \
vgremove --force docker; \
mkfs -t ext4 -L docker -i 4096 -F /dev/xvdcz; \
rm -rf /var/lib/docker/*; \
mkdir /var/lib/docker/overlay2; \
mount /dev/xvdcz /var/lib/docker/overlay2; \
echo 'DOCKER_STORAGE_OPTIONS=\"--storage-driver=overlay2\"' > /etc/sysconfig/docker-storage; \
echo 'CONTAINER_ROOT_LV_SIZE=100%FREE' >> /etc/sysconfig/docker-storage-setup; \
grep -v dm\.basesize /etc/sysconfig/docker > /etc/sysconfig/docker-tmp; \
mv -f /etc/sysconfig/docker-tmp /etc/sysconfig/docker; \
/etc/init.d/docker start; \
rm -rf /var/lib/ecs/data/* /var/cache/ecs/*; \
start ecs
```

I've tested this on my staging servers and everything is still working fine for me. But please let me know if that solves your issue!

**Comment by phuongnd08** [comment]
I used this:
```
/etc/init.d/docker stop; dmsetup remove_all; vgremove --force docker; mkfs -t ext4 -L docker -i 4096 -F /dev/xvdcz; mkdir /var/lib/docker-images; mount /dev/xvdcz /var/lib/docker-images; echo 'DOCKER_STORAGE_OPTIONS="--storage-driver=overlay2 -g /var/lib/docker-images"' > /etc/sysconfig/docker-storage; grep -v dm\.basesize /etc/sysconfig/docker > /etc/sysconfig/docker-tmp; mv -f /etc/sysconfig/docker-tmp /etc/sysconfig/docker; /etc/init.d/docker start; rm -rf /var/lib/ecs/data/* /var/cache/ecs/*; start ecs
```

The idea is to change `DOCKER_STORAGE_OPTIONS` to `--storage-driver=overlay2 -g /var/lib/docker-images` so it use a different path than the default path which is on the root device. Also there is another params called `RootSize` which I think we can use without the patch of DOCKER_STORAGE_OPTIONS but I didn't have the time to try that yet.

**Comment by ndbroadbent** [comment]
For anyone else who sees this, here's the command you can run to set the `InstanceBootCommand` param:

```
convox rack params set InstanceBootCommand="/etc/init.d/docker stop; dmsetup remove_all; vgremove --force docker; mkfs -t ext4 -L docker -i 4096 -F /dev/xvdcz; mkdir /var/lib/docker-images; mount /dev/xvdcz /var/lib/docker-images; echo 'DOCKER_STORAGE_OPTIONS=\"--storage-driver=overlay2 -g /var/lib/docker-images\"' > /etc/sysconfig/docker-storage; grep -v dm\.basesize /etc/sysconfig/docker > /etc/sysconfig/docker-tmp; mv -f /etc/sysconfig/docker-tmp /etc/sysconfig/docker; /etc/init.d/docker start; rm -rf /var/lib/ecs/data/* /var/cache/ecs/*; start ecs"
```

**Comment by ddollar** [comment]
Just a note that I do not recommend trying to use the overlay2 driver in this way. You'll likely run into issues with disk utilization as others have seen. Once the official ECS AMI moves to Amazon Linux 2 it will likely use the overlay2 driver natively.

**Comment by ndbroadbent** [comment]
Woohoo, build instances are now using overlay2: https://github.com/convox/rack/pull/2951

Thanks @ddollar!
