### ISSUE TITLE
Cloudformation: json -> yaml?

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#2553]
Just wondering if you've pondered migrating from JSON to YML for the cloudformation templates? I came across this handy tool from aws-labs: https://github.com/awslabs/aws-cfn-template-flip

It also supports switching from `Join` to `Sub` for improved readability in places:
![](https://s3.amazonaws.com/mwarkentin-snaps/Kaleidoscope_2018-03-15_15-41-02.png)

This would mainly be an improvement for readability and easier for new people to understand the internals of convox.

I've created a gist showing both clean (`Join` -> `Sub`) and dirty versions of what the tool gave me for the `rack.json` template: https://gist.github.com/mwarkentin/4c5748b585d63a74080df98daac05313

If you're interested I'd be happy to help by opening a PR with these changes (some of the cloudformation files are templates, so would need to dig in a bit more to see how to migrate those).

**Comment by ddollar** [comment]
Going to go ahead and close this. I poked around a bit and YAML is much more finicky around things like indentation when it comes to building CloudFormation templates using a templating language.
