### ISSUE TITLE
Feature Request: support docker-compose version 3

### ISSUE THREAD

**Issue by buckle2000** [convox/rack#2555]
```
> convox deploy
Deploying echo-server
Creating tarball... OK
Uploading:  1.52 MiB / 1.52 MiB [========================] 100.01% 22s
Starting build... OK
Authenticating ?????: WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
ERROR: unknown manifest version: 3
ERROR: echo-server build failed
```
Now Docker Compose config file has version 3. Can convox support version 3?

**Comment by ddollar** [comment]
This could potentially be submitted as a PR but seeing as future development work is concentrated on Generation 2 which does not use the `docker-compose.yml` this will likely not come from the Convox team itself.
