### ISSUE TITLE
Memory HardLimit/SoftLimit

### ISSUE THREAD

**Issue by jlchenwenbo** [convox/rack#2570]
Hi,

When I issue command
$ convox scale web --memory=128

I see in the task definition, is shows hardlimit is 128MB. How can I just specify softlimit but no hardlimit? Since hardlimit will shut down container once reach up to that limit, but softlimit more flexible.

**Comment by ddollar** [comment]
Not currently possible. Many things such as the ECS scheduler and Convox's autoscaler use this memory size as a calculation for how many instances are needed so it's best to define the size that you will need.
