### ISSUE TITLE
[GEN2] generation 2 documents and scale key word in convox.yml

### ISSUE THREAD

**Issue by jlchenwenbo** [convox/rack#2571]
I have two confuses:
1. Is generation 2 is still supported? I couldn't find gen2 reference at https://convox.com/docs/overview/
2. Scale key word is actually is not working in my rails project, I have set up like:
               scale:
                   count: 2
                   memory: 1024
                   cpu: 512

**Comment by mwarkentin** [comment]
Gen2 is now the default for new apps that are created - I believe the docs have been updated to reflect that. There's separate sections for legacy gen1 references.

**Comment by jlchenwenbo** [comment]
Thanks for the answer. Any comments on "scale" key word?

**Comment by mwarkentin** [comment]
Not sure about scale, I think that’s supposed to work. 😊
