### ISSUE TITLE
Unable to run local router on OSX High Sierra

### ISSUE THREAD

**Issue by anicholson** [convox/rack#2575]
When I run `sudo convox rack install local`, everything appears to be okay:

```
pulling: convox/rack:20180328031038
installing: /Library/LaunchDaemons/convox.router.plist
installing: /Library/LaunchDaemons/convox.rack.plist
```

However, looking at the logs, `convox.router.log` is full of the following:
```
ERROR: user: Current not implemented on darwin/amd64
```

which suggests a similar issue to #999.

System-related info:

* OSX: High Sierra 1013.3
* CLI version: 20180328031038
* Docker4mac version: 8.03.0-ce-mac59 (23608)

**Comment by ddollar** [comment]
Try running `convox update` and then `sudo launchctl stop convox.router` (it will be automatically restarted)

**Comment by ddollar** [comment]
Comment here if the issue is still happening and I'll reopen

**Comment by jsierles** [comment]
This is still happening for me.
