### ISSUE TITLE
Can the rack connect to different branches

### ISSUE THREAD

**Issue by grandmore** [convox/rack#262]
We use a production and master branch in Github.

The Production branch is used when developing and testing before releasing to the master branch which is used for live deployment.

Can the Rack be updated to choose which branch gets triggered, currently master is automatically selected.

Then we would create 2 separate racks, one for testing and production deployment and one for master and live deployment.

**Comment by nzoschke** [comment]
I can confirm that we currently only build from master. Configuring another branch totally makes sense. I've opened an issue on the internal project that coordinates GitHub hooks, and will update this issue when that change lands.

**Comment by nzoschke** [comment]
This is working on https://console.convox.com/. Give it a try there and see if it solves your problem.

It's also available on the builds API. You can include a Git URL with a branch name (i.e. http://github.com/convox/rack#my-branch) and it'll clone and check out that branch before building.

http://convox.github.io/api/#!/default/post_apps_app_builds

The URL parameter is not yet wired up to the CLI, but that should be an easy fix: https://github.com/convox/rack/issues/440

I'm closing this in favor of the existing solutions and #440. Thanks!
