### ISSUE TITLE
GEN2 seems that does not support Dockerfile Overwrite ARG values?

### ISSUE THREAD

**Issue by kevinhuang12345678** [convox/rack#2631]
GEN2 seems that does not support <a href="https://stackoverflow.com/questions/45157895/dockerfile-overwrite-arg-values">Dockerfile Overwrite ARG values</a>

**Comment by ddollar** [comment]
Gen2 does support build args.

**Comment by kevinhuang12345678** [comment]
it supports build args in Dockerfile.

1. how about in convox.xml?

services:
  product-service:
    build:
      path: .
      manifest: ./docker/alpine/Dockerfile
      args:
         myArg1-xxx
         myArg2=yyy 
...

2. how about overwrite ARG values in parent Dockerfile?

Thanks.

Regards,
Kevin
