### ISSUE TITLE
Panic inside create build index call

### ISSUE THREAD

**Issue by thieman** [convox/rack#2642]
Got a poorly-formatted dump from rack logs: https://gist.github.com/thieman/b9f71fcdea79443608cd82ea7bc3f8fe

Just posting this for now, will try to look into a fix.

**Comment by thieman** [comment]
This certainly makes it seem like LastStatus should always be set to _something_: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_life_cycle.html

**Comment by thieman** [comment]
I'm hoping to be able to get more detailed logs on this issue soon, as we're seeing it quite a bit. I think this is a relatively new issue, and I somewhat suspect my previous PR may be causing it: https://github.com/convox/rack/pull/2601

No concrete evidence, just a hunch.

**Comment by thieman** [comment]
Ah, am I hitting some sort of scoping problem here?

```
func (p *AWSProvider) describeTask(arn string) (*ecs.Task, error) {
	var err error
	for attempt := 0; attempt < 3; attempt++ {
		task, err := p.describeTaskInner(arn)
		if err != nil {
			time.Sleep((1 << uint(attempt)) * time.Second)
		} else {
			return task, nil
		}
	}
	return nil, err
}
```

If `describeTaskInner` returns an error, then sets `err` to that error, does that assignment not escape the block? If so that would cause this bug, as it'd return `nil, nil` instead of `nil, error`.

@ddollar ping since you've got way more Go knowledge than me

**Comment by ddollar** [comment]
I believe this issue is no longer valid. Please comment if it's still affecting you.
