### ISSUE TITLE
Request: Add documentation for cost estimate and AWS resources consumed by a rack

### ISSUE THREAD

**Issue by xtagon** [convox/rack#2659]
Hi,

Previously, there was a page on the website documentation describing an estimate for what it would cost to run a rack on AWS. That's exactly what I'm trying to determine right now, but the page is missing. I'd hate to have to run a rack for a day just to know what it actually uses.

So far I have learned that Rack now uses one ALB instead of an ELB per app. What other AWS resources does it provision and use, and what is the expected monthly cost for running a minimal rack 24/7 for a month?

I know it completely depends on scaling, but I'm just asking for a general idea.

**Comment by ddollar** [comment]
This is highly variable and never accurate for long. Perhaps it could be generated somehow? I'd accept a PR that attempted to do this.

**Comment by xtagon** [comment]
Does Rack use a Cloudformation template before generating resources? If so, perhaps we could use something like this: https://docs.aws.amazon.com/cli/latest/reference/cloudformation/estimate-template-cost.html

**Comment by ddollar** [comment]
Yes it does. The rack and each app are represented by CloudFormation stacks.

**Comment by xtagon** [comment]
Good to know, thank you. If I can figure out how to do it I'll open a PR.
