### ISSUE TITLE
WebSockets Authentication

### ISSUE THREAD

**Issue by b3njamin** [convox/rack#266]
Currently web sockets routes in the API, are authenticated by sending headers with the request Even whilst part of the spec isn't supported by browser clients. This is the best way to authenticate WS? Is there a better way?

**Comment by nzoschke** [comment]
Thanks for your security question.

This is a good guide on websocket security: https://devcenter.heroku.com/articles/websocket-security

Right now the convox golang client and CLI is the only consumer of these APIs, so basic auth headers are fine.

If a browser UI needs to consume these APIs, perhaps we will need to update the auth methods.
