### ISSUE TITLE
Fail to delete apps with roles attached

### ISSUE THREAD

**Issue by devbuscandomeuape** [convox/rack#2672]
Hello,

This problem ocourred sometimes. When we attached new polices in apps roles and we need delete these apps, the delete fails. It's occours because this app has a policy attached manually.

The error on Cloudformation is:

```

  | The following resource(s) failed to delete: [ServiceRole].
-- | --
  | 21:16:48 UTC-0300 | DELETE_FAILED | AWS::IAM::Role | ServiceRole | Cannot delete entity, must delete policies first
```

**Comment by ddollar** [comment]
If you modify a CloudFormation-created resource you put the stack in an undefined state.

Use the `IamPolicy` attribute on gen2 apps.
