### ISSUE TITLE
Support for tmpfs

### ISSUE THREAD

**Issue by stefanomasini** [convox/rack#2680]
Please implement support for the following docker feature: https://docs.docker.com/storage/tmpfs/

Being able to create a `tmpfs` mount of a given size allows the application to make use of a fast in-memory file system. This can be beneficial to speed up the creation and manipulation of temporary files.

When such an option is not available, the only alternative is to make use of huge and expensive storage space just to have enough IOPS to meet the application requirements.

**Comment by ddollar** [comment]
I would accept this as a PR given a sufficiently simple design. Perhaps the best place to start would be a suggested convox.yml layout?
