### ISSUE TITLE
Timers in Gen2 apps ignore convox app env - used to work in Gen 1

### ISSUE THREAD

**Issue by swisslala** [convox/rack#2687]
I ported over my Gen 1 apps into Gen 2, havign an app in convox where I set aws creds and default region etc... I then use timers to schedule various cron tasks against aws. 

The timers fire nicely but the convox env is blank!

Rack updated to : 20180521013812

Here is my convox.yml

services:
  awscli:
    image: myorg/awscli:1.0.3
    command: sleep 3600
    scale: 0
  timers:
    wojo-test:
     schedule: 46 22 * * ? *
     command: env
     service: awscli

As you can see form the screen shots I define aws key and region yes when the timer run s the convox env is "" also these settings are not present in the container.

![screen shot 2018-05-22 at 6 47 12 pm](https://user-images.githubusercontent.com/12313656/40394506-c1b9a866-5df1-11e8-8b85-5e1dfa5571e4.png)
![screen shot 2018-05-22 at 6 41 38 pm](https://user-images.githubusercontent.com/12313656/40394507-c1c55242-5df1-11e8-82f0-057a76ea8f07.png)

**Comment by ddollar** [comment]
All Gen2 services need an `environment:` section to act as a whitelist from the master app env.

**Comment by swisslala** [comment]
@ddollar consider updating the docs with a sample to be more explicit - little details like this tend to get lost as your read through...

**Comment by ddollar** [comment]
Do you have a suggestion on how they could be made more explicit?

**Comment by swisslala** [comment]
Sure thing, 

How about giving a sample env and yml file and highlighting the env vars that will be used and the ones that will be ignored. Also using the "*" to inherit all of the env etc... Its little things like this that would help the product since it becomes a search through source code, convox channel and trial and error.  

PS. Sample screen shots are a gift :)

Features are coming in fast and honestly the docs were always lagging behind... Convox is a mature product and docs could be as well.
