### ISSUE TITLE
Allow re-processing of formation template before submitting to CloudFormation

### ISSUE THREAD

**Issue by phuongnd08** [convox/rack#2697]
Since it would take times for new changes to be implemented in convox (for example path based routing), I would suggest to make it flexible for someone who know what to do to re-process the formation before submitting to CloudFormation

Perhaps something like: 
```
services:
   web:
      - command: ...
      - cf-processor: bin/cf-web-processor
```
This way we can interpolate the cf formation, leverage the existing components created by convox and optionally add our own tweaks. This is not for everyone but obviously soon some will grow out of current convox features, so let them modify the formation instead. Some can use this room to experiment various improvement with convox, that idea can then be tested with time and then can eventually come back to the core implementation of convox had it prove to be useful.

**Comment by phuongnd08** [comment]
The processor can be any executable that accept input from STDIN (until EOF) and then spit the result to STDOUT. Input and output should use some format like JSON that allows flexibility of data structure.
I would personally donate 1500$ for any one who can make this feature into convox.

**Comment by ddollar** [comment]
I can't see a way to do this without getting incredibly complex. The existing templates are subject to change at any time and I wouldn't want to have the template format be the contract with the app.
