### ISSUE TITLE
Respect --build-instance "" for convox install

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2699]
I would like to install a rack with no build instance, but the rack param `BuildInstance` is being set to `t2.small` by default. It's not possible to override this with `convox install --build-instance ""`.

I noticed `install.go` has:

```
			cli.StringFlag{
				Name:   "build-instance",
				Value:  "",
				Usage:  "instance type for a dedicated build cluster",
				EnvVar: "RACK_BUILD_INSTANCE",
			},

...

			cli.StringFlag{
				Name:  "instance-type",
				Value: "t2.small",
				Usage: "type of instances in the rack",
			},
```

And in `rack.json`:

```
    "BuildInstance": {
      "Type": "String",
      "Description": "Instance type for a dedicated build cluster",
      "Default": "t2.small"
    },

...

    "InstanceType": {
      "Default": "t2.small",
      "Description": "The type of the instances in the runtime cluster",
      "Type": "String"
    },
```

Maybe the default value could only be set in `install.go` for build-instance, instead of `rack.json`?

**Comment by ndbroadbent** [comment]
Opened a PR: #2700 

(But not sure if that's the best solution.)

**Comment by ddollar** [comment]
Closing this issue but as discussed in #2700 would accept a PR adding `--no-build-instance` to the install CLI.
