### ISSUE TITLE
Environment variables not set in ECS task on first deploy

### ISSUE THREAD

**Issue by alexbilbie** [convox/rack#271]
I have a `docker-compose.yml` file similar to the one below:

```yaml
main:
  build: .
  environment:
    - FOO
    - BAR
```

and an accompanying `.env` file which includes the values for each of these keys:

```
FOO=foo
BAR=bar
```

When I first run `convox deploy` the task created in ECS does not include any of the environment key-value pairs listed.

Instead I have to run a separate `convox env set FOO=foo BAR=bar` command which creates an updated task definition.

Then I have to run `convox release promote XYZ` (based on output of previous command) to get a functioning container.

This is very counterintuitive.

**Comment by grandmore** [comment]
I find this area very confusing as well. 

Why do we have the variables in a ```.var``` file? I would assume the environment variables would be private, in that you don't want to push them to a repository.

**Comment by alexbilbie** [comment]
I have a different .env file for each environment (dev/staging/production)
which are encrypted so they can be stored in git. Then I've got a makefile
which decrypts them before pushing the vars to Convox

**Comment by nzoschke** [comment]
Thanks for your question.

The `convox start` .env file behavior is very much influenced by `foreman`, and documented here: http://convox.com/docs/environment-variables/

If there is a way that the documentation could be improved, please re-open an issue on https://github.com/convox/convox.github.io

As the docs say, .env is for local development secrets only, and should be in .gitignore and not checked into source control

If you have environment values that are not secret and you want to be default both in development and production on `convox app create`, set the k=v pairs in docker-compose.yml:

```
main:
  build: .
  environment:
    - FOO=foo
    - BAR=bar
```

There have been some interesting ideas about using the convox environment API for development secrets too, however the simplicity of a .env file if favored for now.
