### ISSUE TITLE
Convox builds export/import are no longer working

### ISSUE THREAD

**Issue by swisslala** [convox/rack#2711]
convox builds export xxxxxxx -a myapp --rack myrack | convox builds import -a myapp --rack myrack
Uploading:  14.99 KiB / ? [-----------=--------------------------] 3s
Importing build... OK
ERROR: Request failed

This is a Gen 1 app
 convox -v
client: 20180521013812
server: 20180507173314 (console.convox.com)

**Comment by ddollar** [comment]
This should definitely be working. Please try the latest server and client versions if you are still having issues.
