### ISSUE TITLE
`convox ps -a` lists all running processes w/ app and image info

### ISSUE THREAD

**Issue by grandmore** [convox/rack#272]
'convox ps' only outputs the process, when ideally it should also output the images the processes belong to as otherwise it is very difficult to know what your looking at.

If I have two apps called app1 and app2 and their docker-compose.yml files are like this

```
main:
  build: .
  ports:
    - 80:8080
  command: app
```

Then convox ps would output something time this:

```
ID                      NAME  RELEASE              SIZE  STARTED    COMMAND               
50bca8de5977  main    RMKUUHCWNBH  256   1 hour ago  /go/bin/init sh -c app
eb57e4b8ab2c  main    RMKUUHCWNBH  256   1 hour ago  /go/bin/init sh -c app
```

When it's better to display the processes like this:

```
ID                      NAME           RELEASE              SIZE  STARTED    COMMAND               
50bca8de5977  app1:main    RMKUUHCWNBH  256   1 hour ago  /go/bin/init sh -c app
eb57e4b8ab2c  app2:main    RMKUUHCWNBH  256   1 hour ago  /go/bin/init sh -c app
```

or reversed

```
ID                      NAME           RELEASE              SIZE  STARTED    COMMAND               
50bca8de5977  main:app1    RMKUUHCWNBH  256   1 hour ago  /go/bin/init sh -c app
eb57e4b8ab2c  main:app2    RMKUUHCWNBH  256   1 hour ago  /go/bin/init sh -c app
```

**Comment by nzoschke** [comment]
Thanks for your suggestion, but I'd like some clarification.

`convox ps` displays all the processes for a single app. The NAME field comes from the label in the docker-compose.yml file. So in your first output you're looking at the result of scaling the main process to 2 on a single app.

```
$ cd httpd

$ cat docker-compose.yml
web:
  image: httpd
  ports:
    - 80:80
main:
  image: httpd
  ports:
    - 81:80

$ convox ps --app httpd
ID            NAME  RELEASE      SIZE  STARTED         COMMAND         
2c088bc95781  main  RFYXKXICXRT  256   56 seconds ago  httpd-foreground
68bc25a6e27d  web   RFYXKXICXRT  256   1 minute ago    httpd-foreground
```

I do see that docker includes some image information that helps orient you to what app that is running in output... Is your request along these lines?

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS                                     NAMES
3c126ce51ae5        httpd/web           "httpd-foreground"   3 seconds ago       Up 2 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:443->80/tcp   httpd-web
46ca003893e4        httpd/main          "httpd-foreground"   4 seconds ago       Up 3 seconds        0.0.0.0:81->80/tcp                        httpd-main
```

**Comment by grandmore** [comment]
I was thinking more of ALL processes that are running, rather than the directory I am in and inferring the app.

I assume it would actually be ```convox ps -a``` to show all processes (if it was not already being used for the application link ```convo ps - a app1```)

Bet certainly having the image info as part of it makes it very clear what I'm seeing.

**Comment by nzoschke** [comment]
I get this suggestion now, and have heard it from plenty of other users. It would be great to have one API / command  that shows everything that's running in the cluster.

**Comment by nzoschke** [comment]
My first thought is that the `convox instances` API could include info about all the containers running on every instance too.  Then `convox instances` could still show a per-instance overview, but `convox ps -a` could use the same API/data but show all the app containers.

**Comment by nzoschke** [comment]
I keep finding the need for this myself. Here's a horrible bash script that does it...

```bash
convox api get /apps | jq -r '.[].name' | xargs -L1 -I{} sh -c "echo {}; convox api get /apps/{}/formation | jq -r '.[] | \"\(.name) x \(.memory) x \(.count)\"'" | column -t -s' '
httpd
web        x  256  x  1
httpd-old
web        x  256  x  1
rails
web        x 1025  x 2
```

**Comment by ddollar** [comment]
`convox rack ps` to list the processes of the rack itself

`convox rack ps -a` to list all processes on the cluster

**Comment by jessepollak** [comment]
@ddollar `convox rack ps` works, but `convox rack ps -a` doesn't -- is it supposed to right now or is this still open?

**Comment by mwarkentin** [comment]
@jessepollak This is still open, afaik.

**Comment by ddollar** [comment]
This now exists
