### ISSUE TITLE
'max depth exceeded'

### ISSUE THREAD

**Issue by fugufish** [convox/rack#2728]
I am receiving `max depth exceeded` during build. It builds cleanly locally, and builds cleanly on a separate convox cluster, and even builds cleanly on the same cluster that is erroring out at random. It eventually resolves itself and works for a few builds then stops working again. It should be noted that the docker file does not change at all during these builds. 

Dockerfile

```
FROM capshare/web

COPY config/convox/nginx.conf /etc/nginx/nginx.conf
COPY config/convox/Allura-Regular.ttf /usr/share/fonts/truetype/Allura-Regular.ttf
RUN chmod 0755 /usr/share/fonts/truetype/Allura-Regular.ttf
RUN fc-cache -f -v

WORKDIR /app

COPY Gemfile      ./
COPY Gemfile.lock .
RUN bundle install --deployment --without development test
RUN npm install yarn -g
COPY package.json ./
RUN yarn install

# copy just the files needed for assets:precompile

COPY . .
COPY config/database.example config/database.yml
RUN bundle exec rake assets:precompile
```

It should be also noted that capshare/web is a squashed build and only has a single layer.

**Comment by fugufish** [comment]
makes sense, is there a "convox way" of logging into a build instance or do i have do that manually?

**Comment by mwarkentin** [comment]
convox instances ssh should work but you might need to get the instance ID from the EC2 console.

**Comment by mwarkentin** [comment]
Not really sorry - not clear to me what would be causing docker on that instance to end up in that state..

**Comment by mwarkentin** [comment]
In any case, I think this is more docker than convox related - unless the idea was to have convox configure a cron to do docker pruning for you.

**Comment by fugufish** [comment]
I may do that last barring any better answer. It could be how we are doing CI. Thanks for the help!
