### ISSUE TITLE
Idea: Mark an application as staging (Task load order)

### ISSUE THREAD

**Issue by matthewford** [convox/rack#273]
I've noticed during a rolling update ECS tried to rebalance and fit all processes onto the remaining 2 servers. 

It would be nice if we can mark some apps at staging (meaning they can be safely killed/stopped) without trying to rebalance. Not sure if possible.

**Comment by matthewford** [comment]
As an example, some processes e,g, staging are not as important and can be spun up once the cluster is in a happy state. While others -prod ideally should be back up and running ASAP.

<img width="1169" alt="screen shot 2016-01-25 at 12 57 27 pm" src="https://cloud.githubusercontent.com/assets/215/12551556/3ce0c5d2-c363-11e5-9c71-086ca333acce.png">

**Comment by matthewford** [comment]
:thought_balloon: does it do it in alphabetical order?

**Comment by ddollar** [comment]
#641 allows for the deployment parameters to be tweaked, this may cover what you're trying to do. Closing this for now but please feel free to comment if this doesn't work for you.
