### ISSUE TITLE
Display cost of rack

### ISSUE THREAD

**Issue by amlwwalker** [convox/rack#2734]
It would be nice to have something that gave a basic break down of a rack's cost in total, at the moment have to dig around in AWS/AWS docs and at best get an estimation of what is costing me

**Comment by mwarkentin** [comment]
Can this be figured out with tagging (convox already tags a bunch of resources) + AWS billing tools like cost explorer?

**Comment by ddollar** [comment]
Yes, this can likely be done with tags or using the AWS CloudFormation template cost estimator 

https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-cfn-editor-estimate-cost.html
