### ISSUE TITLE
Gen 2 local rack and AWS rack different hostnames?

### ISSUE THREAD

**Issue by amlwwalker** [convox/rack#2744]
Since Gen 2, the `links` command in convox.yml no longer works and hostnames are set inside containers as `servicename.appname.rackname.convox`. However when running locally, the format seems to be `servicename.appname.convox` which means dev and production are different. 

I may be wrong, but this seems to be the case, as locally, when I browse to (for my app) https://nginx.boiler.convox/ I can see my app, but browsing to https://nginx.boiler.convox.convox/ doesnt work.

A

**Comment by ddollar** [comment]
Yes they are different. You'll probably want to set an env var to point at the remote service. This would be the case anyway if you ever use different (staging, production?) racks.
