### ISSUE TITLE
Multiple schedule jobs causes execution errors.

### ISSUE THREAD

**Issue by fugufish** [convox/rack#2747]
I have multiple scheduled jobs that run at the same time (3 to be exact). One of the jobs fails to run consistently, after digging into it the error is this:

```
 InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: <numbers>
```

**Comment by fugufish** [comment]
incidentally when troubleshooting the scheduled task, it will run correctly if called manually

**Comment by ddollar** [comment]
That error is a red herring. That "error" happens in normal execution when logging to CloudWatch. Your first call always fails and the error returns a valid sequence token to continue logging.

Closing this issue as debugging individual racks is more suited to a support ticket.
