### ISSUE TITLE
Support for multiple aws racks in convox racks

### ISSUE THREAD

**Issue by jayjanssen** [convox/rack#2787]
$ convox racks
NAME          STATUS
local/convox  running

I have two AWS racks that I use (staging and prod).  I am not using console.convox, just convox login to switch between them.  It'd be a nice-to-have if convox racks showed all three.

**Comment by ddollar** [comment]
The convenience of multiuser/multirack is one of the selling points of Console so this functionality will likely not make it down into the single-rack CLI-only experience.
