### ISSUE TITLE
Rack uninstall local does not remove container

### ISSUE THREAD

**Issue by trashguy** [convox/rack#2796]
After uninstalling the local rack the containers still persists. Even after forcefully removing the container it via docker cli it returns. Is there a way to stop the container form starting up? This is happening on a Mac.

**Comment by ddollar** [comment]
Look for a convox.* file in /Library/LaunchDaemons and remove it. Remove the associated entry from launchd.

**Comment by agonbina** [comment]
@ddollar can you consider this issue as a feature request for having a `convox stop` command? For someone who does not understand the tools you listed in your comment it requires digging through documentation just to understand how to stop convox.

**Comment by trashguy** [comment]
@agonbina I agree, it seems a bit arduous to do where uninstalling the rack from the cli should complete this. At least update the documentation to include how to uninstall the local rack. I searched quite a bit until just asking here.

**Comment by ddollar** [comment]
Uninstalling the local rack should be removing all launchd scripts and stopping them. If you're seeing otherwise please file a bug including your uninstallation steps and what containers you are still seeing running.

**Comment by trashguy** [comment]
After updating and trying again looks like #2807 fixed everything.
