### ISSUE TITLE
LoadBalancer name cannot be longer than 32 characters after setting Internal=Yes

### ISSUE THREAD

**Issue by fugufish** [convox/rack#2806]
this is for an app named `elasticsearch`. If this not fixable, is there a way to rename the app without losing the volume?

**Comment by ddollar** [comment]
Sorry, there's no way to rename a CloudFormation stack which is what forms the basis for an app name. Given that this appears to be Gen1 and the difficulty of making backwards-compatible naming changes it is unlikely that this will be changed.
