### ISSUE TITLE
Rack name longer than 15 characters fails RouterInternalCertificate creation during rack install

### ISSUE THREAD

**Issue by stephenchu** [convox/rack#2818]
Version:

```
client: 20180728174119
server: 20180521013812
```

When I `convox rack install --name <name> ...` with a name that has >= 16 characters (e.g. `foo-bar-baz-bam1`), I get the following errors:

```
ERROR: The first domain name can be no longer than 64 characters. (Service: AWSCertificateManager; Status Code: 400; Error Code: InvalidDomainValidationOptionsException; Request ID: 89b24fbb-947c-11e8-8a15-e9c909d71ef7)
```

```
CREATE_FAILED         RouterInternalCertificate            AWS::CertificateManager::Certificate
```

**Comment by ddollar** [comment]
Yes, seems like a limit of AWS certificate hostnames

**Comment by qnm** [comment]
I'm seeing this same issue with a rack name of `integration` which is less than 15 chars.

**Comment by qnm** [comment]
Running the same create with the same rack name a second time worked.

Why would this be non-deterministic? Are components of the hostname of variable length?
