### ISSUE TITLE
Error while installing convox with MySql resource.

### ISSUE THREAD

**Issue by skatkov** [convox/rack#2824]
<img width="1271" alt="screen shot 2018-08-06 at 18 18 41" src="https://user-images.githubusercontent.com/544377/43727551-82515d06-99cc-11e8-82cb-14957f7756b7.png">

I'm trying to get this project running on AWS through convox. But running in to S3 related error (screenshot attached).

It's a bit strange to see this error, because app itself doesn't use s3 storage. 
I also found buckets from convox (logs, preferences) on S3 and they contain files.

Not sure what is it all about.

**Comment by skatkov** [comment]
Okey, I got some answers from slack

ddollar [11:03 PM]
@Stas i think it's probably because you're trying to create a mysql resource?
the current release only support postgres and redis as resource types.. i'm adding mysql right now

**Comment by ddollar** [comment]
This should work on the latest rack version.
