### ISSUE TITLE
ARG ignores convox.yml-defined environment vars

### ISSUE THREAD

**Issue by frsechet** [convox/rack#2834]
The following service:
```
  myqueue:
    build: ./some/path
    environment:
      - LOCAL_VAR=whatever
```
With the following dockerfile:
```
FROM alpine

ARG LOCAL_VAR
ARG ENV_VAR

RUN echo $LOCAL_VAR
RUN echo $ENV_VAR
```
Where ENV_VAR is defined by `convox env set ENV_VAR=something` will not have LOCAL_VAR available as a build arg. However, ENV_VAR is:

```
...
Step 2/5 : ARG LOCAL_VAR
 ---> Running in 1e700011743d
Removing intermediate container 1e700011743d
Step 3/5 : ARG ENV_VAR
 ---> Running in b05dfe7940a3
Removing intermediate container b05dfe7940a3
 ---> 375f118ec0ce
Step 4/5 : RUN echo $LOCAL_VAR
 ---> Running in 299b8c63d466

Removing intermediate container 299b8c63d466
 ---> 4ce760e8da36
Step 5/5 : RUN echo $ENV_VAR
 ---> Running in b0a00cb95236
something
```

It feels like a bug, because it forces to define a very local variable as a global variable, accessible to all services. Without a way to define [build-time args in convox.yml](https://convox.com/docs/dockerfile/#arg), it's a bit cumbersome to do otherwise.

**Comment by ddollar** [comment]
Yes, this is true. Couldn't you just `ARG LOCAL_VAR=foo` to set a default if you're making it part of your code anyway?
