### ISSUE TITLE
Unable to deploy `is not a valid repository/tag: invalid reference format`

### ISSUE THREAD

**Issue by iCreateJB** [convox/rack#2844]
Environment that's doing the deployment is travis, install information was taken from the documentation. 

```
curl -L https://convox.com/cli/linux/convox -o /tmp/convox && \
  sudo mv /tmp/convox /usr/local/bin/convox && \
  sudo chmod 755 /usr/local/bin/convox
```

CLI: 20180811020500

Note: The environment variables are set when the build runs.

`convox deploy --rack $MASTER_CONVOX_RACK --app "$MASTER_CONVOX_APP-$TRAVIS_PULL_REQUEST" --manifest $CONVOX_COMPOSE`

**Comment by ddollar** [comment]
In order to faciliate debugging please log in to Console and create a support ticket with the following:

* Your exact `convox.yml`
* The output of `convox version` (need both client and server)
* The full output of the command that you ran
