### ISSUE TITLE
Feature request: support ECS memory & memoryReservation setting

### ISSUE THREAD

**Issue by tfront** [convox/rack#2909]
From this [container definition of ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definitions), it supports both memory soft limit and hard limit. But in convox it supports only ApiMemory parameter which maps to ECS memoryReservation (soft limit), it is better to support both in convox to limit total memory usage in some rare case.

Could you please add this feature.

Thanks

**Comment by ddollar** [comment]
The `memory:` attribute of Convox services maps to the `Memory` attribute of a container definition which is the hard limit.

https://github.com/convox/rack/blob/master/provider/aws/formation/service.json.tmpl#L451
