### ISSUE TITLE
App names with hyphen

### ISSUE THREAD

**Issue by chrislengerich** [convox/rack#293]
One can create apps with a hyphen in the name, but the app name is truncated in later commands: 

convox apps create sinatra-1

succeeds. 

$ convox scale sinatra-1 --count 1
ERROR: no such app: sinatra
$convox scale "sinatra-1" --count 1
ERROR: no such app: sinatra

**Comment by matthewford** [comment]
try with the app flag, `--app sinatra-1` @chrislengerich

**Comment by xtfxme** [comment]
Double check there is no `.convox/app` in the repo, set to "sinatra"...
This got me a few times!

**Comment by xtfxme** [comment]
Double check there is no `.convox/app` in the repo, set to "sinatra"... This got me a few times!

**Comment by nzoschke** [comment]
This is an issue with your usage of the `convox scale` command.

```
$ convox scale --help
convox scale: scale an app's processes

Usage:
  convox scale PROCESS [--count 2] [--memory 512]
```

So `convox scale sinatra-1 --count 1` is trying to scale the `sinatra-1` process on the app that it is detecting from the directory name. Try:

`convox scale web --count 1 --app sinatra-1`

I'm sure app names with hypens are ok. I exercise this constantly in our CI tool, e.g. the httpd-459 and node-workers-459 apps created in https://circleci.com/gh/convox/rack/459

So I'm closing this, but would happily accept feedback on how the CLI error message could be more instructive here.
