### ISSUE TITLE
CloudFormation cannot update a stack when a custom-named resource requires replacing

### ISSUE THREAD

**Issue by krmannix** [convox/rack#2941]
Version:
```
client: 20180913211708
server: 20180904141452
```

We ran the following command:
```
$ convox resources update <resource-name> AllocatedStorage=50 --wait
$ Updating resource... OK
```

However, when checking CloudFormation we received an `UPDATE_FAILED` event with the following error message:
`CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename prod-convox-<resource-name> and update the stack again.`

After some investigation, it's unclear what this error may indicate, what the next steps are, and why we received an `OK` via the Convox CLI.

**Comment by ddollar** [comment]
The change you are requesting would require deleting the existing resource and creating a new one so CloudFormation is refusing to continue.

`convox resources update` is an async command so it returns OK when the request succeeds. You can add `--wait` to the end if you'd like to wait for success/failure.
