### ISSUE TITLE
Can't update rack with SpotInstanceBid set and OnDemandMinCount=0

### ISSUE THREAD

**Issue by crohr** [convox/rack#2956]
The ApiMonitorService will refuse to be scheduled on a container instance that doesn't fulfill the following constraint: `memberOf(attribute:asg == primary)`

```
service saas-ApiMonitorService-GKYK3BFF5P16 was unable to place a task because no container instance met all of its requirements. The closest matching container-instance 6948ef2a-4e94-4c05-8ff3-fca20d62ddf4 encountered error "memberOf constraint unsatisfied"
```

EC2 spot instances have `attribute:asg = spot`, which means we can't update a rack unless it has at least one on demand instance. I would prefer to be able to go full spot instances on a rack, but if it's not possible, then it should be made clear in the doc that you MUST have at least one on-demand instance.

**Comment by ddollar** [comment]
https://github.com/convox/rack/pull/2959 will change OnDemandMinCount to be a minimum of 1
