### ISSUE TITLE
Rack Install failed during Cloudformation Create

### ISSUE THREAD

**Issue by chrishenry** [convox/rack#2995]
In a brand new account, creating a rack in us-east-2 yields this error.
```
12:13:27 UTC-0400 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | baton-stage | The following resource(s) failed to create: [CustomTopic, InstancesLifecycleHandler, HostedZone]. . Rollback requested by user.
-- | -- | -- | -- | --
  | 12:13:26 UTC-0400 | CREATE_FAILED | AWS::Route53::HostedZone | HostedZone | Resource creation cancelled
  | 12:13:25 UTC-0400 | CREATE_FAILED | AWS::Lambda::Function | CustomTopic | Template error: IAM role baton-stage-CustomTopicRole-1A9HCO78TUIP8 doesn't exist
  | 12:13:25 UTC-0400 | CREATE_FAILED | AWS::Lambda::Function | InstancesLifecycleHandler | Template error: IAM role baton-stage-InstancesLifecycleHandlerRole-1BFARB1I0GXL6 doesn't exist
```

When installing AWS, I experienced a few issues where the convox role wasn't found, despite it clearly being present. is there an ongoing outage or a know issue with spinning up new racks?

**Comment by ddollar** [comment]
Looks like IAM is currently experiencing an issue

https://github.com/awslabs/serverless-application-model/issues/641#issuecomment-433122826

**Comment by chrishenry** [comment]
Ugh, AWS seems to be getting slower updating their dashboards. I just had a build go through, but thanks for the quick response!
