### ISSUE TITLE
convox cli - convox rack uninstall doesn't use account IAM profile -- uses local AWS credentials

### ISSUE THREAD

**Issue by kwazi** [convox/rack#3036]
`convox rack uninstall aws staging1
ERROR: ValidationError: Stack with id staging1 does not exist`

Despite
`convox rack --rack xxx/staging1
Name     staging1
Status   running
Version  20181115134335
Region   us-east-1`

Turns out, that this command uses the local environment AWS credentials instead of the convox IAM role which is not very clear from the documentation.

Is this intended?

Seems to be the offending code: https://github.com/convox/rack/blob/5111eefd1f9de1f208fded0b7dc8379a14e43c18/provider/aws/system.go#L437

**Comment by ddollar** [comment]
Yes, this is intended. CLI-based rack install and uninstall use the `aws` CLI to create/delete the relevant CloudFormation stack.

A new version of Console is coming this weekend which allows uninstallation from the web UI which bypasses this requirement.
