### ISSUE TITLE
Question about Amazon ECS migrating to the new ARN and and resource identifier (ID) formats

### ISSUE THREAD

**Issue by exalted** [convox/rack#3037]
Hi there! A little while ago we received a heads-up from AWS about them migrating Amazon ECS to the new ARN and and resource identifier (ID) formats. It’s opt-in until December 31, 2019; however we would like to know beforehand, from convox’s perspective, is anything we should do, if convox is ready for the migration, or is it safe to upgrade our racks in future, etc.?

Your feedback would be greatly appreciated, thank you! :pray:

**Comment by ddollar** [comment]
Should be fine. Give it a shot and report back.
