### ISSUE TITLE
Add Rack > Add Parameter does not work in Console

### ISSUE THREAD

**Issue by andrewchak** [convox/rack#3042]
When trying to add an AWS rack via console.convox.com, currently the Add Parameter link does not work and no form fields show up to set rack parameter values.

Tested on Mac High Sierra 10.13.6 Chrome 71.0.3578.80

![screen shot 2018-12-13 at 4 16 08 pm](https://user-images.githubusercontent.com/678259/49917257-93340200-fef2-11e8-9403-c67f45dfc03b.png)

**Comment by ddollar** [comment]
A fix for this is deploying now.
