### ISSUE TITLE
Use CloudWatch Events to subscribe to ECS Service Events

### ISSUE THREAD

**Issue by patrobinson** [convox/rack#3046]
We've noticed that the Worker Events process calls the ECS API once a second by default. This generates a rather large number of CloudTrail logs, which we pay to ingest and index in our log aggregation system.

It seems to me it would be more efficient and better for us if this function (found [here](https://github.com/convox/rack/blob/6f95ee8c1e3a03642340ff0e8b42088253bbcd5f/provider/aws/workers_events.go#L183)) instead subscribed to [ECS CloudWatch Events](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_cwe_events.html).

**Comment by ddollar** [comment]
Unfortunately the ECS cloudwatch events do not yet contain all of the service-level events necessary to build the logs. This does, however, appear to be coming in ECS roadmap.
