### ISSUE TITLE
Allow configuration of ECS_CONTAINER_STOP_TIMEOUT

### ISSUE THREAD

**Issue by idris** [convox/rack#3047]
I would like to set `ECS_CONTAINER_STOP_TIMEOUT` on our non-HTTP services, so that services have more time to wrap things up before being killed.

More specifically, I have a service that processes jobs on a queue, and since a job might take a minute to complete, I need the timeout to be more than a minute so that processing can complete before the service gets killed.

**Comment by mwarkentin** [comment]
Isn’t this something that you set on the cluster instances? I think it’s an env var that the ECS agent reads.

**Comment by ddollar** [comment]
As far as I know this is at the instance level and not per-service. You should be able to set it at the instance level with an InstanceBootCommand if you like.
