### ISSUE TITLE
Convox run shows no output with null stdin / non-interactive use cases

### ISSUE THREAD

**Issue by thieman** [convox/rack#3055]
`convox run` normally outputs the stdout of the process you ran, for example:

```
> convox run --rack R --app A ls /usr/local
bin  etc  games  include  lib  lib64  libexec  sbin  share  src
```

We noticed that recently we are no longer getting stdout back when running `convox run` in our Jenkins pipeline, a non-interactive flow without a TTY attached. We're not 100% sure these are the same thing, but we can reproduce the same behavior by redirecting stdin to /dev/null:

```
> convox run --rack R --app A ls /usr/local < /dev/null
# no output
```

rschlesser in Slack added the following:

> Hi, we had the same problem with our runner in gitlab.  It even seemed that it was not only the output but the command did not run at all.   To fix it we prepended "unbuffer" to every command. For example: "unbuffer convox run ..."
The issue started for us around the same time as for you.

We've confirmed that using `unbuffer` from the `expect` package will make stdout visible again, even when redirecting to /dev/null. Obviously we would prefer to fix the bug in Convox rather than layer on this hack everywhere, but the information might be useful.

Our Jenkins logs show that this behavior was introduced between Dec 7 and Dec 10, 2018. We made no changes of any kind on our end during this timeframe (it was a weekend), but if memory serves this was when Console 2.0 was rolled out to everyone, so we suspect the issue lies within Console 2.0.

**Comment by mwarkentin** [comment]
Possibly related: https://github.com/convox/rack/issues/3017

**Comment by thieman** [comment]
Per @ddollar in a support ticket:

> A fix for this is rolling out to Console right now, should be out in the next 5-10 minutes

We've confirmed on our end that we're seeing output from `convox run` again in these conditions. Thanks!
