### ISSUE TITLE
Convox Rack Scale causes downtime

### ISSUE THREAD

**Issue by cozmo** [convox/rack#311]
It was not clear to me from https://convox.com/docs/scaling-rack/ that issuing the command `convox rack scale --count 2 --type t2.micro` would cause downtime in my services. What I _expected_ to happen was

1. 2 new machines of size `t2.micro` to be created
2. add the machines to the convox ELB and any ELBs for applications that have been created
3. wait for the machines to come into sevice
4. Remove the old machines from the ELBs and shut the machines down

What instead happened was

1. Create 2 machines of size `t2.micro`
2. Shut down old machines
3. Wait for new machines to come up
4. Attach new machines to ELB.

This caused significant downtime between steps 2 and 4, since that process can be relatively lengthy. If this order is for some reason required (I don't think it is) it should be documented very clearly. If it's not required then the order should be changed to the expected order which should not create downtime. 

A third possibility is that this wasn't supposed to cause downtime and it was a bug. If that's the case let me know what information I can provide to assist in debugging. 

Thanks!

**Comment by nzoschke** [comment]
Thanks for your report. 

The goal is that `convox rack update` should not cause downtime as long as your apps are scaled to at least 2 processes behind a load balancer.

I think this recent change improves the situation and should remove the downtime you saw:

https://github.com/convox/rack/blob/master/api/dist/kernel.json#L671

It's not quite as you expect, but it is close. We now fully wait for a new instance to boot up before terminating any old ones with the AutoScaling MinInstancesInService setting.

https://github.com/convox/rack/blob/master/api/dist/kernel.json#L709

I'll update the docs to make the expectations here more clear.

**Comment by nzoschke** [comment]
PR on docs:

https://github.com/convox/convox.github.io/compare/instance-replacement?expand=1

I'm going to close this issue. If you do experience downtime after updating to the latest version, please open a new issue.

**Comment by cozmo** [comment]
Thanks for the update! I'll try this out tomorrow.
