### ISSUE TITLE
add optional name/tag to builds and releases

### ISSUE THREAD

**Issue by soulware** [convox/rack#312]
It would be great if there was a way to optionally name (or tag) a build or release - and be able to refer to it by name as an alternative to the auto generated id.

So you could do something along the lines of - 

```
$ convox build "v1.0"
$ convov releases promote "v1.0"
```

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0EmeiOkd&#x2F;320-add-optional-name-tag-to-builds-and-releases"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> add optional name&#x2F;tag to builds and releases</a>

**Comment by soulware** [comment]
Nice to have - ability to optionally autogenerate word-pair names/tags.

**Comment by mtrofimm** [comment]
+1

**Comment by nzoschke** [comment]
This was also requested with lots more context here: #190

Closing this issue in favor of that one.

**Comment by nzoschke** [comment]
The builds API now has a description field: http://convox.github.io/api/#!/default/post_apps_app_builds

**Comment by nzoschke** [comment]
See this related issue and comments for some more info:

https://github.com/convox/rack/issues/193#issuecomment-207838575
https://github.com/convox/rack/issues/193#issuecomment-207840854

The build description option satisfies describing a build, and every release is based off a build by definition.

This doesn't satisfy a porcelean command like `convov releases promote "v1.0"` but that's actually not obvious how to implement. There can be many releases based of the `v1.0` build for environment changes.

**Comment by ddollar** [comment]
Closing this for now. Please feel free to comment if the description field is not sufficient.
