### ISSUE TITLE
Expose link host and port (in addition to full url) for linked containers

### ISSUE THREAD

**Issue by soulware** [convox/rack#323]
Links currently expose a URL to allow one container to access another.
It would add flexibility if the HOST and PORT were also exposed.

The url is exposed like this - 
`LINK_URL=tcp://internal-xxx.elb.amazonaws.com:8000`

i.e. in the form `<scheme>://<username>:<password>@<host>:<port><path>`

We have a particular use-case where we want to run nginx in one container
and link another container as an nginx upstream server.
In this case the full url does not work as nginx expects the upstream to be specified as simply HOST:PORT
It would be useful if Convox could expose the following for flexibility - 

* LINK_URL
* LINK_HOST
* LINK_PORT

This would avoid apps needing to parse and potentially rewrite the link urls.

**Comment by nzoschke** [comment]
Thanks for your feature request. This is now the behavior of the link environment variables!

https://github.com/convox/rack/pull/300

**Comment by soulware** [comment]
Awesome. Thanks!
