### ISSUE TITLE
scheduling containers

### ISSUE THREAD

**Issue by mtrofimm** [convox/rack#331]
I have a 3-node t2.micro rack (named apihistory) with 3 apps deployed. 

![image](https://cloud.githubusercontent.com/assets/10633617/12910118/cbb0f53e-cf07-11e5-9de6-8b15d24d5f16.png)

Such distribution of containers causes out-of-memory and restarts of api when I try to build a new version.

**Comment by nzoschke** [comment]
Can you also share how much memory each container is configured for?

**Comment by mtrofimm** [comment]
piwikrun-app - 384
piwikrun-cron - 160
apihistorywebapi-web - 256
apihistoryworker-apihistorywordernewvehiclefile - 256
vindecoderplrun-web - 256
automoplwebapp-processunfinishedtransaction-128
automoplwebapp-reportgeneratecron-128
automoplwebapp-web-256

current situation:

![image](https://cloud.githubusercontent.com/assets/10633617/12947863/a80cc61a-cffe-11e5-946d-8d0f61a4eca7.png)

**Comment by ddollar** [comment]
This is all up to ECS so we should not be seeing placement issues.
