### ISSUE TITLE
mount s3/ebs volume inside a container

### ISSUE THREAD

**Issue by mtrofimm** [convox/rack#333]
I need to generate and serve quite big sitemaps in my convox app.
I was thinking about mounting S3 bucket. I tried to use s3fs but there is a issue with access to /dev/fuse.

Any ideas?

**Comment by nzoschke** [comment]
Great minds think alike. I just published a release that lets you specifiy privileged: true in docker-compose.yml which will give your container permission to use s3fs. `convox rack update` to get it.

Here's an example where s3fs works: https://github.com/convox-examples/s3fs

Note the privileged flag in https://github.com/convox-examples/s3fs/blob/master/docker-compose.yml#L7

Here's the PR: https://github.com/convox/rack/pull/332
The issue: https://github.com/convox/rack/issues/155

**Comment by mtrofimm** [comment]
Thanks!!!
