### ISSUE TITLE
System update fails when deleting parameters

### ISSUE THREAD

**Issue by ddollar** [convox/rack#34]
When updating to a new CloudFormation template if the new one removes any parameters it will fail. This is because the old parameter list is used to initialize the parameter list for the new stack and may contain parameters that no longer exist.

App#UpdateParamsAndTemplate() needs to be made smarter about parameters and removing the ones that no longer exist somehow.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8tDqWAc9&#x2F;155-models-systemupdate-should-not-send-parameters-that-no-longer-exist"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> models.SystemUpdate should not send parameters that no longer exist</a>

**Comment by nzoschke** [comment]
Fixed in https://github.com/convox/rack/pull/365/files

UpdateParamsAndTemplate was harmful and removed. But Release.Promote() and System.Save() both do very similar things w.r.t. params now.
