### ISSUE TITLE
Changing an apps primary balancer from public to private causes an UPDATE_FAILED

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#354]
```
16:24:11 UTC-0800    UPDATE_FAILED    AWS::ElasticLoadBalancing::LoadBalancer    Balancer    CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename httpdp and update the stack again.
```

This looks related to `func (mb ManifestBalancer) LoadBalancerName()` and the special casing for the manifest primary load balancer. There's no logic to change the primary load balancers name if it flips to private.

**Comment by nzoschke** [comment]
The logic for determining the primary process is confusing and undocumented.

**Comment by RongxinZhang** [comment]
:+1: cool.

**Comment by nzoschke** [comment]
For more context, the primary process ELB name is a special case for backwards compatibility.
The very first apps on the platform used a single task definition for all process types, and therefor a single ELB named after the stack.

When we split this up to multiple process types, it opened up the usage of multiple ELBs, but we had some production apps that were depending on the old ELB convention. So the primary process logic was added to let web processes re-use the stack name ELB, and other processes to get more explicit process name ELBs.

**Comment by nzoschke** [comment]
This will be fixed for new apps when https://github.com/convox/rack/pull/341 lands. For existing apps I think it's a wontfix...

**Comment by nzoschke** [comment]
#341 landed so this problem won't happen on new apps going forward.

Because we have the new/improved path, I don't want to change anything in the old path.

If you hit this problem again, ideally migrate to a new app to get the new load balancer naming.

The other workaround is to rename process types in the manifest, i.e. change 

```
web:
  ports: 80:80
```

to

```
webp:
  ports: 80
```
