### ISSUE TITLE
Handle ECR 500 image limit

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#361]
An ECR repository is limited to 500 images.  http://docs.aws.amazon.com/AmazonECR/latest/userguide/service_limits.html

Once a repo hits the limit you can no longer deploy the corresponding app. We should rotate out old images. This probably has implications for the build and release history too, since you won't be able to roll back to a release for which the images have been deleted.

**Comment by xtfxme** [comment]
Features I'd like to see here are per-app retention policies, eg. last 10 for app X and last 20 for app Y, and the ability to pin releases, possibly builds too. I might want to keep specific versions around for whatever reason.

"Keep last N" strategy is the most obvious, but are there others that make sense?

We should also never attempt to rotate the current/active release; it should be pinned on promotion. This allows rolling back to an old release and doing a build that would have otherwise dropped the now active release.

**Comment by nzoschke** [comment]
Saw another customer report of this:

```
unknown: The repository with name 'foo-ixsosnjqzq' in registry with id 'ZZZ' already has the maximum allowed number of images which is '500'
ERROR: exit status 1
```

**Comment by nzoschke** [comment]
The Rack monitor could poll for this and clean old images. Or the build controller could remove one before pushing a new one if its at 500.

**Comment by nzoschke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6Xs2SSwR&#x2F;25-clean-up-older-releases-and-images"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Clean up older releases (and images)</a>

**Comment by nzoschke** [comment]
I propose starting with something simple / naive:

```
After a successful build/release
  While number of images >= ECR_MAX_IMAGES
    Delete oldest release, build, and images
```

It's definitely annoying / scary to delete old artifacts. Build / release pinning, per-app configuration and image archival would be nice to add in the future.

**Comment by nzoschke** [comment]
I'm also working an AWS support ticket to see what types of service limit increases are available here.

**Comment by nzoschke** [comment]
We recently shipped some primatives to help with this... https://github.com/convox/rack/pull/495

* DELETE /apps/{app}/builds/{id} API
* convox builds delete <ID> CLI
* Deleting a build removes images from ECR, and build item and related release items from DynamoDB

Also we were able to get a service limit increase on one account, and have word that the 500 image limit will be raised in the near future.

So I think this all buys us time...

We have not yet implemented an automated cleanup. Still thinking about the ideal design there.

**Comment by nzoschke** [comment]
In general I want our solutions to be possible if not actually implemented through APIs. One obstacle to cleaning up old builds with our APIs is that the `GET /apps/{app}/builds` API is hard coded to list the most 20 recent builds.

Can we add some parameters to either list more builds and/or to list builds in reverse order? Here's a straw man design:

`GET /apps/{app}/builds?sort=-started`

**Comment by mwarkentin** [comment]
Would that API be paginated, or what happens if you left off `limit`? Would you get back all 500 builds?

**Comment by awsmsrc** [comment]
@nzoschke @MiguelMoll this came up for a customer again today. bump

**Comment by nzoschke** [comment]
Some next steps:

- Document or playbook that you can ask Amazon to update the limits
- Add options to the builds API to order by oldest first
- Add options to builds API for limit
- Delete the oldest build on a new successful build

**Comment by ddollar** [comment]
These steps continue to make this the user's problem when it could be easily solved through automation or working with Amazon to globally raise these unnecessary limits. I'm -1 on doing work to reorder and limit the builds API and +1 on solving this behind the scenes with no user action necessary.

**Comment by nzoschke** [comment]
That's the `Delete the oldest build on a new successful build` next step

**Comment by nzoschke** [comment]
And there's serious context missing here. @awsmsrc and I discussed doing just that part and nothing else.

**Comment by ddollar** [comment]
We already have some processes running every N minutes. We could delete all builds > eg 200 periodically. The API and CLI changes seem like a lot of extra work and don't really achieve the desired outcome.

**Comment by nzoschke** [comment]
We're in agreement. The design @awsmsrc proposed is to automatically delete builds on the API side when > 200 images. In addition to periodic stuff, there is a consideration to do it in the background at the end of the BuildCreate API.

**Comment by ddollar** [comment]
+1

**Comment by nzoschke** [comment]
This was recently released.
