### ISSUE TITLE
Avoid generating non-alphanumeric CF Parameter names

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#364]
Many CloudFormation parameters are generated from the process names in Docker compose. If the process name has non-alphanumeric characters, this can result in an invalid Parameter name. For example, trying to deploy an app with the process name `www-1` will result in the error `ERROR: Template format error: Parameter name Www_1DesiredCount is non alphanumeric.`

I'm not sure about the best fix for this. Simply dropping the invalid characters could result in collisons like if you had a process named `www1` and another named `www-1`, for example.

**Comment by RongxinZhang** [comment]
Cool! :+1: This is what they did with `docker-compose.yml` might be helpful

**Comment by nzoschke** [comment]
I'm worried about side effects dropping characters from the manifest too.

How about validate the manifest process names in `convox start` and `convox deploy` and instruct the user to change it themselves?

**Comment by mwarkentin** [comment]
+1 to adding the same validation during `convox *` vs. dropping chars.

**Comment by nzoschke** [comment]
This process name works just fine for dev and deploy:

```
web-1:
  image: httpd
  ports:
    - 80:80
```

```
$ convox start
RUNNING: docker tag -f httpd httpd/web-1
web-1  | docker run -i --name httpd-web-1 -p 81:80 httpd/web-1
```

And resources:
* BalancerWeb1
* Web1ECSService
* Web1ECSTaskDefinition

**Comment by nzoschke** [comment]
However this does not deploy well:

```
web_1:
  image: httpd
  ports:
    - 81:80
```

```
$ convox start
RUNNING: docker tag -f httpd httpd/web_1
web_1  | docker run -i --name httpd-web_1 -p 81:80 httpd/web_1
```

```
$ convox deploy
...
Promoting RMGIKBBKRUT... ERROR: Template format error: Parameter name Web_1DesiredCount is non alphanumeric.
```
