### ISSUE TITLE
How can I get the X-Forwarded-For headers

### ISSUE THREAD

**Issue by grandmore** [convox/rack#366]
I need to get the http client's ip address but the ELB headers are not being passed to the docker instance. 

The elb docs [X-Forwarded Headers for Elastic Load Balancing](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html#x-forwarded-for) say that there are three headers being set.
X-Forwarded-For
X-Forwarded-Proto
X-Forwarded-Port

How can I get this data?

I noticed some discussion in [#124](https://github.com/convox/rack/issues/124)

**Comment by mtrofimm** [comment]
change the type of lb to http using aws console.

**Comment by grandmore** [comment]
Thanks for the info. I managed to work this out with @ddollar. What did catch me out is that when you manually change the receive from tcp to http, the dialog auto-changed the Instance port to 80 instead of staying with the original port that was set (64299 in my case).
