### ISSUE TITLE
AWS services

### ISSUE THREAD

**Issue by ddollar** [convox/rack#377]
Let's wrap the following in convox services:
- [x] S3
- [ ] SES
- [x] SQS
- [x] SNS

**Comment by shicholas** [comment]
:+1: damn each one would make my life easier.

I guess here's appropriate to throw this in too: https://aws.amazon.com/elasticsearch-service/

**Comment by mwarkentin** [comment]
Elastic MapReduce and Elasticsearch Service support was also added to Cloudformation recently: https://aws.amazon.com/about-aws/whats-new/2016/02/aws-cloudformation-adds-support-for-amazon-vpc-nat-gateway-amazon-ec2-container-registry-and-more/

**Comment by nzoschke** [comment]
Dynamo would be nice to have someday too. `convox services add dynamodb` creates an IAM user and policy, and sets a DYNAMO_ACCESS_KEY_ID, DYNAMO_SECRET_ACCESS_KEY and DYNAMO_TABLE_PREFIX.

**Comment by nzoschke** [comment]
S3, SQS, and SNS are going to land here: https://github.com/convox/rack/pull/468

**Comment by contra** [comment]
@ddollar No plans for SES?
