### ISSUE TITLE
Better default parameters for Postgres

### ISSUE THREAD

**Issue by ddollar** [convox/rack#386]
From @idyll

> You need to:
> 
> 1. make a new parameter group based on the same type as the old one in RDS
> 2. change the DB instance to use the new parameter group
> 3. reboot the server.
> 
> to check the changes have been applied open a console and run `show max_connections;`
> 
> It looks like AWS reduced the numbers by 60% with the latest PG release.

```
max_connections
{DBInstanceClassMemory/20000000}
```

Need to make the `postgres` service template create a parameter group and use it.

**Comment by idyll** [comment]
Here's the background on this. The current AWS limit restricts a t2.micro instance to 22 connections. (26 but 4 are reserved for the system.) 

The idea is to limit connections so you don't run the DB server out of RAM, but in my experience there was more than enough memory to accommodate double the DB connections.

The above number `20000000` will increase from 26 to 41. I am experimenting with this right now to see how it impacts memory usage.

It may be better to use `15000000` for smaller instances, as that is closer to the original AWS value before this change with PG 9.4.x.

**Comment by dlanger** [comment]
@ddollar Once this makes its way into convox, any idea what I'll have to do to get an existing DB (created with `convox services create`) to pick up the change?

**Comment by nzoschke** [comment]
`convox services update`!

That can apply cloudformation updates, same as rack and apps.

**Comment by dlanger** [comment]
@nzoschke This means we can update `rack` and `cli` without updating this, right?

**Comment by nzoschke** [comment]
Yes... This is work in progress, but I'm starting to make a pass on these services issues. So someday soon I hope you can do:

```
# update your rack for the newest API and services templates
$ convox rack update

# update your CLI to get the latest usage / clients
$ convox update

# Migrate an existing postgres service to get a parameter group
$ convox services update my-existing-pg
```

I also see adding more parameters / options that update will understand

```
$ convox services update my-existing-pg --instance-type t2.large 
```

**Comment by nzoschke** [comment]
I'm seeing the a new parameter group default to `{DBInstanceClassMemory/31457280}`

**Comment by dlanger** [comment]
That sounds reasonable. My big concern is that I can clearly reason about which operations are guaranteed to not cause downtime, and which ones (like this) might.

**Comment by nzoschke** [comment]
Totally. For the datastores, `convox services update` should be very explicit about downtime.

The CF docs are pretty good about helping us understand this, except when they say:

> Update requires: No interruption or Some interruptions

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbparametergroup.html

**Comment by nzoschke** [comment]
@idyll, so I can imagine a MaxConnections Parameter on a postgres stack now.

Should the value be the whole `{DBInstanceClassMemory/15000000}` string? Passing options through transparent is always nice and easy.

I can also imagine trying to make MaxConnections an integer and calculating the right denominator, but we'd need to maintain a map of DBInstanceClassMemory values...

**Comment by nzoschke** [comment]
In a dev server with https://github.com/convox/rack/pull/428 I can do create a postgres service, then update the MaxConnections to `{DBInstanceClassMemory/15000000}` and it reboots the database with the new settings.

**Comment by nzoschke** [comment]
An experimental version of this landed in https://github.com/convox/rack/pull/428
