### ISSUE TITLE
Improve line wrapping behavior for convox exec

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#387]
When `convox exec`'d into a container, the terminal line wrapping is not very friendly. Here's an example with a line and what it looks like when it's long enough to wrap:

```
root@3ee60bbac9fd:/app# here are a bunch of characters that cause the line to
<e are a bunch of characters that cause the line to wrap
```

The wrap happens at 78 characters.

**Comment by ddollar** [comment]
fixed by #388, tracking there
