### ISSUE TITLE
Rack, App, and Service name validation

### ISSUE THREAD

**Issue by ddollar** [convox/rack#397]
rack name, app name, service name should all be validated as [a-z0-9-] (no caps, no underscore)

this helps with aesthetics, makes them nice to use in urls, and fits with naming guidelines of various other services, e.g. http://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreateRepository.html

**Comment by xtfxme** [comment]
Also enforcing the first character is a letter instead of a dash or number might be good.

**Comment by ddollar** [comment]
Good idea. First letter should be a-z.

**Comment by nzoschke** [comment]
install now validates this https://github.com/convox/rack/pull/402

**Comment by mwarkentin** [comment]
Can this be closed, or did this validation need to be added elsewhere?

**Comment by nzoschke** [comment]
I believe both the App and Service controllers or models need to do validation still.

**Comment by nzoschke** [comment]
Fixed. All unified to the same regex.
