### ISSUE TITLE
New cloudformation resources

### ISSUE THREAD

**Issue by alex** [convox/rack#400]
Right now convox uses some custom resources, a few of those can be replaced with native resources now: https://aws.amazon.com/about-aws/whats-new/2016/02/aws-cloudformation-adds-support-for-amazon-vpc-nat-gateway-amazon-ec2-container-registry-and-more/

**Comment by nzoschke** [comment]
Thanks for the heads up. 

The list of custom resources that are officially supported is pretty big now:

Rack:

* Custom::EC2NatGateway
* Custom::EC2Route
* Custom::KMSKey
* Custom::EC2AvailabilityZones
* Custom::ECSTaskDefinition
* Custom::ECSService

App:

* Custom::ECSTaskDefinition
* Custom::ECSService
* Custom::ECRRepository

However each one has its own challenges in migrating off it we want to keep existin apps up and preserve app and rack rollbacks.

**Comment by nzoschke** [comment]
Custom::EC2NatGateway and Custom::EC2Route are good targets, as I don't think too many people are using the --private mode yet.

Rack updates and rollbacks should be generally ok, except that custom peering configuration could break.

**Comment by nzoschke** [comment]
Custom::KMSKey is a prime example of something hard to migrate to the native CF resource. If a new KMS key resource is created and passed as a reference to the Custom::ECSTaskDefinition, environment decryption will break.

We could pass two keys to the Custom::ECSTaskDefinition and it could try to use both.

This also is a good pattern to enable key rotation which is a best security practice.

**Comment by nzoschke** [comment]
Custom::ECSTaskDefinition and Custom::ECSService could be replaced in rack very easily.

Apps, not so easy since the custom handler does environment decription and injection.

**Comment by nzoschke** [comment]
Custom::ECRRepository is also tricky to preserve release rollback. We would need to retain the old resource (either with a rention policy or by changing the custom handler delete to noop), and provision a new one with the native handler.

App release templates are saved in S3 so rollbacks should be ok as long as the Custom::ECRRepository resource and data is available.

**Comment by nzoschke** [comment]
One thing we discussed internally is making some breaking changes for this for a 1.0 release along with a migration tool.

This is interesting, but I'd still strongly favor incremental changes to learn about the reliability of the new resources.

**Comment by mwarkentin** [comment]
We've got a staging rack set up with `--private` - not sure when we'll be launching our production rack, but definitely following with interest (and can probably help test the migration if needed).

**Comment by nzoschke** [comment]
Applying the help wanted label, and want AWS to help. :)

Seems like CloudFormation could make this easy, but right now its really in the way.

**Comment by ddollar** [comment]
We have replaced most of these now
