### ISSUE TITLE
Apps with capital letters fail ECR provisioning

### ISSUE THREAD

**Issue by xtfxme** [convox/rack#407]
```
# convox apps create CAPS
Creating app CAPS... CREATING

# convox apps info CAPS | grep Status
Status     failed

# aws cloudformation describe-stack-events --stack-name=ci-CAPS | jq -r '.StackEvents[]|select(.ResourceStatus=="CREATE_FAILED")|.ResourceStatusReason,.PhysicalResourceId'
Invalid PhysicalResourceId
ci-CAPS-RegistryRepository-RGQI49D4GA1I
```

I'm not 100% certain this is the problem (many capital letters get added by CF automatically?), nor can I find any documentation suggesting capital letters are reserved, but when they do exist, apps fail to create.

The template references `AWS::StackName` directly... wat do?

**Comment by nzoschke** [comment]
Thanks for the report, lets track it here https://github.com/convox/rack/issues/397

**Comment by xtfxme** [comment]
Ah OK, if that is enforcing lowercase then we'll be good. Thanks!
