### ISSUE TITLE
Run one off commands on a specific release

### ISSUE THREAD

**Issue by bowmande** [convox/rack#409]
It would be great to be able to specify a specific release id when running a one off command.

Ex. `convox run bash --release REZAALHGXHQ`

**Comment by peterlauri** [comment]
Agree. My use case is that I need to run Django migrations before deploying the new release (based on the assumption that the old release is compatible with the new release schema.

**Comment by bowmande** [comment]
https://github.com/convox/rack/pull/526

**Comment by ddollar** [comment]
Closing in favor of #526
