### ISSUE TITLE
Convox scale is broken with -a

### ISSUE THREAD

**Issue by xer0x** [convox/rack#410]
I tried out `convox scale --count X` and was surprised when my api went down. Convox set the desired number to 0 instead of X.

My session looked a little like this:

```
$ convox scale -a app
NAME    DESIRED  RUNNING  MEMORY
api     1        1        256
$ convox scale -a app api --count 2
NAME    DESIRED  RUNNING  MEMORY
api     0        1        256
$ convox scale -a app
api     0        0        256
```

 I'm using the `-a app` flag to select my app instead of being in the appropriate directory. When I made an `app` directory things worked normally:

```
$ mkdir app
$ cd app
$ convox scale
NAME    DESIRED  RUNNING  MEMORY
api     1        1        256
$ convox scale api --count 2
NAME    DESIRED  RUNNING  MEMORY
api     2        1        256
$ convox scale -a app
api     2        2        256
```

Thanks. Convox is pretty great so far.

**Comment by nzoschke** [comment]
Thanks for the report. This is pretty scary, we'll get it fixed ASAP.

I made a change recently based on reports that scaling to 0 was broken. Maybe this is a side effect:

https://github.com/convox/rack/commit/ce0328d8beb9d0b533abc5d21f9ecc80aef06fe3

**Comment by xer0x** [comment]
Thanks @nzoschke appreciate it.

**Comment by nzoschke** [comment]
One problem: if no --count is specified it scales to 0

```
$ convox scale --app httpd web
web   0        2        256   
```

**Comment by nzoschke** [comment]
Surprised to see that the order of the flags matters. I'm printing the arguments to client.SetFormation:

```
$ convox scale -a httpd --count 2 --memory 256 web
"httpd" "web" "2" "256"
NAME  DESIRED  RUNNING  MEMORY
web   2        0        256 

$ convox scale -a httpd web --count 2 --memory 256 
"httpd" "web" "" ""
NAME  DESIRED  RUNNING  MEMORY
web   2        0        256 
```

**Comment by nzoschke** [comment]
This is a regression based on my change. No explicit value for count is eventually turning into a zero.

**Comment by nzoschke** [comment]
Patch here: https://github.com/convox/rack/pull/415

**Comment by xer0x** [comment]
Awesome!

**Comment by nzoschke** [comment]
For the record I couldn't reproduce the app flag part of this...

**Comment by xer0x** [comment]
Odd that you didn't also see the app flag behaviour. Anyways, I think you've fixed the issue since your example about the order of the flags matches my problem example too.

```
$ convox scale -a httpd web --count 2 --memory 256 
"httpd" "web" "" ""
NAME  DESIRED  RUNNING  MEMORY
web   2        0        256 
```
