### ISSUE TITLE
`convox uninstall` and `convox rack uninstall` with safety checks

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#411]
I was trying to clean up some of our test racks:

```
$ convox update
OK, 20160302220151
$ convox uninstall


     ___    ___     ___   __  __    ___   __  _
    / ___\ / __ \ /  _  \/\ \/\ \  / __ \/\ \/ \
   /\ \__//\ \_\ \/\ \/\ \ \ \_/ |/\ \_\ \/>  </
   \ \____\ \____/\ \_\ \_\ \___/ \ \____//\_/\_\
    \/____/\/___/  \/_/\/_/\/__/   \/___/ \//\/_/



Uninstalling Convox...
ERROR: InvalidClientTokenId: The security token included in the request is invalid.
	status code: 403, request id: 5ee64df0-e146-11e5-8071-e308c9ce5cab
```

This rack was originally created via Grid, with a `convox` admin user which has since been deleted.

**Comment by mwarkentin** [comment]
Looks like this was an issue with how I ran this - had `AWS_*` env vars set for a separate account. Error message could have been more clear.

I was actually expecting that `rack uninstall` would uninstall the currently active rack - not default to the `convox` rack. Also wasn't expecting that it required separate IAM credentials.

**Comment by mwarkentin** [comment]
Some other raw feedback from when we were cleaning up racks:

```
@Rob Can you delete your `rvanoo` convox rack + services? Going to create our first official racks, and want to make sure things are cleaned out first (I think our racks + apps were created before they had full namespacing)
Rob van Oostrum·9:47 AM
ok uninstalling our racks now
Michael Warkentin·9:47 AM
@Rob Did you uninstall mine as well? I was in the middle of that, trying to figure out a CLI error
Rob van Oostrum·9:47 AM
the CLI is a bit inconsistent ... so I inadvertently pooched your test rack as well ... didn't even need to be logged into it
Michael Warkentin·9:47 AM
Or did mine work?
How'd you do that?
Rob van Oostrum·9:48 AM
convox rack -> shows the rack I'm logged into
convox uninstall -> uninstalls the "convox" rack by default
Michael Warkentin·9:48 AM
Ah.. gotcha
Rob van Oostrum·9:48 AM
you have to explicitly name the rack you want to uninstall otherwise
Michael Warkentin·9:48 AM
Yeah, we're not going to have a default "convox" rack at all when the new ones are set up
Rob van Oostrum·9:48 AM
good
Michael Warkentin·9:48 AM
So that shouldn't be an issue
Rob van Oostrum·9:49 AM
it's a bit scary though, it doesn't ask for confirmation at all
Michael Warkentin·9:49 AM
@Rob I think that's because I had already deleted my apps:
Rob van Oostrum·9:49 AM
it'll just error out if you have apps
Michael Warkentin·9:49 AM
convox uninstall: uninstall convox from an aws account
Usage:
  convox uninstall [credentials.csv]
Options:
   --force                      uninstall even if apps exist
Rob van Oostrum·9:49 AM
still won't tell you what exactly it's deleting
the error is just generic: ERROR: Please delete all apps before uninstalling.
so I deleted my apps
and then all of a sudden it seemed to uninstall the rack, so it may just have been that your apps finished uninstalling around the same time
anyway ... it'll be locked down once the racks are up and running so hopefully it's not something we have to worry about day-to-day
ok both racks are gone
nothing showing up in CloudFormation anymore
```

**Comment by mwarkentin** [comment]
Would be nice to have a confirmation message, or even put a little bit of friction in by either prompting for the rack name to uninstall, or `convox uninstall --confirm rack-name`.

**Comment by nzoschke** [comment]
Thanks. Anything that could accidentally operate on the wrong stack or pick up the wrong AWS creds could be disasterous. I renamed the issue to reflect the nature of this.

I'm leaning towards making everything explicit here. Stack name, region, and AWS account credentials need to be explicitly passed in as arguments or prompted for, no defaults or detection.

**Comment by nzoschke** [comment]
I also want a `convox racks uninstall` that talks to the convox API and starts the self-destruct. This also needs friction, but will get around the need to supply any options, since the running rack knows everything.

**Comment by mwarkentin** [comment]
@nzoschke Both of your suggestions sound reasonable to me!

**Comment by nzoschke** [comment]
I also observed that `convox uninstall` checks apps on whatever rack you are logged into, which doesn't necessarily match the --stack-name parameter

**Comment by nzoschke** [comment]
I'm going to work on this now due to seeing a fair amount of uninstall challenges out in the wild. Some problems I have seen in order of occurrence:

* Can't uninstall rack with active services. Presumably because of the auto-installed convox-events service
* Failure hitting /apps to check that no apps exist. Presumably uninstalling bad racks
* "No such file or directory" error. Presumably from a bad argument for the file to read credentials from
* InvalidClientTokenId or SignatureDoesNotMatch. Presumably from bad credentials
* Can't uninstall rack with active apps.
* Stack deletion failed. Presumably actually rack cloudformation bug
* Cannot be deleted with in status UPDATE_ROLLBACK_IN_PROGRESS

The vast majority of these can be eliminated with:

* Better pre-flight credential validation
* Better pre-flight stack status checks
* Automatic service / stack deletion that doesn't need a working Rack API

**Comment by nzoschke** [comment]
I also think the argument improvements discussed here are good too. Going to pick this off now.

**Comment by nzoschke** [comment]
This is fixed in https://github.com/convox/rack/releases/tag/20160526133520
