### ISSUE TITLE
Pass app environment to build context

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#416]
In some cases we'd like to be able to switch build behaviors using variables in the Dockerfile. For example, passing DEVELOPMENT=true or =false.

Docker provides for this with the ARG instruction https://docs.docker.com/engine/reference/builder/#arg

A straightforward way to do this would be to pass the application's environment to `docker build` as a series of `--build-arg` options. This is very similar in spirit to Heroku's user-env-compile labs feature.

**Comment by xtfxme** [comment]
"If a user specifies a build argument that was not defined in the Dockerfile, the build outputs an error: One or more build-args were not consumed, failing build."

I think you'd have to enumerate the `ARG` lines from the target Dockerfile to make it work like that (is there an existing programmatic way to analyze a dockerfile?). Honestly I'm not sure you want to conflate env args and build args.

Now, if convox instead add support for version 2 of docker-compose.yml, there is a dedicated section for this: https://docs.docker.com/compose/compose-file/#args

**Comment by nzoschke** [comment]
There is an issue for Build Environment here. Can you move your request to the discussion there? Thanks.
