### ISSUE TITLE
Expose release info to containers

### ISSUE THREAD

**Issue by andykent** [convox/rack#417]
It would be really helpful if you were able to introspect the current release from within a container. My current usecase is for tying error and metrics reporting to a release but I'm sure there are other usecases too.

If possible I'd love the information to be injected into the container via ENV variables (so just merged with the other env coming out of S3 I guess)...

`CONVOX_RELEASE` would be most helpful to me but maybe `CONVOX_RACK` and `CONVOX_PROCESS` could be useful too?

**Comment by nzoschke** [comment]
`RELEASE` and `PROCESS` are already set in the env!

```
$ convox run --app httpd web env
HTTPD_VERSION=2.4.18
HOSTNAME=efe98388239a
HOME=/root
TERM=xterm
KINESIS=httpd-Kinesis-4DIKJSD5YZ0S
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/apache2/bin
LOG_GROUP=httpd-LogGroup-NY1QC12433FB
PROCESS=web
HTTPD_PREFIX=/usr/local/apache2
RELEASE=RRPVRYXBVWQ
PWD=/usr/local/apache2
HTTPD_BZ2_URL=https://www.apache.org/dist/httpd/httpd-2.4.18.tar.bz2
```

RACK makes sense too. If that is important to you can you update the issue title to just RACK?

Cluster (e.g. convox-Cluster-1E4XJ0PQWNAYS) is already an app parameter and could easily be added to the env the same way KINESIS and LOG_GROUP are.

https://github.com/convox/rack/blob/master/api/models/templates/app.tmpl#L445

os.Getenv("RACK") could be injected into the  .EnvMap easy enough too:

https://github.com/convox/rack/blob/master/api/models/manifest.go#L342

FYI, the rest of the environment, including RELEASE, is stored encrypted in S3 and decrypted in the custom task definition handler.

The `CONVOX_` namespace is a good idea too, though I haven't seen reports of any problems not having that prefix yet.

**Comment by mwarkentin** [comment]
+1 on `CONVOX_` namespace - seems reasonable to prevent possible collisions in the future.

**Comment by stevepereira** [comment]
+1 to namespacing

**Comment by mwarkentin** [comment]
In addition to prevent problems, it would make it easy to see all of the params at a glance with a simple `env | grep CONVOX`

**Comment by nzoschke** [comment]
Yeah, namespacing makes sense.

`CONVOX_REGION` would be helpful too

**Comment by bitwalker** [comment]
+1 for `CONVOX_REGION`, I actually have a use for that currently, and I'm just populating it manually

**Comment by nzoschke** [comment]
`CONVOX_APP` would be helpful too.

**Comment by ddollar** [comment]
I would prefer to not use a `CONVOX_` namespace as there is a greater chance we can get everyone to agree to some sort of standard for these environment variables if they are more generic. It's much easier for a random library to pluck something like `PORT` out of the environment rather than having to check for `CONVOX_PORT` and many others.
