### ISSUE TITLE
convox login, switch, rack and racks enhancements

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#424]
Collecting various issues here... Login and switch is often surprising or confusing. 

As reported by @mwarkentin here https://github.com/convox/rack/issues/419

* Improved error messaging / docs
* `convox install` shouldn't mess with your login if you’re already logged in to convox
* If you are logged in to grid automatically add the newly-installed rack to grid

I'm frequently juggling multiple racks for dev and support work.

* You should be able to operate on two different racks from two different shells

**Comment by nzoschke** [comment]
Adding `rack` and `racks` subcommands to the list of things to tighten up.

I propose two commands: `convox auth` and `convox racks` 

These can handle pretty much everything related to authing Console vs a rack directly, and listing, switching, and updating racks.

**Comment by cliveza** [comment]
When using convox switch on one machine it changes the rack a second machine was previously accessing.

**Comment by nzoschke** [comment]
Yeah, this behavior is confusing and a potential deal breaker for automated deployment tools. A fix is in the works

**Comment by ddollar** [comment]
Closed by #691
