### ISSUE TITLE
command in docker-compose.yml using *shell form* and not *exec form*

### ISSUE THREAD

**Issue by soulware** [convox/rack#430]
Specifying a `command` in docker-compose appears to always use the *shell form* and not the *exec form*. App runs as subcommand of `/bin/sh -c` (and does not handle signals correctly etc.) and there does not appear to be a way to prevent this.

My understanding is docker-compose.yml should use *exec form* by default.

### `command` in docker-compose.yml overriding default `CMD` in Dockerfile

Dockerfile -
```
FROM node:0.10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH="$PATH:/usr/src/node_modules/.bin"
COPY package.json /usr/src/
RUN cd /usr/src && npm install

COPY . /usr/src/app

CMD [ "npm", "start" ]
```

docker-compose.yml -
```
web:
  build: .
  command: npm start
  ports:
    - 3000:3000
  volumes:
    - .:/usr/src/app
```

Result (subcommand of `sh -c`) -
```
$ convox ps --app express
ID            NAME  RELEASE      SIZE  STARTED        COMMAND
ede8247f8f91  web   RKHIFBJEUAM  256   7 seconds ago  sh -c 'npm start'
```

npm is not pid 1 -
```
root@ede8247f8f91:/usr/src/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4336   720 ?        Ss   13:05   0:00 sh -c npm start
root         6  0.1  0.8 834780 35496 ?        Sl   13:05   0:00 npm
```

### No `command` in docker-compose.yml, default `CMD` in exec form in Dockerfile

Dockerfile -
```
FROM node:0.10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV PATH="$PATH:/usr/src/node_modules/.bin"
COPY package.json /usr/src/
RUN cd /usr/src && npm install

COPY . /usr/src/app

CMD [ "npm", "start" ]
```

docker-compose.yml -
```
web:
  build: .
  #command: npm start
  ports:
    - 3000:3000
  volumes:
    - .:/usr/src/app
```

Result (no subcommand) -
```
$ convox ps --app express
ID            NAME  RELEASE      SIZE  STARTED       COMMAND
54c9e709fa1b  web   RTNYIAOJNZD  256   1 minute ago  npm start
```

npm is pid 1 -
```
root@54c9e709fa1b:/usr/src/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  1.3  0.8 834772 35652 ?        Ssl  13:13   0:00 npm
```

From testing it looks like this behavior exists with `entrypoint` also.

**Comment by soulware** [comment]
Running `docker-compose up -d` locally gives the expected result in both scenarios - 

```
$ docker-compose ps
    Name         Command    State           Ports          
----------------------------------------------------------
express_web_1   npm start   Up      0.0.0.0:3000->3000/tcp 
```

The only way to get npm to run as a subcommand of `/bin/sh -c` locally is to use the `shell form` in Dockerfile and not override it in docker-compose.yml.

```
# CMD [ "npm", "start" ]
CMD npm start
```

```
$ docker-compose ps
    Name              Command          State           Ports          
---------------------------------------------------------------------
express_web_1   /bin/sh -c npm start   Up      0.0.0.0:3000->3000/tcp 
```

**Comment by anthonyrisinger** [comment]
The `docker-compose.yml` docs say the `command` line can be expressed as a string or array (unsure if convox supports both):

```yaml
command: bundle exec thin -p 3000
command: [bundle, exec, thin, -p, 3000]
```

How could the string form *not* use the shell? It has to perform word-splitting to extract the arguments. Is this the expected behavior of docker compose? Feels like an oversight/regression to me. I would expect the yaml file to always override the Dockerfile, and if the yaml file uses the string form, I would expect it to then use the shell.

It seems like this issue wants the yaml `command` to be unconditionally processed as an array (even though word-splitting must be performed first to make it an array) but I can't find anything suggesting that's expected or preferred, or any reasoning why it should work that way (except the fact docker compose is currently doing that). What about `ENV` vars? Shouldn't the yaml string form process those just like the string form of `CMD` does in a Dockerfile?

Did I misunderstand the request or the docs? Is this a bug in docker compose?

**Comment by soulware** [comment]
I *think* this is a bug in the convox approach to using docker-compose. From my testing docker-compose always uses `exec form` locally. I assume it must split on whitespace. And I'm ~~99%~~ 70% sure I read something to this effect somewhere (but cannot find the reference now).

I believe docker-compose uses `exec form` due to the way you can override both `command` and `entrypoint` and it almost never makes sense to use `shell form` when combining the two.

But that said - I would definitely expect convox to preserve the intent with this (definitely an issue) - 

```
command: [bundle, exec, thin, -p, 3000]`
```

**Comment by soulware** [comment]
Some additional investigation showing the ECS Task Definition is likely being generated incorrectly.

The following ECS Task Definition is created when specifying the command in docker-compose.yml as - 
   * `command: npm start` 
   * `command: [npm, start]`
   * `command: ["npm", "start"]`

```
{
  "requiresAttributes": [],
  "taskDefinitionArn": "arn:aws:ecs:us-west-2:878712717934:task-definition/convox-test-express-web:10",
  "status": "ACTIVE",
  "revision": 10,
  "containerDefinitions": [
    {
      ...
      "command": [
        "sh",
        "-c",
        "npm start"
      ],
      ...
    }
  ],
  ...
}
```

With the following running container in convox - 

```
$ convox ps
ID            NAME  RELEASE      SIZE  STARTED        COMMAND          
8ac35de7c8de  web   RFFXUUQTFKF  256   4 minutes ago  sh -c 'npm start'
```

Manually updating the command in the task definition to - 

```
"command": [
  "npm",
  "start"
],
```

Results in the following running containers - 

```
$ convox ps
ID            NAME  RELEASE      SIZE  STARTED         COMMAND          
050eba16ea78  web   RLIWDVTJXHV  256   53 seconds ago  npm start
```

**Comment by nzoschke** [comment]
This was fixed on https://github.com/convox/rack/pull/449
