### ISSUE TITLE
Custom env vars on rack instances

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#433]
Rack instances can already be customized by using a custom AMI, or via custom UserData (ref: https://github.com/convox/rack/issues/356). These will allow logging + monitoring agents to be installed easily.

Many of these agents are customizable via environment variables. It would be nice if we could configure these agents via Convox as well, without having to add a bunch of extra code to custom UserData or writing something which pulls and initializes env variables from another source.

It looks like some code to handle this is already written: https://github.com/convox/rack/blob/master/api/models/environment.go#L116-L148

This could be exposed to the end user via similar CLI as `convox env` - instead of setting app variables, you could have `convox rack env set` and `convox rack env get`.

**Comment by nzoschke** [comment]
I really like this idea, particularly to help the logging / monitoring agent use case.

If you set a new rack environment variable, what is the expectation? Rolling all the instances is the cleanest way to get the change out but heavy.

**Comment by mwarkentin** [comment]
Obviously it'd be nice if this was a quick set operation, but I'm not clear on how that would work.

Rolling the rack seems reasonable to me, at least as a starting point:

* I wouldn't expect to be making env changes to the rack very often - likely a few when I'm first setting it up, and then sporadically after that
* If I have multiple environment variables to set, it would be nice if I could do it without rolling the rack each time - either allow me to set multiple values (not sure if `convox env set` supports this right now or not), or let me "stage" several envs before applying them by rolling the rack

**Comment by mwarkentin** [comment]
This could potentially leverage the new [Systems Manager Parameter Store](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/systems-manager-paramstore.html) announced at re:invent 2016.

It provides a [`get-parameters` CLI command](http://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameters.html) which could be used during instance bootstrap.

* https://www.youtube.com/watch?v=Me2xbKzxbq8
* https://www.youtube.com/watch?v=2ZqmRSIqQ6Q

**Comment by mwarkentin** [comment]
Parameter Store limits were bumped recently:

```
| Maximum number of parameters per account | 1000            |
| Max size for parameter value             | 4096 characters |
| Max history for a parameter              | 100 past values |
```

**Comment by MiguelMoll** [comment]
Could this issue be addressed with the new [convox.agent](https://convox.com/docs/docker-compose-labels#convoxagent) label?

**Comment by mwarkentin** [comment]
@MiguelMoll I'm not sure I understand. Do you mean using the `convox.agent` label to set environment variables somehow, or just that we can run all of our monitoring inside of containers now?

The latter may be true, but also may not be.. would need to look at each agent we run.

**Comment by MiguelMoll** [comment]
I should've been explicit. I did mean the latter. Running tools in a container so that environment variables can be set like other apps.

**Comment by mwarkentin** [comment]
Here's a list of agents we're running on the instance, unsure if they can all be run in docker or not (but obviously no guarantee that everything will be):

* rsyslog
* newrelic server monitoring
* datadog (can be run in docker, but we're not yet)
* threatstack

**Comment by MiguelMoll** [comment]
Thanks for reporting back. I see what you mean. It would still be nice to have instance-level environment variables for _X_ reasons.

**Comment by mwarkentin** [comment]
https://engineering.ticketea.com/securely-access-aws-parameter-store-from-your-elastic-beanstalk-docker-containers/
