### ISSUE TITLE
Inconsistencies in some commands (-a and -h flags in particular)

### ISSUE THREAD

**Issue by anthonyrisinger** [convox/rack#435]
I think there is another ticket about `-h` and `--help` not always working, but this specific request is about `-a` and `--app`. They're ignored if passed too early:

```
# convox scale main --app=manage --count=2
NAME  DESIRED  RUNNING  MEMORY
main  2        3        256
```

works, but:

```
# convox scale --app=manage main --count=3
ERROR: no updates are to be performed: manage
```

does not. The help text is not clear about this, and `--app` feels like something that can pretty much show up anywhere and still be valid (similar to git and `--git-dir` setting the context for later subcommands). Can this be supported with the argument parser in use?

**Comment by mwarkentin** [comment]
This trello ticket is the only reference I could find for refactoring help usage, although I've seen it discussed in chat, etc.

https://trello.com/c/Tvmw39hM

**Comment by nzoschke** [comment]
Help is fixed. Subcommands need to explicitly handle the flag.

Agreed --app should be able to go anywhere. I'm still not exactly sure why the parser thinks the two examples you shared are different. I bet it can be sorted out tho.

**Comment by ddollar** [comment]
Most of these should be fixed now
