### ISSUE TITLE
Add ability to do `convox ps` for all apps in a rack

### ISSUE THREAD

**Issue by aisipos** [convox/rack#443]
Sometimes when addressing issues relating to your entire rack it would be helpful to see all processes running in all apps in a rack. There is no current option for `convox ps` to do that, having one could be helpful.

**Comment by anthonyrisinger** [comment]
Dupe of https://github.com/convox/rack/issues/272 methinks :-)

**Comment by nzoschke** [comment]
This is a duplicate of https://github.com/convox/rack/issues/272. Closing in favor of that.
