### ISSUE TITLE
Auto spin up VPN instance when using --private-api

### ISSUE THREAD

**Issue by frankleng** [convox/rack#444]
be nice to have convox spin up a vpn instance when installing a new rack in private mode

**Comment by nzoschke** [comment]
That would be rad. @cleblanc87 left some breadcrumbs on the original PR https://github.com/convox/rack/pull/214

> I have been using https://docs.openvpn.net/how-to-tutorialsguides/virtual-platforms/amazon-ec2-appliance-ami-quick-start-guide/ for access, but will be relying on vpc peering for actual deployment

The OpenVPN appliance looks like Cloudformation which is promising. However the marketplace, options, and configuration all looks daunting to me.

**Comment by matthewford** [comment]
Its can be a bit of a pain to setup, restricting ssh to a set of IPs - so you can at least use your existing VPN would be nice tho.

**Comment by adamenger** [comment]
Can't we just spin up a bastion for the user instead? Communicating to http services behind a bastion is quite trivial if we could generate an SSH config for them to plop onto their workstation. 

Additional benefits include zero server side maintenance and config given that the instance remains healthy.

**Comment by soulware** [comment]
Have you considered ZeroTier as an alternative to spinning up a VPN instance?
https://www.zerotier.com/
Looks like this may potentially be a nicer solution to handling secure connections into AWS.

**Comment by ddollar** [comment]
We have some plans to allow you to bring your own networking layer to the Rack but will probably not support creating specific individual configurations like this. Going forward things will look like a choice between using the network the Rack provides or bringing your own entirely.
