### ISSUE TITLE
List available racks from Convox CLI

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#445]
There should be a command to list available racks. The `convox switch` error message already does this, so the data is available. This is basically a UX task.

**Comment by aweagel** [comment]
:+1: Something like `convox racks` then `convox switch <rack>` seems like a natural / common workflow

**Comment by awsmsrc** [comment]
WIP PR here: https://github.com/convox/rack/pull/447

**Comment by nzoschke** [comment]
This is released.

```
$ convox racks
RACK               STATUS 
convox/staging     running
convox/demo        running
convox/production  running
personal/dev-east  running
personal/west      running
```
