### ISSUE TITLE
docker-compose v2 support

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#452]
Kamal on slack inquired about the following error:

```
$ convox deploy 
Deploying envoy-web 
Creating tarball... OK 
Uploading... OK 
ERROR: yaml: unmarshal errors: 
line 1: cannot unmarshal !!str `2` into manifest.ManifestEntry
```

This happens with a docker-compose.yml that looks like:

```yaml
version: 2

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    volumes:
      - .:/app

  worker:
    build: .
    command: bundle exec sidekiq -q critical -q entries -q box -q default -v
```

**Comment by warmwaffles** [comment]
In the docker compose docs for those that are curious https://docs.docker.com/compose/compose-file/#version-2

**Comment by mwarkentin** [comment]
As per discussion in Slack, came across this docker Go lib to parse docker-compose files: https://github.com/docker/libcompose

There's an issue with a list of v1/v2 compatibility items: https://github.com/docker/libcompose/issues/124

**Comment by nzoschke** [comment]
Released in https://github.com/convox/rack/pull/508
