### ISSUE TITLE
Make Yes/No and true/false consistent in CF parameters

### ISSUE THREAD

**Issue by ddollar** [convox/rack#457]
As discovered in #386 and #428 we have some inconsistencies with how we handle booleans in various CloudFormation stacks. Some places use `Yes` and `No` while others use `true` and `false`. We should pick one and make them consistent (via conditions or whatever if necessary).
- [ ] rack formation
- [ ] app formation
- [ ] service formation

Places to update when this goes out:
- [ ] blog posts
- [ ] docs
- [ ] cli help text

**Comment by nzoschke** [comment]
It looks like true/false have a huge advantage of passing straight through for boolean fields.

If you set "Yes" as the value for a property like MultiAZ ([docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-multiaz)) you get the error:

> 19:13:25 UTC-0700   CREATE_FAILED   AWS::RDS::DBInstance    Instance    Encountered unsupported boolean value Yes

**Comment by mwarkentin** [comment]
+1 for sticking w/ `true` / `false` if that's simpler when passing params through to CloudFormation.
