### ISSUE TITLE
Deployment targets

### ISSUE THREAD

**Issue by ddollar** [convox/rack#458]
I propose we make app selection a bit more explicit:

```
$ convox deploy
ERROR: No default target.
Please add one with `convox targets add default` or specify --app.

$ convox targets add staging myapp-staging
Adding staging target... OK

$ convox targets add default myapp-staging --rack convox/staging
Adding default target... OK

$ convox deploy
Deploying to myapp-staging...

$ convox deploy staging
Deploying to myapp-staging...

$ convox deploy foo
ERROR: No target named foo
```

Creating an app should set the `default` target if it doesn't exist.

Config should be managed in `.convox`:

```
$ cat .convox/target/default/rack
convox/staging

$ cat .convox/target/default/app
console-staging
```

**Comment by ddollar** [comment]
Also add some easy way to get current target info for adding to a shell prompt.

**Comment by matthewford** [comment]
Can we include the rack in the target, i.e. wouldn't want to deploy to and other app called the same thing on a different rack.

**Comment by ddollar** [comment]
Yes, rack is included in the target
