### ISSUE TITLE
Rack instance hostnames

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#459]
It would be nice if convox set the rack instance hostnames - things like New Relic Server Monitoring use the hostnames to name the servers in the UI:

![](https://mwarkentin-snaps.s3.amazonaws.com/All_servers_-_New_Relic_2016-03-16_16-28-55.png)

Something like `<rack name>-<aws instance id>` would be good: `convox-stage-i-i-03de5a`

If convox info was exposed in environment variables on the servers themselves we could probably set this ourselves in our bootstrap script.

**Comment by mwarkentin** [comment]
I'm looking into if there's a way to pull this metadata out from the instance - I know I can get the instance ID from the local metadata - trying to find a good place to pull the convox stack name from.

**Comment by ddollar** [comment]
I can't find a way to pull it straight from metadata. You could, however, write `{ "Ref": "AWS::StackName"}` out to a file:

https://github.com/convox/rack/blob/master/api/dist/kernel.json#L875

**Comment by ddollar** [comment]
If you can find a way to set the hostnames to something nice that sounds really interesting too.

**Comment by mwarkentin** [comment]
@ddollar I tried writing the Ref out to a file in the InstanceBootCommand, but it didn't seem to work right:

Here's the start of the `InstanceBootCommand` - haven't figured out the right incantation yet:

```
convox rack params set InstanceBootCommand="echo { 'Ref' : 'AWS::StackName' } > /etc/convox/stack; ...
```

```
$ cat /etc/convox/stack
{ Ref : AWS::StackName }
```

Is writing values out to `/etc/convox` the canonical way you guys are handling references like this at the moment? Running into more places where having environment variables set could be useful as we're doing more instance configuration (https://github.com/convox/rack/issues/433).

**Comment by mwarkentin** [comment]
@ddollar Assuming we can get the components we want, it should just be something like this before running `InstanceBootCommand`:

```bash
FRIENDLY_HOSTNAME=$CONVOX_RACK--$INSTANCE_ID
hostname $FRIENDLY_HOSTNAME
```

**Comment by mwarkentin** [comment]
Confirmed that setting `hostname` as per above works:

![](https://mwarkentin-snaps.s3.amazonaws.com/All_servers_-_New_Relic_2016-03-17_10-14-17.png_908146_2016-03-17_10-17-25.png)

**Comment by nzoschke** [comment]
Another strategy would be to use the cluster name that is written to the disk for ECS configuration 

But I'd definitely accept a patch for writing /etc/convox/stack in userdata.
