### ISSUE TITLE
Allow users to start a shell in a running process

### ISSUE THREAD

**Issue by ddollar** [convox/rack#46]
`convox exec <pid> bash`

**Comment by ddollar** [comment]
This conflicts with the existing `convox exec` which needs to be re-thought. The `exec` here parallels Docker.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZxqYPy4P&#x2F;165-allow-users-to-start-a-shell-in-a-running-process"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Allow users to start a shell in a running process</a>

**Comment by nzoschke** [comment]
This was implemented in https://github.com/convox/rack/pull/64
