### ISSUE TITLE
Unable to audit use of `convox ssh` 

### ISSUE THREAD

**Issue by dlanger** [convox/rack#462]
The operator experience of `convox ssh` is great, but the lack of any type of logging on it makes it hard to integrate into a security solution. 

As an example, here's `/var/log/secure` from my using `convox ssh` to connect to one of our instances:
```
Mar 17 19:57:07 ip-10-0-4-154 sshd[10205]: Accepted publickey for ec2-user from 10.0.5.201 port 42952 ssh2: RSA f4:35:61:e1:f6:64:ac:44:70:0a:10:a2:95:7a:86:e3
Mar 17 19:57:07 ip-10-0-4-154 sshd[10205]: pam_unix(sshd:session): session opened for user ec2-user by (uid=0)
Mar 17 19:57:24 ip-10-0-4-154 sshd[10205]: pam_unix(sshd:session): session closed for user ec2-user
```
I'm not quite sure what I'd like to show up there - Grid username? How does that work if I'm not using Grid?

Ultimately, I need a log that I can send into my third-party logging system showing that the login at `Mar 17 19:57:07` was initiated by "me" (my local username, my Grid account, something), via `convox ssh`.

**Comment by nzoschke** [comment]
This applies to the proxy stuff that just landed in https://github.com/convox/rack/pull/475 too.

Definitely a big +1 for auditing these important access points.

**Comment by mwarkentin** [comment]
[bless](https://github.com/netflix/bless) is an interesting looking tool that runs on lambda - no idea what an integration with convox would look like, but food for thought!

**Comment by ddollar** [comment]
Console now logs usage of the SSH endpoint. We have been talking about cert-based SSH to provide some user context.

**Comment by dlanger** [comment]
@ddollar Can you drop a screenshot or link to what these logs are like?

**Comment by ddollar** [comment]
<img width="560" alt="screen shot 2016-09-21 at 10 33 37 am" src="https://cloud.githubusercontent.com/assets/3308/18715321/e2829d18-7fe6-11e6-80f8-58359959f0a3.png">
