### ISSUE TITLE
EC2 instances in Private racks shouldn't have public IPs

### ISSUE THREAD

**Issue by dlanger** [convox/rack#465]
Even though the public IP isn't accessible, it shouldn't have one. Slack discussion with @ddollar:

![image](https://cloud.githubusercontent.com/assets/529037/13883464/e8414de6-ecff-11e5-982d-1201a7c9f4de.png)

**Comment by snario** [comment]
This is important to me as well  -- we have some strict security requirements we need to adhere to for our clients.

**Comment by nzoschke** [comment]
I don't see any reason why instances need public IP addresses in either normal or private mode. Ingress can happen through the Rack API ELB and `convox instances ssh`.

**Comment by nzoschke** [comment]
Does the Public IP Address somehow affect the internet connectivity?

I tried this diff:

```diff
diff --git a/api/dist/kernel.json b/api/dist/kernel.json
index 34a6f05..5bcf0be 100644
--- a/api/dist/kernel.json
+++ b/api/dist/kernel.json
@@ -852,7 +852,7 @@
       "DependsOn": [ "Balancer", "Cluster", "InstanceProfile", "SecurityGroup", "Kinesis", "LogGroup" ],
       "Type": "AWS::AutoScaling::LaunchConfiguration",
       "Properties": {
-        "AssociatePublicIpAddress": true,
+        "AssociatePublicIpAddress": false,
         "BlockDeviceMappings": [
           {
             "DeviceName": "/dev/sdb",
```

But new instances all fail because of:

<img width="772" alt="screen shot 2016-05-26 at 3 48 24 pm" src="https://cloud.githubusercontent.com/assets/147410/15592539/66c6f76c-2359-11e6-8df4-d547166bb423.png">

**Comment by nzoschke** [comment]
Actually that makes sense. I think this does control attachment to the internet gateway in public mode. This patch is testing much better:

```
-        "AssociatePublicIpAddress": false,
+        "AssociatePublicIpAddress": { "Fn::If": [ "Private", false, true ] },
```
