### ISSUE TITLE
Support for eu-central-1 (Frankfurt)?

### ISSUE THREAD

**Issue by rjocoleman** [convox/rack#470]
> AWS Lambda is now available in the EU (Frankfurt) region.
> 
> AWS Lambda lets you run code without provisioning or managing servers. You pay only for the compute time you consume - there is no charge when your code is not running. With Lambda, you can run code for virtually any type of application or backend service - all with zero administration. Just upload your code and Lambda takes care of everything required to run and scale your code with high availability. You can set up your code to automatically trigger from other AWS services or call it directly from any web or mobile app.
> 

https://aws.amazon.com/about-aws/whats-new/2016/03/aws-lambda-available-in-eu-frankfurt/
https://docs.aws.amazon.com/general/latest/gr/rande.html#lambda_region

Last I was around the installer code the only blocker for installing a rack in `eu-central-1` was here: https://github.com/convox/rack/blob/master/cmd/convox/install.go#L60

**Comment by rjocoleman** [comment]
Sorry, my bad `eu-central-1` only has 2 AZs. I'm not sure if this is still a rack install blocker.

**Comment by felixbuenemann** [comment]
Well the help for instance count says "number of EC2 instances (must be greater than 1)", so I guess eu-central-1 should work…

**Comment by mwarkentin** [comment]
Related issues:

* https://github.com/convox/rack/issues/117
* https://github.com/convox/rack/issues/513

**Comment by rjocoleman** [comment]
eu-central-1 only has 2 azs and thus isn't a supported by the subnet
creation lambda.. Unless that's changed.

**Comment by ddollar** [comment]
Will be fixed by #117
