### ISSUE TITLE
Consider lowering the default proc memory to 128MiB

### ISSUE THREAD

**Issue by anthonyrisinger** [convox/rack#471]
* Make people able to hit the ceiling so they can decide if they need more.
* 64 is a better development target but too small for default
* 35+ active procs right now doing a variety of things with minimal (less than 1/3) utilization with mix of Go, Node, Elixir, and Python procs
* With marathon/mesos we used 128MiB company wide and it was *rarely* adjusted
* Convox runs it's own procs at 128 and 64
* If it's all the same to everyone, might be nice way to fake doubling a racks default capacity without any adverse effect
* If I go over 128 my proc is probably leaking, if not I will adjust it myself accordingly

IME 128 is more than enough, but there is some concern less frugal runtimes like Ruby and Perl might struggle... perhaps #353 along with some heuristics in `convox init` can help with that. Also containers that combine many processes (eg. they run nginx + app + process manager or something) may certainly need to bump the limit, but container best practices recommend against such things anyway (containers should behave as much like a single process as possible) unless there is a need.

I know the limit can be adjusted after the fact (or on first deploy with #353) but this change would probably let most people pack more apps into their rack. I very much doubt many people *lower* the default memory allocation.

**Comment by nzoschke** [comment]
Thanks for opening the discussion. My only concern is what a rails app would do out of the box. As long as it runs and doesn't OOM a small default is nice since it can be scaled up any time.

**Comment by nzoschke** [comment]
Definitely considering this. The context I have:

* 256 was chosen arbitrarily, also biasing towards small dev processes, not scaled processes
* 128 is very reasonable for lots of use cases in lots of languages
* 128 should be enough for a simple rails 4 app ([anecdotal 127 MB test](https://blog.wiemann.name/rails-server/))
* Convox offers some log and metric visibility around OOMs ([agent](https://github.com/convox/agent/blob/master/containers.go#L170))
* 128 has been fine for the convox API and registry processes

**Comment by ddollar** [comment]
Closing this for now. Most newer users are running into problems in the other direction.
