### ISSUE TITLE
Destroy ELB when process scaled to `0`

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#472]
When my `docker-compose.yml` has a `redis` or `postgres` service defined, but I'm using an external service on convox, I scale that process to `0`, as I don't need those containers running.

However, the ELB which has been created for these processes sticks around, and costs me money (I believe $18/month/ELB).

The ELB should either be removed when I scale to `0`, or I should have some way of specifying that I want the ELB removed (option on `convox scale`?).

**Comment by mwarkentin** [comment]
Slack logs:

> mwarkentin [4:50 PM] 
Looks like ELBs are created and stick around even for internal processes scaled down to 0 (eg. redis) - thoughts on destroying the ELB in that case?

> ddollar [5:09 PM] 
@mwarkentin: i think we should.. we can now.. before the names were not deterministic so it would break dns if you scaled to 0 and back up

> [5:09] 
but i think it should be ok now

**Comment by anthonyrisinger** [comment]
ELBs end up looking like this: `barebones-main-ABG7T5Z-755141446.us-east-1.elb.amazonaws.com`

The `barebones-main` part is stable for the lifetime of the process's stack. The `ABG7T5Z` part is a b32 encoded hash of various things and is also stable. Is there a way to make the AWS generated `755141446` part stable?

My guess is no, but if so, is there *any* way to implement this? I hope so because scaling the ELB to nothing makes perfect sense.

**Comment by mwarkentin** [comment]
I'm not too clear on where all we need to be able to reference the ELB id - is the issue that we need to be able to reference it in order to register our containers with the ELB in ECS if we scale it back up?

**Comment by anthonyrisinger** [comment]
The only real hangup is the fact that someone might create a CNAME entry like `barebones.pretty.tld` mapped to `barebones-main-ABG7T5Z-755141446.us-east-1.elb.amazonaws.com`, but after a delete/recreate cycle the integer appended to the end changes from:

`barebones-main-ABG7T5Z-755141446.us-east-1.elb.amazonaws.com`

to

`barebones-main-ABG7T5Z-644141557.us-east-1.elb.amazonaws.com`

Even though the inputs to CF were identical (`barebones-main-ABG7T5Z`), the resultant ELB name uses `644141557` instead of `755141446`, so DNS fails. I think we can test by creating/deploying an app, deleting it, then create/deploy again. if the ELB hostname comes out *identical* (AWS decides to reuse the previously generated name), things might work. My hunch is that this number is random... it's what I would do :-(

**Comment by mwarkentin** [comment]
Could we use a similar strategy as https://github.com/convox/rack/pull/505 to mark a process as non production?

Something like:

```
web:
  build: .
  ports:
    80:80
redis:
  image: convox/redis
  labels:
    - "com.convox.localonly=true"
```

This could trigger an automatic scaledown to `0`, or even prevent the service from being created in the first place, as well as removing the ELB.

**Comment by nzoschke** [comment]
There are a couple things here that we should tease apart.

## How do you best swap out redis and postgres with an ElasticCache or RDS?

We do plan to (re) introduce the concept of service linking to an app. This already exists for syslog and papertrail which are simple subscriptions that don't modify the app. Next up is adding linking as a way to replace a container with a service:

`convox services link myrds postgres -a myapp`. 

This will create a new release of your app that no longer has a ECS Task, Service or ELB for the postgres container, and sets POSTGRES_URL to the RDS on other processes.

Right now we're still in flux here relying on documentation that tells you to manually scale the process down.

## Does scale any process type to 0 destroy the ELB to save money?

I'm curious if there are use cases other than these databases. Autoscaling or something?

**Comment by mwarkentin** [comment]
Cool - that linking sounds neat, I also like injecting the environment variable as well.

We haven't hit any use cases for this outside of redis (and rds eventually), but the most obvious would be an internal app that's only run during business hours to save money.

TBH, redis/rds are our main use case - so if that's resolved via linking, I'm happy leaving it at that.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4JyGJvE2&#x2F;199-elb-removal-when-scaled-to-0"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> ELB removal when scaled to 0</a>

**Comment by mwarkentin** [comment]
One other thing to keep in mind - many people will probably have non-convox managed services (eg. manage their own RDS/elasticache, use compose.io, use heroku postgres, etc.) - so it'd still be nice if they could remove the service / ELB for redis/db containers, even if they're not linking to a convox service.

**Comment by beedub** [comment]
> I'm curious if there are use cases other than these databases. Autoscaling or something?

During DB maintenance, we like to shut down the app to disconnect all connections, so it would be a big nuisance to have the ELB destroyed and created again

**Comment by nzoschke** [comment]
@beedub interesting, and good use case. Maybe we add a way to differentiate between scale to zero and totally destroy...

Count=-1 -> No Service / ELB, Count=0 -> Service with Count=0 and and ELB

I'm working on this now so good time to get the design right

**Comment by mwarkentin** [comment]
`count==-1` would work for me..

**Comment by nzoschke** [comment]
I don't think we can actually do -1 as a CloudFormation numeric parameter. New idea is to add one more process parameter:

`WebDisabled = Yes/No`

**Comment by mwarkentin** [comment]
How is `-1` not a number? Damn you Cloudformation...

In your suggestion, `Web` would actually be `<ProcessName>` I assume? So we could do `RedisDisabled`, `DatabaseDisabled`, etc.?

Will this have a corresponding label for `docker-compose.yml` as well?

**Comment by nzoschke** [comment]
I was guessing, but it turns out you can use -1 as a parameter. That feels better than adding yet another boolean.

**Comment by mwarkentin** [comment]
👍

**Comment by nzoschke** [comment]
@mwarkentin a label could make sense but I'd like to keep scope and design in check and release the core parameter change without one.

**Comment by nzoschke** [comment]
This is fixed in https://github.com/convox/rack/releases/tag/20160602143119.

Scale a process type to `-1` to destroy the ELB and ECS service.
