### ISSUE TITLE
More meaningful container hostnames

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#483]
By default the HOSTNAME of a container running in ECS is the Docker-generated random hostname. It's usually hex that looks like this: `ca89d71f07da`. A new hostname gets generated each time a container starts.

This is somewhat problematic for users who want to track host-specific metrics. For example, we have a user using New Relic who would rather see something more meaningful like `appname:processname` for example.

Is this something we can reasonably do? I know the `--hostname` option can be passed via Docker, but are there side effects to consider in the AWS deployment? For logging? Do hostnames have to be unique? What hostname should we set? Can we allow the user to set an arbitrary host name?

**Comment by nzoschke** [comment]
W.r.t. to New Relic, is it APM (App Performance Monitoring) or Servers that is confusing?

**Comment by mattmanning** [comment]
@nzoschke The user I'm working with is using New Relic APM, but they can still slice data by server (hostname). I would assume New Relic Servers has similar functionality.

FWIW, New Relic does have a "categories and labels" feature that would allow one to get around this issue with clever configuration, but I think having meaningful hostnames has other benefits besides New Relic convenience.

**Comment by nzoschke** [comment]
I'm not yet +1 on this idea. We can set a custom hostname in the TaskDefinition / ContainerDefinition:

http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html

```
hostname
The hostname to use for your container. This parameter maps to Hostname in the Create a container section of the Docker Remote API and the --hostname option to docker run.

Type: String

Required: No
```

But...

* `appname.processname` isn't right for process types that will be scaled >=2.
* `appname.processname.4` is tantalizing but almost impossible to coordinate.
* `appname.processname.7ecb31ec9e3f`? Would this improve the New Relic story or still effectively be random? And it's not obvious how to get between ECS and Docker to change this.

This is one of the big challenges in our migrations to containers. Containers are so much more ephemeral concepts like `hostname` barely mean anything compared to VMs.

**Comment by nzoschke** [comment]
Also did you see that we now are setting a RACK and APP environment variable for every process, in addition to PROCESS and RELEASE. And the hostname is the container id. So all the data you need for segmenting metrics is available at runtime.

**Comment by lisajluo** [comment]
+1 if we can have the option to set hostnames while disallowing scaling on those processes with hostnames (something like rack.appname.processname).

**Comment by ddollar** [comment]
Closing in favor of #459

**Comment by mwarkentin** [comment]
@ddollar I don't think this is directly related to #459 - that was for the cluster instances, this one is for service containers.

**Comment by ddollar** [comment]
You're right! Triage fatigue :)

**Comment by mwarkentin** [comment]
Np - looks like you were blasting through quite a few. :)
