### ISSUE TITLE
Rack name conflict with app name can be confusing

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#490]
A customer ran into this problem. They have a rack called `company-production`. They tried to create an app with the same name and got this error:

```
$ convox apps create company-production
Creating app company-production... ERROR: there is already a legacy app named company-production (running). We recommend you delete this app and create it again.
```

(This error message is misleading. The conflict is with the rack, not a legacy app.) So the customer tried to delete:

```
$ convox apps delete company-production
Deleting company-production... ERROR: invalid app: company-production
```

which lead to more confusion.

Do stack name prefixes give us a way to get around this conflict? If not can we improve the initial error message to make things less confusing?

**Comment by nzoschke** [comment]
This error message can be improved because we have the rack stack name available as os.Getenv("RACK")
