### ISSUE TITLE
haproxy as an ELB alternative?

### ISSUE THREAD

**Issue by mojodna** [convox/rack#50]
Ponying up for an ELB for each app, regardless of size, is kind of a bummer (especially for the low-traffic one-offs). Since Convox is already tracking which apps are running where on an ECS cluster, it seems like it would be possible to have it use haproxy instead.

Is this on the roadmap anywhere?

**Comment by ddollar** [comment]
Unfortunately this is not on the Convox roadmap. Our primary design goal right now is to offload to AWS services whenever possible to save you the burden of operating (and debugging and wearing the pager for) a custom routing layer.

**Comment by davewasmer** [comment]
@ddollar - I think I know the answer here, but I wanted to double check - is there any way to share an ELB across multiple apps? If not, it seems like that automatically makes Convox more expensive than most hosted/managed alternatives for small apps.

Also, while I understand (and appreciate!) your point about the design goals behind Convox, would it be possible (now or at some point on the roadmap) to simply opt-out of the ELB-per-app, and perhaps allow a userland module to supply the haproxy?
