### ISSUE TITLE
Restrict ECS cluster to certain AZs

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#513]
A customer would like to run a 2-instance rack using reserved instances. To do this, he needs to be able to specify which 2 availability zones the instances boot in. Can we add a Parameter which holds a list of AZs to be used by the Autoscaling group? It could default to blank and only be used if populated.

**Comment by nzoschke** [comment]
A 2-instance reserved instance Rack does sound desirable. That could be a really cost effective way to run services.

However it's not the most straightforward patch. Some things to consider:

* The names set and name of availability zones you can use is different and random for every account. I believe AWS does this for their own workload balancing reasons.
* We have a Custom::EC2AvailabilityZones resource hack to make working with this easier. [Code](https://github.com/convox/rack/blob/master/api/cmd/formation/handler/ec2.go#L80)

* Some Regions don't have 3 AZs! There is a very old issue about this: https://github.com/convox/rack/issues/117. This work would close that out.

* We "hard coded" 3 Subnets, one for each AZ
* We "hard coded" 3 AZs in for AutoScalingGroup

There probably is a way to achieve this with a new Parameter, and `Condition` statements and `Fn::If` functions.

**Comment by nzoschke** [comment]
Here's one idea for a solution... 

* A `NumAZs` Parameter with allowed values [2, 3].
* A `ThreeAZ` Condition that is true if NumAZs=3
* Use the ThreeAZ condition on the `Subnet2`, `SubnetPrivate2`, `RoutesPrivate2`, `RoutePrivateDefault2`, `Subnet2Routes`, etc. Resources.
* Use Fn::If and AWS::NoValue around references to Subnet2 resources

Psuedo code:

```json
        "AvailabilityZones": [
          { "Fn::GetAtt": [ "AvailabilityZones", "AvailabilityZone0" ] },
          { "Fn::GetAtt": [ "AvailabilityZones", "AvailabilityZone1" ] },
          { "Fn::If": [ "ThreeAZs", 
            { "Fn::GetAtt": [ "AvailabilityZones", "AvailabilityZone2" ] },
            { "Ref": "AWS::NoValue" }
          ]}
        ],
```

**Comment by nzoschke** [comment]
I think you'll need to pass something new to the Custom::EC2AvailabilityZones handler too to work around the randomness in what it returns.

Perhaps you want not a `NumAZs` parameter but an optional `LimitAZs` parameter where you put in comma separated AZs `us-east-1a,us-east-1c`. Send this to the Custom::EC2AvailabilityZones and it can verify those AZs and return a map with only those AZs.

**Comment by nzoschke** [comment]
Here's something to ponder or experiment with... What if the `Custom::EC2AvailabilityZones` took a Parameters with a value of "us-east-1a,us-east-1b" and returned:

PhysicalID: us-east-1a,us-east-1b,us-east-1a
Data: {"AvailabilityZone0": "us-east-1a", "AvailabilityZone1": "us-east-1b", "AvailabilityZone2": "us-east-1a", "AvailabilityZone2": "us-east-1a"}

That is it still returns 3 AZs to refer to but it artificially only uses 2 for the values. This could potentially avoid a lot of CF conditionals.

However I'm not sure what would happen with two of the same values in the ASG AvailabilityZones list

```
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "Properties" : {
        "LaunchConfigurationName" : { "Ref": "LaunchConfiguration" },
        "AvailabilityZones": [
          { "Fn::GetAtt": [ "AvailabilityZones", "AvailabilityZone0" ] },
          { "Fn::GetAtt": [ "AvailabilityZones", "AvailabilityZone1" ] },
          { "Fn::GetAtt": [ "AvailabilityZones", "AvailabilityZone2" ] }
        ],
```

**Comment by ddollar** [comment]
I don't think we can easily restrict to certain AZs.

**Comment by chuckwu-aa** [comment]
Any plans to support it? It is good for RI instance cases.
