### ISSUE TITLE
Add logging when using local convox proxy

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#515]
After enabling `ProxyProtocol` locally, I had to verify that it was functional by manually testing my application and double-checking that the nginx config was expecting `ProxyProtocol` and responding w/ `200`s. Adding some logging to the output on `convox start` or when each request is proxied could be useful. 

Options:

* No logging (current)
  * Pro: simple, low (no) volume
  * Con: no indication of any manipulation done by convox when you start your app
* Log on start up
  * Pro: visible change when you enable proxy and start the app
* Log on each request
  * Pro: Extra detail possible - log header added to each request, etc.
  * Con: High volume, could be noisy / make it harder to follow actual application logs

**Comment by mwarkentin** [comment]
CC @ddollar

**Comment by ddollar** [comment]
Closed by #516
