### ISSUE TITLE
Redis service customization

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#518]
In order to configure redis correctly for our current use case, we need the ability to modify some settings in a parameter group:
- `maxmemory-policy=allkeys-lru` (default: `volatile-lru`)
- `reserved-memory` to ~80% of total memory (default: `0`)

I see a few ways this could be supported: new parameters, or allow me to specify a custom parameter group which I define outside of convox (full definition of custom parameter groups within convox could be another, but that seems like a larger scope than this).
#### `MaxMemoryPolicy`

String.

Options (from [ParameterGroup docs](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/ParameterGroups.Redis.html#ParameterGroups.Redis.2-6-13):
- `volatile-lru` (default)
- `allkeys-lru`
- `volatile-random`
- `allkeys-random`
- `volatile-ttl`
- `noeviction`
#### `ReservedMemory`

Int. 

Default: `0`

Max: [`maxmemory` value for cache instance type](http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/ParameterGroups.Redis.html#ParameterGroups.Redis.NodeSpecific) (can probably lean on Cloudformation validation)
### Custom Parameter Group

A more flexible approach, which would let me generate and manage my ParameterGroup in any way I see fit (eg. we have Terraform profiles already for managing things which are outside of Convox' scope which we could leverage their [Parameter Group support](https://www.terraform.io/docs/providers/aws/r/elasticache_parameter_group.html)).

If we had a custom Parameter Group, the name of the group could just be passed in as a parameter to the redis service and applied via Cloudformation. This could be useful on any service which uses Parameter Groups (RDS, etc.).

**Comment by mwarkentin** [comment]
Looks like this could probably be considered a dupe of https://github.com/convox/rack/issues/461 - feel free to close if you think so too (although I'd like to keep the idea of using a custom parameter group in the discussion somewhere).

**Comment by ddollar** [comment]
The idea of using custom parameter groups by name has some merit but I'd want to think through how to manage these. For now perhapy we can solve these with `--param` from #461
