### ISSUE TITLE
Get just the URL of a service

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#532]
It would be nice to have a `--url` option on `convox services info`. That would enable easier scripting and command chaining like `convox env set WHATEVER_URL=$(convox services info whatever --url)`.

**Comment by mwarkentin** [comment]
Another option could be to have a `--json` option, which returns a json blob instead of the plain text version you get normally - then you could parse out whatever fields you want w/ `jq` or some other program.

I suppose this might already be an option if you use the `convox api` command instead?

**Comment by ddollar** [comment]
Yes, use `convox api` to get the JSON. Let's make this `convox services url <service-name>`
