### ISSUE TITLE
Build System Architecture Improvements

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#534]
Some more high level thoughts on the build system architecture:

- [ ] Document build system architecture
- [ ] Document build system metrics
- [ ] Document build pipeline commands
- [ ] Make cmd/build also PUT logs. Makes build process totally self-contained.
- [ ] Make cmd/build pull and push have access to rack env, but docker build run with restricted env
- [ ] Make it possible to schedule builds as ECS tasks. This would help find the most resources available to do a build.
- [ ] Add timestamps to build logs

**Comment by ddollar** [comment]
Fixed in #1231
