### ISSUE TITLE
convox apps error before any apps are created

### ISSUE THREAD

**Issue by nathany** [convox/rack#546]
This could fail more gracefully:

```
❯ convox apps
ERROR: unexpected end of JSON input
```

When the Rack installation log in Console finishes, it suggests running `convox apps`. But no apps have been created on the Rack yet.

**Comment by awsmsrc** [comment]
I just tried this locally and couldn't repro it?
I got an empty cli table

<img width="511" alt="screen shot 2016-06-03 at 12 37 54 pm" src="https://cloud.githubusercontent.com/assets/994907/15777540/0920d602-2988-11e6-8541-e478ea4fadf4.png">

**Comment by nathany** [comment]
Hi Luke. Maybe it was resolved since I reported it? This is what I see now:

```
❯ convox login                   
Password: 
Logged in successfully.
                                                                                
❯ convox apps
ERROR: response status: 500
```

**Comment by nathany** [comment]
That was client: 20160504204240, but I'm still seeing something different than you.

```
❯ convox update
OK, 20160602213113
                                                                                
❯ convox apps   
ERROR: response status: 500
```

**Comment by ddollar** [comment]
I believe this is no longer an issue but please reopen if you are still seeing it.
