### ISSUE TITLE
Convox logs dies after a while

### ISSUE THREAD

**Issue by jordan-thoms** [convox/rack#55]
Whenever I use the `convox logs` command, it exits after some period of time (sometimes a minute or two, sometimes longer). When it exits, it doesn't produce any error messages.

I assume that the websocket is getting disconnected?

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kTptzpQw&#x2F;179-convox-logs-disconnection"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> convox logs disconnection</a>

**Comment by nzoschke** [comment]
This was improved in https://github.com/convox/rack/pull/160
