### ISSUE TITLE
Log rotation for docker logs

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#552]
It appears that docker logs can grow quite large (800MB after a couple of days) and cause issues with disk space on the boot volume:

```
$ ll /var/log/docker
-rw-r--r-- 1 root root 836051643 Apr 18 15:26 /var/log/docker
```

This file was mainly full of similar logs:

```
$ tail /var/log/docker
2016/04/18 16:02:23 http: multiple response.WriteHeader calls
time="2016-04-18T16:02:23.518656414Z" level=info msg="GET /containers/44aebbd65a08570b33ec51aac9a4e01a744511f80158c70edfc7cd3671758676/json"
time="2016-04-18T16:02:23.519068975Z" level=info msg="GET /containers/4fc1b1758895dd73d75c6b8112479310931979a9754c4346b26653720ee58a06/top"
time="2016-04-18T16:02:23.527493833Z" level=info msg="GET /containers/4fc1b1758895dd73d75c6b8112479310931979a9754c4346b26653720ee58a06/json"
time="2016-04-18T16:02:23.528072817Z" level=info msg="GET /containers/9e3f44d19d170a099ccdceec9dcaab59ebd3d79e5118a30d06e303b1eeb62916/top"
time="2016-04-18T16:02:23.539116829Z" level=info msg="GET /containers/9e3f44d19d170a099ccdceec9dcaab59ebd3d79e5118a30d06e303b1eeb62916/json"
```

**Comment by mwarkentin** [comment]
Wonder if we should look at logrotate for these other docker logs in `/var/lib/docker/containers/` as well: https://sandro-keil.de/blog/2015/03/11/logrotate-for-docker-container/

**Comment by nzoschke** [comment]
A docker logrotate config was introduced in https://github.com/convox/rack/releases/tag/20160502194942. Thanks for your issue and your patch :)

For the record, container logs are already truncated with the custom `--log-opt max-file=2 --log-opt max-size=50m` args passed to the Docker daemon.
