### ISSUE TITLE
Parameterize swap configuration for rack instances

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#553]
By default, `/swapfile` takes up a large amount (`62.5%`) of the default boot volume's disk space - this can cause issues if you have alarms set up for disk usage, etc.

As discussed in slack, maybe this should be a configurable parameter - is it just a `swap=on/off` switch, or a param that lets you specify the size of the swapfile (`0` to disable?)?

**Comment by mwarkentin** [comment]
If anyone wants a workaround in the meantime, you can add the following to your `InstanceBootCommand` param to reduce the swapfile size to 1GB (tweak to fit your needs): `swapoff -v /swapfile && rm /swapfile && fallocate -l 1G /swapfile && chmod 0600 /swapfile && mkswap /swapfile && swapon /swapfile`

**Comment by nzoschke** [comment]
This is moved off the root partition and parameterized as `SwapSize` in https://github.com/convox/rack/releases/tag/20160502194942

Thanks for your feedback.
