### ISSUE TITLE
Clean up abandoned `convox run` sessions

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#555]
Currently, processes started by `convox run` are terminated when the client exits. However if the client does not cleanly exit the process might keep running until the instance reboots.

This can cause problems as resources become scarce on the instances running the Rack API. We've seen evidence of slow builds and failed rollouts when instances are weighed down by these abandoned sessions.

How can we prevent these processes from being abandoned and/or kill them faster when they are?

**Comment by beedub** [comment]
I just started to notice this as well. Is there a way to detect if a client has disconnected from a one-off run?

**Comment by ddollar** [comment]
Fixed by #1231
