### ISSUE TITLE
Incremental Uploads for Build

### ISSUE THREAD

**Issue by jordan-thoms** [convox/rack#56]
We have some projects which unfortunately have large codebases. It seems convox is uploading the entire directory every time we run `convox deploy`. 

It'd be great if it could upload only the changes, like how a git-based deploy would work.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Fyse7cmL&#x2F;180-delta-upload"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> delta upload</a>

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Fyse7cmL&#x2F;180-delta-upload"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> delta upload</a>

**Comment by nzoschke** [comment]
Thanks for the feature request.

Generating and uploading a .tar.gz is simple and working for a surprisingly large variety of apps, so I don't have the urgency to replace the current system right now.

We also have a GitHub integration in https://grid.convox.com. That links your normal GitHub git push workflow to convox app builds and deployments.

That said, native rack `git push` deploys would be rad. A convox-esque strategy to accomplish this would be by integrating AWS CodeCommit.

**Comment by nzoschke** [comment]
This is becoming more of a problem. Some steps to fix it:

- [ ] Add an upload progress indicator
- [ ] Add progressive HTTP upload

**Comment by xtfxme** [comment]
We had team members in Taiwan accidentally trying to push half a gig across the globe each deploy... developer experience not great :-)

In that case it was node_modules and the lack of a .dockerignore file, which is possibly a different improvement(s), albeit related (low-bandwidth links).

**Comment by jamiequint** [comment]
+1

**Comment by mwarkentin** [comment]
It looks like this is being handled in two separate ways:

* https://github.com/convox/rack/pull/395: Experimenting with support for git-based deploys
* https://github.com/convox/rack/pull/385: Incremental builds (w/ followups: https://github.com/convox/rack/pull/401, https://github.com/convox/rack/pull/390)

**Comment by nzoschke** [comment]
There is plenty of open work on making the existing --incremental work well and be suitable as a default.

See https://github.com/convox/rack/issues/491 and https://github.com/convox/rack/pull/507#issuecomment-207601569 for more info.

**Comment by contra** [comment]
It seems like this has been shipped already, close? Or is there more work needed here?

**Comment by ddollar** [comment]
Another pass has been made in #1018. Tracking there
