### ISSUE TITLE
Add arbitrary tags to everything 

### ISSUE THREAD

**Issue by dlanger** [convox/rack#560]
Almost all AWS cost-reporting [tools](http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/configurecostallocreport.html) are based on tags. In order to make cost analysis easier/automated, it'd be great if I could set one or more key/value pairs that would get added to everything taggable in a rack.

I know convox adds the `Rack` tag, but it'd be nice if I could pick one so it fits in with my reporting of non-convox AWS spending.

**Comment by ddollar** [comment]
Perhaps as a parameter on the Rack CloudFormation stack?

https://github.com/convox/rack/blob/master/api/dist/kernel.json

**Comment by dlanger** [comment]
Any thoughts on how flexible you'd make it? If I was doing this myself I'd add `CostTagName` and `CostTagValue` as parameters (and only apply anything if both are set), but that may be too specific.

**Comment by ddollar** [comment]
How about just `TagName` and `TagValue`

**Comment by mwarkentin** [comment]
Maybe misunderstanding the requirement here, but it seems like that would let you add a single tag - seems like it might be nicer to have a single `Tags` parameter, which takes a list of key/value pairs - not sure what that would look like in a CloudFormation param - but could be something like `Tag1=Value1,Tag2=Value2` or `Tag1=Value1;Tag2=Value2`.

**Comment by ddollar** [comment]
While you can do lists there's not (as far as I can tell) a good way to do arbitrary-length lists.

**Comment by mwarkentin** [comment]
How about my first suggestion where it's just a string (comma / semicolon separated) that we parse into a list?

**Comment by ddollar** [comment]
As far as I know there's no way to do that kind of parsing inside the CloudFormation template and turn it into multiple "Tag" entries, at least not anyway I have figured out.

**Comment by mwarkentin** [comment]
Hmm.. gotcha. Last idea: pre-define multiple tag name / value parameters (even if we just start with 1-3, at least it could be expanded on in the future if needed):

`TagName01`, `TagValue01`, `TagName02`, `TagValue02`, `TagName03`, `TagValue03`

A little ugly, but doesn't look like CloudFormation gives us a lot to work with here. 😄

**Comment by mwarkentin** [comment]
@dlanger came across this information: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

Looks like the tags can be automatically propagated down the stack resources (for the most part) by just setting the tag on the main stack.

**Comment by jason-riddle** [comment]
Any updates to this?

**Comment by ddollar** [comment]
We've added a bunch to the default infrastructure. Please open a new issue if there are any other specific tags you'd like to see.
