### ISSUE TITLE
Errors during InstanceBootCommand

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#561]
Still seeing many issues with errors during our `InstanceBootCommand`s across our racks.

Not really sure what's causing them, but they seem to be random.

Example failure (other instances launched successfully):

```
http://yum.newrelic.com/pub/newrelic/el5/x86_64/repodata/primary.xml.gz: [Errno -1] Metadata file does not match checksum
Trying other mirror.
Traceback (most recent call last):
  File "/usr/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 367, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 174, in main
    result, resultmsgs = base.doCommands()
  File "/usr/share/yum-cli/cli.py", line 572, in doCommands
    return self.yum_cli_commands[self.basecmd].doCommand(self, self.basecmd, self.extcmds)
  File "/usr/share/yum-cli/yumcommands.py", line 435, in doCommand
    return base.installPkgs(extcmds, basecmd=basecmd)
  File "/usr/share/yum-cli/cli.py", line 968, in installPkgs
    txmbrs = self.install(pattern=arg)
  File "/usr/lib/python2.7/dist-packages/yum/__init__.py", line 4751, in install
    mypkgs = self.pkgSack.returnPackages(patterns=pats,
  File "/usr/lib/python2.7/dist-packages/yum/__init__.py", line 1077, in <lambda>
    pkgSack = property(fget=lambda self: self._getSacks(),
  File "/usr/lib/python2.7/dist-packages/yum/__init__.py", line 782, in _getSacks
    self.repos.populateSack(which=repos)
  File "/usr/lib/python2.7/dist-packages/yum/repos.py", line 383, in populateSack
    sack.populate(repo, mdtype, callback, cacheonly)
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 286, in populate
    dobj = repo_cache_function(xml, csum)
  File "/usr/lib64/python2.7/dist-packages/sqlitecachec.py", line 46, in getPrimary
    self.repoid))
TypeError: Can not create requiresname index: disk I/O error
/tmp/bootstrap.sh: line 25: nrsysmond-config: command not found
usermod: user 'newrelic' does not exist
/tmp/bootstrap.sh: line 27: /etc/init.d/newrelic-sysmond: No such file or directory
```

**Comment by mwarkentin** [comment]
This might be resolved by https://github.com/convox/rack/pull/550 - testing w/ `20160419202311-amis` release now.

**Comment by nzoschke** [comment]
So https://github.com/convox/rack/releases/tag/20160502194942 and InstanceRunCommand didn't totally fix this?

I don't have a good guess at what disk io could be causing an error at this part of the boot.

**Comment by mwarkentin** [comment]
@nzoschke When I reviewed the logs closely, I noticed that there were some messages about a yum lock file. Adding a `5s` sleep between each agent install seems to have resolved it (though pretty hacky).

I think during our discussions we chatted about opening up more cloud-init hooks - I wonder if this would be a good use-case for allowing a comma-separated list of packages to be set in a parameter, that convox could add to the package cloud-init step?

**Comment by nzoschke** [comment]
A InstancePackages parameter makes sense to me. CloudInit supports a couple formats:

packages:
 - pwgen
 - pastebinit
 - [libpython2.7, 2.7.3-0ubuntu3.1]

So a user-supplied comma separated list could be passed through easy enough.

**Comment by mwarkentin** [comment]
Some packages might need a custom repository to be added first - thoughts on that?

http://cloudinit.readthedocs.io/en/latest/topics/examples.html#adding-a-yum-repository

```
#cloud-config
# vim: syntax=yaml
#
# Add yum repository configuration to the system
#
# The following example adds the file /etc/yum.repos.d/epel_testing.repo
# which can then subsequently be used by yum for later operations.
yum_repos:
    # The name of the repository
    epel-testing:
        # Any repository configuration options
        # See: man yum.conf
        #
        # This one is required!
        baseurl: http://download.fedoraproject.org/pub/epel/testing/5/$basearch
        enabled: false
        failovermethod: priority
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
        name: Extra Packages for Enterprise Linux 5 - Testing
```

**Comment by nzoschke** [comment]
@mwarkentin Are you still experiencing this issue? Do you think InstanceBootCommand is ok as is to document and recommend?

**Comment by mwarkentin** [comment]
@nzoschke Well, the `sleep 5` workaround we added seemed to have resolved the issue. Obviously that's a bit hack-ish, though. We're also using `InstanceRunCommand` now. Main improvements that I see:

* Rack env vars: remove the need to set these for API keys, etc. inside our command
* Add yum repos / packages via cloud-init: this would (hopefully) resolve the need for our `sleep` hack

As-is: We are successfully using it in production - definitely feels like it would be good to get documented, but still really feels like an advanced / dangerous / power-user feature at this point.

**Comment by mwarkentin** [comment]
Closing, as this is no longer an issue for us as we've switched to installing yum packages in packer and using a custom AMI.
