### ISSUE TITLE
Dockerfile's in subdirectories

### ISSUE THREAD

**Issue by mfine** [convox/rack#567]
I have a `docker-compose.yml` with contents like:

```
api:
  build: .
  dockerfile: skylark-api/Dockerfile
```

The `Dockerfile` to build is in a subdirectory, `./skylark-api`, but the build directory is specified as `.`. When convox goes to deploy this compose file, it seems to jump into the directory where the `Dockerfile` is:

```
$ convox deploy -f docker-compose.yml --app skylark-staging
Deploying skylark-staging
Creating tarball... OK
Uploading... OK
RUNNING: tar xz
RUNNING: docker build -t convox-nrsdenbqrn -f /go/src/github.com/convox/rack/src/skylark-api/Dockerfile /go/src/github.com/convox/rack/src/skylark-api/
```

**Comment by awsmsrc** [comment]
This has been fixed
