### ISSUE TITLE
Convox cli always uses $CWD to look up for name of the app

### ISSUE THREAD

**Issue by jjperezaguinaga** [convox/rack#57]
If I try to access `convox` outside of the working directory of my app, even if I pass the name as an argument, I get an error.

```
➜  ~  convox apps info jjperezaguinaga-io
ERROR: no such app: jose.aguinaga
```

If I go to a folder named with the name of the app, even if it's not the working directory, it will work.

```
➜  ~  mkdir jjperezaguinaga-io && $_
➜  jjperezaguinaga-io  convox apps jjperezaguinaga-io
Name       jjperezaguinaga-io
Status     running
Release    RTWWQEROJEJ
Processes  web
Hostname   jjperezaguinaga-io-123456789.us-east-1.elb.amazonaws.com
Ports      web:80
```

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XMloqVYd&#x2F;181-better-default-app-name-handling"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> better default app name handling</a>
