### ISSUE TITLE
Optionally run syslog Lambda functions in a given VPC

### ISSUE THREAD

**Issue by robatwave** [convox/rack#574]
We're looking to run a syslog server for the purpose of in-house aggregation of container log events. We want to be able to do this without having to open the endpoint up to the web (or having to route traffic to the endpoint to the web and back for that matter). We'd like to setup a dedicated VPC (so as to not interfere with the CloudFormation-managed VPCs of our racks), and run something (e.g. syslog-ng) to receive syslog events over the wire. A Security Group would then limit access to the VPC, and no public IP address would be needed.

**Comment by skwp** [comment]
Confirmed this is an issue. This is what we did (by hand) to fix:

1. Allow convox to create the syslog lambda (`convox services create syslog`)
2. Go to the convox created IAM role and add AWSLambdaVPCAccessExecutionRole
3. Go to the convox created lambda, select the convox created vpc and the 3 private subnets created by convox.

**Comment by skwp** [comment]
Confused as to why this is not the default. It would seem to me the lambda should be in the same vpc as the rack.

**Comment by skwp** [comment]
One possible option that might be the best of both worlds is always provision the lambda in the rack's VPC and add a gateway for internet access. But it seems like either or both would need to be config options.

**Comment by ddollar** [comment]
Solving more generally in #976
