### ISSUE TITLE
CNAMED elb url throws 401 when using `convox switch`

### ISSUE THREAD

**Issue by jjperezaguinaga** [convox/rack#58]
I want to use a proper url for handling my rack, so instead of `convox-123456789.us-east-1.elb.amazonaws.com`, I want to do `staging.jjperezaguinaga.io`.

After adding the CNAME, I get a 401 response:

```
➜  jjperezaguinaga-io git:(development) convox switch staging.jjperezaguinaga.io
Switched to staging.jjperezaguinaga.io
➜  jjperezaguinaga-io git:(development) convox apps
ERROR: response status: 401
```

Digging the url:

```
➜  jjperezaguinaga-io git:(development) dig staging.jjperezaguinaga.io

; <<>> DiG 9.8.3-P1 <<>> staging.jjperezaguinaga.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12345
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;staging.jjperezaguinaga.io.		IN	A

;; ANSWER SECTION:
staging.jjperezaguinaga.io.	86400	IN	CNAME	convox-12345689.us-east-1.elb.amazonaws.com.
convox-12345689.us-east-1.elb.amazonaws.com. 60 IN A XX.XX.XX.XX
convox-12345689.us-east-1.elb.amazonaws.com. 60 IN A XX.XXX.XXX.XX

;; Query time: 32 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Sep 29 13:39:49 2015
;; MSG SIZE  rcvd: 127
```

If I just use the elb url, I have no issues. I'm trying to do a CNAME to the convox rack url, not a specific app, which I imagine it works. This is due a suggestion in the slack channel of using different racks per environments; ideally I would have a way to use clean urls instead of the convox one. Any insights on this?

**Comment by csquared** [comment]
you might just need to do a convox login so that the new hostname/pw combo gets stored in `~/.convox/auth`

**Comment by csquared** [comment]
or, do a `convox update` and trying `convox switch` again -> we've updated switch to default to logging in so you can't switch and then wind up in a bad state like this

**Comment by jjperezaguinaga** [comment]
Will give it a try and update, thanks.

**Comment by jjperezaguinaga** [comment]
Yeah, it's working now! `convox switch` to a custom domain now will prompt the login, which password can be found in `~/.convox/auth` as @csquared described. Closing.
