### ISSUE TITLE
new syslog service url scheme is potentially confusing

### ISSUE THREAD

**Issue by soulware** [convox/rack#581]
I added a new syslog service - 

```convox services create syslog --url tcp+ssl://logs1.papertrailapp.com:12345```

It was created successfully but logs never made it to papertrail.

Turns out the url was incorrectly specified `tcp+ssl` vs. `tcp+tls`.

Ideally this would have validated the url was correct.
I have no idea if `tcp+ssl` is even a valid protocol definition and have never seen `tcp+tls` specified like this in a url.

**Comment by nzoschke** [comment]
Definitely needs validation and better docs for the schemes it supports. 

The URL schemes are borrowed directly from the https://github.com/RackSec/srslog package. They possible schemes are `udp`, `tcp`, or `tcp+tls`.

**Comment by nzoschke** [comment]
This is fixed in #632.
