### ISSUE TITLE
syslog service uses static zip file on s3

### ISSUE THREAD

**Issue by ddollar** [convox/rack#585]
We need to either version and upload this file as part of the release process or inline it into the CF template. I prefer the latter.

**Comment by nzoschke** [comment]
It is a compiled go program so it can't be inlined.

What's the problem you are seeing? We got buy with a static papertrail zip file on S3 this whole time...

**Comment by ddollar** [comment]
If we ever need to make a backwards-incompatible change to that zip file we will break a bunch of existing Racks.

**Comment by nzoschke** [comment]
I was under the impression that a source .zip is copied on lambda function creation. So deleting or updating the s3 .zip will not affect existing lambdas.

**Comment by nzoschke** [comment]
that said I'm happy to improve release management here and in general

**Comment by ddollar** [comment]
It would break an old rack pre-breaking change that tried to `convox services create syslog`

Not the most pressing of concerns right now but we'll want to figure out how to do versioned release management of these assets in general, like `cmd/formation`

**Comment by nzoschke** [comment]
Even more fun, technically speaking convox/agent and the syslog lambda function need to be compatible too.
