### ISSUE TITLE
Add ability to configure elb's stickiness policy

### ISSUE THREAD

**Issue by beedub** [convox/rack#594]
Here's the relevant documentation: http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-sticky-sessions.html

**Comment by nzoschke** [comment]
I think this fits in very well with the numerous other ELB options convox helps you maintain: https://convox.com/docs/load-balancers/

The steps to get this in are to:

- [ ] Add a new parameter to the app load balancer cloudformation template. #464 is good prior art.
- [ ] Add a new label to the docker-compose.yaml to control the parameter. #505 is good prior art

**Comment by nzoschke** [comment]
The CloudFormation AWS::ElasticLoadBalancing::LoadBalancer resource has a LBCookieStickinessPolicy property

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-lbcookiestickinesspolicy
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-LBCookieStickinessPolicy.html

**Comment by nzoschke** [comment]
Existing parameters are `WebPort80Protocol=tcp`, `WebPort80Proxy=No`, `WebPort80Secure=No`

The toggles I see here are whether LBCookieStickinessPolicy is set at all, and if it is an optional value for the CookieExpirationPeriod value:

> The time period, in seconds, after which the cookie should be considered stale. If this parameter isn't specified, the sticky session will last for the duration of the browser session.

@beedub do you want to use an expiration period?

**Comment by beedub** [comment]
i'm not sure (yet). would it be a lot more incremental work to make it configurable?

**Comment by nzoschke** [comment]
I can see either `WebPort80Stickiness` with a `Yes` or `No` setting, or a `WebPort80StickinessPeriod` that takes a number from 0 to 30 or whatever.

**Comment by nzoschke** [comment]
If there are two settings (one for on/off, one for optional duration) the cloudformation bit will be marginally harder but nothing too bad.

But if we can do it with a single parameter its easier to document and use.

**Comment by nzoschke** [comment]
I'm not sure myself, having never used the toggle. In cases like this we try to do the simplest thing first, then iterate from ther. In that case it'd be the single `Stickiness` Yes/No setting.

**Comment by nzoschke** [comment]
Another nice strategy we have at our disposal is that for experimentation, you can go modify the ELB directly. In most cases these modifications will persist between deploys so you can do some experiments with how your app behaves.

**Comment by nzoschke** [comment]
Hmm, we already have a setting.

"LBCookieStickinessPolicy": [{ "PolicyName": "affinity" }]

**Comment by nzoschke** [comment]
Sure enough, it's set...

```
$ aws elb describe-load-balancers --load-balancer-name httpd-web-7E5UPCM
{
    "LoadBalancerDescriptions": [
        {
            "Subnets": [
                "subnet-13de3139", 
                "subnet-21c13379", 
                "subnet-b5578fc3"
            ], 
            "CanonicalHostedZoneNameID": "Z3DZXE0Q79N41H", 
            "CanonicalHostedZoneName": "httpd-web-7E5UPCM-2145977375.us-east-1.elb.amazonaws.com", 
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 60866, 
                        "LoadBalancerPort": 80, 
                        "Protocol": "TCP", 
                        "InstanceProtocol": "TCP"
                    }, 
                    "PolicyNames": []
                }
            ], 
            "HealthCheck": {
                "HealthyThreshold": 2, 
                "Interval": 5, 
                "Target": "TCP:60866", 
                "Timeout": 3, 
                "UnhealthyThreshold": 2
            }, 
            "VPCId": "vpc-f8006b9c", 
            "BackendServerDescriptions": [], 
            "Instances": [
                {
                    "InstanceId": "i-31968baa"
                }, 
                {
                    "InstanceId": "i-83158e04"
                }
            ], 
            "DNSName": "httpd-web-7E5UPCM-2145977375.us-east-1.elb.amazonaws.com", 
            "SecurityGroups": [
                "sg-f45a698c"
            ], 
            "Policies": {
                "LBCookieStickinessPolicies": [
                    {
                        "PolicyName": "affinity", 
                        "CookieExpirationPeriod": 0
                    }
                ], 
                "AppCookieStickinessPolicies": [], 
                "OtherPolicies": []
            }, 
            "LoadBalancerName": "httpd-web-7E5UPCM", 
            "CreatedTime": "2016-04-11T20:36:10.710Z", 
            "AvailabilityZones": [
                "us-east-1b", 
                "us-east-1c", 
                "us-east-1d"
            ], 
            "Scheme": "internet-facing", 
            "SourceSecurityGroup": {
                "OwnerAlias": "132866487567", 
                "GroupName": "convox-httpd-BalancerWebSecurityGroup-U8J1RS42HQ2L"
            }
        }
    ]
}
```

**Comment by nzoschke** [comment]
Maybe we want the AppCookieStickinessPolicy? http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb-AppCookieStickinessPolicy.html

**Comment by nzoschke** [comment]
Or maybe we want the option to turn affinity off?

**Comment by ddollar** [comment]
It seems like it makes sense to have affinity be the default. Would anyone even need to turn that off?

**Comment by alex** [comment]
I would be super sad if affinity were the default. Affinity by default
encourages people to write stateful web process, which I think is a
tremendous anti-pattern.

On Wed, May 4, 2016 at 11:31 PM, David Dollar <notifications@github.com>
wrote:

> It seems like it makes sense to have affinity be the default. Would anyone
> even need to turn that off?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/convox/rack/issues/594#issuecomment-217070153>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by ddollar** [comment]
While that's true it can also be helpful to avoid weird flip flops in the user experience during rolling deploys.

**Comment by beedub** [comment]
> avoid weird flip flops in the user experience during rolling deploys.

(this was the original reason for the ask)

> I would be super sad if affinity were the default. Affinity by default
encourages people to write stateful web process, which I think is a
tremendous anti-pattern.

I personally don't think having affinity turned on by default would noticeably encourage anyone to make their processes stateful, but I'm just one data point 😄

**Comment by ddollar** [comment]
Seems like we might just be getting the right thing by default here. Will address more in #613 if necessary.
