### ISSUE TITLE
`convox run` could have nicer output

### ISSUE THREAD

**Issue by beedub** [convox/rack#601]
```
$ convox run RLVSHBOYZML bash
ERROR: InvalidParameterException: Task Definition can not be blank.
	status code: 400, request id: 769efe3c-1319-11e6-b48e-dd0e977921b0
```

I accidentally used the release instead of service name. It seems like convox should be checking if the service name exists before passing it through to ECS. In any case, it seems like the error message could be friendlier.

**Comment by nzoschke** [comment]
A friendlier error message landed on #631. This was a CLI patch. Someday we can also fix this in the API.
