### ISSUE TITLE
Document pricing ("base" price and expected per-app price)

### ISSUE THREAD

**Issue by dbp** [convox/rack#602]
It would be really great if (approximate) pricing could be documented. I just created a rack and let it run for 12 hours in order to see about how much it would cost (ignoring free tier stuff, as I created a new account for this purpose). As far as I could tell, it looks like the rack costs roughly $85/month (assuming low traffic/activity, as obviously then it becomes hard to estimate), which is broken down into:

dynamo - 80 read, 80 write capacity, so roughly $45/month
an elb for the rack - $18
kinesis shard - $11
about 600MB worth of ec2 cluster memory, but round up and say about a t2.micro worth - $11

Then, every app has one ELB per networked service (at $18/each), and then of course however much cluster you actually need worth of ec2 instances. 

Does that sound about right? Obviously there are lots of other services used, but as far as I could tell, on a relatively low activity application (I did a bunch of stuff deploying / troubleshooting at first, and then just let it run), the rest of them were incurring charges in the pennies. 

One thing that stands out - the dynamo cost seems like a lot! Is it possible to reduce that? Especially if the advice is to create separate racks for staging/production, on small applications that is going to start adding up!

**Comment by ddollar** [comment]
Added to our docs todo list, thanks!
