### ISSUE TITLE
Package convox CLI for homebrew?

### ISSUE THREAD

**Issue by alex** [convox/rack#603]
This would make it significantly easier to get started for many folks.

**Comment by jeremy** [comment]
First thing I looked for 😊 Unpacking a zipfile in `/usr/local/bin` was a little bit of a surprise.

**Comment by adamenger** [comment]
It seems there's already a formula out there for this:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/convox.rb though I'm not sure if it's up to date with the latest release: https://github.com/convox/rack/tree/20160628221152/cmd/convox

My brew currently shows: 
```
⮀ brew search convox
convox
⮀ brew info convox
convox: stable 20160623185456 (bottled)
The convox AWS PaaS CLI tool
https://convox.com/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/convox.rb
==> Dependencies
Build: go ✔
```

**Comment by mwarkentin** [comment]
@adamenger Yep, I created the convox formula in homebrew - not sure if it's up to date or not, but running `convox update` works fine after installing.

**Comment by adamenger** [comment]
@mwarkentin yep just what I was thinking, this can probably be closed. Good work!

**Comment by ddollar** [comment]
Adding #824 to cover that. Thanks @mwarkentin !
