### ISSUE TITLE
Is `--generate-bash-completion` for `convox ssl` expected?

### ISSUE THREAD

**Issue by beedub** [convox/rack#604]
When I run `convox ssl --help`:

```bash
$ convox ssl --help
convox ssl: manage SSL certificates

Usage:
  convox ssl <command> [args...]

Subcommands: (convox ssl help <subcommand>)
  update	upload a replacement ssl certificate
  help, h

Options:
  --app, -a 			App name. Inferred from current directory if not specified.
  --help, -h			show help
  --generate-bash-completion
```

It shows the option for `--generate-bash-completion`. Is that expected? It seems unusual to create bash completion for just one command on the cli (as opposed to the entire CLI). I actually don't know what adding the `--generate-bash-completion` would do either. Does it generate a bash script that I need to pipe into a file and move somewhere? Does it install the bash completion entirely?

**Comment by nzoschke** [comment]
Good catch. Not expected. Seems to be a side effect from https://github.com/convox/rack/commit/9ef8c2c107d6f7130387559722342386737478c9

I have no idea why it ends up on the SSL command...

**Comment by mwarkentin** [comment]
@nzoschke I noticed it on some other commands too. Possible it's on all commands?

**Comment by nzoschke** [comment]
Maybe we need a newer version of the `cli` package. The docs show a `Hidden` property on the `generate-bash-completion` flag. That doesn't exist in the vendored version.

https://godoc.org/github.com/codegangsta/cli
