### ISSUE TITLE
`convox cli update`?

### ISSUE THREAD

**Issue by beedub** [convox/rack#605]
It would be awesome if the convox cli had a command itself to upgrade like `convox cli update`

kind of related to https://github.com/convox/rack/issues/603 in the vein of making the cli experience easier

**Comment by shicholas** [comment]
There is a convox update, what is different with what you're proposing?

**Comment by mwarkentin** [comment]
Yep, `convox update` will do what you want.

**Comment by beedub** [comment]
Ah! I didn't know that existed. I didn't see a mention of it in the docs anywhere. Perhaps a CLI section in the docs would be helpful?

**Comment by jordansexton** [comment]
`convox update` doesn't seem to accept a version argument, unlike `convox rack update`. Is there a way to install a specific CLI release? There's a lot of active development here, so the releases cut for merged PRs and closed issues are often not in the latest available.
