### ISSUE TITLE
Autoscale process count

### ISSUE THREAD

**Issue by dbp** [convox/rack#606]
Currently, convox can automatically scale the number of EC2 instances that make up the cluster, based on how many copies of processes you ask for. But as far as I can tell, there is no way to automatically change the number of copies of a given process, based on metrics like CPU usage, response time (if it's a networked process), etc. 

This is one of the really neat features of Elastic Beanstalk, which is in some senses a competitor (as it allows you to run docker containers on ECS clusters - albeit, more clumsily in all ways aside from this autoscaling, and perhaps collection of metric). For client projects where traffic can vary widely (by an order of magnitude or two), this behavior is a pretty key feature.

Are there plans to add something like this? I see that at least some people[1] are doing this by having cloudwatch alarms trigger lambda functions that then change the number of copies of a given task, which seems like something that could fit in with how convox works. I guess a major question would be where the metrics come from, but ELBs can report a lot, and presumably ECS can also report many things into cloudwatch.

1. https://aws.amazon.com/blogs/compute/scaling-amazon-ecs-services-automatically-using-amazon-cloudwatch-and-aws-lambda/

**Comment by ddollar** [comment]
Yes, I'd love to have this. I think the pattern of CloudWatch -> Lambda -> Update Service makes a lot of sense and could be encoded in the CloudFormation stacks that Convox uses.

**Comment by ddollar** [comment]
Tracking in #1074
