### ISSUE TITLE
Verify that VolumeSize is being honored with new AMI

### ISSUE THREAD

**Issue by ddollar** [convox/rack#608]
I was poking around a rack and it seemed like the root filesystem was not the size requested in the `VolumeSize` parameter.

**Comment by nzoschke** [comment]
Because of devicemapper and growing devices its sometimes very confusing. Did you look at `lsblk` and `docker info`?

**Comment by ddollar** [comment]
Gotcha, I think I saw the wrong number in `df -h`. Will close for now and reopen if I see it again.
