### ISSUE TITLE
Default Rails Dockerfile should assets:precompile

### ISSUE THREAD

**Issue by ddollar** [convox/rack#61]
Need to test to make sure it works with `convox start` and deploying.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ATclmtlb&#x2F;170-default-rails-dockerfile-should-assets-precompile"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Default Rails Dockerfile should assets:precompile</a>

**Comment by nzoschke** [comment]
https://github.com/convox/rack/pull/93

Works with my simple testing...

http://simple-rails-173749661.us-east-1.elb.amazonaws.com:5000/assets/application-2d7968994a750350abb50028e047ed290d63c9bac692117bce66d6c43f178800.js

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;B6rgDNyJ&#x2F;193-remove-cpu-memory-stats-from-convox-ps-by-default"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Remove CPU&#x2F;Memory stats from convox ps by default</a>

**Comment by ddollar** [comment]
Fixed now
