### ISSUE TITLE
convox uninstall text update

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#610]
A user reported that the `convox uninstall` text was confusing because it mentions it "needs AWS credentials to install". I think we're probably reusing the same text from the install command. The uninstall text should be customized for uninstalling.

**Comment by keshavab** [comment]
@mattmanning @nzoschke I've refactored messages and cleaned up some code as part of #625 too. Let me know if some changes in message or formatting are required.

**Comment by nzoschke** [comment]
Thank you for the patch @keshavab.
