### ISSUE TITLE
Support RDS Aurora as a service

### ISSUE THREAD

**Issue by jagtesh** [convox/rack#617]
Currently, there are only two RDS based services, namely Postgres and MySQL. Aurora is another alternative that is slowly gaining popularity and we currently it where I work. I'd love to see it being added as service.

I'd love to help. Is adding it simply a matter of creating another CloudFormation template such as rack/api/models/templates/service/mysql.tmpl?

**Comment by ddollar** [comment]
Yes, that's right. Copy/paste that template and run `make templates` to turn it into Go code that will be compiled into Rack. Thank you!

**Comment by jagtesh** [comment]
My pleasure! Here its is:
https://github.com/convox/rack/pull/622

**Comment by ddollar** [comment]
Closing in favor of #622
