### ISSUE TITLE
convox start fails when trying to setup development environment

### ISSUE THREAD

**Issue by keshavab** [convox/rack#620]
while setting up local dev environment - https://github.com/convox/rack/blob/master/Development.md#local-rack-environment
convox start fails

```
keshava@KEHP-M-X03J:rack (master=)$ convox start
ERROR: env expected: DEBUG
```

This is because the env DEBUG is not set in docker-compose.yml nor set when 
`convox exec $WEB_PID env --app $STACK_NAME > .env` is executed.

**Comment by nzoschke** [comment]
Thanks for the report and the patch!
