### ISSUE TITLE
convox init should generate .dockerignore

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#623]
Ignore `.git` if it's present and other things based on framework such as log files.

**Comment by mwarkentin** [comment]
On our rails app we also ignore `vendor/` so we're not sending gems around all over the place.

**Comment by jordansexton** [comment]
+1

Here's the one I'm using in our Node convox app, if it helps:
```
.convox
.DS_Store
.editorconfig
.eslintignore
.eslintrc
.git
.gitignore
.idea
docker-compose.yml
Dockerfile
node_modules
nodemon.json
README.md
test
```
