### ISSUE TITLE
Deploying to the rack name gives confusing error

### ISSUE THREAD

**Issue by ddollar** [convox/rack#633]
If you run `convox deploy -a $rackname` everything looks like it tries to work and then you get a very confusing error message about an S3 bucket. We should validate the app name parameter here and return a helpful error message.

/cc @kmonkeyjam

**Comment by kmonkeyjam** [comment]
I'm not sure, but I think there may be a way to clarify more in the documentation.  

Preparing the app seems to take you through starting and running locally:
https://convox.com/docs/preparing-an-application/

Installing the rack just tells you to install.
https://convox.com/docs/installing-a-rack/

And then deploying just deploys:
https://convox.com/docs/deploying-to-convox/

I think maybe in the deploy doc, it should make sure you've created the application?

**Comment by ddollar** [comment]
Thanks :) If you're up for taking a stab at some changes that documentation lives here:

https://github.com/convox/site/tree/master/_development
https://github.com/convox/site/tree/master/_deployment

**Comment by ddollar** [comment]
Closing as duplicate of #490

**Comment by nzoschke** [comment]
The real fix is to stop being so liberal as to what stacks we treat as an app. I propose making this really strict, which will also fix:

- https://github.com/convox/rack/issues/379

And having a special case for the read-only rack operations like `exec`, `logs`, `ps`, and `run`.

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;VQIadVqD&#x2F;254-prevent-the-deployment-of-rack"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Prevent the deployment of rack</a>

**Comment by MiguelMoll** [comment]
Resolved this issue by preventing a deployment on a rack. Thanks all!

Merged with PR #770
