### ISSUE TITLE
VPC CIDR is hard coded for redis service (and possibly other services)

### ISSUE THREAD

**Issue by snario** [convox/rack#637]
I tried adding a redis service and added an env variable for it on my app, but I could not connect to it. 

Went to check the security group being assigned and noticed that it was only accepting inbound requests from `10.0.0.0/16` whereas I set my  rack's VPC CIDR to `172.16.0.0/16`.

The incoming CIDR block of the security group corresponding to a service in a rack should use the appropriate CIDR block of the rack's VPC.

**Comment by snario** [comment]
Relevant line of code

https://github.com/convox/rack/blob/856b3268bc1dc930a812fd2cfff625dc5986fc09/api/models/templates/service/postgres.tmpl#L76

**Comment by nzoschke** [comment]
Thanks for the report. This is fixed in #690.
