### ISSUE TITLE
As a developer running migrations/pre-release scripts after builds, I would like to set an onBuild process

### ISSUE THREAD

**Issue by snario** [convox/rack#638]
My use case is that I need to build my webpack build and upload to s3 at `/$RELEASE/build/` before I promote a release. It would be nice if that would just happen automatically after the build is finished.

Some use-cases:
1. Running `python migrate.py` (e.g., #409)
2. Building webpack files and pushing to S3

**Comment by ddollar** [comment]
Proposed design:

```
web:
  labels:
    - convox.hook.pre-release="bin/migrate"
```

This would effectively run `convox run --release $id web bin/migrate` right after the user triggers release promotion but before the release is actually promoted.

**Comment by snario** [comment]
The proposed design above would 100% cover my use case @ddollar

**Comment by snario** [comment]
NOTE: This will need to be completed for the proposed design to work: https://github.com/convox/rack/issues/669

**Comment by ddollar** [comment]
Doing a bit of feature request culling so going to close this for now. You can use Workflows in Console to achieve this same thing (build, run, promote)

**Comment by mwarkentin** [comment]
Heroku has something similar where they have a special process definition called `release` which runs as a one-off container before the rest of the deployment starts: https://devcenter.heroku.com/articles/release-phase

Could be a nice approach.

**Comment by ddollar** [comment]
Yes, add a "Run" task after a "Build" but before a "Promote"
