### ISSUE TITLE
Compose version 2 syntax is only partially supported

### ISSUE THREAD

**Issue by mful** [convox/rack#639]
I was hoping to use the version 2 syntax of `build` in my `docker-compose.yml`, in order to specify build args, to work around [this issue](https://github.com/convox/rack/issues/156). For context, the new syntax allows `build` to be specified as:

```
build:
  context: .
  args:
    - RAILS_ENV=production
```

rather than as a string pointing to the app root.

I did some digging after getting a yaml unmarshall error, and it looks like, though some pieces of version 2 syntax are supported, the new `build` syntax is not, as rack expects `build` to be a string: https://github.com/convox/rack/blob/master/api/manifest/manifest.go#L75

I will look into using different `Dockerfile`s for different environments, in the mean time. I may also try to dig through the code one weekend, and see if I can put together a pull in the next month (though I have as much systems programming experience as go experience - none).

**Comment by ddollar** [comment]
See #156 for current discussion on build args support. Going to close this issue in favor of that.
