### ISSUE TITLE
convox rack scale --count doesn't work when Autoscale=Yes

### ISSUE THREAD

**Issue by beedub** [convox/rack#643]

**Comment by ddollar** [comment]
We should prevent scaling by --count manually when Autoscaling is on

**Comment by ddollar** [comment]
A good place for this check would be in here: https://github.com/convox/rack/blob/301fa806a6dbf43fcec8015e5a773ea11723a760/api/controllers/system.go#L52

**Comment by MiguelMoll** [comment]
Closing since a fix has been released via #739
