### ISSUE TITLE
More specific IAM policy for rack installation

### ISSUE THREAD

**Issue by cwandrews** [convox/rack#649]
It would be great if there was an explicit policy document containing exactly what the convox user needs access to, instead of giving it the administrator policy.

**Comment by mwarkentin** [comment]
Wonder if there's a good way to generate this via CloudTrail or similar when you're running install..?

**Comment by cwandrews** [comment]
@mwarkentin I would assume one of the maintainers probably has knowledge of exactly what the installer does, and should be able to create a policy so we don't have to give that user access to everything.

**Comment by ddollar** [comment]
This is definitely something we plan to do eventually but is a bit of a moving target at present. For now if you are worried I would suggest installing Convox in a fresh AWS account that you link up with consolidated billing.

**Comment by cwandrews** [comment]
@ddollar thanks, yeah. I am running it in our development account. Is there any work that can be done in determining what that policy will look like?

**Comment by ddollar** [comment]
I think @mwarkentin is on to something with CloudTrail. Maybe we can dump all of the events and turn that into a mapping? The first version of this probably looks like figuring out what base level permissions are needed to install the CloudFormation stack. The Rack creates its own credentials for internal use, and we'll also eventually want to map out what that policy should look like. I imagine this latter policy will be more complicated.

**Comment by rcaught** [comment]
I created a tool for turning Cloudtrail logs into IAM policies.  This doesn't solve the problem entirely, but it's a start!  You can check it out here: https://github.com/rcaught/trailpolicy

I believe though that running an install in it's own account, like @ddollar suggested, is still the best way.

**Comment by ddollar** [comment]
@MiguelMoll is working on policies this week

**Comment by ddollar** [comment]
This has now been implemented
