### ISSUE TITLE
Improve auto-scaling docs

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#653]
Reminded when I saw #643 - I would love to see some more documentation around how AutoScale works - jumped into the code a while ago, and it looked like it takes two things into account:

* Total memory required by all apps
* Largest app (by container count)

It would be nice to explain that in a bit more detail in the docs, as well as having an example or two showing the scaling on multiple axis.

**Comment by ddollar** [comment]
We have an internal card tracking this so closing this issue.
