### ISSUE TITLE
Investigate: ResourceNotFoundException: The specified log group does not exist.

### ISSUE THREAD

**Issue by ddollar** [convox/rack#655]
First guess is that it's a bad app name given to `convox logs`

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;wMq8oaOu&#x2F;167-investigate-log-group-error"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> investigate log group error</a>

**Comment by ddollar** [comment]
https://rollbar.com/convox/rack/items/2818/

**Comment by nzoschke** [comment]
I found one way to trigger this... Try `convox --logs` on a CF stack that isn't an app or rack, like a service:

```
$ convox logs --app convox-events
ERROR: InvalidParameter: 1 validation errors:
- field too short, minimum length 1: LogGroupName
```

**Comment by ddollar** [comment]
Haven't seen this in quite some time. Probably fixed by the latest log updates.
