### ISSUE TITLE
Cron jobs with underscores in their name fail when trying to promote a release

### ISSUE THREAD

**Issue by snario** [convox/rack#667]
e.g.,

```yml
labels:
    - convox.cron.do_thing=0 * * * ? bin/thing
```

```bash
$ convox releases promote RMVEKAEXPTK
Promoting RMVEKAEXPTK... ERROR: Template format error: Resource name WebDo_thingLambdaPermission is non alphanumeric.
```

## Possible solutions
- [ ]  Catch error and point out what needs to be fixed
- [ ] Mention in documentation no underscores allowed

**Comment by ddollar** [comment]
Let's remove the underscores before we try to make the lambda function name. We could also make the name be a hash of the job name or something.

**Comment by ddollar** [comment]
If you're interested in taking a swing at it we could do some post-processing of `name here:
https://github.com/convox/rack/blob/master/api/models/cronjob.go#L19

Perhaps something hashing the input like this:
https://play.golang.org/p/nxpyk0nZgN

**Comment by rcaught** [comment]
It's interesting... I would consider the current behaviour to be the correct one.

- If you replace or remove the underscores, you could have potential naming collisions with other jobs that are using no underscores.  e.g. (`convox.cron.my_job` and `convox.cron.myjob`)
- If you hash the input, you lose transparency of what the lambda function is within AWS.

Perhaps documentation updates and build time validation is the answer here!

**Comment by awsmsrc** [comment]
I was going to do this one today @ddollar but realized cronjobs are in api/models/manifest.go and parse is in api/manifest/manifest.go so I'll wait for the refactor to land

**Comment by nzoschke** [comment]
This is fixed in https://github.com/convox/rack/releases/tag/20160614203313. Thanks!
