### ISSUE TITLE
Error for DOCKER_HOST not set

### ISSUE THREAD

**Issue by gregpardo** [convox/rack#672]
Rack should check docker configuration before attempting to pull containers. Currently this is the error output if docker-machine env is not loaded.

```bash
ERROR: could not pull container "node": exit status 1
```

Should output something more like

```bash
ERROR: Docker is not loaded. Please run "eval $(docker-machine env default)"
```
Or something like that

**Comment by ddollar** [comment]
I believe #660 solved this. Please try to run `convox update` and try again. Leave a comment here is you are still seeing the problem.

**Comment by gregpardo** [comment]
Working. I installed from binary release which I assumed was latest perhaps not.
