### ISSUE TITLE
check aws credentials have enough permissions before install

### ISSUE THREAD

**Issue by ddollar** [convox/rack#680]

**Comment by nzoschke** [comment]
Does IAM have APIs that we can use to introspect permissions?

**Comment by ddollar** [comment]
Not sure. This may actually be fine as-is in Rack and simply need some better invalid-credentials handling in Console.

**Comment by mwarkentin** [comment]
IAM has a bunch of APIs for getting policies, roles, etc. There's also this, which I think puts everything together - not sure if that would work or not (or if there's an API only version as well): http://docs.aws.amazon.com/cli/latest/reference/iam/get-account-authorization-details.html

**Comment by MiguelMoll** [comment]
http://docs.aws.amazon.com/IAM/latest/APIReference/Welcome.html Would be the place. A few `List*` methods that should help.

**Comment by MiguelMoll** [comment]
Seems the API acts a bit odd. Might have to dig in a bit more. For example, a user that only has the `IAMReadOnlyAccess` policy attached, the API ListPolicies returns:

```
{
  IsTruncated: false,
  Policies: [{
      Arn: "arn:aws:iam::aws:policy/AdministratorAccess",
      AttachmentCount: 2,
      CreateDate: 2015-02-06 18:39:46 +0000 UTC,
      DefaultVersionId: "v1",
      IsAttachable: true,
      Path: "/",
      PolicyId: "ANPAIWMBCKSKIEE64ZLYK",
      PolicyName: "AdministratorAccess",
      UpdateDate: 2015-02-06 18:39:46 +0000 UTC
    },{
      Arn: "arn:aws:iam::aws:policy/IAMReadOnlyAccess",
      AttachmentCount: 1,
      CreateDate: 2015-02-06 18:40:39 +0000 UTC,
      DefaultVersionId: "v2",
      IsAttachable: true,
      Path: "/",
      PolicyId: "ANPAJKSO7NDY4T57MWDSQ",
      PolicyName: "IAMReadOnlyAccess",
      UpdateDate: 2015-04-21 16:03:51 +0000 UTC
    }]
}
```

For some reason `AdministratorAccess` shows attached.
