### ISSUE TITLE
Deploy error on 'docker build -t convox-kcncmpbmrg ...'

### ISSUE THREAD

**Issue by kolanos** [convox/rack#682]
client: 20160521123902
server: 20160521030812 (console.convox.com)

When trying to run 'convox deploy' I get the following error:

    Deploying app
    Creating tarball... OK
    Uploading... OK
    RUNNING: tar xz
    RUNNING: docker build -t convox-kcncmpbmrg -f /go/src/github.com/convox/rack/src/Dockerfile /go/src/github.com/convox/rack/src/
    unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /go/src/github.com/convox/rack/src/Dockerfile: no such file or directory
    exit status 1
    2016/05/24 18:50:59 exit status 1
    ERROR: app build failed

**Comment by nzoschke** [comment]
I tracked this down... The repo that is triggering this has `Dockerfile` in the `.dockerignore` file. Convox omits things in .dockerignore during the `Creating tarball...` phase, so when it starts to build there is no Dockerfile present.
