### ISSUE TITLE
EC2 instances not being successfully terminated after uninstalling a rack

### ISSUE THREAD

**Issue by nerdylocks** [convox/rack#687]
I uninstalled a test rack and manually terminated (after noticing that they never got terminated) the EC2 instances but new instances kept on being instantiated. The solution was to delete stack in the CloudFormation console. The date was on 05/16/16.

Here are the events I retrieved from (Convox events and test rack events in a separate file): https://gist.github.com/nerdylocks/d9ae151adb9e658e2aaea442870c3c36

**Comment by nzoschke** [comment]
Thanks for the feedback. 

I'm going to close this in favor of re-using #411 for a good place to track problems with uninstall.

As we speak I'm testing a new uninstall that addresses some known issues where the first uninstall failed and required manual cloudformation cleanup. See #676 and #686 for PRs.
