### ISSUE TITLE
`convox services update <redis> --private` fails

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#689]
```
~convox-prod~ $ convox services update cheques-redis-01 --private
Updating cheques-redis-01 (private="true")...UPDATING
```

Cloudformation error:

```
The subnet ID subnet-XXXXXX is in use.
```

**Comment by nzoschke** [comment]
I have some tickets with AWS open. I'm starting to see that there are lots of subtleties updating network settings for resources.

**Comment by nzoschke** [comment]
I did learn that we can't replace the base VPC networking resources easily in CloudFormation. However I'm still not sure if that means its impossible. And I'm not still not sure if that applies to other services.

A service -> service migrator command would be sweet :)

**Comment by ddollar** [comment]
Seems like this not possible due to CF for now
