### ISSUE TITLE
Better error message for deploying to a new app

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#69]
If you try to deploy to a brand new app before it has finished creating the error message is:

`ERROR: websocket.Dial wss://grid.convox.com/apps/dungeon/builds//logs: bad status`

We should make that more helpful. Maybe something like:

`dungeon is still creating. Please try the deploy again after convox apps info reports the status as "running"`

**Comment by ddollar** [comment]
This should already be fixed in the latest CLI.

https://github.com/convox/rack/blob/master/cmd/convox/deploy.go#L48-L56

Please reopen if you're still seeing it.
