### ISSUE TITLE
GitHub webhooks with the same app name overwrite each other

### ISSUE THREAD

**Issue by snario** [convox/rack#702]
## Steps to Reproduce

1. Create a rack called `staging` and an app called `example` inside that rack
2. Create a rack called `production` and an app called `example` inside that rack
3. Use the console to link a GitHub repo `user/repo` to `staging/example`
4. Navigate to `production/example` and notice the app will already be thought to be linked (because it thinks it is `staging/example`)

**Comment by awsmsrc** [comment]
hey @snario thanks for the report.

This is actually an issue with console so I've added it to our internal issue tracker but I'll leave this here in the name of transparency.

Thanks a bunch

**Comment by awsmsrc** [comment]
this should be fixed now @snario
