### ISSUE TITLE
Include rack name in app ELB name

### ISSUE THREAD

**Issue by contra** [convox/rack#706]
Issue: Given a setup where you have two racks (production and staging) each running an app with the same name, it's impossible to tell the difference because they are named the same thing.

![](https://cldup.com/Qr9_G4YWjU-3000x3000.png)

Proposed solution: Include the rack name in the app ELB host, so in this case it would go from `staeco-web` to `stae-production-staeco-web`.

Thoughts?

**Comment by mwarkentin** [comment]
There might be an AWS restriction on what you can name the ELB - if not, this would be helpful.

**Comment by mattmanning** [comment]
@contra If you run `convox apps info -a <appname>` you'll get an output showing you which load balancer goes with which app/process.

https://convox.com/docs/port-mapping/

**Comment by contra** [comment]
@mattmanning I get that there is a way to do it, the issue is to improve the process and make it more intuitive.

**Comment by MiguelMoll** [comment]
Hey @contra. To make sure I understand,  you'd like for the distinction to be visible via the AWS console as well? Worth noting here that an ELB name has a maximum of 32 characters.

**Comment by contra** [comment]
@MiguelMoll yep

**Comment by ddollar** [comment]
Could be useful but unlikely to happen as changing ELB hostnames is hard/dangerous and we are already very limited by the amount of space available there.
