### ISSUE TITLE
Allow use of existing ELB for services

### ISSUE THREAD

**Issue by beedub** [convox/rack#708]
We'd like to do green/blue deployments using an ELB (detailed here: http://www.slideshare.net/AmazonWebServices/dvo401-deep-dive-into-bluegreen-deployments-on-aws) that points to multiple services

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JG45UXMY&#x2F;466-existing-elb-for-apps"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> existing elb for apps</a>

**Comment by ddollar** [comment]
How would this work at a high level? Two apps in the same ELB? Would you scale one up and the other down?

**Comment by beedub** [comment]
Yup, exactly. 2 or more apps could point to the same ELB and scaled in separately.

However, we ended up going with a different approach outside of ECS/ELB as using those 2 alone was a bit constricting, so this request is not important anymore for us (but still may be helpful for other reasons?)
