### ISSUE TITLE
convox login should be more clear about password vs api key

### ISSUE THREAD

**Issue by beedub** [convox/rack#709]
The cli language for `convox login` uses the term `password`, but it's actually an api key, which is actually the language used on the console website

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;eAO2HmKP&#x2F;260-convox-login-should-be-more-clear-about-password-vs-api-key"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> convox login should be more clear about password vs api key</a>

**Comment by MiguelMoll** [comment]
Thanks for the suggestion @beedub. The change should be out soon.
