### ISSUE TITLE
convox rack security group ssh

### ISSUE THREAD

**Issue by beedub** [convox/rack#710]
I noticed that the sg created for the rack instances allows ssh for `0.0.0.0/22`. It looks like `convox instance ssh` actually creates a websocket that streams through the api, so could the allowable range be more specific to an internal subnet (and thus more secure)? I tested this out on my rack and I was still able to use `convox instances ssh` into boxes

**Comment by nzoschke** [comment]
This has been released. Thanks for the issue and patch :)
