### ISSUE TITLE
TEMPLATE_FILE too large for install

### ISSUE THREAD

**Issue by beedub** [convox/rack#714]
I was following the development instructions and tried to specify `TEMPLATE_FILE` and received an error: `'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200`. Found a similar issue https://github.com/mapbox/cfn-config/issues/16

**Comment by nzoschke** [comment]
The template file is 56561 bytes currently. 

We can upload it to S3 before installing though there is a bit of a challenge in picking a bucket to PUT it to. If you use the CloudFormation management console it creates a bucket like `cf-templates-7k121xl5kax6-us-east-1` in your account. 

The file minifies to 35k. Maybe that's a good enough hack?
