### ISSUE TITLE
Security Group inbound rules

### ISSUE THREAD

**Issue by reczy** [convox/rack#720]
A couple of the security groups created by Convox have inbound rules allowing 0.0.0.0/0 where I would have expected to see my VPC CIDR. For example, I have a linked process in my `docker-compose.yml` with a single port, correctly resulting in the creation of an internal load balancer. However, the associated security group inbound rules look as follows:

<img width="520" alt="internal elb inbound" src="https://cloud.githubusercontent.com/assets/1100860/15761559/80166966-28de-11e6-8e89-2da14d45ca76.png">

Looking at the [AWS documentation](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-security-groups.html#elb-vpc-security-groups), I would have expected to see my VPC CIDR instead of 0.0.0.0/0. The security group with tag value "BalancerSecurityGroup" also has some 0.0.0.0/0 rules. The security groups for the web process, redis service, postgres service, and the one with tag value "SecurityGroup" all look as I would have expected.

Happy to provide additional info if needed.

**Comment by mwarkentin** [comment]
Seems similar to #710

**Comment by nzoschke** [comment]
A fix for the SSH security group is going out with #710 / #725.

From my reading of [the ELB Security Group docs](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-security-groups.html), we want 0.0.0.0/0 on all internet-facing ELBs, but the VPC CIDR for any internal ELBs.

So good catch, the security groups in `kernel.json` and `app.tmpl` should have conditionals.

**Comment by reczy** [comment]
Thanks for taking a look, Noah.

I just noticed that the AWS docs suggest limiting the outbound rules on both external and internal load balancers as well (same documentation that we both linked to above). Not sure if that would impact anything on Convox's end...

Also, a question for you while we're on the subject here - the Security Group tied to the load balancer that has the same name as my rack shows the following:
<img width="983" alt="screen shot 2016-06-03 at 5 34 58 pm" src="https://cloud.githubusercontent.com/assets/1100860/15794664/4e8e0000-29b2-11e6-973d-b8a8df2a2a66.png">

Not suggesting anything is wrong here, just curious - are these ports used for the CLI/Console?

**Comment by nzoschke** [comment]
Yes, the Rack API uses ports 80 and 443. The legacy registry uses port 5000.

**Comment by reczy** [comment]
Got it - thanks for the clarification!

**Comment by nzoschke** [comment]
For clarification, the next steps here are to:

- [ ] Add a conditional in kernel.json around the security group to use the VPCCIDR the PrivateApi flag is set
- [ ] Add a condition in app.tmpl around the balancer security groups if they are internal ELBs

**Comment by matthewford** [comment]
it would be nice if we could define inbound rules e.g. SSH only allowed from a VPN IP.

Or you can only access this ELB from CDN IPs.

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0rL30zwZ&#x2F;272-security-group-inbound-rules"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Security Group inbound rules</a>
