### ISSUE TITLE
convox ps stop vs convox kill?

### ISSUE THREAD

**Issue by beedub** [convox/rack#724]
I was under the impression that convox tries to mirror/mimic docker commands whenever possible. Assuming that to be true, would `convox kill` be a better fit than `convox ps stop`?

**Comment by awsmsrc** [comment]
Although I love consistency, I don't think Convox intends to have a 1:1 mapping to docker.
Docker should merely be thought of as a very useful implementation detail.

Thoughts @nzoschke?

**Comment by nzoschke** [comment]
There's no design goal to mimic Docker. The design goal is to make the Convox API as nice as possible for developers, independent of what Docker and AWS do. Then we map that API to CLI commands that are as nice as possible.

Currently the API is `DELETE /apps/{app}/processes/{process}` so I think the `convox ps` subommcna dnamespace is close enough.

I do like `convox kill` in that its shorter and many of the other process things like `exec` and `run` aren't in a subcommand either. But I don't think there is a clear enough motivation to change it right now.

The clearest motivation I see is that soon we will make a big push towards a 1.0 API that has been designed, reviewed, documented and tested much more thoroughly. I just opened an issue for this to track stuff like this and more:

https://github.com/convox/rack/issues/758

I'm closing this in favor of that. Thanks!
