### ISSUE TITLE
Update to amzn-ami-2016.03.c-amazon-ecs-optimized AMIs

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#730]
There are new AMIs. They include Docker 1.11.

We did observe a compatibility issue with Docker 1.11:

```bash
$ convox run --app httpd-807 web echo "hello world”
> hello world
> ERROR: API error (500): Container c5ef6ea6901a616ec68f57712b2eb41104b654949ef30d72b625e473f80f1a23 is not running
```

This will need to be addressed before we can release an update with the latest AMIs

**Comment by nzoschke** [comment]
I shelled onto a box with #725 (20160606214509) installed and see this message:

```
$ convox instances ssh i-0207ad9e

   __|  __|  __|
   _|  (   \__ \   Amazon ECS-Optimized Amazon Linux AMI 2016.03.a
 ____|\___|____/

For documentation visit, http://aws.amazon.com/documentation/ecs
12 package(s) needed for security, out of 30 available
Run "sudo yum update" to apply all updates.
```

But `openssl` was updated for security purposes. Need to double check security updates but not system updates like the kernel and docker are applied.

**Comment by ddollar** [comment]
Will probably need to update the docker client inside the convox/rack Docker image

**Comment by nzoschke** [comment]
New AMIs went out a while ago!
