### ISSUE TITLE
convox ps ERROR: cannot connect to Docker endpoint

### ISSUE THREAD

**Issue by beedub** [convox/rack#734]
```bash
$ convox ps
ERROR: cannot connect to Docker endpoint
```

The rack is also undergoing a rolling update, so the error may be related to that. But this error is sporadic and does go away

**Comment by nzoschke** [comment]
Thanks for the report, other people are seeing this too. Some things we can do to improve this:

* Still return something in `convox ps` even if there are Docker client connect or API errors
* Simplify the fanout to Docker clients. We make a Docker client connection and API call for every container, where this could be batched per instance

We try to connect to Docker to augment this information on top of what ECS has:

* command -- docker knows the RUN command in Dockerfile if the task definition command is empty
* id -- we prefer to use docker container IDs over ECS task ids
* started -- docker knows best when the container actually started
* ports -- but this seems wrong, the task definition should know...

We also try to connect to Docker to get one-off processes in the `convox ps` list.

**Comment by nzoschke** [comment]
A good next step would be to get `convox ps` still show output from a development rack that can not talk to any instance docker daemons.

**Comment by nzoschke** [comment]
Tangentially related, I noticed the `convox api get /apps/myapp/processes` looks strange with the `memory` and `size` attributes. I don't think we need both, and memory is always 0.

**Comment by nzoschke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9Ejn8N6X&#x2F;217-interstate-convox-ps-broken-right-after-deploy"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> interstate `convox ps` broken right after deploy</a>

**Comment by nzoschke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9Ejn8N6X&#x2F;217-interstate-convox-ps-broken-right-after-deploy"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> interstate `convox ps` broken right after deploy</a>

**Comment by nzoschke** [comment]
Ah, size and memory have something to do with `convox ps --stats`. We also get CPU and Memory stats from dockerd if that option is set.

**Comment by MiguelMoll** [comment]
Changes to address `ps` output have been merged and released via #761. I'm closing the issue for now but please let us know if something else shows up. Thanks!
