### ISSUE TITLE
Install and configure convox rack on new organization

### ISSUE THREAD

**Issue by cyrusd87** [convox/rack#735]
I have tried to create a new rack into a new organization from command line.

I have used the command '**convox switch**' to switch into the new organization, but it gives me an error because no rack was created.

I need to create and configure a rack from command line.

By default convox create 3 small ec2 instances, I want to overwrite this and other configurations (for example creating micro instances and enable only the services that I want).

Is there a documentation about this?

**Comment by mwarkentin** [comment]
@cyrusd87 You can tweak the number and type of instances using the `convox rack scale` command.

Details here: https://convox.com/docs/scaling/

**Comment by nzoschke** [comment]
@cyrusd87 Thanks for your question. 

As @mwarkentin said, you can also customize many things like like the instance size and count by following the "Scaling A Rack" docs: https://convox.com/docs/scaling/

You can also use the CLI to install a rack with more customization out of the box. You can see all the CLI install options with the following command. You will want the `--instance-count` and `--instance-type` flags:

```
$ convox install --help
convox install: install convox into an aws account

Usage:
  convox install [credentials.csv]

Options:
   --ami value			ID of the Amazon Machine Image to install
   --dedicated			create EC2 instances on dedicated hardware
   --instance-count value	number of EC2 instances (must be greater than 1) (default: 3)
   --instance-type value	type of EC2 instances (default: "t2.small")
   --region value		aws region to install in (default: "us-east-1") [$AWS_REGION]
   --stack-name value		name of the CloudFormation stack (default: "convox") [$STACK_NAME]
   --development		create additional CloudFormation outputs to copy development .env file [$DEVELOPMENT]
   --key value			name of an SSH keypair to install on EC2 instances
   --email value		email address to receive project updates [$CONVOX_EMAIL]
   --password value		custom API password. If not set a secure password will be randomly generated. [$PASSWORD]
   --version value		release version in the format of '20150810161818', or 'latest' by default (default: "latest") [$VERSION]
   --vpc-cidr value		The VPC CIDR block (default: "10.0.0.0/16")
   --subnet0-cidr value		Subnet 0 CIDR block (default: "10.0.1.0/24")
   --subnet1-cidr value		Subnet 1 CIDR block (default: "10.0.2.0/24")
   --subnet2-cidr value		Subnet 2 CIDR block (default: "10.0.3.0/24")
   --subnet-private0-cidr value	Private Subnet 0 CIDR block (default: "10.0.4.0/24")
   --subnet-private1-cidr value	Private Subnet 1 CIDR block (default: "10.0.5.0/24")
   --subnet-private2-cidr value	Private Subnet 2 CIDR block (default: "10.0.6.0/24")
   --private			Create private network resources
   --private-api		Put Rack API Load Balancer in private network. Implies --private
```

After you do this, you will need to use the "Add Existing Rack" option in Console to register your new rack there.

<img width="423" alt="screen shot 2016-06-17 at 8 44 57 am" src="https://cloud.githubusercontent.com/assets/147410/16156192/d427a81e-3467-11e6-9057-43ad7e5daad1.png">
