### ISSUE TITLE
Tagging inconsistencies

### ISSUE THREAD

**Issue by dlanger** [convox/rack#740]
Until #560 is done, I'm trying to use the existing tags to do my cost reporting. There are a few missing `Name` and `Rack`:

- [ ] The ELB for the Convox API
- [ ] The EBS volumes that come with instances
- [ ] The ENIs 

The VPC doesn't have `Rack`, but that makes sense. The NAT Gateways don't have any, but that's (sadly) because AWS doesn't support tags on them.

**Comment by nzoschke** [comment]
I've hit cost reporting challenges too. Thanks for the tips @dlanger, big +1 to get this fixed up.

Any other resource tracking or cost reporting tips while we're at it?

**Comment by mwarkentin** [comment]
I think these types of tags are also really useful for building out dashboards in DataDog as well (we use `Rack` heavily where we can).

**Comment by dlanger** [comment]
Stack-level tags are your friend - if you set the tag there, it'll automatically propagate down to every* taggable resource in the stack, including ones you create in the future. In the absence of this happening in `convox` itself, I've gone and manually set them though the AWS console on all my stacks.

*Everything except EBS devices. For this, we have a four-line Python script that runs every hour on a Jenkins box which enumerates all the EBS devices we have, and copies down every tag (except those starting with `aws:`) from the  EC2 instance it's attached to. ElastiCache instances are also tricky to tag properly.

**Comment by mwarkentin** [comment]
[Stack-level tags docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html)

**Comment by ddollar** [comment]
Fixing in #560
