### ISSUE TITLE
Cannot spin down 3 old instances after scaling instances up

### ISSUE THREAD

**Issue by theonetheycallneo** [convox/rack#748]
convox rack scale --type=t2.small --count=0 ERROR: count must be greater than 1

we now have 3 t2.small and 3 t2.medium and unable to remove the original t2.small after scaling to 3x 2.medium

**Comment by matthewford** [comment]
AWS Cloudformations will kill the old instances for you, you do not need to scale down manually, in fact that command is trying to scale your current rack to 0 instances, which is why it is failing.

**Comment by theonetheycallneo** [comment]
Thank you, that did the trick!

**Comment by awsmsrc** [comment]
I have tested this and everything appears to work as expected on the latest rack/client.

It looks like @theonetheycallneo's concerns have been addressed, so I am going to go ahead and close this.

If you notice anything is still amiss do feel free to reopen or submit a new issue.

Thanks for using Convox and providing feedback on your experience :)
