### ISSUE TITLE
convox uninstall with credentials.csv specified does nothing

### ISSUE THREAD

**Issue by beedub** [convox/rack#749]
Without specifying `[credentials.csv]`, the cli prompts for credentials and once inputted, continues.

When specifying `[credentials.csv]` like 
`$ convox uninstall us-west-2 staging ~/Downloads/credentials\ \(1\).csv`, the cli doesn't do anything

**Comment by oren** [comment]
It might just be the order of the arguments. try to put the stack-name before the region: `convox uninstall staging us-west-2 ~/Downloads/credentials\ \(1\).csv`. 

I just tried it and it deleted my convox resources with proper output. Let me know.

**Comment by nzoschke** [comment]
There was a bug around this, patched in https://github.com/convox/rack/commit/ca1f6d1f8f011b838420bc129582c2248bbf0859. Please try it after a `convox update` and feel free to reopen if its still broken.
