### ISSUE TITLE
Add parameter for load balancers to use custom security group

### ISSUE THREAD

**Issue by ddollar** [convox/rack#750]
Users want to limit access to certain applications to various individual offices or locations.

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;gbZsH3dR&#x2F;262-app-param-for-elb-security-group"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> App param for elb security group</a>

**Comment by MiguelMoll** [comment]
Resolved via #779
