### ISSUE TITLE
Some ways Convox' .dockerignore support seems lacking

### ISSUE THREAD

**Issue by mrluc** [convox/rack#756]
The basic issue is that Convox' support of `.dockerignore` files to cut down on the size of the build context sent up to Rack isn't 1:1 with docker's understanding of a `.dockerignore` file.

**This leads to situations where something works with `convox start`, and doesn't on `convox deploy`.**

Some examples that bit me in the space of 90 minutes while working somewhere with bad internet:

1. **It doesn't support exclusion.**

  Here's a valid .dockerignore for the top-level of an umbrella app, which it seems as though Convox doesn't support:

  ```
  *
  !release-binaries/apps/*/binary-artifact
  ```
  
  See https://github.com/convox/rack/pull/175#discussion_r63209774

2.  **It doesn't seem to respect that dockerignore rules are top-level-only by default.**

  I had a top-level .dockerignore that included:
  ```
  bin
  ```
  Which ignored a directory that contained some project-wide deploy scripts and things. This worked locally and didn't interfere with the functioning of the app.

  I also had
  ```
  /release-binaries/appname/Dockerfile
  /release-binaries/appname/binary-artifacts/appname/bin/...
  ```

  And my docker-compose referenced it with `build: release-binaries/appname`.

  However, while my app built and ran via `convox start`, deploying it to Rack resulted in the processes dying with  `/rel/appname/bin/appname: not found`, which was confusing. I was able to use Convox' nice `convox run` support to see what's wrong with that container image, and lo and behold, the `'rel/appname/bin` folder was missing! Why would that be? After much head-scratching, I tried commenting out the `bin` line in the top-level `.dockerignore` and `convox deploy` succeeded.

**Comment by nzoschke** [comment]
Thanks for the really detailed bug report. A fix for this is in the testing/release process right now.

**Comment by nzoschke** [comment]
This is fixed in https://github.com/convox/rack/releases/tag/20160614203313. Thanks again for the bug report!

**Comment by mrluc** [comment]
Convox, you never cease to amaze. :)
