### ISSUE TITLE
API 1.0: design, documentation, testing and client/server version compatibility

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#758]
There is room for improvement in the Convox API before we could take a "beta" label off of it:
- [ ] Design of API endpoints and parameters
- [ ] Design of CLI commands that map to API endpoints
- [ ] Comprehensive documentation
- [ ] Comprehensive API testing
- [ ] Versioning with client/server compatibility

**Comment by nzoschke** [comment]
On #724 @beedub raises a CLI design question around `convox ps stop` vs `convox kill`. Should process commands like `run, exec, scale, stop` be under the `ps` subcommand or be top level commands?

**Comment by beedub** [comment]
I noticed another minor inconsistency with the cli:

`

**Comment by beedub** [comment]
I noticed a potential minor inconsistency with the redis service params:

```
  redis       [--automatic-failover-enabled] [--instance-type=cache.t2.micro] [--num-cache-clusters=1] [--private]
```

Should enabling automatic failover just be `--automatic-failover` instead of `--automatic-failover-enabled` given that private is simply `--private`?
