### ISSUE TITLE
Allow version to be passed in when creating a new service

### ISSUE THREAD

**Issue by caseycrites** [convox/rack#760]
I'd like to create a postgres database with 9.5.2 as the version, but 9.4.5 is hardcoded in the template [here](https://github.com/convox/rack/blob/master/api/models/templates/service/postgres.tmpl#L105). Instead, I'd like to be able to pass the version I'd like in as a command-line argument when creating the service.

**Comment by jordansexton** [comment]
+1 I ran into the same issue. I had to downgrade my local postgres install to 9.4.5 for a complicated dump and restore operations recently because of this.

**Comment by nzoschke** [comment]
Big +1. It's good CloudFormation patch if anyone wants any pointers.

**Comment by MiguelMoll** [comment]
Postgres service now supports [Version](https://github.com/convox/rack/blob/f329cc3591bda22400e72988355caa120b2b18eb/provider/aws/templates/resource/postgres.tmpl#L71-L74) parameter, Along with [Family](https://github.com/convox/rack/blob/f329cc3591bda22400e72988355caa120b2b18eb/provider/aws/templates/resource/postgres.tmpl#L24-L27) version.

**Comment by jordansexton** [comment]
Nice! :+1:
