### ISSUE TITLE
Clone additional GitHub private repos during build

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#771]
As requested from frank in Slack:

>  if a repo has a dependency from another private repo. then `git clone` during build would fail.

**Comment by nzoschke** [comment]
I'm not entirely sure about the OAuth token scope, but perhaps we can use a strategy as the GitLab access token here:

https://github.com/convox/rack/blob/master/api/cmd/build/main.go#L119

But write to a .netrc file. An older version of the build utility actually did this:

https://github.com/convox-archive/build/blob/master/data/netrc

**Comment by frankleng** [comment]
@nzoschke thanks!
possible to get an ETA on a fix? as it's breaking one of our CD pipes.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ci8VNEBH&#x2F;281-github-private-build-token"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> GitHub private build token</a>
