### ISSUE TITLE
API Auth Security and Protocol

### ISSUE THREAD

**Issue by snario** [convox/rack#776]
We should have greater security for convox racks, for example public-private key or client_id and secret. 

A new rack could perhaps start with a single API key with the current authentication method, and then a user would tell the rack to add a public key, then the user could set API key auth to False. For example:

```
cat ~/.ssh/id_rsa.pub | convox rack auth set
==> Successfully added key snario-local-laptop
```

```
convox rack auth set DisableAPIKey=True
```

Connections to the rack API from here on would use public private key as an auth method. By default `~/.ssh/id_rsa` but optionally pass in a parameter `-i my-custom-key.pem`.

This would also enable user-by-user auth instead of a single SSH key into hosts.

**Comment by snario** [comment]
Another good idea @nzoschke had was to use IAM roles / users as authentication to the Convox API.

**Comment by nzoschke** [comment]
This is an important decision. Basic Auth is simple but surely not the final form of API access.

**Comment by ddollar** [comment]
For now we are going to continue using the single master password for Rack.
