### ISSUE TITLE
Rack ClientId value can cause convox/agent to not start

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#777]
convox/agent upstart shell script can fail based on shell interpretation passing the value of ClientId into the docker container environment as CLIENT_ID.

https://github.com/convox/agent/blob/master/convox.conf

**Comment by nzoschke** [comment]
Convox without a running agent is really bad. I don't think this is happening much but it would be really nice if it couldn't.

**Comment by MiguelMoll** [comment]
Is this a bash vs sh issue? This could present itself if a custom AMI is used?
