### ISSUE TITLE
Convox client fails to deploy if the cwd is a symlink

### ISSUE THREAD

**Issue by anthias** [convox/rack#778]
Below is the error. Again, this happens when the project is symlinked and you use the symlink to get to the project.

```
$ convox deploy
Deploying rails
Creating tarball... WARN[0001] Tar: Can't archive a file with includes      
OK
Uploading... OK
RUNNING: tar xz
file not found: docker-compose.yml
2016/06/17 22:41:50 exit status 1
ERROR: rails build failed
```

**Comment by nzoschke** [comment]
Thanks for the report. The symlink hint came from other reports of the "Tar: Can't archive a file with includes" error

https://github.com/docker/docker/issues/16339

**Comment by awsmsrc** [comment]
@nzoschke is this new with the new release?

**Comment by anthias** [comment]
Rolling back to `20160606232025` (@nzoschke's recommendation) fixed it.

**Comment by nzoschke** [comment]
@awsmsrc yes this is a regression with the docker/archive stuff. It's easy to reproduce, symlink an app into a tmp folder and `convox deploy`
