### ISSUE TITLE
Build failing for docker 1.12 due to `docker tag -f` flag which is now removed

### ISSUE THREAD

**Issue by asyazwan** [convox/rack#781]
We've done it folks. Deprecation warning since 1.10 and have we done? Ignore it!

Fix should be just to remove `-f` altogether from all references of `docker tag` such as the offending https://github.com/convox/rack/blob/c533520b5e587e6e44253fb0240bab618c355bc4/api/manifest/manifest.go#L349 that prevents `convox start` from working with this error:

```
Successfully built 52b83b62a098
RUNNING: docker tag -f convox-hkrfeetpkt web-dev/web
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.
ERROR: exit status 1
```

**Comment by nzoschke** [comment]
Caught a side effect of this when testing https://github.com/convox/rack/pull/779

```
Successfully built 387a081243b7
RUNNING: docker tag convox-ojdlxlvxew release/release
Error response from daemon: Conflict: Tag release/release:latest is already set to image a755c7bc5dc9, if you want to replace it, please use -f option
exit status 1
2016/06/21 22:14:07 exit status 1
ERROR: release build failed
```
