### ISSUE TITLE
Don't create multiple self-signed certs for *.*.elb.amazonaws.com in the same account

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#786]
AWS accounts are limited to 20 certs. Creating many of these certs can eat up that limit pretty quickly. We shouldn't need more than 1 in any particular AWS account.

**Comment by mwarkentin** [comment]
We ran into this today as well.

**Comment by ddollar** [comment]
Yes you are free to delete them. The underlying API won't let you delete them (will return an error) if they are being used by anything.

**Comment by ddollar** [comment]
#1402 should also prevent the proliferation of these
