### ISSUE TITLE
Periodically call PullAppImages to keep caches warm

### ISSUE THREAD

**Issue by ddollar** [convox/rack#787]
Let's call `models.PullAppImages()` periodically rather than just on boot to maximize the chance of cache hits during builds.

**Comment by mwarkentin** [comment]
👍 is there any event / notification that could be hooked into so that when a build is finished, the other API container pulls immediately?

**Comment by ddollar** [comment]
Builds now happen cluster-wide so we'll need a different overall warming strategy.
