### ISSUE TITLE
"Rack in steady state" message not very helpful

### ISSUE THREAD

**Issue by ddollar** [convox/rack#789]
One user reported seeing this message spamming when they had a worker container refusing to start. Can we make this message more helpful in tracking down what's happening?

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;myJu43RK&#x2F;271-check-out-console-rack-spamming-slack-w-ready-state-message"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Check out console&#x2F;rack spamming slack w&#x2F; ready state message</a>

**Comment by nzoschke** [comment]
Closing this in favor of https://github.com/convox/rack/issues/68.
