### ISSUE TITLE
memcached service

### ISSUE THREAD

**Issue by ddollar** [convox/rack#791]
Wrap ElastiCache memcached in a service. Should be mostly the same as `redis`

**Comment by dtran320** [comment]
Just looking through Convox in detail for the first time and jumped into the bug list— is this addressed by #804 or am I misunderstanding this bug— it's not very clear :)

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Gg8NGBpW&#x2F;576-memcached-service"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> memcached service</a>
