### ISSUE TITLE
Release created by environment change uses unexpected build

### ISSUE THREAD

**Issue by ddollar** [convox/rack#793]
Currently when an environment variable is changed the `ForkRelease()` function forks from the latest release.

https://github.com/convox/rack/blob/master/api/models/app.go#L345-L361

So in the following scenario:

* User creates build but does not promote it
* User updates environment variable and promotes the new release
* App is now running on the unpromoted build

I think the right answer is to make ForkRelease() fork from the currently promoted Release. Anyone see any possible issues with that?

**Comment by mattmanning** [comment]
+1 This seems to be the preferred behavior among users I've talked to.

**Comment by mwarkentin** [comment]
👍

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ilsEvrhf&#x2F;277-release-created-by-environment-change-uses-unexpected-build"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Release created by environment change uses unexpected build</a>

**Comment by nzoschke** [comment]
In reviewing this I found a case to think about... Setting 2 environment variables, one at a time.

If we always fork from the current release, you can't progressively build up a new release.

**Comment by nzoschke** [comment]
Is the desired behavior something like this: fork from the latest release that's based off the current build.

**Comment by mwarkentin** [comment]
Good catch. Is setting multiple environment variables possible in one shot? I've generally done it in multiple steps, promoting the last one.. but if you could do them all in one, that would make it less of an issue.

Your suggestion seems like it could fix the issue too.

**Comment by MiguelMoll** [comment]
Fix for this is available in rack version 20160629165916. More info in #803
