### ISSUE TITLE
Wordpress and wp-content directory support

### ISSUE THREAD

**Issue by cyrusd87** [convox/rack#798]
Hi,

I am trying to mount as a volume an S3 bucket into a docker container.

I have done several attempts also using the following docker container https://github.com/convox-archive/s3fs without success (in the last one if I inspect the container no directories and files from the buckets are present.

I have seen another issue about the same topic  https://github.com/convox/rack/issues/183 where it explained that volumes are not supported in production.

I need to use S3 bucket because I want to publish a wordpress container and I want to mount the wp-content directory on a aws storage service like S3.

Are there other solutions? 

Thanks

**Comment by nzoschke** [comment]
This release has the new EFS service.

https://github.com/convox/rack/releases/tag/20160714004416

In theory Wordpress should work very well with this. 

You might be one of the first to try it! If it works, let everyone know. :)

**Comment by ddollar** [comment]
We have lots of reports of Wordpress working for people now so closing this.
