### ISSUE TITLE
Logstash support

### ISSUE THREAD

**Issue by sanel** [convox/rack#802]
Hi guys,

Is it possible to redirect logs from `papertrail` to logstash? I've managed to find few mentions, but nothing usable. Or, how hard would be to add support for that?

Thanks,
Sanel

**Comment by mwarkentin** [comment]
Do you mean sending all of the logs to a centralized logstash server, or something else?

It looks like logstash supports ingesting syslog events: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html

The convox papertrail service has been deprecated and replaced with a [generic syslog service](https://convox.com/docs/syslog/), so potentially you could point that at your own logstash box running some place?

**Comment by sanel** [comment]
> Do you mean sending all of the logs to a centralized logstash server, or something else?

Yes.

Didn't know about generic syslog service - I'll continue from here :)

Thanks!
