### ISSUE TITLE
Better default for convox logs --since

### ISSUE THREAD

**Issue by ddollar** [convox/rack#808]
2mins is pretty short, let's bump this up. What makes sense here? 10m? 1h?

**Comment by skwp** [comment]
I want to offer a contrary opinion here. Most real apps produce lots of logs. Going back 10 minutes could make the `convox logs` command have gigantic outoupt.

**Comment by ddollar** [comment]
Good point. Maybe some combination of longer "since" and a limit?

**Comment by skwp** [comment]
Yeah that would be fine but if nobody is complaining about this log tail not being long enough, I wouldn't even do this ticket :)

**Comment by nzoschke** [comment]
Yeah I like the default and don't see many complaints yet.

The CWL API only supports a start_time.

Last N messages would be a nicer default, for apps under little development.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6lg1g7uF&#x2F;465-default-for-convox-logs-since"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> default for convox logs --since</a>
