### ISSUE TITLE
Automatically update homebrew formula on CLI releases

### ISSUE THREAD

**Issue by ddollar** [convox/rack#824]

**Comment by mwarkentin** [comment]
This would be :godmode: 

These are the only two lines which need to be updated: https://github.com/mwarkentin/homebrew-core/blob/a22237a769391c2d17439306b67724a4ab7e79e4/Formula/convox.rb#L4-L5

**Comment by alex** [comment]
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb may be useful/relevant

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use equinox.io homebrew tap](https://trello.com/c/3ZR36l13/1227-use-equinox-io-homebrew-tap)
