### ISSUE TITLE
docker-compose run equivalent?

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#827]
- [docker-compose run docs](https://docs.docker.com/compose/reference/run/)

Our use case is running an interactive debugger in one of our web or rpc processes - which doesn’t work with `convox start` as it’s not an interactive terminal. We’ve got a hacky way to handle it for our web processes detailed below), however this doesn’t work for our rpc processes as we would have to modify our calling code as well to point to the new port (would probably get laughed out of the room if I asked devs to do this 😄).

What we’d like is something like (ignore the terrible naming, there’s already a `convox run` command..) - `convox runlocal rpc —service-ports python manage.py runserver 0.0.0.0:8000`

This would run the command above inside the `rpc` process, launch all of our other required containers in the background, and map the ports.
### Hacky McHackface

docker-compose.yml

``` yaml
web:
  build: .
  command: /app/bin/web
  ports:
    - 10008:80
    - 8008:8000  # this is the extra port for running the debug process interactively on
```

Makefile

```
start: ## Start application
    @convox start
debug: ## Launch a interactive runserver process
    @open https://localhost:8008  # Launch the browser to the correct port, so that devs don't have to remember which port is which
    docker exec -it notifications-web python manage.py runserver 0.0.0.0:8000  # Launch the dev server w/ debugger in interactive terminal
```

To use the interactive debugger, I would run `make start` in one tab, then `make debug` in another - so I'm running my debug process _in addition to the normal web process_ on a different port.

Ideally (as far as my short amount of thinking goes), what I'd do instead:
- Remove the `8008` port definition from my `docker-compose.yml`
- Replace `docker exec -it notifications-web python manage.py runserver 0.0.0.0:8000` with `convox runlocal web —service-ports` (I'm not sure if I could do this to run my default command, or if I'd need to specify)
  - This would launch an interactive terminal with my web process running on it's usual port, which means I could continue to use my existing domain mapping, etc.

**Comment by mwarkentin** [comment]
This might not be needed if we can use `docker attach` to hook up to a docker stdin/out.

**Comment by mwarkentin** [comment]
Did some testing of `docker attach` - I was still having issues because convox is launching containers in non-tty mode, even if I specify `tty: true` in the `docker-compose.yml`.

@ddollar created a [`convox`](https://files.slack.com/files-pri/T08HXR6G2-F1RTK62F8/download/convox.gz) binary which enabled tty mode. He successfully ran an interactive rails debugger, and I was able to do the same in the django dev server using this binary.

@ddollar raised some concerns about running tty mode on rack deployments:

> most likely would be problems capturing logs
sometimes processes behave differently if stdin is a tty
could maybe try to do tty but not attach stdin
my guess would be ecs task definitions dont support that

So that leaves the question about the best way to do this:

* Support `tty: true` in `convox start` only
  * This may be confusing if someone had a reason to want to run a deployed app in `tty` mode - I don't have any use cases that come to mind though
  * Could add a warning to the logs that the app process isn't running in tty even though it's specified in the compose file
* Support `tty: true` in both `convox start` and rack deployments
  * Would require using two different `docker-compose.yml` files if you wanted to run in tty local-only (our use case)
* Some other way of enabling tty mode for `convox start` - a command line option, environment variable, etc.
  * Seems like this could have some discoverability issues / people would wonder why it's not using the existing compose configuration

I'm not familiar enough with docker compose outside of using it for convox configuration - is it possible that this just isn't an issue for them as docker compose is mainly used only as a dev tool? 

It also appears that AWS doesn't support the `tty` directive when you create an ECS service from a compose file ([ref](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html)). This would lead me towards option 1.

**Comment by mwarkentin** [comment]
> 
ddollar [2:23 PM]  
yep.. i think making it local only is fine for now

**Comment by mwarkentin** [comment]
I'm hoping to take a crack at this soon.

**Comment by ddollar** [comment]
This is now `convox start <process> <command>`

**Comment by mwarkentin** [comment]
@ddollar Are there any docs about this? Or just a link to where this functionality was introduced? I'd like to understand it better to see if it covers our use case.

**Comment by soulshake** [comment]
@mwarkentin this is documented [here](https://convox.com/docs/one-off-commands/#convox-start).

**Comment by ryanwilsonperkin** [comment]
@mwarkentin heya, fancy seeing you here. I'm wondering - did this project ever add support for `tty: true` in docker-compose?
