### ISSUE TITLE
Output "cpu" and "memory" with "convox api get /system"

### ISSUE THREAD

**Issue by lawrencepit** [convox/rack#84]
It would be nice if `convox api get /system` (and `convox rack`) also outputs "cpu" and "memory" just like /apps/{app}/processes does. That would allow to monitor the values and scale the rack when necessary (*).

Reference: http://convox.github.io/api/#!/default/get_system

(*) I suppose it would also be possible to add a Scaling policy to the Autoscaling Group of the convox instances in AWS to scale the rack when necessary.

**Comment by csquared** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;E7xMh5oy&#x2F;218-systemwide-cpu-and-memory"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> systemwide &quot;cpu&quot; and &quot;memory&quot;</a>

**Comment by csquared** [comment]
Thanks!

**Comment by csquared** [comment]
this is going to be exposed via `GET /instances` -> each instance has per-machine cpu and memory

**Comment by csquared** [comment]
see #181
