### ISSUE TITLE
Customizing log driver

### ISSUE THREAD

**Issue by adamenger** [convox/rack#842]
Hi there,

I'd like to be able to customize the `logConfiguration` key of the task definition that's submitted for a given convox app. Digging through the code it doesn't look like this is there.

Is this something Convox would accept as a patch/support as a feature?

**Comment by mwarkentin** [comment]
CC @robatwave

**Comment by nzoschke** [comment]
In general yes. It is pretty annoying to not have the task definition options available to experiment with without a convox patch.

Do you have ideas for a design here? We can't make every process task definition a stack parameter.

**Comment by nzoschke** [comment]
@adamenger yes, log driver customization would be accepted as a patch.

Some of my thoughts...

I'm not sure the benefit until there's more than the `awslogs` driver. Convox is effectively using the driver, and adding important context like process name and container id that you don't get with the native driver.

I also see something tricky about the design here.

We want to manage app settings like this with CloudFormation.

I think you'd need both a `LogDriver` and `LogDriverOptions` and I assume options would be wildly different between `awslogs` and say `fluentd` if support ever lands for that.

But the logConfiguration options map isn't very CF friendly.

```
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "awslogs-mysql",
                    "awslogs-region": "us-west-2"
                }
```

I think this might require parsing the `LogDriverOptions` value in the custom resource.

**Comment by adamenger** [comment]
I've given this one a shot on a branch and you were correct, it's actually quite difficult to do this. Honestly after a lot of consideration I have accepted the existing path shipping logs via Cloudwatch.  I figured out that if I were to change the underlying log driver, I wouldn't be able to use the live streaming via web sockets, which would break some expected functionality for some devs on our rack. 

I've submitted support for a fluentd service driver instead. So if anybody else has a need for this, please press on, otherwise I'm content with using the logging system as it was originally designed and using the FluentD service I wrote to pull logs from cloudwatch.

**Comment by nzoschke** [comment]
The fluentd adaptor is great. Thanks! We'll revisit this later if/when more log driver options makes sense.
