### ISSUE TITLE
Minimum healthy percent

### ISSUE THREAD

**Issue by matthewford** [convox/rack#849]
I see a lot of the following errors when deploying apps: 

> was unable to place a task because no container instance met all of its requirements

This is partly due to the default "Minimum healthy percent"  being 100. 

Could we set the default to 50? or something similar?

**Comment by MiguelMoll** [comment]
How many instance containers are you running in a rack? I believe the general idea is to have one more instances than the number of processes so that ECS can find an instance to use. Doesn't seem ideal though.

Any other thoughts on changing the minimum health percent?

**Comment by ddollar** [comment]
This would need to be somewhat dynamic. If you are only scaled to `1` then it is my understanding that any value below 100 could cause downtime.

**Comment by matthewford** [comment]
yeah I guess for anything more than 1

**Comment by matthewford** [comment]
The issue is mainly seen when the app is scaled close to the number of instances in the rack.

**Comment by mwarkentin** [comment]
There's a ticket open with discussion around dynamic values already: https://github.com/convox/rack/issues/429
