### ISSUE TITLE
convox start hangs if linked container is external

### ISSUE THREAD

**Issue by donpark** [convox/rack#85]
I have a container named `postgres` running locally so left it out of `docker-compose.yml` but referenced like this:

	foo:
	  build: .
	  ports:
	  - 3001:3001
	  - 4001:4001
	  environment:
	  - RACK_ENV=development
	  - POSTGRES_URL=postgres://postgres:password@postgres:5432/app
	  links:
	  - postgres

but this hangs `convox start`. `docker images` also showed an unknown image.

**Comment by csquared** [comment]
thanks for the heads up! that's expected right now -> links need to point to other running containers. we're waiting for docker networking to land before we revisit links in general.

for this to work with convox just drop the `links` section altogether. you can use the RDS service in production and point to your local postgres all via the ENV var. plz reopen if that doesn't work out!
