### ISSUE TITLE
Increase reliability of build caches

### ISSUE THREAD

**Issue by snario** [convox/rack#851]
Once https://github.com/convox/rack/pull/822 is merged, the Convox API can start using EFS for the docker cache. It might be as simple as mounting the docker directory, but I'm sure there are edge cases to consider.

``` yml
volumes:
    - /var/lib/docker
```

**Comment by mwarkentin** [comment]
Could perhaps add it in as a rack parameter option, at least to begin with? Put it through a bit of a "beta" phase and let people try it out and report if they find any issues?

**Comment by mdub** [comment]
I'm pretty sure Docker advise against sharing `/var/lib/docker` between Docker daemons. What is the (perceived) benefit of putting it on EFS?

**Comment by mwarkentin** [comment]
@mdub Mainly preventing rebuilds when a `convox deploy` runs against a different server than it's built on previously.

**Comment by nzoschke** [comment]
Better caching of docker images is a great idea, but I share the same concerns about putting EFS in the production path in general, as well as moving `/var/lib/docker` to EFS.

/var/lib/docker has a lot more content than just the images, and as mdub says it probably shouldn't be shared across instances.

Is the simpler strategy of pulling the latest app images on every API boot not working for build caching?

**Comment by mwarkentin** [comment]
Not sure, but that would only work for images that would be built **before** the new API container launched.

This might be most noticeable when a new app has just been created, and deployed twice (or however many times it takes to build on a second API container). If you do 2 `convox deploy`s in short sequence, and they both do full app builds (which could be pretty slow) - you'll be concerned that the deploy process will be like that every time (and ask about it in chat).

**Comment by nzoschke** [comment]
Ah, multiple builds landing on the 2 API instances can definitely be slow. This is a simpler solution but wouldn't catch every scenario:

https://github.com/convox/rack/issues/787

**Comment by snario** [comment]
This may be helpful: http://blog.runnable.com/post/145362675491/distributing-docker-cache-across-hosts

**Comment by snario** [comment]
That article also links to a relevant GitHub issue in the Docker repo about images loaded the full build cache when pulled https://github.com/docker/docker/issues/20316.

**Comment by ddollar** [comment]
Another option here is to build a storage driver that uses both EFS and local file system together as a blob store.
 
https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/

**Comment by bladealslayer** [comment]
Perhaps the recently merged https://github.com/docker/docker/pull/26839 could help, but it might take quite a while before that release hits ECS AMIs.

**Comment by ddollar** [comment]
We're likely going to have to look to CodeBuild or Docker to get this one right in the medium term.

**Comment by mwarkentin** [comment]
+1 to CodeBuild, would be nice getting build processes off of the cluster.
