### ISSUE TITLE
`convox update` gets stuck and dies

### ISSUE THREAD

**Issue by nikolay** [convox/rack#852]
```
$ convox update
Updating: - ERROR: unexpected EOF
```

**Comment by ddollar** [comment]
Do you have any sort of out-of-the-ordinary network setup going on?

**Comment by nikolay** [comment]
@ddollar Nothing out of the ordinary. Installed via Homebrew.

**Comment by mwarkentin** [comment]
Just confirmed that my brew installed version was able to update:

```
mwarkentin@Michaels-MacBook-Pro ~  ~unknown~ $ brew list | grep convox
convox
mwarkentin@Michaels-MacBook-Pro ~  ~unknown~ $ convox -v
client: 20160624144537
ERROR: must login first
mwarkentin@Michaels-MacBook-Pro ~  ~unknown~ $ convox update
OK, 20160706210644
```

What version is currently installed?

**Comment by nikolay** [comment]
@mwarkentin It works sometimes, but fails most of the time. I did a `brew reinstall convox`, cleaned up `~/.convox`, and reconfigured - same thing. Very spotty performance, but... I'm abroad, in Bulgaria. Never had issues in Southern California.

**Comment by mwarkentin** [comment]
I believe convox pulls updates from https://dl.equinox.io/convox/convox/stable - are you able to download a release directly from there successfully? Could just be network issues I guess.

**Comment by nikolay** [comment]
@mwarkentin Let me try a clean install outside of Homebrew. I don't have networking issues with anything else.

**Comment by nzoschke** [comment]
Is this still happening? We delegate updates to the fantastic https://equinox.io/ service. Based on a code review of:

https://github.com/convox/rack/blob/master/cmd/convox/update.go

I think you're getting the EOF in the equinox path.

If this is reproducible can you ping me/us on slack when we can look at it together?

**Comment by nikolay** [comment]
@nzoschke It still gets stuck - stop spinning and then errors out after a clean install. I tried using a VPN service, it goes different route then, and still gets stuck.

**Comment by ddollar** [comment]
We have fixed a bunch of network and proxy issues since this issue was submitted. Please let me know if you're still seeing issues.
