### ISSUE TITLE
convox install/uninstall leftovers

### ISSUE THREAD

**Issue by donpark** [convox/rack#86]
Steps to reproduce:

1. `convox install`
2. `convox uninstall`
3. Check AWS dashboard

Artifacts left behind:

1. 3 key pairs
2. 3 extra security groups other than the default one
3. 2 S3 buckets (convox-registrybucket-xxx and convox-settings-xxx)

No big deal but filed as FYI. Docker images & contains left behind after local `convox start` iterations is more annoying in comparison.

**Comment by csquared** [comment]
thanks for the heads up and doing the accounting there.

Right now this is part of a limitation on CloudFormation -> they don't natively support deleting an s3 bucket with anything in it. Our attempts to create a custom resource showed that if the bucket deletion hangs at all it can block the entire uninstall or even worse -> randomly delete the bucket at CloudFormation's will.

our recommendedation is to follow up a `convox uninstall` with a few calls to the AWS api via `aws-cli`.

**Comment by csquared** [comment]
also, i've been using these for the docker artifacts:

```
docker-cleanup-containers () {
  docker rm $(docker ps -a -q)
}

docker-cleanup-images () {
  docker rmi $(docker images | grep "^<none>" | awk '{print $3}')
}
```
