### ISSUE TITLE
Investigate support for builds that use npm and private repos via SSH.

### ISSUE THREAD

**Issue by MiguelMoll** [convox/rack#862]
```
npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror ssh://git@github.com/OrgName/internal-repo.git /root/.npm/_git-remotes/git-ssh-git-github-com-OrgName-internal-repo-git-develop-abc123
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-ssh-git-github-com-OrgName-internal-repo-git-develop-abc123'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
```
#839 addressed git credentials via HTTP. Take the opportunity here to solve the same with SSH.

**Comment by frankleng** [comment]
install via https also failed.
```npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/org/repo.git /root/.npm/_git-remotes/git-https-github-com-app-git-develop-254ebb68: Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-app-git-develop'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/org/repo.git /root/.npm/_git-remotes/git-https-github-com-app-git-develop-254ebb68: remote: Invalid username or password.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/org/repo.git /root/.npm/_git-remotes/git-https-github-com-app-git-develop-254ebb68: fatal: Authentication failed for 'https://github.com/org/repo.git/'
npm ERR! Linux 4.4.10-22.54.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/org/repo.git /root/.npm/_git-remotes/git-https-github-com-app-git-develop-214ebb68
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-app-git-develop-214ebb68'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/org/repo.git/'
npm ERR!

**Comment by nzoschke** [comment]
@frankleng did the patch that closed #771 (https://github.com/convox/rack/pull/834) help with private github repos in some way? Does your Convox OAuth token have the right scope to clone those repos?

@MiguelMoll SSH will need some design. One idea is a rack-wide `convox repos` command where you manage GitHub / GitLab / BitBucket / NPM credentials. The build script would need some plumbing to log into the various repos before it starts building.

This would be very similar to how we handle private docker registries. Anything you put in there is passed to a `docker login` call at the beginning of the build to facilitate pulling from private registries.

https://convox.com/docs/private-registries/

**Comment by frankleng** [comment]
@nzoschke no unfortunately those didn't help. and the OAuth token has full access to the org.
but this could be an `npm` problem when using https.

**Comment by nzoschke** [comment]
Could be. I would hope that npm is shelling out to `git` which honors .netrc, but it might be doing something funny.

**Comment by MiguelMoll** [comment]
For reference: https://github.com/npm/npm/issues/4284
Seems like an old issue with no plans for support.

**Comment by frankleng** [comment]
@MiguelMoll maybe implement github deploy key in convox and stick npm to ssh?

**Comment by frankleng** [comment]
@MiguelMoll any movement on this? possible to implement deploy keys from github?

**Comment by kopax** [comment]
I have the same issue, is this resolved?
