### ISSUE TITLE
Simple way to restart an app

### ISSUE THREAD

**Issue by skwp** [convox/rack#863]
The developer experience of restarting an app is not obvious right now. This is the shell script I've been using to make it easier, but it would be nice if the CLI did something like this.

``` bash
# Usage: convox_restart app-name
# Assumes an app with a single running instance
convox_restart() {
  app_name=$1
  convox ps stop `convox api get /apps/$app_name/processes | jq -r "first.id"` --app $app_name
}
```

**Comment by skwp** [comment]
I think the script above is only good on single-process apps. Probably need to iterate over all ids there.

**Comment by skwp** [comment]
Another technique proposed is to set a dummy var in the env (e.g. to the current timestamp?) and promote that release?

**Comment by nzoschke** [comment]
Great feedback. This needs a bit of design. How about something like `convox ps stop --all` ?

**Comment by mwarkentin** [comment]
@nzoschke I know there've been multiple people in slack who have mentioned that using `stop` to restart a process is not exactly obvious (I'd have to agree).

If you've wrapped your head around the declarative nature of ECS/k8s/etc. then it makes some sense:

* I've declared I want <x> number of processes running
* I manually stop the processes
* The scheduler notices that they've stopped and starts new processes

But this is still a layer of abstraction that people need to learn, vs. something like `heroku ps:restart`

**Comment by nzoschke** [comment]
Good feedback. It can be renamed... `convox ps restart` restarts the app, `convox ps restart --ps ID` restarts a single process?

**Comment by ddollar** [comment]
`convox ps restart` and `convox ps restart ID`

**Comment by mwarkentin** [comment]
@ddollar's suggested UI seems good.

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RFRjjlvK&#x2F;480-simple-way-to-restart-an-app"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Simple way to restart an app</a>

**Comment by advance512** [comment]
I see there was a card for this, yet eventually it was deleted? Is this still planned?

It's a good idea, and I actually needed it right now. Maybe not for production, but definitely for some dynamic or staging environments.

**Comment by ndbroadbent** [comment]
I also needed to restart my app, and could only found this issue. I ran `convox ps stop` to kill the web processes one by one, but I think a rolling restart would be very useful.
