### ISSUE TITLE
govcloud region support?

### ISSUE THREAD

**Issue by contra** [convox/rack#867]
AFAIK the govcloud region supports everything convox needs to work.

If not I can bug some people to make it happen.

**Comment by ddollar** [comment]
I'll look into this, have never tried using Govcloud.

**Comment by contra** [comment]
@ddollar Thanks! Super important for some government stuff we're working on right now, the feds are pretty insistent on using govcloud for everything. I think there might be a mandate that any new government contracts have to use it now.

**Comment by nzoschke** [comment]
http://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html

Different region endpoints, and some services use special encryption.

**Comment by alex** [comment]
govcloud is missing ECS, at least last time I checked.

**Comment by contra** [comment]
If I can get them to add ECS to govcloud, is there anything else missing? Going to speak with them about it this week.

**Comment by alex** [comment]
It was the long pole last time I checked. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ indicates it's also missing:

- ECR
- EFS
- Cert Manager

**Comment by alex** [comment]
Probably worth mentioning that if you're in a position where you're using GovCloud, you may also care about whether things are FedRAMP'd or not, for that you can review: https://aws.amazon.com/compliance/services-in-scope/

(To folks dealing with this, I'm personally very sorry, thanks for trying to use convox and do something sane with computers.)

**Comment by contra** [comment]
@alex Alright, I'll see what I can do about getting ECS/ECR/EFS/Certs into govcloud.

**Comment by ddollar** [comment]
ECS and ECR are required, the other two are opti Nap and support generating certificates and persistent volumes.

**Comment by contra** [comment]
Any idea if the way convox sets stuff up is FedRAMP compliant? We're working with our AWS people still to get the services into govcloud, some may already be in there now - might want to look again.

**Comment by alex** [comment]
A setup isn't FedRAMP compliant, specific services are FedRAMP'd. To check, you'd have to cross reference the list of services Convox uses with the services-in-scope page I linked.

Unfortunately, ECS/ECR/EFS are almost certainly not FedRAMP'd at the High level since they haven't been deployed there yet -- they're also not FedRAMP'd at moderate in East/West either.
