### ISSUE TITLE
"convox instances keyroll" failure inconsistency

### ISSUE THREAD

**Issue by beedub** [convox/rack#871]
When a `convox instances keyroll` is run while a rack update is already in progress, the command errors out but the key is not rolled back. Because the key is not rolled back, the instances are not accessible via ssh until the next successful keyroll.

**Comment by nzoschke** [comment]
Thanks for the report.

They EC2 keypair is generated and saved, then the keyname is passed into the CloudFormation for a stack update.

The simplest fix will be to not allow a `convox instances keyroll` if a stack update is happening.

The more advanced fix would be to keep old private keys around, so `convox instances ssh` could get the right key based on the current stack keyname.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs: Keyroll](https://trello.com/c/NQZTU11p/1229-docs-keyroll)
