### ISSUE TITLE
convox api memory usage

### ISSUE THREAD

**Issue by beedub** [convox/rack#877]
Right now, I'm seeing the convox web api's memory get saturated during builds, so I manually increased the memory reservation to 1024. Should this be configurable via rack settings?

**Comment by nzoschke** [comment]
@beedub interesting! This is not good but I'd hope we can reduce the memory usage in the api, or else make the default bigger. Can you share what tools you've used to see this?

**Comment by beedub** [comment]
I just checked out the ecs service metrics of the Web service and the max mem usage hit 100% multiple times. I'm not sure if this is directly correlated to any build errors but usually hitting max mem isn't good.

**Comment by skwp** [comment]
I've also noticed this 
<img width="1153" alt="amazon_ec2_container_service" src="https://cloud.githubusercontent.com/assets/1731/17148255/06327a4a-532c-11e6-84b6-21b0d72f4236.png">

**Comment by beedub** [comment]
@nzoschke basically looking at the ECS service graphs like @skwp just posted

**Comment by ddollar** [comment]
Closed in #926
