### ISSUE TITLE
convox rack ps - listing rack processes for debugging

### ISSUE THREAD

**Issue by adamenger** [convox/rack#888]
It'd be useful to be able to simply print out these processes when debugging/investigating rack issues.

**Comment by awsmsrc** [comment]
You can actually already do this via

`convox ps -a $STACK_NAME`

**Comment by ddollar** [comment]
Definitely want to add `convox rack ps`

**Comment by ddollar** [comment]
Would also like `convox rack ps -a` for all processes running on all apps on the Rack

**Comment by ddollar** [comment]
This has been in for a while now
