### ISSUE TITLE
Show both desired and actual process count in convox scale

### ISSUE THREAD

**Issue by ddollar** [convox/rack#89]

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;3sAEIiyb&#x2F;195-show-both-desired-and-actual-process-count-in-convox-scale"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Show both desired and actual process count in convox scale</a>

**Comment by joonathan** [comment]
:+1: Thanks for this.
