### ISSUE TITLE
Reference convox/docker host from container

### ISSUE THREAD

**Issue by frankleng** [convox/rack#895]
We have a use case where the container running the app needs to broadcast events to the statsD instance on the host machine. In this case - datadogD

related to https://github.com/docker/docker/issues/1143

potential workaround would be https://gist.github.com/dimitrovs/493678fd86c7cdf0c88312d9ddb4906b
will need to either customize it into AMI, or perhaps piggy back on `InstanceBootCommand`

Be nice to have convox standardize this.

**Comment by ddollar** [comment]
We should be able to set up a DNS alias for `host` during both `convox start` and deployment to ECS.

**Comment by skwp** [comment]
yes please, we also need this for datadog

**Comment by ddollar** [comment]
Covered by #1282
