### ISSUE TITLE
Convox "api" app is ambiguous, hidden

### ISSUE THREAD

**Issue by jordansexton** [convox/rack#896]
Ran into this today:

```
> convox apps create api
Creating app api... ERROR: there is already a legacy app named api (running). We recommend you delete this app and create it again.
```

On inspection, the ECS cluster has a process `<RACK>-api-web-<ID>`. The app is hidden from listing via `convox apps`. Would it be reasonable to namespace the app, e.g. `convox-api`, or would it be a lot of work? I realize this is kind of trivial.

**Comment by mwarkentin** [comment]
I do think `api` is potentially a pretty common name to want to name an app... we have one in fact (not migrated yet).

Maybe the convox app should be named.. `convox`? Originally I think this might've conflicted with the default rack name.. but apps are namespaced now, so maybe not an issue anymore?

**Comment by awsmsrc** [comment]
The error message here was actually not THAT unclear although that is easy to say with a bit of context.

Cloudformation Stack names are now neatly name spaced so this should no longer occur.
