### ISSUE TITLE
Alternate Dockerfile specified in docker-compose.yml not respected

### ISSUE THREAD

**Issue by jordansexton** [convox/rack#903]
From [Slack](https://convox-public.slack.com/archives/convox/p1469144654000626):

> My builds started failing with the latest convox installed from https://install.convox.com/linux.zip. I'm using `convox start --no-cache --file docker-compose.build.yml` which has a `dockerfile: Dockerfile.build` directive. However, this results in: `build  │ running: docker build --no-cache -f ./Dockerfile -t convox-ba4c56a612 .`

> In short, even though the compose file specifies a different dockerfile, convox is now building using the main Dockerfile

@mwarkentin suggested (thanks!) that it could be a regression induced in https://github.com/convox/rack/pull/768

**Comment by mwarkentin** [comment]
CC @awsmsrc

**Comment by jordansexton** [comment]
Confirmed that version **20160706210644** works.

**Comment by awsmsrc** [comment]
hey @jordansexton Im looking into this. Does it work if you use the following format.
```
build:
  context: .
  dockerfile: Dockerfile-alternate
```

**Comment by frewsxcv** [comment]
I have something along the lines of this:

```docker
  nginx:
    build:
      dockerfile: nginx.Dockerfile
      context: .
```

Which results in:

```
Deploying corey-testing
Creating tarball... OK
Uploading... 21.38 MB / 21.38 MB  100.00 % 0
RUNNING: tar xz
yaml: unmarshal errors:
  line 5: cannot unmarshal !!map into string
2016/07/22 14:17:55 exit status 1
ERROR: corey-testing build failed
```

**Comment by awsmsrc** [comment]
hey @frewsxcv are you on the latest cli?

**Comment by frewsxcv** [comment]
> hey @frewsxcv are you on the latest cli?

```
> convox update
Updating: Already up to date
> convox --version
client: 20160721214728
server: 20160720211125 (console.convox.com)
```

Here's the exact Dockerfile:

```dockerfile
version: "2"
services:
  nginx:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    labels:
      - "convox.port.80.protocol=http"
    ports:
      - "80:80"
    volumes:
      - "a:/srv/shared/"
      - "./deploy/nginx.conf:/etc/nginx/nginx.conf:ro"
  hub:
    build: .
    command: "gunicorn -c deploy/gunicorn-conf.ini hub.wsgi:application"
    volumes:
      - "a:/srv/shared/"
volumes:
  a:
    external: false
```
