### ISSUE TITLE
Upgrading to 20160720211125 errors out

### ISSUE THREAD

**Issue by adamenger** [convox/rack#905]
Doing a `convox rack update` on my rack results in this error in CloudFormation:

```
    ELB cannot be attached to multiple subnets in the same AZ.
```

**Comment by frankleng** [comment]
+1

**Comment by ddollar** [comment]
I reverted some changes around the exisiting-VPC stuff and cut a new release. Please try again and let me know if you still see this.

**Comment by frankleng** [comment]
@ddollar thanks. confirm fixed
