### ISSUE TITLE
Vendor fluentd handler

### ISSUE THREAD

**Issue by ddollar** [convox/rack#916]
> the fluentd support that we (@atom_enger) contributed and you guys merged - it doesn’t quite work. I think you never uploaded the service to your own s3 bucket or the perms are not public as they should be. `Your access has been denied by S3, please make sure your request credentials have permission to GetObject for convox-us-east-1/fluentd.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied` -

https://github.com/reverbdotcom/convox-fluentd

**Comment by skwp** [comment]
The makefile from the convox-syslog project should be more or less enough to compile the convox-fluentd project.

**Comment by ddollar** [comment]
This is vendored
