### ISSUE TITLE
convox racks should warn when not connected to console.convox.com

### ISSUE THREAD

**Issue by adamenger** [convox/rack#931]
There's a bit of confusing experience around using `convox racks`. Right now it just returns the rack you're connected to, which is a bit weird since it's a pluralized command and as a user I would expect this command to return the different racks I've connected to and set up. For example if I have a staging and production rack and I'm connected  to prod, it only returns prod:

```
⮀ convox racks
RACK               STATUS
convox-production  running
```

Can we add some warning text if we can verify that the user is not connected to console.convox.com or something that helpfully explains why they only see one rack? By adding this we can notify them that console will help them track their separate racks and maybe link to the add existing rack panel in console.

**Comment by ddollar** [comment]
An individual Rack now returns an error for this endpoint
