### ISSUE TITLE
convox start does not support docker-compose's extra_hosts flag

### ISSUE THREAD

**Issue by eladidan** [convox/rack#933]
`docker-compose` reference: https://docs.docker.com/compose/compose-file/#/extra-hosts
This flag is extra useful when testing since it allows to reference services running on the host.

In my use-case, I have an ssh tunnel redirecting me to a DB host, and so referencing the host is the only way to access the db (short of running a second container that opens the ssh tunnel and linking them, but that's a lot of overhead since I'll need to copy the keys into that container etc.)

**Comment by soulshake** [comment]
@eladidan It looks like this may have been addressed in #1019 
Can you confirm?
