### ISSUE TITLE
Rack updates don't update app templates

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#935]
A common issue I've noticed in Slack is that people will see a new feature they want to use, run `convox rack update` to upgrade their rack to the required version, and then attempt to use the feature which can sometimes fail if the update included a template (?) change as well.

The standard answer is "Re-deploy your application to pick up the new template, then it'll work". This has the following issues:
- Discoverability: there's nothing that lets people know they need to do any other steps
- Unwanted deploys: Not an issue if your latest deploy is up to date with your repo, but this could potentially cause people to deploy code before they wanted it to go out unless they're careful or their processes prevent it
- Deploys can be slow

I've had a few alternatives bubbling around in my head, so here they are from smallest impact to largest.
### Add "release notes" to rack updates

If we could tell that there was a change which would require a redeploy to update the template, this could be called out when the rack update is done.

🔴 Users could miss it
🔴 Manual work to update all of your apps
🔴 You could rely on normal deploys to update it, but if something goes wrong, the timing is now decoupled from the rack update which introduced the change, which could make it hard to track down what happened
🔴 Would require some way of indicating this on the release which could be extra maintenance effort
🍏 No changes to apps without user action
🍏 Could be useful to have more info about what just happened anyways when updating racks
### Add a `convox apps update` command

This option would add a new command, which would allow users to simply update the template, without going through a whole deploy process.

🔴 Still manual work, users might miss it
🔴 Requires (potentially?) more implementation effort
🔴 Adds an extra command to the CLI
🍏 Much faster (and clearer) than doing a full deploy from a UX perspective
### Automatically update application templates when a rack is updated

This is the hands-off approach (with potential risks that might come along with that). When a rack is updated, update all of the app templates as well.

🔴 Potential risk of immediate impact if the rack release is bad
`    `🍏 However, a user would have no way of knowing that there's an issue either if they're using one of the other methods - and those might decouple the issue from the rack update, which could make figuring out what happened harder
🍏 Best UX - new features just work, out of the box
🔴 Harder to implement (maybe?)
🍏 No need for extra messaging on rack upgrades
🍏 Could make it easier to test that template updates on rack upgrades work as expected?

**Comment by ddollar** [comment]
+1 for automatic possibly with a rack param to disable it (default on)

**Comment by ddollar** [comment]
Let's add a `convox apps update`
