### ISSUE TITLE
Security updates not applied on instance launch

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#949]
It appears that the expected behaviour of applying `yum` security updates at instance launch via cloud-init is not happening:

```
$ convox instances
ID                   AGENT  STATUS  STARTED        PS  CPU     MEM
i-03c528cd198c13f67  on     active  2 minutes ago  0   0.00%   0.00%

$ convox instances ssh i-03c528cd198c13f67
Last login: Thu Jul 28 20:30:24 2016 from ip-10-0-5-84.ec2.internal

   __|  __|  __|
   _|  (   \__ \   Amazon ECS-Optimized Amazon Linux AMI 2016.03.c
 ____|\___|____/

For documentation visit, http://aws.amazon.com/documentation/ecs
4 package(s) needed for security, out of 10 available
Run "sudo yum update" to apply all updates.
```

@MiguelMoll thought that `repo_upgrade: security` should be the default for Amazon Linux, however that doesn't seem to be the case (docs?).

**Comment by mwarkentin** [comment]
Slack logs: 

```

mwarkentin [4:01 PM]  
How are people dealing with package / security updates on their rack instances? If I reboot an instance is it going to get replaced in the ASG?

skwp [4:01 PM]  
yeah i don’t think it’s a health check thing, but thanks

mattmanning [4:04 PM]  
You're welcome. Another place to get more data is in the ECS web console. If you click on the service name and then go to the events tab you might be able to click on previous task ids and find more errors.

mwarkentin [4:04 PM]  
Am I imagining things or didn’t convox used to do a `yum update` when an instance launched?

lukeyoungblood [4:06 PM]  
@mwarkentin: I just looked in user-data and didn't see anything, but it's also possible convox is just regularly updating their AMI

mwarkentin [4:08 PM]  
`4 package(s) needed for security, out of 10 available`

miguel [4:16 PM]  
It's supposed to apply only security updates. It used to update everything but then a new version of docker was available in the repo (~1.8 vs ~1.11) and a few things broke with that update.

mwarkentin [4:17 PM]  
@miguel: So if I terminate an instance, the new one should have security updates applied?

miguel [4:18 PM]  
definitely should. but that snippet you posted up above... is it from a new instance?

mwarkentin [4:18 PM]  
I don’t think that’s happening, but I can check now if that’s the expected way things work

[4:19]  
`i-059780ab9a671643b  on     active  4 hours ago  0   2.67%  0.00%`

[4:19]  
 ```$ convox instances ssh i-059780ab9a671643b
Last login: Thu Jul 28 20:05:06 2016 from ip-10-0-5-84.ec2.internal

   __|  __|  __|
   _|  (   \__ \   Amazon ECS-Optimized Amazon Linux AMI 2016.03.c
 ____|\___|____/

For documentation visit, http://aws.amazon.com/documentation/ecs
4 package(s) needed for security, out of 10 available
```

[4:19]  
So pretty new

miguel [4:22 PM]  
weird thing is that for Amazon linux, the cloud-init `repo_upgrade` setting defaults to "security". We don't override that so it should still be working (edited)

[4:23]  
are those 4 packages kernel related? that we do exclude (edited)

mwarkentin [4:25 PM]  
Checking

[4:26]  
 ```[ec2-user@convox-stage--i-059780ab9a671643b ~]$ yum check-update --security
Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper
4 package(s) needed for security, out of 10 available

ntp.x86_64                                                                                                       4.2.6p5-40.30.amzn1                                                                                              amzn-updates
ntpdate.x86_64                                                                                                   4.2.6p5-40.30.amzn1                                                                                              amzn-updates
python27.x86_64                                                                                                  2.7.10-4.122.amzn1                                                                                               amzn-updates
python27-libs.x86_64                                                                                             2.7.10-4.122.amzn1                                                                                               amzn-updates
```

[4:27]  
I’m going to terminate one of those instances just to make sure these aren’t some (really) recent package updates

[4:31]  
 ```$ convox instances
ID                   AGENT  STATUS  STARTED        PS  CPU     MEM
i-03c528cd198c13f67  on     active  2 minutes ago  0   0.00%   0.00%
```

```$ convox instances ssh i-03c528cd198c13f67
Last login: Thu Jul 28 20:30:24 2016 from ip-10-0-5-84.ec2.internal

   __|  __|  __|
   _|  (   \__ \   Amazon ECS-Optimized Amazon Linux AMI 2016.03.c
 ____|\___|____/

For documentation visit, http://aws.amazon.com/documentation/ecs
4 package(s) needed for security, out of 10 available
Run "sudo yum update" to apply all updates.
```

[4:31]  
@miguel: ^^

miguel [4:31 PM]  
well thats a bummer. :disappointed: you'd think cloud-init would behave as documented. definitely something we have to look at

mwarkentin [4:34 PM]  
Worst documented project? :face_with_rolling_eyes:

[4:34]  
@miguel: I’ll open an issue

lukeyoungblood [4:34 PM]  
added and commented on a Plain Text snippet 
# Refresh the locally cached package listing from the network repository
# Default: true
repo_update: true
# Upgrade the instance on first boot. The value is an upgrade level.
#
# Currently supported levels are:
# none, off, false    : do no perform any package upgrades on instance launch
# security, critical  : apply security/critical updates on first launch 
#                       (Not supported on CentOS 5.6)
# all, on, true       : apply all available upgrades
#
# This will also turn on repo_update
# Default: security
#
repo_upgrade: security
1 Comment Collapse
This is not what's in convox's cloud-init, but it's an example of how you would do it (upgrade on launch)

miguel [4:36 PM]  
Thank you @mwarkentin!

lukeyoungblood [4:36 PM]  
added and commented on a Plain Text snippet 
#cloud-config
repo_upgrade_exclude:
  - kernel*
packages:
  - aws-cfn-bootstrap
mounts:
  - ['/dev/xvdb', 'none', 'swap', 'sw', '0', '0']
bootcmd:
  - mkswap /dev/xvdb
  - swapon /dev/xvdb
  - yum install -y nfs-utils
  - mkdir /volumes
  - while true; do mount -t nfs -o nfsvers=4.1 $(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).fs-1b6fa952.efs.us-east-1.amazonaws.com:/ /volumes && break; sleep 5; done
  - [ cloud-init-per, instance, docker_storage_setup, /usr/bin/docker-storage-setup ]
  - echo ECS_CLUSTER=convox-Cluster-VT8HVZ1ZL0Y9 >> /etc/ecs/ecs.config
  - echo ECS_ENGINE_AUTH_TYPE=docker >> /etc/ecs/ecs.config
  - head -n -1 /etc/sysconfig/docker >> /etc/sysconfig/docker-tmp
  - mv /etc/sysconfig/docker-tmp /etc/sysconfig/docker
  - echo 'OPTIONS="--default-ulimit nofile=1024000:1024000"' >> /etc/sysconfig/docker
  - echo 'OPTIONS="${OPTIONS} --storage-opt dm.basesize=10G"' >> /etc/sysconfig/docker
  - echo 'ECS_ENGINE_AUTH_DATA={"index.docker.io":{"username":"","password":"","email":""},"redacted":{"username":"convox","password":"redacted","email":"user@convox.io"}}' >> /etc/ecs/ecs.config
  - echo 'OPTIONS="${OPTIONS} --log-opt max-file=2 --log-opt max-size=50m --insecure-registry=redacted --host=unix:///var/run/docker.sock --host=0.0.0.0:2376"' >> /etc/sysconfig/docker
  - mkdir -p /etc/convox
  - echo "us-east-1" > /etc/convox/region
  - echo "redacted" > /etc/convox/client_id
  - echo "redacted" > /etc/convox/log_group
  - curl -s https://convox.s3.amazonaws.com/agent/0.70/convox.conf > /etc/init/convox.conf
  - echo -e '/var/log/docker {\n  rotate 7\n  daily\n  nocompress\n  copytruncate\n}' >> /etc/logrotate.d/docker
runcmd:
  - sleep 30
  - /opt/aws/bin/cfn-signal --stack convox --region us-east-1 --resource Instances
1 Comment Collapse
Convox's cloud-init looks like this.

miguel [4:36 PM]  
current user data: https://github.com/convox/rack/blob/master/api/dist/kernel.json#L908 good bet is to set it explicitly if the default is working.

[4:36]  
too fast for me :smile:

lukeyoungblood [4:37 PM]  
I just took it out of my current autoscaling group instead of the code

[4:37]  
Seems like a fairly simple pull request to get it fixed - :heart: open source

mwarkentin [4:38 PM]  
https://github.com/convox/rack/issues/949
```

**Comment by MiguelMoll** [comment]
Digging into this further, this link states the default behavior: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonLinuxAMIBasics.html#security-updates

What it doesn't mention is that there are four levels of security updates that the Amazon Linux AMI receives -- critical, important, medium, and low.

By default, the Amazon Linux AMI is set up to apply all critical and important security updates on initial launch. ([source](https://forums.aws.amazon.com/message.jspa?messageID=370765))

The updates listed above are indeed classified as [medium](https://alas.aws.amazon.com/).

Next best guess to test is `repo_upgrade: bugfix` which:

> Apply updates that Amazon marks as bug fixes. Bug fixes are a larger set of updates, which include security updates and fixes for various other minor bugs.

That could apply all levels of security bugs but could also introduce other issues for certain packages. Something worth discussing.

**Comment by mwarkentin** [comment]
Well.. that's annoying. I'll update my PR, so we can at least figure out if setting to `bugfix` actually applies all of the security patches.

**Comment by MiguelMoll** [comment]
`bugfix` seems to do the trick:

```
For documentation visit, http://aws.amazon.com/documentation/ecs
1 package(s) needed for security, out of 1 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-10-0-1-17 ~]$ yum check-update --security
1 package(s) needed for security, out of 1 available

kernel.x86_64                                  4.4.14-24.50.amzn1                                  amzn-updates
```

Only the kernel is left which is explicitly blocked. Now to think of any side effects this could have on the system, if any.

**Comment by mwarkentin** [comment]
Thanks! I'll ponder / ask around the team if they have any thoughts.

**Comment by mwarkentin** [comment]
@MiguelMoll Thoughts on setting to `bugfix`, but in addition to excluding kernel exclude other convox critical packages like `docker`?

**Comment by mwarkentin** [comment]
@MiguelMoll Spent some time discussing with our security guy - we're ok with it as-is for now. We'll spend some more time monitoring and analyzing ALAS alerts over the next couple of weeks to get a better sense of how important we consider being able to update the medium / low vulnerable packages are to us.

**Comment by MiguelMoll** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;lw0R39Qx&#x2F;408-security-updates-not-applied-on-instance-launch"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Security updates not applied on instance launch</a>

**Comment by MiguelMoll** [comment]
Excellent. Also believe that as long as important and critical updates are applied, we have time to think it though.

**Comment by MiguelMoll** [comment]
Closing this for now. The idea is to stick with Amazon defaults which apply important and critical updates on launch. Going forward, the goal is to update the Amazon ECS AMI faster which have any bugfixes applied.
