### ISSUE TITLE
`convox build` broken on CircleCI

### ISSUE THREAD

**Issue by jordansexton** [convox/rack#973]
This appears to affect version **20160802200459**.
Last known working version we tried was **20160706210644**

`docker exec` doesn't work on CircleCI (https://circleci.com/docs/docker/#docker-exec)

We don't call that anywhere, but we run `convox start` to create a container to run our tests, and it now seems to be calling `docker exec` somewhere. Has anyone encountered this?

**Comment by jordansexton** [comment]
Log:

```
build  │ running: docker build --no-cache -f ./Dockerfile.build -t website/build .

[snip]

build  │ Successfully built 4d27a4a5a5a5
build  │ running: docker run -i --rm --name website-build website/build npm run gulp
build  │ time="2016-08-03T06:19:59Z" level=info msg="Unable to locate npm run gulp"
convox │ error: API error (500): Unsupported: Exec is not supported by the lxc driver
convox │ error: API error (500): Unsupported: Exec is not supported by the lxc driver
convox │ error: API error (500): Unsupported: Exec is not supported by the lxc driver

[snip]
```

**Comment by ddollar** [comment]
Hmm, not sure but this seems to be a CircleCI problem with running docker containers more than anything. Is `docker run` supported in your CircleCI tests?
