### ISSUE TITLE
Support Lambda services to have access to VPC

### ISSUE THREAD

**Issue by eladidan** [convox/rack#976]
Convox services that run as lambda tasks currently run externally to the Convox VPC. This presents a challenge when the service needs access to convox apps.

To run the lambda on your VPC resources see: http://docs.aws.amazon.com/lambda/latest/dg/vpc.html wi

Use-case: I have a syslog service running on my cluster that I want to use to forward logs to Sumo Logic. For that I'm running a Sumo Logic collector as along-running app on my cluster. Right now, my only option in order for the syslog service to be able to reach the SL collector is to have it publicly open, which is obviously a security risk.

**Comment by bladealslayer** [comment]
#574 is a nice addition, but supporting VPC for lambda when the rack is not private would be even better!
