### ISSUE TITLE
macOS Sierra support... the continuing saga

### ISSUE THREAD

**Issue by nathany** [convox/rack#984]
Thanks for building with Go 1.6.3 in your recent release. That fixed hanging issues in macOS Sierra beta 3.

Apparently Go's support for `gettimeofday` breaks again on macOS Sierra beta 4. There is a patch included in Go 1.7 rc5.

Once Go 1.7 is released (possibly next Monday) it will probably be worth upgrading to it in convox/release. Hopefully that is the last update needed to resolve issues experienced on Sierra, though until Sierra is released, it's hard to say.

https://github.com/golang/go/issues/16579
https://github.com/golang/go/issues/16606

**Comment by ddollar** [comment]
Thanks for the research on this :)

**Comment by nathany** [comment]
You're welcome. :-)

They expect to release Go 1.7 on the 15th.

**Comment by nathany** [comment]
https://blog.golang.org/go1.7

**Comment by idyll** [comment]
BUMP.

Please consider this with the next release. Every time the command line tool is updated we have to pass around an internal go 1.7 build.

**Comment by nathany** [comment]
https://github.com/convox/release/pull/24

**Comment by MiguelMoll** [comment]
convox/release#24 has been deployed. I'm closing the issue, but if this shows up again please let us know. Thanks!
