### ISSUE TITLE
Make promotions first class

### ISSUE THREAD

**Issue by beedub** [convox/rack#985]
This would facilitate rollbacks. Right now, there's only a releases api, but there's no guarantee that a release was ever promoted

**Comment by awsmsrc** [comment]
@ddollar @MiguelMoll @nzoschke thoughts??

**Comment by ddollar** [comment]
Could you add a bit more detail to what you mean here?

**Comment by beedub** [comment]
In the case of rollbacks, we want to promote the previously promoted release, not simply the last release, and there's currently no way (afaik) to query for that. As a workaround, we're currently just storing releases that have actually been promoted on the side and using that for our rollback functionality

**Comment by ddollar** [comment]
When a rollback happens it should be rolling back to the previous state of the CloudFormation stack (including whatever was actually promoted before the rollback). Are you trying to go back further than one?

**Comment by beedub** [comment]
I may have stale information about convox today, but when I created this issue, convox didn't have a first-class rollback feature. Based on your comment, it sounds like it may be present today. Is that true? https://convox.com/docs/rolling-back/ is all I can find now and that doesn't suggest that there is a first-class rollback to only promoted releases

**Comment by ddollar** [comment]
I see. I'm talking about CloudFormation rollbacks. You are talking about intentionally rolling back from the command line to an older release?

**Comment by beedub** [comment]
Exactly, and I imagine 99% of the time that older release will just be the most recently promoted release after the currently promoted release

**Comment by ddollar** [comment]
Gotcha. How would you feel about the "latest" release always being the current one and a rollback working by copying an older release to a new one and promoting that. Then the release list would always be chronological by "actually promoted".

**Comment by beedub** [comment]
Wouldn't that mess with releases that are created but never promoted? like setting evars, creating builds explicitly during deploy, etc
