### ISSUE TITLE
Links without ports defined

### ISSUE THREAD

**Issue by ddollar** [convox/rack#990]
A few changes to the behavior of `convox start` with regard to link variables:

- [ ] Print a warning (or even error) if a service defines a link to a service with no defined ports.
- [ ] If just a warning, do not set link env vars when linking to a service with no defined ports.

Changes to `convox build`:

- [ ] Print a warning (or error, same as above) if the docker-compose.yml tries to link to a service with no defined ports.

**Comment by awsmsrc** [comment]
fixed in: https://github.com/convox/rack/releases/tag/20160810023912
