### ISSUE TITLE
Document potential issues when volume mounting /var

### ISSUE THREAD

**Issue by twelvelabs** [convox/rack#992]
I was attempting to configure persistent volumes on a postgres container and ran into a few issues similar to those here: https://github.com/convox-examples/rails/commit/237f61013129bd448fb639fa4a52e99c774780d6. I was finally able to get it working by doing the following:

1. I had to explicitly reference `/private/var` rather than just `/var`. Docker for Mac shares `/private/` by default, but the docker daemon wasn't able to follow the symlink.

2. Docker for Mac is not running as a privileged user, and thus couldn't write to `/var/lib`. I ended up creating `/var/lib/convox`, chowned it so that it could be written to, and then changed my docker-compose file to `/private/var/lib/convox/foo`.

It took a bit of time to figure all this out. Given that many people using Convox will be running Docker for Mac and that `/var` is a pretty common place to want to store data directories,  this seems like something that should be documented at https://convox.com/docs/volumes/.

**Comment by ddollar** [comment]
Tracking this on our Docs trello
