### ISSUE TITLE
docker-compose variable substitution

### ISSUE THREAD

**Issue by soulware** [convox/rack#993]
https://docs.docker.com/compose/compose-file/#/variable-substitution

Support for variable substitution in `docker-compose.yml` would allow flexibility at deploy time.

For example being able to specify a "tagged" image when pulling from Docker Hub -

```
# docker-compose.yml
app:
  image: $IMAGE_NAME
```

Note: this is different to build time variables in the Docker file itself - 
https://github.com/convox/rack/issues/156

**Comment by awsmsrc** [comment]
this was implemented in: https://github.com/convox/rack/releases/tag/20160814235318
