### ISSUE TITLE
Issues with using aws_session_token

### ISSUE THREAD

**Issue by jason-riddle** [convox/rack#997]
I acquire credentials through the sts assume role workflow where the following is set.

```
[Dev_Developer]
aws_access_key_id = XXXXXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
aws_session_token = ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
```

upon trying to use those credentials with <code>export AWS_PROFILE="Dev_Developer"</code>, I'm  getting the following error.

```
ERROR: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: ff2d4b55-0e5c-4471-afcd-aa3c6ba8feb6
```

If I export those credentials directly with 

```
export AWS_ACCESS_KEY_ID="XXXXXXXXXXXXXXXXXXXXXXX"
export AWS_SECRET_ACCESS_KEY="YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
export AWS_SESSION_TOKEN="ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
```

then everything works as expected.

**Comment by awsmsrc** [comment]
hey @jason-riddle i'll look into this, have you tried: `export AWS_PROFILE=Dev_Developer` without the quotes, you may also want to try without the capital letters and underscores
