### ISSUE TITLE
Current not implemented on darwin/amd64

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#999]
When you try to mount a volume with Docker for Mac using only the container path:

```
volumes:
  - /my/container/path
```

`convox start` fails with:

`user: Current not implemented on darwin/amd64` It looks like this is related to the way we cross-compile for OS X on Linux. When I build the CLI on my Mac I don't run into this problem.

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GZZxMKvv&#x2F;444-volumes-error-on-os-x"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Volumes error on OS X</a>

**Comment by ddollar** [comment]
Fixed in #991

**Comment by mwarkentin** [comment]
Confirmed fixed on latest CLI.
